In [54]:
from pathlib import Path
import pandas as pd
import torch
import math
import time

In [55]:
!pwd

/Users/ronit/Desktop/QeFEM/main/maxcut_results

In [6]:
# ------------------------------------------------------------
# Required base paths / objects
# ------------------------------------------------------------

GSET_DIR = Path("../data-gset/")

assert "GSET_DIR" in globals(), (
    "GSET_DIR is missing. Define the Gset data directory before running this cell."
)

print("=" * 80)
print("QEFEM V2: UNIFIED GSET METADATA")
print("=" * 80)

print("GSET_DIR:")
print(GSET_DIR.resolve())

================================================================================
QEFEM V2: UNIFIED GSET METADATA
================================================================================
GSET_DIR:
/Users/ronit/Desktop/QeFEM/main/data-gset

In [58]:
GSET_PARTITIONS = {
    1: ["G1", "G2", "G3", "G4", "G5", "G6", "G7", "G8", "G9", "G10"],
    2: ["G11", "G12", "G13"],
    3: ["G14", "G15", "G16", "G17", "G18", "G19", "G20", "G21"],
    4: ["G22", "G23", "G24", "G25", "G26", "G27", "G28", "G29", "G30", "G31"],
    5: ["G32", "G33", "G34"],
    6: ["G35", "G36", "G37", "G38", "G39", "G40", "G41", "G42"],
    7: ["G43", "G44", "G45", "G46", "G47"],
    8: ["G48", "G49", "G50"],
    9: ["G51", "G52", "G53", "G54"],
    10: ["G55", "G56"],
    11: ["G57"],
    12: ["G58", "G59"],
    13: ["G60", "G61"],
    14: ["G62"],
    15: ["G63", "G64"],
    16: ["G65"],
    17: ["G66"],
    18: ["G67", "G72"],
    19: ["G70"],
    20: ["G77"],
    21: ["G81"],
}

GSET_GRAPH_TYPES_BY_PARTITION = {
    1: "random",
    2: "toroidal",
    3: "plain",
    4: "random",
    5: "toroidal",
    6: "plain",
    7: "random",
    8: "toroidal",
    9: "plain",
    10: "plain",
    11: "toroid",
    12: "random",
    13: "plain",
    14: "toroid",
    15: "random",
    16: "toroid",
    17: "toroid",
    18: "toroid",
    19: "plain",
    20: "toroid",
    21: "toroid",
}


# ------------------------------------------------------------
# Storage mode by partition
# ------------------------------------------------------------

GSET_STORAGE_MODE_BY_PARTITION = {}

for partition_id in GSET_PARTITIONS:
    if partition_id <= 9:
        GSET_STORAGE_MODE_BY_PARTITION[partition_id] = "dense"
    else:
        GSET_STORAGE_MODE_BY_PARTITION[partition_id] = "edge_list"



# partition = batch number (1-21)
# graph = gset #
# graph type = plain/ toroid/ random
# storage mode = dense/ edge list

In [59]:
# ------------------------------------------------------------
# Build graph-level target table
# ------------------------------------------------------------

target_rows = []

for partition_id, graphs in GSET_PARTITIONS.items():
    graph_type = GSET_GRAPH_TYPES_BY_PARTITION[partition_id]
    storage_mode = GSET_STORAGE_MODE_BY_PARTITION[partition_id]

    for graph in graphs:
        graph_path = GSET_DIR / graph

        target_rows.append(
            {
                "partition": partition_id,
                "graph": graph,
                "graph_type": graph_type,
                "storage_mode": storage_mode,
                "path": graph_path,
                "exists": graph_path.exists(),
            }
        )

targets_df = pd.DataFrame(target_rows)

# ------------------------------------------------------------
# Print partition-level overview
# ------------------------------------------------------------

print("\nPartition overview:")

for partition_id, graphs in GSET_PARTITIONS.items():
    graph_type = GSET_GRAPH_TYPES_BY_PARTITION[partition_id]
    storage_mode = GSET_STORAGE_MODE_BY_PARTITION[partition_id]

    print(
        f"Partition {partition_id:2d}: "
        f"{graphs[0]}-{graphs[-1]} | "
        f"{len(graphs):2d} instances | "
        f"type={graph_type:} | "
        #f"path ={graph_path} | "
        f"storage={storage_mode}"
    )

Partition overview:
Partition  1: G1-G10 | 10 instances | type=random | storage=dense
Partition  2: G11-G13 |  3 instances | type=toroidal | storage=dense
Partition  3: G14-G21 |  8 instances | type=plain | storage=dense
Partition  4: G22-G31 | 10 instances | type=random | storage=dense
Partition  5: G32-G34 |  3 instances | type=toroidal | storage=dense
Partition  6: G35-G42 |  8 instances | type=plain | storage=dense
Partition  7: G43-G47 |  5 instances | type=random | storage=dense
Partition  8: G48-G50 |  3 instances | type=toroidal | storage=dense
Partition  9: G51-G54 |  4 instances | type=plain | storage=dense
Partition 10: G55-G56 |  2 instances | type=plain | storage=edge_list
Partition 11: G57-G57 |  1 instances | type=toroid | storage=edge_list
Partition 12: G58-G59 |  2 instances | type=random | storage=edge_list
Partition 13: G60-G61 |  2 instances | type=plain | storage=edge_list
Partition 14: G62-G62 |  1 instances | type=toroid | storage=edge_list
Partition 15: G63-G64 |  2 instances | type=random | storage=edge_list
Partition 16: G65-G65 |  1 instances | type=toroid | storage=edge_list
Partition 17: G66-G66 |  1 instances | type=toroid | storage=edge_list
Partition 18: G67-G72 |  2 instances | type=toroid | storage=edge_list
Partition 19: G70-G70 |  1 instances | type=plain | storage=edge_list
Partition 20: G77-G77 |  1 instances | type=toroid | storage=edge_list
Partition 21: G81-G81 |  1 instances | type=toroid | storage=edge_list

In [60]:
# ------------------------------------------------------------
# Print graph-level table
# ------------------------------------------------------------

print("\nGraph-level target table:")
display(targets_df)


# ------------------------------------------------------------
# File checks
# ------------------------------------------------------------

missing_graph_files = targets_df[
    targets_df["exists"] == False
]["graph"].tolist()

print("\nMissing graph files:")
print(missing_graph_files)

assert len(missing_graph_files) == 0, (
    f"Missing graph files: {missing_graph_files}"
)


# ------------------------------------------------------------
# Basic consistency checks
# ------------------------------------------------------------

all_graphs = targets_df["graph"].tolist()
unique_graphs = sorted(set(all_graphs))

EXPECTED_NUM_GSET_GRAPHS = sum(
    len(graphs)
    for graphs in GSET_PARTITIONS.values()
)

assert len(all_graphs) == EXPECTED_NUM_GSET_GRAPHS, (
    f"Expected {EXPECTED_NUM_GSET_GRAPHS} graph entries, got {len(all_graphs)}."
)

assert len(unique_graphs) == EXPECTED_NUM_GSET_GRAPHS, (
    "Duplicate graph names detected in GSET_PARTITIONS."
)

assert set(GSET_PARTITIONS.keys()) == set(range(1, 22)), (
    "Partitions should be exactly 1 through 21."
)

assert set(GSET_GRAPH_TYPES_BY_PARTITION.keys()) == set(GSET_PARTITIONS.keys()), (
    "Graph-type partition keys do not match GSET_PARTITIONS."
)

assert set(GSET_STORAGE_MODE_BY_PARTITION.keys()) == set(GSET_PARTITIONS.keys()), (
    "Storage-mode partition keys do not match GSET_PARTITIONS."
)

assert (
    targets_df[targets_df["partition"] <= 9]["storage_mode"] == "dense"
).all(), (
    "Partitions 1-9 should use dense storage."
)

assert (
    targets_df[targets_df["partition"] >= 10]["storage_mode"] == "edge_list"
).all(), (
    "Partitions 10-21 should use edge-list storage."
)

Graph-level target table:

    partition graph graph_type storage_mode              path  exists
0           1    G1     random        dense   ../data-gset/G1    True
1           1    G2     random        dense   ../data-gset/G2    True
2           1    G3     random        dense   ../data-gset/G3    True
3           1    G4     random        dense   ../data-gset/G4    True
4           1    G5     random        dense   ../data-gset/G5    True
..        ...   ...        ...          ...               ...     ...
66         18   G67     toroid    edge_list  ../data-gset/G67    True
67         18   G72     toroid    edge_list  ../data-gset/G72    True
68         19   G70      plain    edge_list  ../data-gset/G70    True
69         20   G77     toroid    edge_list  ../data-gset/G77    True
70         21   G81     toroid    edge_list  ../data-gset/G81    True

[71 rows x 6 columns]

Missing graph files:
[]

In [61]:
assert "GSET_PARTITIONS" in globals(), (
    "Run Cell 01 first: GSET_PARTITIONS is missing."
)

assert "GSET_GRAPH_TYPES_BY_PARTITION" in globals(), (
    "Run Cell 01 first: GSET_GRAPH_TYPES_BY_PARTITION is missing."
)

assert "GSET_STORAGE_MODE_BY_PARTITION" in globals(), (
    "Run Cell 01 first: GSET_STORAGE_MODE_BY_PARTITION is missing."
)

assert "targets_df" in globals(), (
    "Run Cell 01 first: targets_df is missing."
)

assert "GSET_DIR" in globals(), (
    "Run Cell 01 first: GSET_DIR is missing."
)


# ------------------------------------------------------------
# Run groups
# ------------------------------------------------------------
# G1-G54 are grouped in threes of partitions.
# G55-G81 remain separated partitionwise.

RUN_GROUPS = {
    "small_1_3": [1, 2, 3],
    "small_4_6": [4, 5, 6],
    "small_7_9": [7, 8, 9],
    "big_10_12": [10,11,12],
    "big_13_15": [13,14,15],
    "big_16_18": [16,17,18],
    "big_19_21": [19,20,21],
}


# ------------------------------------------------------------
# Build run-group graph table
# ------------------------------------------------------------

run_group_rows = []

for run_group, partitions in RUN_GROUPS.items():
    for partition_id in partitions:
        graphs = GSET_PARTITIONS[partition_id]
        graph_type = GSET_GRAPH_TYPES_BY_PARTITION[partition_id]
        storage_mode = GSET_STORAGE_MODE_BY_PARTITION[partition_id]

        for graph in graphs:
            graph_path = GSET_DIR / graph

            run_group_rows.append(
                {
                    "run_group": run_group,
                    "partition": partition_id,
                    "graph": graph,
                    "graph_type": graph_type,
                    "storage_mode": storage_mode,
                    "path": graph_path,
                    "exists": graph_path.exists(),
                }
            )

run_groups_df = pd.DataFrame(run_group_rows)

In [62]:
# ------------------------------------------------------------
# Build run-group summary table
# ------------------------------------------------------------

run_group_summary_rows = []

for run_group, partitions in RUN_GROUPS.items():
    group_graphs = []

    for partition_id in partitions:
        group_graphs.extend(GSET_PARTITIONS[partition_id])

    group_types = [
        GSET_GRAPH_TYPES_BY_PARTITION[partition_id]
        for partition_id in partitions
    ]

    group_storage_modes = [
        GSET_STORAGE_MODE_BY_PARTITION[partition_id]
        for partition_id in partitions
    ]

    run_group_summary_rows.append(
        {
            "run_group": run_group,
            "partitions": partitions,
            "graphs_start": group_graphs[0],
            "graphs_end": group_graphs[-1],
            "num_graphs": len(group_graphs),
            "graph_types": sorted(set(group_types)),
            "storage_modes": sorted(set(group_storage_modes)),
            "graphs": group_graphs,
        }
    )

run_group_summary_df = pd.DataFrame(run_group_summary_rows)

In [63]:
# ------------------------------------------------------------
# Print run-group overview
# ------------------------------------------------------------

print("=" * 80)
print("RUN GROUPS")
print("=" * 80)

for _, row in run_group_summary_df.iterrows():
    print(
        f"{row['run_group']:<14s} | "
        f"partitions={row['partitions']} | "
        f"{row['graphs_start']}-{row['graphs_end']} | "
        f"{row['num_graphs']:2d} graphs | "
        f"types={row['graph_types']} | "
        f"storage={row['storage_modes']}"
    )

================================================================================
RUN GROUPS
================================================================================
small_1_3      | partitions=[1, 2, 3] | G1-G21 | 21 graphs | types=['plain', 'random', 'toroidal'] | storage=['dense']
small_4_6      | partitions=[4, 5, 6] | G22-G42 | 21 graphs | types=['plain', 'random', 'toroidal'] | storage=['dense']
small_7_9      | partitions=[7, 8, 9] | G43-G54 | 12 graphs | types=['plain', 'random', 'toroidal'] | storage=['dense']
big_10_12      | partitions=[10, 11, 12] | G55-G59 |  5 graphs | types=['plain', 'random', 'toroid'] | storage=['edge_list']
big_13_15      | partitions=[13, 14, 15] | G60-G64 |  5 graphs | types=['plain', 'random', 'toroid'] | storage=['edge_list']
big_16_18      | partitions=[16, 17, 18] | G65-G72 |  4 graphs | types=['toroid'] | storage=['edge_list']
big_19_21      | partitions=[19, 20, 21] | G70-G81 |  3 graphs | types=['plain', 'toroid'] | storage=['edge_list']

In [64]:
# ------------------------------------------------------------
# File checks
# ------------------------------------------------------------

missing_group_files = run_groups_df[
    run_groups_df["exists"] == False
]["graph"].tolist()

print("\nMissing graph files:")
print(missing_group_files)

assert len(missing_group_files) == 0, (
    f"Missing graph files in run groups: {missing_group_files}"
)


# ------------------------------------------------------------
# Consistency checks
# ------------------------------------------------------------

assert len(run_groups_df) == len(targets_df), (
    "Run-group graph count does not match targets_df."
)

assert sorted(run_groups_df["graph"].tolist()) == sorted(targets_df["graph"].tolist()), (
    "Run-group graph list does not match target graph list."
)

all_group_partitions = []

for partitions in RUN_GROUPS.values():
    all_group_partitions.extend(partitions)

assert sorted(all_group_partitions) == list(range(1, 22)), (
    "Run groups should cover partitions 1 through 21 exactly once."
)

assert len(all_group_partitions) == len(set(all_group_partitions)), (
    "Some partition appears in more than one run group."
)

assert (
    run_groups_df[run_groups_df["partition"] <= 9]["storage_mode"] == "dense"
).all(), (
    "Partitions 1-9 should use dense storage."
)

assert (
    run_groups_df[run_groups_df["partition"] >= 10]["storage_mode"] == "edge_list"
).all(), (
    "Partitions 10-21 should use edge-list storage."
)

small_run_groups = run_group_summary_df[
    run_group_summary_df["run_group"].str.startswith("small")
]

assert len(small_run_groups) == 3, (
    "Expected exactly three small run groups."
)

Missing graph files:
[]

In [65]:
print("\nRun-group summary dataframe:")
display(run_group_summary_df)

Run-group summary dataframe:

,run_group,partitions,graphs_start,graphs_end,num_graphs,graph_types,storage_modes,graphs
0,small_1_3,"[1, 2, 3]",G1,G21,21,"[plain, random, toroidal]",[dense],"[G1, G2, G3, G4, G5, G6, G7, G8, G9, G10, G11,..."
1,small_4_6,"[4, 5, 6]",G22,G42,21,"[plain, random, toroidal]",[dense],"[G22, G23, G24, G25, G26, G27, G28, G29, G30, ..."
2,small_7_9,"[7, 8, 9]",G43,G54,12,"[plain, random, toroidal]",[dense],"[G43, G44, G45, G46, G47, G48, G49, G50, G51, ..."
3,big_10_12,"[10, 11, 12]",G55,G59,5,"[plain, random, toroid]",[edge_list],"[G55, G56, G57, G58, G59]"
4,big_13_15,"[13, 14, 15]",G60,G64,5,"[plain, random, toroid]",[edge_list],"[G60, G61, G62, G63, G64]"
5,big_16_18,"[16, 17, 18]",G65,G72,4,[toroid],[edge_list],"[G65, G66, G67, G72]"
6,big_19_21,"[19, 20, 21]",G70,G81,3,"[plain, toroid]",[edge_list],"[G70, G77, G81]"

In [66]:
print("\nRun-group graph dataframe:")
display(run_groups_df)

Run-group graph dataframe:

,run_group,partition,graph,graph_type,storage_mode,path,exists
0,small_1_3,1,G1,random,dense,../data-gset/G1,True
1,small_1_3,1,G2,random,dense,../data-gset/G2,True
2,small_1_3,1,G3,random,dense,../data-gset/G3,True
3,small_1_3,1,G4,random,dense,../data-gset/G4,True
4,small_1_3,1,G5,random,dense,../data-gset/G5,True
...,...,...,...,...,...,...,...
66,big_16_18,18,G67,toroid,edge_list,../data-gset/G67,True
67,big_16_18,18,G72,toroid,edge_list,../data-gset/G72,True
68,big_19_21,19,G70,plain,edge_list,../data-gset/G70,True
69,big_19_21,20,G77,toroid,edge_list,../data-gset/G77,True
70,big_19_21,21,G81,toroid,edge_list,../data-gset/G81,True

In [68]:
assert "targets_df" in globals(), (
    "Run Cell 01 first: targets_df is missing."
)

assert "GSET_DIR" in globals(), (
    "Run Cell 01 first: GSET_DIR is missing."
)


# ------------------------------------------------------------
# Locate validation file
# ------------------------------------------------------------

GSET_BEST_KNOWN_PATH = Path("gset_validation.txt")

if not GSET_BEST_KNOWN_PATH.exists():
    GSET_BEST_KNOWN_PATH = Path("../gset_validation.txt")

if not GSET_BEST_KNOWN_PATH.exists():
    GSET_BEST_KNOWN_PATH = GSET_DIR / "gset_validation.txt"

if not GSET_BEST_KNOWN_PATH.exists():
    GSET_BEST_KNOWN_PATH = Path("../data-gset/gset_validation.txt")


print("=" * 80)
print("BEST-KNOWN GSET VALIDATION VALUES")
print("=" * 80)

print("Validation path:")
print(GSET_BEST_KNOWN_PATH)

print("\nFile exists?")
print(GSET_BEST_KNOWN_PATH.exists())

assert GSET_BEST_KNOWN_PATH.exists(), (
    "Could not find gset_validation.txt. "
    "Set GSET_BEST_KNOWN_PATH manually."
)


# ------------------------------------------------------------
# Read validation file
# ------------------------------------------------------------

best_known_rows = []

with GSET_BEST_KNOWN_PATH.open("r") as f:
    for line_no, line in enumerate(f, start=1):
        line = line.strip()

        if not line:
            continue

        if line.startswith("#"):
            continue

        parts = line.replace(",", " ").split()

        if len(parts) < 2:
            continue

        graph_raw = parts[0]
        cut_raw = parts[1]

        if graph_raw.lower() in ["graph", "instance", "name"]:
            continue

        if graph_raw.startswith("G"):
            graph = graph_raw
        else:
            graph = "G" + graph_raw

        best_known_cut = float(cut_raw)

        best_known_rows.append(
            {
                "graph": graph,
                "best_known_cut": best_known_cut,
            }
        )

best_known_df = pd.DataFrame(best_known_rows)


# ------------------------------------------------------------
# Attach validation values to target table
# ------------------------------------------------------------

targets_with_validation_df = targets_df.merge(
    best_known_df,
    on="graph",
    how="left",
)

================================================================================
BEST-KNOWN GSET VALIDATION VALUES
================================================================================
Validation path:
gset_validation.txt

File exists?
True

In [69]:
# ------------------------------------------------------------
# Display
# ------------------------------------------------------------

print("\nLoaded best-known validation table:")
display(best_known_df)

Loaded best-known validation table:

   graph  best_known_cut
0     G1         11624.0
1     G2         11620.0
2     G3         11622.0
3     G4         11646.0
4     G5         11631.0
..   ...             ...
66   G67          6950.0
67   G70          9591.0
68   G72          7008.0
69   G77          9940.0
70   G81         14060.0

[71 rows x 2 columns]

In [71]:
print("\nTargets with validation:")
display(targets_with_validation_df.drop(columns=["path","exists"]))

Targets with validation:

    partition graph graph_type storage_mode  best_known_cut
0           1    G1     random        dense         11624.0
1           1    G2     random        dense         11620.0
2           1    G3     random        dense         11622.0
3           1    G4     random        dense         11646.0
4           1    G5     random        dense         11631.0
..        ...   ...        ...          ...             ...
66         18   G67     toroid    edge_list          6950.0
67         18   G72     toroid    edge_list          7008.0
68         19   G70      plain    edge_list          9591.0
69         20   G77     toroid    edge_list          9940.0
70         21   G81     toroid    edge_list         14060.0

[71 rows x 5 columns]

In [73]:
# ------------------------------------------------------------
# Checks
# ------------------------------------------------------------

missing_best_known = targets_with_validation_df[
    targets_with_validation_df["best_known_cut"].isna()
]["graph"].tolist()

print("\nMissing best-known values for selected graphs:")
print(missing_best_known)

assert len(missing_best_known) == 0, (
    f"Missing best-known cut values for: {missing_best_known}"
)

assert len(targets_with_validation_df) == len(targets_df), (
    "Validation merge changed the number of target rows."
)

assert targets_with_validation_df["graph"].is_unique, (
    "Duplicate graph names after validation merge."
)

assert targets_with_validation_df["best_known_cut"].notna().all(), (
    "Some selected graphs still have missing best-known cuts."
)

Missing best-known values for selected graphs:
[]

In [75]:
from pathlib import Path
import pandas as pd

# ------------------------------------------------------------
# Input files
# ------------------------------------------------------------

V1_SMALL_RESULTS_PATH = Path("qefem_anneal_G1_G54_final_results.csv")
V1_BIG_RESULTS_PATH = Path("qefem_g55-g81_summary.csv")

print("=" * 80)
print("BUILDING CLEAN V1 BENCHMARK TABLE")
print("=" * 80)

print("Small V1 file:")
print(V1_SMALL_RESULTS_PATH.resolve())
print("exists:", V1_SMALL_RESULTS_PATH.exists())

print("\nBig V1 file:")
print(V1_BIG_RESULTS_PATH.resolve())
print("exists:", V1_BIG_RESULTS_PATH.exists())


# ------------------------------------------------------------
# Load small V1 results: G1-G54
# ------------------------------------------------------------

v1_small_raw_df = pd.read_csv(V1_SMALL_RESULTS_PATH)

v1_small_benchmark_df = v1_small_raw_df[
    [
        "instance",
        "nodes",
        "edges",
        "n_steps",
        "replicas",
        "lr",
        "best_cut",
        "best_value",
        "gap",
        "percent_accuracy",
        "best_replica",
        "runtime_sec",
    ]
].copy()

v1_small_benchmark_df = v1_small_benchmark_df.rename(
    columns={
        "best_cut": "v1_best",
        "best_value": "historical_best",
        "gap": "v1_gap",
        "percent_accuracy": "v1_percent_accuracy",
        "best_replica": "v1_best_replica",
        "runtime_sec": "v1_runtime_sec",
    }
)


# ------------------------------------------------------------
# Load big V1 results: G55-G81 selected subset
# ------------------------------------------------------------

v1_big_raw_df = pd.read_csv(V1_BIG_RESULTS_PATH)

v1_big_graph_df = v1_big_raw_df[
    v1_big_raw_df["graph"].notna()
].copy()

v1_big_benchmark_df = pd.DataFrame(
    {
        "instance": v1_big_graph_df["graph"],
        "nodes": v1_big_graph_df["N"].astype(int),
        "edges": v1_big_graph_df["M"].astype(int),
        "n_steps": v1_big_graph_df["steps"].astype(int),
        "replicas": v1_big_graph_df["replicas"].astype(int),
        "lr": v1_big_graph_df["lr"],
        "v1_best": v1_big_graph_df["qefem_best_cut"],
        "historical_best": v1_big_graph_df["best_known_cut"],
        "v1_gap": v1_big_graph_df["gap"],
        "v1_percent_accuracy": v1_big_graph_df["accuracy_percent"],
        "v1_best_replica": v1_big_graph_df["best_replica"].astype(int),
        "v1_runtime_sec": v1_big_graph_df["runtime_sec"],
    }
)


# ------------------------------------------------------------
# Combine small and big V1 benchmark tables
# ------------------------------------------------------------

benchmark_df = pd.concat(
    [
        v1_small_benchmark_df,
        v1_big_benchmark_df,
    ],
    ignore_index=True,
)

benchmark_df["graph_number"] = (
    benchmark_df["instance"]
    .str.replace("G", "", regex=False)
    .astype(int)
)

benchmark_df = benchmark_df.sort_values(
    "graph_number"
).reset_index(drop=True)


# ------------------------------------------------------------
# Add graph type and storage mode from targets_df
# ------------------------------------------------------------

benchmark_df = benchmark_df.merge(
    targets_df[
        [
            "graph",
            "partition",
            "graph_type",
            "storage_mode",
        ]
    ].rename(
        columns={
            "graph": "instance",
        }
    ),
    on="instance",
    how="left",
)

benchmark_df = benchmark_df[
    [
        "partition",
        "instance",
        "graph_type",
        "storage_mode",
        "nodes",
        "edges",
        "n_steps",
        "replicas",
        "lr",
        "v1_best",
        "historical_best",
        "v1_gap",
        "v1_percent_accuracy",
        "v1_best_replica",
        "v1_runtime_sec",
    ]
].copy()


# ------------------------------------------------------------
# Recompute simple consistency columns internally, but do not keep them
# ------------------------------------------------------------

gap_check = benchmark_df["historical_best"] - benchmark_df["v1_best"]
accuracy_check = 100.0 * benchmark_df["v1_best"] / benchmark_df["historical_best"]

max_gap_error = (gap_check - benchmark_df["v1_gap"]).abs().max()
max_accuracy_error = (accuracy_check - benchmark_df["v1_percent_accuracy"]).abs().max()

print("\nConsistency:")
print("max gap error:", float(max_gap_error))
print("max accuracy error:", float(max_accuracy_error))

================================================================================
BUILDING CLEAN V1 BENCHMARK TABLE
================================================================================
Small V1 file:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_anneal_G1_G54_final_results.csv
exists: True

Big V1 file:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_g55-g81_summary.csv
exists: True

Consistency:
max gap error: 0.0
max accuracy error: 1.4210854715202004e-14

In [76]:
# ------------------------------------------------------------
# Display clean table
# ------------------------------------------------------------

print("\nClean benchmark table:")
display(benchmark_df)


# ------------------------------------------------------------
# Save
# ------------------------------------------------------------

BENCHMARK_PATH = Path("qefem_v1_benchmark_table.csv")

benchmark_df.to_csv(
    BENCHMARK_PATH,
    index=False,
)

print("\nSaved benchmark table:")
print(BENCHMARK_PATH.resolve())

Clean benchmark table:

,partition,instance,graph_type,storage_mode,nodes,edges,n_steps,replicas,lr,v1_best,historical_best,v1_gap,v1_percent_accuracy,v1_best_replica,v1_runtime_sec
0,1,G1,random,dense,800,19176,1000,128,0.01,11611.0,11624.0,13.0,99.888162,43,19.635248
1,1,G2,random,dense,800,19176,1000,128,0.01,11610.0,11620.0,10.0,99.913941,61,19.694396
2,1,G3,random,dense,800,19176,1000,128,0.01,11610.0,11622.0,12.0,99.896748,51,19.681336
3,1,G4,random,dense,800,19176,1000,128,0.01,11637.0,11646.0,9.0,99.922720,71,19.562205
4,1,G5,random,dense,800,19176,1000,128,0.01,11622.0,11631.0,9.0,99.922621,53,19.961461
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,18,G67,toroid,edge_list,10000,20000,1000,128,0.01,6806.0,6950.0,144.0,97.928058,35,51.017605
67,19,G70,plain,edge_list,10000,9999,1000,128,0.01,9412.0,9591.0,179.0,98.133667,62,36.532485
68,18,G72,toroid,edge_list,10000,20000,1000,128,0.01,6860.0,7008.0,148.0,97.888128,17,56.816828
69,20,G77,toroid,edge_list,14000,28000,1000,128,0.01,9722.0,9940.0,218.0,97.806841,106,62.788516
70,21,G81,toroid,edge_list,20000,40000,1000,128,0.01,13716.0,14060.0,344.0,97.553343,63,84.624155

Saved benchmark table:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v1_benchmark_table.csv

In [78]:
# ------------------------------------------------------------
# Minimal useful summary
# ------------------------------------------------------------

print("Benchmark summary:")
print("graphs:", len(benchmark_df))
print("mean V1 accuracy %:", float(benchmark_df["v1_percent_accuracy"].mean()))
print("min V1 accuracy % :", float(benchmark_df["v1_percent_accuracy"].min()))
print("max V1 accuracy % :", float(benchmark_df["v1_percent_accuracy"].max()))
print("V1 gap-zero count :", int((benchmark_df["v1_gap"] == 0).sum()))

Benchmark summary:
graphs: 71
mean V1 accuracy %: 98.75137552535392
min V1 accuracy % : 95.17671517671518
max V1 accuracy % : 100.0
V1 gap-zero count : 2

# My targets for V2 run

In [83]:
import math
import time
from pathlib import Path

import torch
import pandas as pd


if torch.backends.mps.is_available():
    device = torch.device("mps")
elif torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")

DTYPE = torch.float32


N_REPLICAS = 128
N_STEPS = 2000
LOG_EVERY = 50
SEED = 7

OPTIMIZER_NAME = "Adam"
ADAM_LR = 0.03

T_MAX = 1.16
T_MIN = 6e-5


GAMMA_MAX = 1.0
GAMMA_MIN = 0.0

GAMMA_PULSE_AMP = 0.05
GAMMA_PULSE_CENTER_FRAC = 0.80
GAMMA_PULSE_WIDTH_FRAC = 0.03


R_INIT = 1e-2
RAW_R_NOISE = 1e-3

THETA_CENTER = math.pi / 2
THETA_NOISE = 1e-2


QEFEM_V2_OUTPUT_DIR = Path("qefem_v2_outputs")
QEFEM_V2_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True,
)


# ------------------------------------------------------------
# Print settings
# ------------------------------------------------------------

print("=" * 80)
print("QEFEM V2 SETTINGS")
print("=" * 80)

print("device:", device)
print("dtype :", DTYPE)

print("\nOptimizer:")
print("optimizer:", OPTIMIZER_NAME)
print("lr:", ADAM_LR)

print("\nRun size:")
print("replicas:", N_REPLICAS)
print("steps:", N_STEPS)
print("log every:", LOG_EVERY)
print("seed:", SEED)

print("\nTemperature:")
print("T_MAX:", T_MAX)
print("T_MIN:", T_MIN)

print("\nGamma:")
print("GAMMA_MAX:", GAMMA_MAX)
print("GAMMA_MIN:", GAMMA_MIN)
print("GAMMA_PULSE_AMP:", GAMMA_PULSE_AMP)
print("GAMMA_PULSE_CENTER_FRAC:", GAMMA_PULSE_CENTER_FRAC)
print("GAMMA_PULSE_WIDTH_FRAC:", GAMMA_PULSE_WIDTH_FRAC)

print("\nInitialization:")
print("R_INIT:", R_INIT)
print("RAW_R_NOISE:", RAW_R_NOISE)
print("THETA_CENTER:", THETA_CENTER)
print("THETA_NOISE:", THETA_NOISE)

print("\nOutput directory:")
print(QEFEM_V2_OUTPUT_DIR.resolve())


# ------------------------------------------------------------
# Minimal sanity checks
# ------------------------------------------------------------

assert N_REPLICAS > 0
assert N_STEPS > 0
assert LOG_EVERY > 0
assert ADAM_LR > 0

assert T_MAX > T_MIN > 0
assert GAMMA_MAX >= GAMMA_MIN >= 0

assert GAMMA_PULSE_AMP >= 0
assert 0.0 <= GAMMA_PULSE_CENTER_FRAC <= 1.0
assert GAMMA_PULSE_WIDTH_FRAC > 0

assert 0 < R_INIT < 1
assert RAW_R_NOISE >= 0
assert THETA_NOISE >= 0

assert "benchmark_df" in globals()
assert len(benchmark_df) > 0

================================================================================
QEFEM V2 SETTINGS
================================================================================
device: mps
dtype : torch.float32

Optimizer:
optimizer: Adam
lr: 0.03

Run size:
replicas: 128
steps: 2000
log every: 50
seed: 7

Temperature:
T_MAX: 1.16
T_MIN: 6e-05

Gamma:
GAMMA_MAX: 1.0
GAMMA_MIN: 0.0
GAMMA_PULSE_AMP: 0.05
GAMMA_PULSE_CENTER_FRAC: 0.8
GAMMA_PULSE_WIDTH_FRAC: 0.03

Initialization:
R_INIT: 0.01
RAW_R_NOISE: 0.001
THETA_CENTER: 1.5707963267948966
THETA_NOISE: 0.01

Output directory:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs

In [84]:
step_index = torch.arange(
    N_STEPS,
    device=device,
    dtype=DTYPE,
)


# ------------------------------------------------------------
# Temperature and beta
# ------------------------------------------------------------

T_schedule = torch.linspace(
    T_MAX,
    T_MIN,
    N_STEPS,
    device=device,
    dtype=DTYPE,
)

beta_schedule = 1.0 / T_schedule


# ------------------------------------------------------------
# Gamma = linear anneal + Gaussian pulse
# ------------------------------------------------------------

gamma_base_schedule = torch.linspace(
    GAMMA_MAX,
    GAMMA_MIN,
    N_STEPS,
    device=device,
    dtype=DTYPE,
)

gamma_pulse_center = GAMMA_PULSE_CENTER_FRAC * (N_STEPS - 1)
gamma_pulse_width = GAMMA_PULSE_WIDTH_FRAC * N_STEPS

gamma_pulse_schedule = GAMMA_PULSE_AMP * torch.exp(
    -0.5 * (
        (step_index - gamma_pulse_center) / gamma_pulse_width
    ) ** 2
)

gamma_schedule = gamma_base_schedule + gamma_pulse_schedule

# Force final transverse field to zero for final hard readout.
gamma_schedule[-1] = GAMMA_MIN


# ------------------------------------------------------------
# Schedule dataframe
# ------------------------------------------------------------

schedule_df = pd.DataFrame(
    {
        "step": torch.arange(1, N_STEPS + 1).detach().cpu().numpy(),
        "temperature": T_schedule.detach().cpu().numpy(),
        "beta": beta_schedule.detach().cpu().numpy(),
        "gamma_base": gamma_base_schedule.detach().cpu().numpy(),
        "gamma_pulse": gamma_pulse_schedule.detach().cpu().numpy(),
        "gamma": gamma_schedule.detach().cpu().numpy(),
    }
)


# ------------------------------------------------------------
# Print compact summary
# ------------------------------------------------------------

print("=" * 80)
print("ANNEALING SCHEDULES")
print("=" * 80)

print("steps:", N_STEPS)

print("\nTemperature:")
print("first :", float(T_schedule[0].detach().cpu()))
print("middle:", float(T_schedule[N_STEPS // 2].detach().cpu()))
print("last  :", float(T_schedule[-1].detach().cpu()))

print("\nBeta:")
print("first :", float(beta_schedule[0].detach().cpu()))
print("middle:", float(beta_schedule[N_STEPS // 2].detach().cpu()))
print("last  :", float(beta_schedule[-1].detach().cpu()))

print("\nGamma:")
print("first :", float(gamma_schedule[0].detach().cpu()))
print("middle:", float(gamma_schedule[N_STEPS // 2].detach().cpu()))
print("max   :", float(gamma_schedule.max().detach().cpu()))
print("last  :", float(gamma_schedule[-1].detach().cpu()))

print("\nGaussian pulse:")
print("center step:", float(gamma_pulse_center))
print("width steps:", float(gamma_pulse_width))
print("max pulse  :", float(gamma_pulse_schedule.max().detach().cpu()))

================================================================================
ANNEALING SCHEDULES
================================================================================
steps: 2000

Temperature:
first : 1.159999966621399
middle: 0.5797398686408997
last  : 5.999999848427251e-05

Beta:
first : 0.8620690107345581
middle: 1.7249115705490112
last  : 16666.66796875

Gamma:
first : 1.0
middle: 0.4997498393058777
max   : 1.0
last  : 0.0

Gaussian pulse:
center step: 1599.2
width steps: 60.0
max pulse  : 0.049999721348285675

In [85]:
print("\nSchedule preview:")
display(schedule_df.head())
display(schedule_df.tail())

Schedule preview:

   step  temperature      beta  gamma_base  gamma_pulse     gamma
0     1     1.160000  0.862069    1.000000          0.0  1.000000
1     2     1.159420  0.862500    0.999500          0.0  0.999500
2     3     1.158839  0.862932    0.998999          0.0  0.998999
3     4     1.158259  0.863365    0.998499          0.0  0.998499
4     5     1.157679  0.863797    0.997999          0.0  0.997999

      step  temperature          beta  gamma_base   gamma_pulse     gamma
1995  1996     0.002381    419.997406    0.002001  1.776588e-11  0.002001
1996  1997     0.001801    555.316284    0.001501  1.591391e-11  0.001501
1997  1998     0.001220    819.360046    0.001000  1.425110e-11  0.001000
1998  1999     0.000640   1561.833496    0.000500  1.275844e-11  0.000500
1999  2000     0.000060  16666.667969    0.000000  1.141898e-11  0.000000

In [87]:
# ------------------------------------------------------------
# Bloch parametrization
# ------------------------------------------------------------

def bloch_from_raw(raw_R, theta):
    R = torch.sigmoid(raw_R)

    rx = R * torch.sin(theta)
    rz = R * torch.cos(theta)

    return R, rx, rz


# ------------------------------------------------------------
# Quantum entropy from Bloch length
# ------------------------------------------------------------

def quantum_entropy_from_R(R, eps=1e-12):
    lambda_plus = 0.5 * (1.0 + R)
    lambda_minus = 0.5 * (1.0 - R)

    lambda_plus = torch.clamp(
        lambda_plus,
        min=eps,
        max=1.0,
    )

    lambda_minus = torch.clamp(
        lambda_minus,
        min=eps,
        max=1.0,
    )

    entropy_per_site = -(
        lambda_plus * torch.log(lambda_plus)
        +
        lambda_minus * torch.log(lambda_minus)
    )

    entropy = entropy_per_site.sum(dim=1)

    return entropy


# ------------------------------------------------------------
# Transverse driver energy
# ------------------------------------------------------------

def transverse_driver_energy(rx, gamma):
    gamma = torch.as_tensor(
        gamma,
        device=rx.device,
        dtype=rx.dtype,
    )

    driver_energy = -gamma * rx.sum(dim=1)

    return driver_energy


# ------------------------------------------------------------
# Dense symmetric-W MaxCut functions
# ------------------------------------------------------------

def dense_expected_cut(W, rz):
    quad = torch.einsum(
        "ri,ij,rj->r",
        rz,
        W,
        rz,
    )

    expected_cut = 0.25 * (
        W.sum() - quad
    )

    return expected_cut


def dense_hard_cut(W, spins):
    single_input = False

    if spins.dim() == 1:
        spins = spins.unsqueeze(0)
        single_input = True

    spins = spins.to(
        device=W.device,
        dtype=W.dtype,
    )

    quad = torch.einsum(
        "ri,ij,rj->r",
        spins,
        W,
        spins,
    )

    cut = 0.25 * (
        W.sum() - quad
    )

    if single_input:
        cut = cut.squeeze(0)

    return cut


def dense_qefem_free_energy(W, raw_R, theta, beta, gamma):
    beta = torch.as_tensor(
        beta,
        device=raw_R.device,
        dtype=raw_R.dtype,
    )

    R, rx, rz = bloch_from_raw(
        raw_R,
        theta,
    )

    expected_cut = dense_expected_cut(
        W=W,
        rz=rz,
    )

    entropy = quantum_entropy_from_R(R)

    driver_energy = transverse_driver_energy(
        rx=rx,
        gamma=gamma,
    )

    free_energy = (
        -expected_cut
        + driver_energy
        - entropy / beta
    )

    aux = {
        "R": R,
        "rx": rx,
        "rz": rz,
        "expected_cut": expected_cut,
        "entropy": entropy,
        "driver_energy": driver_energy,
        "free_energy": free_energy,
    }

    return free_energy, aux


# ------------------------------------------------------------
# Edge-list MaxCut functions
# ------------------------------------------------------------

def edge_expected_cut(edge_i, edge_j, edge_w, rz):
    zi = rz[:, edge_i]
    zj = rz[:, edge_j]

    expected_cut = 0.5 * (
        edge_w * (1.0 - zi * zj)
    ).sum(dim=1)

    return expected_cut


def edge_hard_cut(edge_i, edge_j, edge_w, spins):
    single_input = False

    if spins.dim() == 1:
        spins = spins.unsqueeze(0)
        single_input = True

    spins = spins.to(
        device=edge_w.device,
        dtype=edge_w.dtype,
    )

    si = spins[:, edge_i]
    sj = spins[:, edge_j]

    cut = 0.5 * (
        edge_w * (1.0 - si * sj)
    ).sum(dim=1)

    if single_input:
        cut = cut.squeeze(0)

    return cut


def edge_qefem_free_energy(edge_i, edge_j, edge_w, raw_R, theta, beta, gamma):
    beta = torch.as_tensor(
        beta,
        device=raw_R.device,
        dtype=raw_R.dtype,
    )

    R, rx, rz = bloch_from_raw(
        raw_R,
        theta,
    )

    expected_cut = edge_expected_cut(
        edge_i=edge_i,
        edge_j=edge_j,
        edge_w=edge_w,
        rz=rz,
    )

    entropy = quantum_entropy_from_R(R)

    driver_energy = transverse_driver_energy(
        rx=rx,
        gamma=gamma,
    )

    free_energy = (
        -expected_cut
        + driver_energy
        - entropy / beta
    )

    aux = {
        "R": R,
        "rx": rx,
        "rz": rz,
        "expected_cut": expected_cut,
        "entropy": entropy,
        "driver_energy": driver_energy,
        "free_energy": free_energy,
    }

    return free_energy, aux


# ------------------------------------------------------------
# Initialization
# ------------------------------------------------------------

def initialize_qefem_variables(
    N,
    replicas,
    R_init,
    raw_R_noise,
    theta_center,
    theta_noise,
    seed,
):
    torch.manual_seed(seed)

    R_init_tensor = torch.tensor(
        R_init,
        device=device,
        dtype=DTYPE,
    )

    raw_R_center = torch.log(
        R_init_tensor / (1.0 - R_init_tensor)
    )

    raw_R = raw_R_center + raw_R_noise * torch.randn(
        replicas,
        N,
        device=device,
        dtype=DTYPE,
    )

    theta = theta_center + theta_noise * torch.randn(
        replicas,
        N,
        device=device,
        dtype=DTYPE,
    )

    raw_R.requires_grad_(True)
    theta.requires_grad_(True)

    return raw_R, theta


# ------------------------------------------------------------
# Hard readout
# ------------------------------------------------------------

def hard_readout_from_rz(rz):
    spins = torch.where(
        rz >= 0,
        torch.ones_like(rz),
        -torch.ones_like(rz),
    )

    return spins


# ------------------------------------------------------------
# Storage-aware wrappers
# ------------------------------------------------------------

def qefem_free_energy_for_graph(graph_data, raw_R, theta, beta, gamma):
    storage_mode = graph_data["storage_mode"]

    if storage_mode == "dense":
        free_energy, aux = dense_qefem_free_energy(
            W=graph_data["W"],
            raw_R=raw_R,
            theta=theta,
            beta=beta,
            gamma=gamma,
        )

    elif storage_mode == "edge_list":
        free_energy, aux = edge_qefem_free_energy(
            edge_i=graph_data["edge_i"],
            edge_j=graph_data["edge_j"],
            edge_w=graph_data["edge_w"],
            raw_R=raw_R,
            theta=theta,
            beta=beta,
            gamma=gamma,
        )

    else:
        raise ValueError(
            f"Unknown storage_mode: {storage_mode}"
        )

    return free_energy, aux


def hard_cut_for_graph(graph_data, spins):
    storage_mode = graph_data["storage_mode"]

    if storage_mode == "dense":
        cut = dense_hard_cut(
            W=graph_data["W"],
            spins=spins,
        )

    elif storage_mode == "edge_list":
        cut = edge_hard_cut(
            edge_i=graph_data["edge_i"],
            edge_j=graph_data["edge_j"],
            edge_w=graph_data["edge_w"],
            spins=spins,
        )

    else:
        raise ValueError(
            f"Unknown storage_mode: {storage_mode}"
        )

    return cut


print("=" * 80)
print("QEFEM CORE FUNCTIONS READY")
print("=" * 80)

print("Functions:")
print("bloch_from_raw(raw_R, theta)")
print("quantum_entropy_from_R(R)")
print("dense_qefem_free_energy(W, raw_R, theta, beta, gamma)")
print("edge_qefem_free_energy(edge_i, edge_j, edge_w, raw_R, theta, beta, gamma)")
print("initialize_qefem_variables(...)")
print("hard_readout_from_rz(rz)")
print("qefem_free_energy_for_graph(graph_data, raw_R, theta, beta, gamma)")
print("hard_cut_for_graph(graph_data, spins)")

================================================================================
QEFEM CORE FUNCTIONS READY
================================================================================
Functions:
bloch_from_raw(raw_R, theta)
quantum_entropy_from_R(R)
dense_qefem_free_energy(W, raw_R, theta, beta, gamma)
edge_qefem_free_energy(edge_i, edge_j, edge_w, raw_R, theta, beta, gamma)
initialize_qefem_variables(...)
hard_readout_from_rz(rz)
qefem_free_energy_for_graph(graph_data, raw_R, theta, beta, gamma)
hard_cut_for_graph(graph_data, spins)

In [88]:
# ------------------------------------------------------------
# Edge-list loader
# ------------------------------------------------------------

def load_gset_edge_list(instance):
    path = Path(GSET_DIR) / instance

    edge_i_list = []
    edge_j_list = []
    edge_w_list = []

    with path.open("r") as f:
        header = f.readline().strip().split()

        N = int(header[0])
        M = int(header[1])

        for line in f:
            line = line.strip()

            if not line:
                continue

            i, j, w = line.split()

            edge_i_list.append(int(i) - 1)
            edge_j_list.append(int(j) - 1)
            edge_w_list.append(float(w))

    edge_i = torch.tensor(
        edge_i_list,
        device=device,
        dtype=torch.long,
    )

    edge_j = torch.tensor(
        edge_j_list,
        device=device,
        dtype=torch.long,
    )

    edge_w = torch.tensor(
        edge_w_list,
        device=device,
        dtype=DTYPE,
    )

    graph_data = {
        "instance": instance,
        "storage_mode": "edge_list",
        "N": N,
        "M": M,
        "edge_i": edge_i,
        "edge_j": edge_j,
        "edge_w": edge_w,
    }

    return graph_data


# ------------------------------------------------------------
# Dense symmetric-W loader
# ------------------------------------------------------------

def load_gset_dense(instance):
    edge_graph_data = load_gset_edge_list(instance)

    N = edge_graph_data["N"]
    M = edge_graph_data["M"]

    edge_i = edge_graph_data["edge_i"]
    edge_j = edge_graph_data["edge_j"]
    edge_w = edge_graph_data["edge_w"]

    W = torch.zeros(
        N,
        N,
        device=device,
        dtype=DTYPE,
    )

    W[edge_i, edge_j] = edge_w
    W[edge_j, edge_i] = edge_w

    graph_data = {
        "instance": instance,
        "storage_mode": "dense",
        "N": N,
        "M": M,
        "W": W,
    }

    return graph_data


# ------------------------------------------------------------
# Storage-aware loader
# ------------------------------------------------------------

def load_graph_for_qefem(instance, storage_mode):
    if storage_mode == "dense":
        graph_data = load_gset_dense(instance)

    elif storage_mode == "edge_list":
        graph_data = load_gset_edge_list(instance)

    else:
        raise ValueError(
            f"Unknown storage_mode={storage_mode}"
        )

    return graph_data


# ------------------------------------------------------------
# Tiny loader preview
# ------------------------------------------------------------

preview_row = benchmark_df.iloc[0]

preview_graph_data = load_graph_for_qefem(
    instance=preview_row["instance"],
    storage_mode=preview_row["storage_mode"],
)

print("=" * 80)
print("GRAPH LOADERS READY")
print("=" * 80)

print("preview instance:", preview_graph_data["instance"])
print("storage mode    :", preview_graph_data["storage_mode"])
print("N               :", preview_graph_data["N"])
print("M               :", preview_graph_data["M"])

if preview_graph_data["storage_mode"] == "dense":
    print("W shape         :", tuple(preview_graph_data["W"].shape))
else:
    print("edge_i shape    :", tuple(preview_graph_data["edge_i"].shape))
    print("edge_j shape    :", tuple(preview_graph_data["edge_j"].shape))
    print("edge_w shape    :", tuple(preview_graph_data["edge_w"].shape))

del preview_graph_data

print("\nCell 08 complete: graph loaders are ready.")

================================================================================
GRAPH LOADERS READY
================================================================================
preview instance: G1
storage mode    : dense
N               : 800
M               : 19176
W shape         : (800, 800)

Cell 08 complete: graph loaders are ready.

In [89]:
import ast


# ------------------------------------------------------------
# Run-group graph extraction
# ------------------------------------------------------------

def get_graphs_from_run_group_row(run_group_row):
    graphs_value = run_group_row["graphs"]

    if isinstance(graphs_value, list):
        graphs = graphs_value

    elif isinstance(graphs_value, str):
        graphs = ast.literal_eval(graphs_value)

    else:
        raise TypeError(
            f"Unsupported graphs field type: {type(graphs_value)}"
        )

    return graphs


# ------------------------------------------------------------
# Print post-run mobility summary
# ------------------------------------------------------------

def print_gradient_mobility_summary(log_df, instance):
    print("\n" + "-" * 80)
    print(f"GRADIENT / MOBILITY SUMMARY: {instance}")
    print("-" * 80)

    summary_fields = [
        "raw_R_grad_mean_abs",
        "theta_grad_mean_abs",
        "raw_R_step_mean_abs",
        "theta_step_mean_abs",
        "raw_R_grad_norm",
        "theta_grad_norm",
        "raw_R_step_norm",
        "theta_step_norm",
    ]

    available_fields = [
        field for field in summary_fields
        if field in log_df.columns
    ]

    mobility_rows = []

    for field in available_fields:
        series = log_df[field].dropna()

        mobility_rows.append(
            {
                "metric": field,
                "first": float(series.iloc[0]),
                "middle": float(series.iloc[len(series) // 2]),
                "last": float(series.iloc[-1]),
                "min": float(series.min()),
                "max": float(series.max()),
            }
        )

    mobility_summary_df = pd.DataFrame(mobility_rows)

    display(mobility_summary_df)


# ------------------------------------------------------------
# Print post-run result summary
# ------------------------------------------------------------

def print_graph_result_summary(result_row):
    print("\n" + "-" * 80)
    print(f"RESULT SUMMARY: {result_row['instance']}")
    print("-" * 80)

    print("historical_best:", result_row["historical_best"])

    print("\nV1:")
    print("v1_best:", result_row["v1_best"])
    print("v1_gap:", result_row["v1_gap"])
    print("v1_percent_accuracy:", result_row["v1_percent_accuracy"])

    print("\nV2:")
    print("v2_best:", result_row["v2_best"])
    print("v2_gap:", result_row["v2_gap"])
    print("v2_percent_accuracy:", result_row["v2_percent_accuracy"])
    print("v2_best_step:", result_row["v2_best_step"])
    print("v2_best_replica:", result_row["v2_best_replica"])

    print("\nReplica success:")
    print("ever_success_count:", result_row["ever_success_count"])
    print("ever_success_probability:", result_row["ever_success_probability"])
    print("best_step_success_count:", result_row["best_step_success_count"])
    print("best_step_success_probability:", result_row["best_step_success_probability"])
    print("final_success_count:", result_row["final_success_count"])
    print("final_success_probability:", result_row["final_success_probability"])

    print("\nRuntime:")
    print("v2_runtime_sec:", result_row["v2_runtime_sec"])

In [90]:
# ------------------------------------------------------------
# Main group-level runner
# ------------------------------------------------------------

def run_qefem_run_group(run_group_index):
    run_group_row = run_group_summary_df.iloc[run_group_index]

    run_group = run_group_row["run_group"]
    graphs = get_graphs_from_run_group_row(run_group_row)

    group_output_dir = QEFEM_V2_OUTPUT_DIR / run_group
    group_output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    log_output_dir = group_output_dir / "logs"
    log_output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    spin_output_dir = group_output_dir / "best_spins"
    spin_output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    selected_benchmark_df = benchmark_df[
        benchmark_df["instance"].isin(graphs)
    ].copy()

    selected_benchmark_df["graph_order"] = (
        selected_benchmark_df["instance"]
        .str.replace("G", "", regex=False)
        .astype(int)
    )

    selected_benchmark_df = selected_benchmark_df.sort_values(
        "graph_order"
    ).reset_index(drop=True)

    selected_benchmark_df = selected_benchmark_df.drop(
        columns=["graph_order"]
    )

    print("=" * 80)
    print("RUNNING QEFEM V2 RUN GROUP")
    print("=" * 80)

    print("run_group_index:", run_group_index)
    print("run_group:", run_group)
    print("graphs:", graphs)
    print("num graphs:", len(graphs))

    print("\nOutput directory:")
    print(group_output_dir.resolve())

    print("\nSelected benchmark rows:")
    display(selected_benchmark_df)

    group_result_rows = []
    group_log_dfs = []

    for graph_idx, benchmark_row in selected_benchmark_df.iterrows():
        instance = benchmark_row["instance"]
        storage_mode = benchmark_row["storage_mode"]

        nodes = int(benchmark_row["nodes"])
        edges = int(benchmark_row["edges"])

        historical_best = float(benchmark_row["historical_best"])

        v1_best = float(benchmark_row["v1_best"])
        v1_gap = float(benchmark_row["v1_gap"])
        v1_percent_accuracy = float(benchmark_row["v1_percent_accuracy"])

        graph_seed = SEED + graph_idx

        print("\n" + "#" * 80)
        print(f"RUNNING {instance} | {storage_mode} | seed={graph_seed}")
        print("#" * 80)

        graph_start_time = time.time()

        graph_data = load_graph_for_qefem(
            instance=instance,
            storage_mode=storage_mode,
        )

        raw_R, theta = initialize_qefem_variables(
            N=nodes,
            replicas=N_REPLICAS,
            R_init=R_INIT,
            raw_R_noise=RAW_R_NOISE,
            theta_center=THETA_CENTER,
            theta_noise=THETA_NOISE,
            seed=graph_seed,
        )

        optimizer = torch.optim.Adam(
            [
                raw_R,
                theta,
            ],
            lr=ADAM_LR,
        )

        v2_best = -float("inf")
        v2_best_step = None
        v2_best_replica = None
        best_step_success_count = 0
        best_step_success_probability = 0.0
        best_spins = None

        ever_success_mask = torch.zeros(
            N_REPLICAS,
            device=device,
            dtype=torch.bool,
        )

        log_rows = []

        for step in range(N_STEPS):
            beta_t = beta_schedule[step]
            gamma_t = gamma_schedule[step]

            should_log = (
                step == 0
                or (step + 1) % LOG_EVERY == 0
                or step == N_STEPS - 1
            )

            optimizer.zero_grad()

            free_energy, aux = qefem_free_energy_for_graph(
                graph_data=graph_data,
                raw_R=raw_R,
                theta=theta,
                beta=beta_t,
                gamma=gamma_t,
            )

            loss = free_energy.mean()
            loss.backward()

            if should_log:
                with torch.no_grad():
                    raw_R_grad_norm = float(raw_R.grad.norm().detach().cpu())
                    theta_grad_norm = float(theta.grad.norm().detach().cpu())

                    raw_R_grad_mean_abs = float(raw_R.grad.abs().mean().detach().cpu())
                    theta_grad_mean_abs = float(theta.grad.abs().mean().detach().cpu())

                    raw_R_grad_max_abs = float(raw_R.grad.abs().max().detach().cpu())
                    theta_grad_max_abs = float(theta.grad.abs().max().detach().cpu())

                    raw_R_before = raw_R.detach().clone()
                    theta_before = theta.detach().clone()

            optimizer.step()

            with torch.no_grad():
                if should_log:
                    raw_R_step = raw_R.detach() - raw_R_before
                    theta_step = theta.detach() - theta_before

                    raw_R_step_norm = float(raw_R_step.norm().detach().cpu())
                    theta_step_norm = float(theta_step.norm().detach().cpu())

                    raw_R_step_mean_abs = float(raw_R_step.abs().mean().detach().cpu())
                    theta_step_mean_abs = float(theta_step.abs().mean().detach().cpu())

                eval_free_energy, eval_aux = qefem_free_energy_for_graph(
                    graph_data=graph_data,
                    raw_R=raw_R,
                    theta=theta,
                    beta=beta_t,
                    gamma=gamma_t,
                )

                R = eval_aux["R"]
                rx = eval_aux["rx"]
                rz = eval_aux["rz"]

                spins = hard_readout_from_rz(rz)

                cut_values = hard_cut_for_graph(
                    graph_data=graph_data,
                    spins=spins,
                )

                step_best_cut_tensor, step_best_replica_tensor = torch.max(
                    cut_values,
                    dim=0,
                )

                step_best_cut = float(step_best_cut_tensor.detach().cpu())
                step_best_replica = int(step_best_replica_tensor.detach().cpu())

                success_mask = cut_values >= historical_best

                step_success_count = int(
                    success_mask.sum().detach().cpu()
                )

                step_success_probability = step_success_count / N_REPLICAS

                ever_success_mask |= success_mask

                if step_best_cut > v2_best:
                    v2_best = step_best_cut
                    v2_best_step = step + 1
                    v2_best_replica = step_best_replica

                    best_step_success_count = step_success_count
                    best_step_success_probability = step_success_probability

                    best_spins = spins[
                        v2_best_replica
                    ].detach().clone()

                current_accuracy = 100.0 * v2_best / historical_best

                if should_log:
                    mean_R = float(R.mean().detach().cpu())
                    mean_abs_rx = float(rx.abs().mean().detach().cpu())
                    mean_abs_rz = float(rz.abs().mean().detach().cpu())

                    frac_polarized = float(
                        (rz.abs() > 0.95).to(DTYPE).mean().detach().cpu()
                    )

                    frac_ambiguous = float(
                        (rz.abs() < 0.05).to(DTYPE).mean().detach().cpu()
                    )

                    log_rows.append(
                        {
                            "run_group": run_group,
                            "instance": instance,
                            "step": step + 1,
                            "temperature": float(T_schedule[step].detach().cpu()),
                            "beta": float(beta_t.detach().cpu()),
                            "gamma": float(gamma_t.detach().cpu()),

                            "loss": float(loss.detach().cpu()),
                            "mean_free_energy": float(eval_aux["free_energy"].mean().detach().cpu()),
                            "mean_expected_cut": float(eval_aux["expected_cut"].mean().detach().cpu()),
                            "max_expected_cut": float(eval_aux["expected_cut"].max().detach().cpu()),
                            "mean_entropy": float(eval_aux["entropy"].mean().detach().cpu()),
                            "mean_driver_energy": float(eval_aux["driver_energy"].mean().detach().cpu()),

                            "step_best_cut": step_best_cut,
                            "global_best_cut": v2_best,
                            "global_best_accuracy": current_accuracy,

                            "step_success_count": step_success_count,
                            "step_success_probability": step_success_probability,
                            "ever_success_count": int(ever_success_mask.sum().detach().cpu()),
                            "ever_success_probability": float(ever_success_mask.sum().detach().cpu()) / N_REPLICAS,

                            "mean_R": mean_R,
                            "mean_abs_rx": mean_abs_rx,
                            "mean_abs_rz": mean_abs_rz,
                            "frac_polarized": frac_polarized,
                            "frac_ambiguous": frac_ambiguous,

                            "raw_R_grad_norm": raw_R_grad_norm,
                            "theta_grad_norm": theta_grad_norm,
                            "raw_R_grad_mean_abs": raw_R_grad_mean_abs,
                            "theta_grad_mean_abs": theta_grad_mean_abs,
                            "raw_R_grad_max_abs": raw_R_grad_max_abs,
                            "theta_grad_max_abs": theta_grad_max_abs,

                            "raw_R_step_norm": raw_R_step_norm,
                            "theta_step_norm": theta_step_norm,
                            "raw_R_step_mean_abs": raw_R_step_mean_abs,
                            "theta_step_mean_abs": theta_step_mean_abs,
                        }
                    )

                    print(
                        f"{instance} | "
                        f"step {step + 1:5d}/{N_STEPS} | "
                        f"best {v2_best:.1f} | "
                        f"acc {current_accuracy:.4f}% | "
                        f"success {step_success_count}/{N_REPLICAS} | "
                        f"gamma {float(gamma_t.detach().cpu()):.5f} | "
                        f"|rz| {mean_abs_rz:.4f}"
                    )

        graph_runtime_sec = time.time() - graph_start_time

        with torch.no_grad():
            final_free_energy, final_aux = qefem_free_energy_for_graph(
                graph_data=graph_data,
                raw_R=raw_R,
                theta=theta,
                beta=beta_schedule[-1],
                gamma=gamma_schedule[-1],
            )

            final_spins = hard_readout_from_rz(
                final_aux["rz"]
            )

            final_cut_values = hard_cut_for_graph(
                graph_data=graph_data,
                spins=final_spins,
            )

            final_best_cut = float(final_cut_values.max().detach().cpu())

            final_success_mask = final_cut_values >= historical_best

            final_success_count = int(
                final_success_mask.sum().detach().cpu()
            )

            final_success_probability = final_success_count / N_REPLICAS

        ever_success_count = int(
            ever_success_mask.sum().detach().cpu()
        )

        ever_success_probability = ever_success_count / N_REPLICAS

        v2_gap = historical_best - v2_best
        v2_percent_accuracy = 100.0 * v2_best / historical_best

        final_gap = historical_best - final_best_cut
        final_percent_accuracy = 100.0 * final_best_cut / historical_best

        result_row = {
            "run_group": run_group,
            "partition": int(benchmark_row["partition"]),
            "instance": instance,
            "graph_type": benchmark_row["graph_type"],
            "storage_mode": storage_mode,

            "nodes": nodes,
            "edges": edges,

            "n_steps": N_STEPS,
            "replicas": N_REPLICAS,
            "lr": ADAM_LR,
            "seed": graph_seed,

            "historical_best": historical_best,

            "v1_best": v1_best,
            "v1_gap": v1_gap,
            "v1_percent_accuracy": v1_percent_accuracy,

            "v2_best": v2_best,
            "v2_gap": v2_gap,
            "v2_percent_accuracy": v2_percent_accuracy,
            "v2_best_step": v2_best_step,
            "v2_best_replica": v2_best_replica,

            "final_best": final_best_cut,
            "final_gap": final_gap,
            "final_percent_accuracy": final_percent_accuracy,

            "best_step_success_count": best_step_success_count,
            "best_step_success_probability": best_step_success_probability,

            "ever_success_count": ever_success_count,
            "ever_success_probability": ever_success_probability,

            "final_success_count": final_success_count,
            "final_success_probability": final_success_probability,

            "v2_runtime_sec": graph_runtime_sec,
        }

        graph_log_df = pd.DataFrame(log_rows)

        group_result_rows.append(result_row)
        group_log_dfs.append(graph_log_df)

        graph_log_path = log_output_dir / f"{instance}_training_log.csv"
        graph_log_df.to_csv(
            graph_log_path,
            index=False,
        )

        best_spin_path = spin_output_dir / f"{instance}_best_spins.pt"
        torch.save(
            best_spins.detach().cpu(),
            best_spin_path,
        )

        print_gradient_mobility_summary(
            log_df=graph_log_df,
            instance=instance,
        )

        print_graph_result_summary(
            result_row=result_row,
        )

        partial_results_df = pd.DataFrame(group_result_rows)

        partial_results_path = group_output_dir / "partial_group_results.csv"
        partial_results_df.to_csv(
            partial_results_path,
            index=False,
        )

        print("\nSaved graph log:")
        print(graph_log_path.resolve())

        print("Saved best spins:")
        print(best_spin_path.resolve())

        print("Saved partial group results:")
        print(partial_results_path.resolve())

        del graph_data
        del raw_R
        del theta
        del optimizer

        if device.type == "cuda":
            torch.cuda.empty_cache()

    group_results_df = pd.DataFrame(group_result_rows)

    group_logs_df = pd.concat(
        group_log_dfs,
        ignore_index=True,
    )

    group_results_path = group_output_dir / "group_results.csv"
    group_logs_path = group_output_dir / "group_training_logs.csv"

    group_results_df.to_csv(
        group_results_path,
        index=False,
    )

    group_logs_df.to_csv(
        group_logs_path,
        index=False,
    )

    print("\n" + "=" * 80)
    print("RUN GROUP COMPLETE")
    print("=" * 80)

    print("run_group:", run_group)
    print("graphs:", len(group_results_df))

    print("\nGroup results:")
    display(group_results_df)

    compact_columns = [
        "instance",
        "historical_best",
        "v1_best",
        "v1_gap",
        "v1_percent_accuracy",
        "v2_best",
        "v2_gap",
        "v2_percent_accuracy",
        "v2_best_step",
        "v2_best_replica",
        "ever_success_count",
        "ever_success_probability",
        "final_best",
        "final_gap",
        "final_percent_accuracy",
        "final_success_count",
        "final_success_probability",
        "v2_runtime_sec",
    ]

    print("\nCompact group results:")
    display(group_results_df[compact_columns])

    print("\nSaved group results:")
    print(group_results_path.resolve())

    print("\nSaved group logs:")
    print(group_logs_path.resolve())

    return group_results_df, group_logs_df


print("=" * 80)
print("GROUP-LEVEL QEFEM RUNNER READY")
print("=" * 80)

print("Use:")
print("group_results_df, group_logs_df = run_qefem_run_group(run_group_index)")

================================================================================
GROUP-LEVEL QEFEM RUNNER READY
================================================================================
Use:
group_results_df, group_logs_df = run_qefem_run_group(run_group_index)

In [91]:
print("\nAvailable run groups:")
display(run_group_summary_df)

Available run groups:

,run_group,partitions,graphs_start,graphs_end,num_graphs,graph_types,storage_modes,graphs
0,small_1_3,"[1, 2, 3]",G1,G21,21,"[plain, random, toroidal]",[dense],"[G1, G2, G3, G4, G5, G6, G7, G8, G9, G10, G11,..."
1,small_4_6,"[4, 5, 6]",G22,G42,21,"[plain, random, toroidal]",[dense],"[G22, G23, G24, G25, G26, G27, G28, G29, G30, ..."
2,small_7_9,"[7, 8, 9]",G43,G54,12,"[plain, random, toroidal]",[dense],"[G43, G44, G45, G46, G47, G48, G49, G50, G51, ..."
3,big_10_12,"[10, 11, 12]",G55,G59,5,"[plain, random, toroid]",[edge_list],"[G55, G56, G57, G58, G59]"
4,big_13_15,"[13, 14, 15]",G60,G64,5,"[plain, random, toroid]",[edge_list],"[G60, G61, G62, G63, G64]"
5,big_16_18,"[16, 17, 18]",G65,G72,4,[toroid],[edge_list],"[G65, G66, G67, G72]"
6,big_19_21,"[19, 20, 21]",G70,G81,3,"[plain, toroid]",[edge_list],"[G70, G77, G81]"

In [92]:
# ============================================================
# Cell 10: Select run group and run QEFEM v2
# ============================================================

# ------------------------------------------------------------
# Choose run group here
# ------------------------------------------------------------
# 0 -> small_1_3   : G1-G21
# 1 -> small_4_6   : G22-G42
# 2 -> small_7_9   : G43-G54
# 3 -> big_10_12   : G55-G59
# 4 -> big_13_15   : G60-G64
# 5 -> big_16_18   : G65, G66, G67, G72
# 6 -> big_19_21   : G70, G77, G81

RUN_GROUP_INDEX = 0


# ------------------------------------------------------------
# Preview selected group
# ------------------------------------------------------------

selected_group_row = run_group_summary_df.iloc[RUN_GROUP_INDEX]

print("=" * 80)
print("SELECTED RUN GROUP")
print("=" * 80)

print("RUN_GROUP_INDEX:", RUN_GROUP_INDEX)
print("run_group:", selected_group_row["run_group"])
print("partitions:", selected_group_row["partitions"])
print("graphs_start:", selected_group_row["graphs_start"])
print("graphs_end:", selected_group_row["graphs_end"])
print("num_graphs:", selected_group_row["num_graphs"])
print("graph_types:", selected_group_row["graph_types"])
print("storage_modes:", selected_group_row["storage_modes"])
print("graphs:", selected_group_row["graphs"])


# ------------------------------------------------------------
# Run selected group
# ------------------------------------------------------------

group_results_df, group_logs_df = run_qefem_run_group(
    run_group_index=RUN_GROUP_INDEX
)


# ------------------------------------------------------------
# Final compact display
# ------------------------------------------------------------

compact_group_results_df = group_results_df[
    [
        "instance",
        "historical_best",
        "v1_best",
        "v1_gap",
        "v1_percent_accuracy",
        "v2_best",
        "v2_gap",
        "v2_percent_accuracy",
        "v2_best_step",
        "v2_best_replica",
        "ever_success_count",
        "ever_success_probability",
        "final_best",
        "final_gap",
        "final_percent_accuracy",
        "final_success_count",
        "final_success_probability",
        "v2_runtime_sec",
    ]
].copy()

print("\n" + "=" * 80)
print("COMPACT GROUP RESULT")
print("=" * 80)

display(compact_group_results_df)

================================================================================
SELECTED RUN GROUP
================================================================================
RUN_GROUP_INDEX: 0
run_group: small_1_3
partitions: [1, 2, 3]
graphs_start: G1
graphs_end: G21
num_graphs: 21
graph_types: ['plain', 'random', 'toroidal']
storage_modes: ['dense']
graphs: ['G1', 'G2', 'G3', 'G4', 'G5', 'G6', 'G7', 'G8', 'G9', 'G10', 'G11', 'G12', 'G13', 'G14', 'G15', 'G16', 'G17', 'G18', 'G19', 'G20', 'G21']
================================================================================
RUNNING QEFEM V2 RUN GROUP
================================================================================
run_group_index: 0
run_group: small_1_3
graphs: ['G1', 'G2', 'G3', 'G4', 'G5', 'G6', 'G7', 'G8', 'G9', 'G10', 'G11', 'G12', 'G13', 'G14', 'G15', 'G16', 'G17', 'G18', 'G19', 'G20', 'G21']
num graphs: 21

Output directory:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3

Selected benchmark rows:

,partition,instance,graph_type,storage_mode,nodes,edges,n_steps,replicas,lr,v1_best,historical_best,v1_gap,v1_percent_accuracy,v1_best_replica,v1_runtime_sec
0,1,G1,random,dense,800,19176,1000,128,0.01,11611.0,11624.0,13.0,99.888162,43,19.635248
1,1,G2,random,dense,800,19176,1000,128,0.01,11610.0,11620.0,10.0,99.913941,61,19.694396
2,1,G3,random,dense,800,19176,1000,128,0.01,11610.0,11622.0,12.0,99.896748,51,19.681336
3,1,G4,random,dense,800,19176,1000,128,0.01,11637.0,11646.0,9.0,99.922720,71,19.562205
4,1,G5,random,dense,800,19176,1000,128,0.01,11622.0,11631.0,9.0,99.922621,53,19.961461
5,1,G6,random,dense,800,19176,1000,128,0.01,2173.0,2178.0,5.0,99.770432,59,19.691165
6,1,G7,random,dense,800,19176,1000,128,0.01,1992.0,2006.0,14.0,99.302094,74,20.118622
7,1,G8,random,dense,800,19176,1000,128,0.01,1991.0,2005.0,14.0,99.301746,102,19.074841
8,1,G9,random,dense,800,19176,1000,128,0.01,2041.0,2054.0,13.0,99.367089,94,19.802351
9,1,G10,random,dense,800,19176,1000,128,0.01,1992.0,2000.0,8.0,99.600000,122,19.633554
10,2,G11,toroidal,dense,800,1600,1000,128,0.01,556.0,564.0,8.0,98.581560,48,20.064666
11,2,G12,toroidal,dense,800,1600,1000,128,0.01,550.0,556.0,6.0,98.920863,92,20.451243
12,2,G13,toroidal,dense,800,1600,1000,128,0.01,580.0,582.0,2.0,99.656357,10,20.195320
13,3,G14,plain,dense,800,4694,1000,128,0.01,3040.0,3064.0,24.0,99.216710,53,20.607247
14,3,G15,plain,dense,800,4661,1000,128,0.01,3025.0,3050.0,25.0,99.180328,67,20.586703
15,3,G16,plain,dense,800,4672,1000,128,0.01,3027.0,3052.0,25.0,99.180865,81,20.083244
16,3,G17,plain,dense,800,4667,1000,128,0.01,3021.0,3047.0,26.0,99.146702,14,20.353204
17,3,G18,plain,dense,800,4694,1000,128,0.01,978.0,992.0,14.0,98.588710,1,20.413980
18,3,G19,plain,dense,800,4661,1000,128,0.01,876.0,906.0,30.0,96.688742,7,20.340401
19,3,G20,plain,dense,800,4672,1000,128,0.01,930.0,941.0,11.0,98.831031,37,20.527158
20,3,G21,plain,dense,800,4667,1000,128,0.01,915.0,931.0,16.0,98.281418,22,20.439184

################################################################################
RUNNING G1 | dense | seed=7
################################################################################
G1 | step     1/2000 | best 9698.0 | acc 83.4308% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G1 | step    50/2000 | best 10062.0 | acc 86.5623% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G1 | step   100/2000 | best 11437.0 | acc 98.3913% | success 0/128 | gamma 0.95048 | |rz| 0.1028
G1 | step   150/2000 | best 11569.0 | acc 99.5268% | success 0/128 | gamma 0.92546 | |rz| 0.8375
G1 | step   200/2000 | best 11588.0 | acc 99.6903% | success 0/128 | gamma 0.90045 | |rz| 0.9019
G1 | step   250/2000 | best 11601.0 | acc 99.8021% | success 0/128 | gamma 0.87544 | |rz| 0.9183
G1 | step   300/2000 | best 11603.0 | acc 99.8193% | success 0/128 | gamma 0.85043 | |rz| 0.9273
G1 | step   350/2000 | best 11603.0 | acc 99.8193% | success 0/128 | gamma 0.82541 | |rz| 0.9333
G1 | step   400/2000 | best 11603.0 | acc 99.8193% | success 0/128 | gamma 0.80040 | |rz| 0.9379
G1 | step   450/2000 | best 11603.0 | acc 99.8193% | success 0/128 | gamma 0.77539 | |rz| 0.9418
G1 | step   500/2000 | best 11603.0 | acc 99.8193% | success 0/128 | gamma 0.75038 | |rz| 0.9454
G1 | step   550/2000 | best 11603.0 | acc 99.8193% | success 0/128 | gamma 0.72536 | |rz| 0.9486
G1 | step   600/2000 | best 11603.0 | acc 99.8193% | success 0/128 | gamma 0.70035 | |rz| 0.9517
G1 | step   650/2000 | best 11605.0 | acc 99.8365% | success 0/128 | gamma 0.67534 | |rz| 0.9546
G1 | step   700/2000 | best 11608.0 | acc 99.8624% | success 0/128 | gamma 0.65033 | |rz| 0.9573
G1 | step   750/2000 | best 11608.0 | acc 99.8624% | success 0/128 | gamma 0.62531 | |rz| 0.9599
G1 | step   800/2000 | best 11608.0 | acc 99.8624% | success 0/128 | gamma 0.60030 | |rz| 0.9623
G1 | step   850/2000 | best 11608.0 | acc 99.8624% | success 0/128 | gamma 0.57529 | |rz| 0.9646
G1 | step   900/2000 | best 11608.0 | acc 99.8624% | success 0/128 | gamma 0.55028 | |rz| 0.9668
G1 | step   950/2000 | best 11608.0 | acc 99.8624% | success 0/128 | gamma 0.52526 | |rz| 0.9690
G1 | step  1000/2000 | best 11608.0 | acc 99.8624% | success 0/128 | gamma 0.50025 | |rz| 0.9710
G1 | step  1050/2000 | best 11608.0 | acc 99.8624% | success 0/128 | gamma 0.47524 | |rz| 0.9730
G1 | step  1100/2000 | best 11608.0 | acc 99.8624% | success 0/128 | gamma 0.45023 | |rz| 0.9749
G1 | step  1150/2000 | best 11608.0 | acc 99.8624% | success 0/128 | gamma 0.42521 | |rz| 0.9767
G1 | step  1200/2000 | best 11608.0 | acc 99.8624% | success 0/128 | gamma 0.40020 | |rz| 0.9785
G1 | step  1250/2000 | best 11608.0 | acc 99.8624% | success 0/128 | gamma 0.37519 | |rz| 0.9801
G1 | step  1300/2000 | best 11608.0 | acc 99.8624% | success 0/128 | gamma 0.35018 | |rz| 0.9817
G1 | step  1350/2000 | best 11608.0 | acc 99.8624% | success 0/128 | gamma 0.32517 | |rz| 0.9832
G1 | step  1400/2000 | best 11608.0 | acc 99.8624% | success 0/128 | gamma 0.30034 | |rz| 0.9845
G1 | step  1450/2000 | best 11608.0 | acc 99.8624% | success 0/128 | gamma 0.27732 | |rz| 0.9858
G1 | step  1500/2000 | best 11608.0 | acc 99.8624% | success 0/128 | gamma 0.26252 | |rz| 0.9867
G1 | step  1550/2000 | best 11608.0 | acc 99.8624% | success 0/128 | gamma 0.26035 | |rz| 0.9870
G1 | step  1600/2000 | best 11608.0 | acc 99.8624% | success 0/128 | gamma 0.25010 | |rz| 0.9877
G1 | step  1650/2000 | best 11608.0 | acc 99.8624% | success 0/128 | gamma 0.21052 | |rz| 0.9893
G1 | step  1700/2000 | best 11608.0 | acc 99.8624% | success 0/128 | gamma 0.16261 | |rz| 0.9908
G1 | step  1750/2000 | best 11608.0 | acc 99.8624% | success 0/128 | gamma 0.12728 | |rz| 0.9917
G1 | step  1800/2000 | best 11608.0 | acc 99.8624% | success 0/128 | gamma 0.10025 | |rz| 0.9923
G1 | step  1850/2000 | best 11608.0 | acc 99.8624% | success 0/128 | gamma 0.07505 | |rz| 0.9928
G1 | step  1900/2000 | best 11608.0 | acc 99.8624% | success 0/128 | gamma 0.05003 | |rz| 0.9931
G1 | step  1950/2000 | best 11608.0 | acc 99.8624% | success 0/128 | gamma 0.02501 | |rz| 0.9934
G1 | step  2000/2000 | best 11608.0 | acc 99.8624% | success 0/128 | gamma 0.00000 | |rz| 0.9942

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G1
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644267e-05,0.000040,0.000015,1.485700e-05,0.001719
1,theta_grad_mean_abs,6.242242e-07,0.000002,0.000002,2.543468e-07,0.000705
2,raw_R_step_mean_abs,2.999592e-02,0.002024,0.001553,1.553187e-03,0.050150
3,theta_step_mean_abs,2.864999e-02,0.000188,0.000293,9.516183e-05,0.046877
4,raw_R_grad_norm,2.446167e-02,0.013975,0.005083,5.083023e-03,0.639630
5,theta_grad_norm,2.498965e-04,0.001966,0.002931,1.025876e-04,0.312282
6,raw_R_step_norm,9.598694e+00,0.671496,0.532780,5.327798e-01,16.053396
7,theta_step_norm,9.208692e+00,0.147751,0.414617,1.436614e-01,15.662506

--------------------------------------------------------------------------------
RESULT SUMMARY: G1
--------------------------------------------------------------------------------
historical_best: 11624.0

V1:
v1_best: 11611.0
v1_gap: 13.0
v1_percent_accuracy: 99.88816242257398

V2:
v2_best: 11608.0
v2_gap: 16.0
v2_percent_accuracy: 99.8623537508603
v2_best_step: 675
v2_best_replica: 49

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 14.494951009750366

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/logs/G1_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/best_spins/G1_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/partial_group_results.csv

################################################################################
RUNNING G2 | dense | seed=8
################################################################################
G2 | step     1/2000 | best 9708.0 | acc 83.5456% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G2 | step    50/2000 | best 10102.0 | acc 86.9363% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G2 | step   100/2000 | best 11448.0 | acc 98.5198% | success 0/128 | gamma 0.95048 | |rz| 0.1031
G2 | step   150/2000 | best 11563.0 | acc 99.5095% | success 0/128 | gamma 0.92546 | |rz| 0.8377
G2 | step   200/2000 | best 11573.0 | acc 99.5955% | success 0/128 | gamma 0.90045 | |rz| 0.9018
G2 | step   250/2000 | best 11583.0 | acc 99.6816% | success 0/128 | gamma 0.87544 | |rz| 0.9185
G2 | step   300/2000 | best 11596.0 | acc 99.7935% | success 0/128 | gamma 0.85043 | |rz| 0.9271
G2 | step   350/2000 | best 11603.0 | acc 99.8537% | success 0/128 | gamma 0.82541 | |rz| 0.9330
G2 | step   400/2000 | best 11604.0 | acc 99.8623% | success 0/128 | gamma 0.80040 | |rz| 0.9378
G2 | step   450/2000 | best 11604.0 | acc 99.8623% | success 0/128 | gamma 0.77539 | |rz| 0.9418
G2 | step   500/2000 | best 11604.0 | acc 99.8623% | success 0/128 | gamma 0.75038 | |rz| 0.9452
G2 | step   550/2000 | best 11604.0 | acc 99.8623% | success 0/128 | gamma 0.72536 | |rz| 0.9486
G2 | step   600/2000 | best 11604.0 | acc 99.8623% | success 0/128 | gamma 0.70035 | |rz| 0.9515
G2 | step   650/2000 | best 11604.0 | acc 99.8623% | success 0/128 | gamma 0.67534 | |rz| 0.9543
G2 | step   700/2000 | best 11604.0 | acc 99.8623% | success 0/128 | gamma 0.65033 | |rz| 0.9570
G2 | step   750/2000 | best 11604.0 | acc 99.8623% | success 0/128 | gamma 0.62531 | |rz| 0.9595
G2 | step   800/2000 | best 11604.0 | acc 99.8623% | success 0/128 | gamma 0.60030 | |rz| 0.9619
G2 | step   850/2000 | best 11604.0 | acc 99.8623% | success 0/128 | gamma 0.57529 | |rz| 0.9642
G2 | step   900/2000 | best 11604.0 | acc 99.8623% | success 0/128 | gamma 0.55028 | |rz| 0.9665
G2 | step   950/2000 | best 11604.0 | acc 99.8623% | success 0/128 | gamma 0.52526 | |rz| 0.9687
G2 | step  1000/2000 | best 11604.0 | acc 99.8623% | success 0/128 | gamma 0.50025 | |rz| 0.9708
G2 | step  1050/2000 | best 11604.0 | acc 99.8623% | success 0/128 | gamma 0.47524 | |rz| 0.9728
G2 | step  1100/2000 | best 11604.0 | acc 99.8623% | success 0/128 | gamma 0.45023 | |rz| 0.9747
G2 | step  1150/2000 | best 11604.0 | acc 99.8623% | success 0/128 | gamma 0.42521 | |rz| 0.9765
G2 | step  1200/2000 | best 11604.0 | acc 99.8623% | success 0/128 | gamma 0.40020 | |rz| 0.9783
G2 | step  1250/2000 | best 11604.0 | acc 99.8623% | success 0/128 | gamma 0.37519 | |rz| 0.9800
G2 | step  1300/2000 | best 11604.0 | acc 99.8623% | success 0/128 | gamma 0.35018 | |rz| 0.9816
G2 | step  1350/2000 | best 11604.0 | acc 99.8623% | success 0/128 | gamma 0.32517 | |rz| 0.9831
G2 | step  1400/2000 | best 11604.0 | acc 99.8623% | success 0/128 | gamma 0.30034 | |rz| 0.9846
G2 | step  1450/2000 | best 11604.0 | acc 99.8623% | success 0/128 | gamma 0.27732 | |rz| 0.9858
G2 | step  1500/2000 | best 11604.0 | acc 99.8623% | success 0/128 | gamma 0.26252 | |rz| 0.9867
G2 | step  1550/2000 | best 11604.0 | acc 99.8623% | success 0/128 | gamma 0.26035 | |rz| 0.9871
G2 | step  1600/2000 | best 11604.0 | acc 99.8623% | success 0/128 | gamma 0.25010 | |rz| 0.9878
G2 | step  1650/2000 | best 11604.0 | acc 99.8623% | success 0/128 | gamma 0.21052 | |rz| 0.9894
G2 | step  1700/2000 | best 11604.0 | acc 99.8623% | success 0/128 | gamma 0.16261 | |rz| 0.9909
G2 | step  1750/2000 | best 11604.0 | acc 99.8623% | success 0/128 | gamma 0.12728 | |rz| 0.9919
G2 | step  1800/2000 | best 11604.0 | acc 99.8623% | success 0/128 | gamma 0.10025 | |rz| 0.9925
G2 | step  1850/2000 | best 11604.0 | acc 99.8623% | success 0/128 | gamma 0.07505 | |rz| 0.9929
G2 | step  1900/2000 | best 11604.0 | acc 99.8623% | success 0/128 | gamma 0.05003 | |rz| 0.9933
G2 | step  1950/2000 | best 11604.0 | acc 99.8623% | success 0/128 | gamma 0.02501 | |rz| 0.9936
G2 | step  2000/2000 | best 11604.0 | acc 99.8623% | success 0/128 | gamma 0.00000 | |rz| 0.9944

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G2
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644282e-05,0.000040,0.000015,1.490432e-05,0.001724
1,theta_grad_mean_abs,6.263898e-07,0.000002,0.000002,2.547293e-07,0.000707
2,raw_R_step_mean_abs,2.999592e-02,0.002024,0.001555,1.555471e-03,0.050158
3,theta_step_mean_abs,2.864580e-02,0.000198,0.000298,1.025940e-04,0.046914
4,raw_R_grad_norm,2.446171e-02,0.014066,0.005101,5.101449e-03,0.641555
5,theta_grad_norm,2.513030e-04,0.002297,0.002924,1.026652e-04,0.314076
6,raw_R_step_norm,9.598694e+00,0.678251,0.534031,5.340307e-01,16.056181
7,theta_step_norm,9.206573e+00,0.253573,0.426900,1.261082e-01,15.672079

--------------------------------------------------------------------------------
RESULT SUMMARY: G2
--------------------------------------------------------------------------------
historical_best: 11620.0

V1:
v1_best: 11610.0
v1_gap: 10.0
v1_percent_accuracy: 99.91394148020656

V2:
v2_best: 11604.0
v2_gap: 16.0
v2_percent_accuracy: 99.86230636833047
v2_best_step: 352
v2_best_replica: 120

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 13.602811813354492

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/logs/G2_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/best_spins/G2_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/partial_group_results.csv

################################################################################
RUNNING G3 | dense | seed=9
################################################################################
G3 | step     1/2000 | best 9689.0 | acc 83.3678% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G3 | step    50/2000 | best 10085.0 | acc 86.7751% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G3 | step   100/2000 | best 11463.0 | acc 98.6319% | success 0/128 | gamma 0.95048 | |rz| 0.1070
G3 | step   150/2000 | best 11589.0 | acc 99.7161% | success 0/128 | gamma 0.92546 | |rz| 0.8376
G3 | step   200/2000 | best 11612.0 | acc 99.9140% | success 0/128 | gamma 0.90045 | |rz| 0.9019
G3 | step   250/2000 | best 11617.0 | acc 99.9570% | success 0/128 | gamma 0.87544 | |rz| 0.9185
G3 | step   300/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.85043 | |rz| 0.9271
G3 | step   350/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.82541 | |rz| 0.9332
G3 | step   400/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.80040 | |rz| 0.9379
G3 | step   450/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.77539 | |rz| 0.9419
G3 | step   500/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.75038 | |rz| 0.9454
G3 | step   550/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.72536 | |rz| 0.9487
G3 | step   600/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.70035 | |rz| 0.9518
G3 | step   650/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.67534 | |rz| 0.9546
G3 | step   700/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.65033 | |rz| 0.9572
G3 | step   750/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.62531 | |rz| 0.9598
G3 | step   800/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.60030 | |rz| 0.9622
G3 | step   850/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.57529 | |rz| 0.9645
G3 | step   900/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.55028 | |rz| 0.9668
G3 | step   950/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.52526 | |rz| 0.9689
G3 | step  1000/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.50025 | |rz| 0.9710
G3 | step  1050/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.47524 | |rz| 0.9730
G3 | step  1100/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.45023 | |rz| 0.9749
G3 | step  1150/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.42521 | |rz| 0.9767
G3 | step  1200/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.40020 | |rz| 0.9785
G3 | step  1250/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.37519 | |rz| 0.9801
G3 | step  1300/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.35018 | |rz| 0.9817
G3 | step  1350/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.32517 | |rz| 0.9832
G3 | step  1400/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.30034 | |rz| 0.9846
G3 | step  1450/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.27732 | |rz| 0.9859
G3 | step  1500/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.26252 | |rz| 0.9868
G3 | step  1550/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.26035 | |rz| 0.9871
G3 | step  1600/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.25010 | |rz| 0.9878
G3 | step  1650/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.21052 | |rz| 0.9894
G3 | step  1700/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.16261 | |rz| 0.9909
G3 | step  1750/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.12728 | |rz| 0.9918
G3 | step  1800/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.10025 | |rz| 0.9924
G3 | step  1850/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.07505 | |rz| 0.9929
G3 | step  1900/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.05003 | |rz| 0.9933
G3 | step  1950/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.02501 | |rz| 0.9936
G3 | step  2000/2000 | best 11619.0 | acc 99.9742% | success 0/128 | gamma 0.00000 | |rz| 0.9943

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G3
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644322e-05,0.000040,0.000015,1.496305e-05,0.001730
1,theta_grad_mean_abs,6.241841e-07,0.000002,0.000002,2.539639e-07,0.000737
2,raw_R_step_mean_abs,2.999592e-02,0.002030,0.001553,1.553018e-03,0.050290
3,theta_step_mean_abs,2.864725e-02,0.000209,0.000292,9.732954e-05,0.047378
4,raw_R_grad_norm,2.446184e-02,0.014189,0.005124,5.123748e-03,0.643981
5,theta_grad_norm,2.503107e-04,0.003327,0.003010,1.022976e-04,0.328056
6,raw_R_step_norm,9.598694e+00,0.682302,0.533006,5.330055e-01,16.099369
7,theta_step_norm,9.207195e+00,0.320180,0.397592,1.397205e-01,15.819397

--------------------------------------------------------------------------------
RESULT SUMMARY: G3
--------------------------------------------------------------------------------
historical_best: 11622.0

V1:
v1_best: 11610.0
v1_gap: 12.0
v1_percent_accuracy: 99.89674754775426

V2:
v2_best: 11619.0
v2_gap: 3.0
v2_percent_accuracy: 99.97418688693857
v2_best_step: 280
v2_best_replica: 104

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 13.859736204147339

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/logs/G3_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/best_spins/G3_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/partial_group_results.csv

################################################################################
RUNNING G4 | dense | seed=10
################################################################################
G4 | step     1/2000 | best 9714.0 | acc 83.4106% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G4 | step    50/2000 | best 10070.0 | acc 86.4675% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G4 | step   100/2000 | best 11501.0 | acc 98.7549% | success 0/128 | gamma 0.95048 | |rz| 0.1107
G4 | step   150/2000 | best 11602.0 | acc 99.6222% | success 0/128 | gamma 0.92546 | |rz| 0.8385
G4 | step   200/2000 | best 11624.0 | acc 99.8111% | success 0/128 | gamma 0.90045 | |rz| 0.9026
G4 | step   250/2000 | best 11628.0 | acc 99.8454% | success 0/128 | gamma 0.87544 | |rz| 0.9188
G4 | step   300/2000 | best 11628.0 | acc 99.8454% | success 0/128 | gamma 0.85043 | |rz| 0.9275
G4 | step   350/2000 | best 11628.0 | acc 99.8454% | success 0/128 | gamma 0.82541 | |rz| 0.9336
G4 | step   400/2000 | best 11632.0 | acc 99.8798% | success 0/128 | gamma 0.80040 | |rz| 0.9384
G4 | step   450/2000 | best 11635.0 | acc 99.9055% | success 0/128 | gamma 0.77539 | |rz| 0.9425
G4 | step   500/2000 | best 11635.0 | acc 99.9055% | success 0/128 | gamma 0.75038 | |rz| 0.9459
G4 | step   550/2000 | best 11635.0 | acc 99.9055% | success 0/128 | gamma 0.72536 | |rz| 0.9489
G4 | step   600/2000 | best 11635.0 | acc 99.9055% | success 0/128 | gamma 0.70035 | |rz| 0.9518
G4 | step   650/2000 | best 11635.0 | acc 99.9055% | success 0/128 | gamma 0.67534 | |rz| 0.9546
G4 | step   700/2000 | best 11635.0 | acc 99.9055% | success 0/128 | gamma 0.65033 | |rz| 0.9573
G4 | step   750/2000 | best 11635.0 | acc 99.9055% | success 0/128 | gamma 0.62531 | |rz| 0.9598
G4 | step   800/2000 | best 11636.0 | acc 99.9141% | success 0/128 | gamma 0.60030 | |rz| 0.9622
G4 | step   850/2000 | best 11636.0 | acc 99.9141% | success 0/128 | gamma 0.57529 | |rz| 0.9645
G4 | step   900/2000 | best 11636.0 | acc 99.9141% | success 0/128 | gamma 0.55028 | |rz| 0.9667
G4 | step   950/2000 | best 11636.0 | acc 99.9141% | success 0/128 | gamma 0.52526 | |rz| 0.9689
G4 | step  1000/2000 | best 11636.0 | acc 99.9141% | success 0/128 | gamma 0.50025 | |rz| 0.9709
G4 | step  1050/2000 | best 11636.0 | acc 99.9141% | success 0/128 | gamma 0.47524 | |rz| 0.9729
G4 | step  1100/2000 | best 11636.0 | acc 99.9141% | success 0/128 | gamma 0.45023 | |rz| 0.9748
G4 | step  1150/2000 | best 11636.0 | acc 99.9141% | success 0/128 | gamma 0.42521 | |rz| 0.9765
G4 | step  1200/2000 | best 11636.0 | acc 99.9141% | success 0/128 | gamma 0.40020 | |rz| 0.9783
G4 | step  1250/2000 | best 11636.0 | acc 99.9141% | success 0/128 | gamma 0.37519 | |rz| 0.9799
G4 | step  1300/2000 | best 11636.0 | acc 99.9141% | success 0/128 | gamma 0.35018 | |rz| 0.9815
G4 | step  1350/2000 | best 11636.0 | acc 99.9141% | success 0/128 | gamma 0.32517 | |rz| 0.9830
G4 | step  1400/2000 | best 11636.0 | acc 99.9141% | success 0/128 | gamma 0.30034 | |rz| 0.9844
G4 | step  1450/2000 | best 11636.0 | acc 99.9141% | success 0/128 | gamma 0.27732 | |rz| 0.9857
G4 | step  1500/2000 | best 11636.0 | acc 99.9141% | success 0/128 | gamma 0.26252 | |rz| 0.9865
G4 | step  1550/2000 | best 11636.0 | acc 99.9141% | success 0/128 | gamma 0.26035 | |rz| 0.9869
G4 | step  1600/2000 | best 11636.0 | acc 99.9141% | success 0/128 | gamma 0.25010 | |rz| 0.9876
G4 | step  1650/2000 | best 11636.0 | acc 99.9141% | success 0/128 | gamma 0.21052 | |rz| 0.9891
G4 | step  1700/2000 | best 11636.0 | acc 99.9141% | success 0/128 | gamma 0.16261 | |rz| 0.9906
G4 | step  1750/2000 | best 11636.0 | acc 99.9141% | success 0/128 | gamma 0.12728 | |rz| 0.9916
G4 | step  1800/2000 | best 11636.0 | acc 99.9141% | success 0/128 | gamma 0.10025 | |rz| 0.9921
G4 | step  1850/2000 | best 11636.0 | acc 99.9141% | success 0/128 | gamma 0.07505 | |rz| 0.9926
G4 | step  1900/2000 | best 11636.0 | acc 99.9141% | success 0/128 | gamma 0.05003 | |rz| 0.9930
G4 | step  1950/2000 | best 11636.0 | acc 99.9141% | success 0/128 | gamma 0.02501 | |rz| 0.9933
G4 | step  2000/2000 | best 11636.0 | acc 99.9141% | success 0/128 | gamma 0.00000 | |rz| 0.9940

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G4
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644263e-05,0.000040,0.000015,1.507641e-05,0.001747
1,theta_grad_mean_abs,6.235636e-07,0.000002,0.000002,2.549578e-07,0.000773
2,raw_R_step_mean_abs,2.999592e-02,0.002026,0.001549,1.548980e-03,0.050415
3,theta_step_mean_abs,2.864324e-02,0.000193,0.000296,1.015236e-04,0.047851
4,raw_R_grad_norm,2.446165e-02,0.014276,0.005168,5.168479e-03,0.651816
5,theta_grad_norm,2.500061e-04,0.002003,0.002974,1.028882e-04,0.343952
6,raw_R_step_norm,9.598694e+00,0.671126,0.531528,5.315276e-01,16.140396
7,theta_step_norm,9.206169e+00,0.145862,0.418002,1.448817e-01,15.965192

--------------------------------------------------------------------------------
RESULT SUMMARY: G4
--------------------------------------------------------------------------------
historical_best: 11646.0

V1:
v1_best: 11637.0
v1_gap: 9.0
v1_percent_accuracy: 99.9227202472952

V2:
v2_best: 11636.0
v2_gap: 10.0
v2_percent_accuracy: 99.91413360810579
v2_best_step: 799
v2_best_replica: 67

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 14.753981351852417

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/logs/G4_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/best_spins/G4_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/partial_group_results.csv

################################################################################
RUNNING G5 | dense | seed=11
################################################################################
G5 | step     1/2000 | best 9705.0 | acc 83.4408% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G5 | step    50/2000 | best 10111.0 | acc 86.9315% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G5 | step   100/2000 | best 11486.0 | acc 98.7533% | success 0/128 | gamma 0.95048 | |rz| 0.1097
G5 | step   150/2000 | best 11590.0 | acc 99.6475% | success 0/128 | gamma 0.92546 | |rz| 0.8379
G5 | step   200/2000 | best 11604.0 | acc 99.7679% | success 0/128 | gamma 0.90045 | |rz| 0.9011
G5 | step   250/2000 | best 11605.0 | acc 99.7765% | success 0/128 | gamma 0.87544 | |rz| 0.9174
G5 | step   300/2000 | best 11606.0 | acc 99.7851% | success 0/128 | gamma 0.85043 | |rz| 0.9261
G5 | step   350/2000 | best 11606.0 | acc 99.7851% | success 0/128 | gamma 0.82541 | |rz| 0.9320
G5 | step   400/2000 | best 11609.0 | acc 99.8109% | success 0/128 | gamma 0.80040 | |rz| 0.9368
G5 | step   450/2000 | best 11617.0 | acc 99.8796% | success 0/128 | gamma 0.77539 | |rz| 0.9409
G5 | step   500/2000 | best 11619.0 | acc 99.8968% | success 0/128 | gamma 0.75038 | |rz| 0.9445
G5 | step   550/2000 | best 11619.0 | acc 99.8968% | success 0/128 | gamma 0.72536 | |rz| 0.9478
G5 | step   600/2000 | best 11619.0 | acc 99.8968% | success 0/128 | gamma 0.70035 | |rz| 0.9510
G5 | step   650/2000 | best 11619.0 | acc 99.8968% | success 0/128 | gamma 0.67534 | |rz| 0.9538
G5 | step   700/2000 | best 11619.0 | acc 99.8968% | success 0/128 | gamma 0.65033 | |rz| 0.9565
G5 | step   750/2000 | best 11619.0 | acc 99.8968% | success 0/128 | gamma 0.62531 | |rz| 0.9592
G5 | step   800/2000 | best 11619.0 | acc 99.8968% | success 0/128 | gamma 0.60030 | |rz| 0.9616
G5 | step   850/2000 | best 11619.0 | acc 99.8968% | success 0/128 | gamma 0.57529 | |rz| 0.9639
G5 | step   900/2000 | best 11619.0 | acc 99.8968% | success 0/128 | gamma 0.55028 | |rz| 0.9662
G5 | step   950/2000 | best 11619.0 | acc 99.8968% | success 0/128 | gamma 0.52526 | |rz| 0.9684
G5 | step  1000/2000 | best 11619.0 | acc 99.8968% | success 0/128 | gamma 0.50025 | |rz| 0.9705
G5 | step  1050/2000 | best 11619.0 | acc 99.8968% | success 0/128 | gamma 0.47524 | |rz| 0.9724
G5 | step  1100/2000 | best 11619.0 | acc 99.8968% | success 0/128 | gamma 0.45023 | |rz| 0.9743
G5 | step  1150/2000 | best 11619.0 | acc 99.8968% | success 0/128 | gamma 0.42521 | |rz| 0.9762
G5 | step  1200/2000 | best 11619.0 | acc 99.8968% | success 0/128 | gamma 0.40020 | |rz| 0.9779
G5 | step  1250/2000 | best 11619.0 | acc 99.8968% | success 0/128 | gamma 0.37519 | |rz| 0.9796
G5 | step  1300/2000 | best 11619.0 | acc 99.8968% | success 0/128 | gamma 0.35018 | |rz| 0.9812
G5 | step  1350/2000 | best 11619.0 | acc 99.8968% | success 0/128 | gamma 0.32517 | |rz| 0.9827
G5 | step  1400/2000 | best 11619.0 | acc 99.8968% | success 0/128 | gamma 0.30034 | |rz| 0.9841
G5 | step  1450/2000 | best 11619.0 | acc 99.8968% | success 0/128 | gamma 0.27732 | |rz| 0.9854
G5 | step  1500/2000 | best 11619.0 | acc 99.8968% | success 0/128 | gamma 0.26252 | |rz| 0.9863
G5 | step  1550/2000 | best 11619.0 | acc 99.8968% | success 0/128 | gamma 0.26035 | |rz| 0.9866
G5 | step  1600/2000 | best 11619.0 | acc 99.8968% | success 0/128 | gamma 0.25010 | |rz| 0.9873
G5 | step  1650/2000 | best 11619.0 | acc 99.8968% | success 0/128 | gamma 0.21052 | |rz| 0.9889
G5 | step  1700/2000 | best 11619.0 | acc 99.8968% | success 0/128 | gamma 0.16261 | |rz| 0.9904
G5 | step  1750/2000 | best 11619.0 | acc 99.8968% | success 0/128 | gamma 0.12728 | |rz| 0.9913
G5 | step  1800/2000 | best 11619.0 | acc 99.8968% | success 0/128 | gamma 0.10025 | |rz| 0.9919
G5 | step  1850/2000 | best 11619.0 | acc 99.8968% | success 0/128 | gamma 0.07505 | |rz| 0.9924
G5 | step  1900/2000 | best 11619.0 | acc 99.8968% | success 0/128 | gamma 0.05003 | |rz| 0.9927
G5 | step  1950/2000 | best 11619.0 | acc 99.8968% | success 0/128 | gamma 0.02501 | |rz| 0.9930
G5 | step  2000/2000 | best 11619.0 | acc 99.8968% | success 0/128 | gamma 0.00000 | |rz| 0.9939

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G5
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644299e-05,0.000040,0.000015,1.502319e-05,0.001739
1,theta_grad_mean_abs,6.219420e-07,0.000002,0.000002,2.550346e-07,0.000765
2,raw_R_step_mean_abs,2.999592e-02,0.002029,0.001555,1.555026e-03,0.050380
3,theta_step_mean_abs,2.863445e-02,0.000193,0.000303,9.831952e-05,0.047741
4,raw_R_grad_norm,2.446177e-02,0.014242,0.005149,5.148728e-03,0.650089
5,theta_grad_norm,2.496569e-04,0.001925,0.002880,1.028419e-04,0.341438
6,raw_R_step_norm,9.598694e+00,0.673192,0.534234,5.342345e-01,16.128998
7,theta_step_norm,9.203908e+00,0.142106,0.435796,1.362342e-01,15.930723

--------------------------------------------------------------------------------
RESULT SUMMARY: G5
--------------------------------------------------------------------------------
historical_best: 11631.0

V1:
v1_best: 11622.0
v1_gap: 9.0
v1_percent_accuracy: 99.92262058292494

V2:
v2_best: 11619.0
v2_gap: 12.0
v2_percent_accuracy: 99.89682744389992
v2_best_step: 476
v2_best_replica: 10

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 14.187588214874268

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/logs/G5_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/best_spins/G5_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/partial_group_results.csv

################################################################################
RUNNING G6 | dense | seed=12
################################################################################
G6 | step     1/2000 | best 198.0 | acc 9.0909% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G6 | step    50/2000 | best 568.0 | acc 26.0790% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G6 | step   100/2000 | best 2114.0 | acc 97.0615% | success 0/128 | gamma 0.95048 | |rz| 0.2596
G6 | step   150/2000 | best 2157.0 | acc 99.0358% | success 0/128 | gamma 0.92546 | |rz| 0.8468
G6 | step   200/2000 | best 2163.0 | acc 99.3113% | success 0/128 | gamma 0.90045 | |rz| 0.9051
G6 | step   250/2000 | best 2165.0 | acc 99.4031% | success 0/128 | gamma 0.87544 | |rz| 0.9209
G6 | step   300/2000 | best 2166.0 | acc 99.4490% | success 0/128 | gamma 0.85043 | |rz| 0.9292
G6 | step   350/2000 | best 2166.0 | acc 99.4490% | success 0/128 | gamma 0.82541 | |rz| 0.9350
G6 | step   400/2000 | best 2166.0 | acc 99.4490% | success 0/128 | gamma 0.80040 | |rz| 0.9395
G6 | step   450/2000 | best 2166.0 | acc 99.4490% | success 0/128 | gamma 0.77539 | |rz| 0.9433
G6 | step   500/2000 | best 2167.0 | acc 99.4949% | success 0/128 | gamma 0.75038 | |rz| 0.9466
G6 | step   550/2000 | best 2167.0 | acc 99.4949% | success 0/128 | gamma 0.72536 | |rz| 0.9498
G6 | step   600/2000 | best 2167.0 | acc 99.4949% | success 0/128 | gamma 0.70035 | |rz| 0.9528
G6 | step   650/2000 | best 2167.0 | acc 99.4949% | success 0/128 | gamma 0.67534 | |rz| 0.9556
G6 | step   700/2000 | best 2167.0 | acc 99.4949% | success 0/128 | gamma 0.65033 | |rz| 0.9582
G6 | step   750/2000 | best 2167.0 | acc 99.4949% | success 0/128 | gamma 0.62531 | |rz| 0.9607
G6 | step   800/2000 | best 2167.0 | acc 99.4949% | success 0/128 | gamma 0.60030 | |rz| 0.9631
G6 | step   850/2000 | best 2167.0 | acc 99.4949% | success 0/128 | gamma 0.57529 | |rz| 0.9653
G6 | step   900/2000 | best 2167.0 | acc 99.4949% | success 0/128 | gamma 0.55028 | |rz| 0.9675
G6 | step   950/2000 | best 2167.0 | acc 99.4949% | success 0/128 | gamma 0.52526 | |rz| 0.9696
G6 | step  1000/2000 | best 2167.0 | acc 99.4949% | success 0/128 | gamma 0.50025 | |rz| 0.9715
G6 | step  1050/2000 | best 2167.0 | acc 99.4949% | success 0/128 | gamma 0.47524 | |rz| 0.9735
G6 | step  1100/2000 | best 2167.0 | acc 99.4949% | success 0/128 | gamma 0.45023 | |rz| 0.9753
G6 | step  1150/2000 | best 2167.0 | acc 99.4949% | success 0/128 | gamma 0.42521 | |rz| 0.9771
G6 | step  1200/2000 | best 2167.0 | acc 99.4949% | success 0/128 | gamma 0.40020 | |rz| 0.9788
G6 | step  1250/2000 | best 2167.0 | acc 99.4949% | success 0/128 | gamma 0.37519 | |rz| 0.9804
G6 | step  1300/2000 | best 2167.0 | acc 99.4949% | success 0/128 | gamma 0.35018 | |rz| 0.9819
G6 | step  1350/2000 | best 2167.0 | acc 99.4949% | success 0/128 | gamma 0.32517 | |rz| 0.9834
G6 | step  1400/2000 | best 2167.0 | acc 99.4949% | success 0/128 | gamma 0.30034 | |rz| 0.9848
G6 | step  1450/2000 | best 2167.0 | acc 99.4949% | success 0/128 | gamma 0.27732 | |rz| 0.9861
G6 | step  1500/2000 | best 2167.0 | acc 99.4949% | success 0/128 | gamma 0.26252 | |rz| 0.9869
G6 | step  1550/2000 | best 2167.0 | acc 99.4949% | success 0/128 | gamma 0.26035 | |rz| 0.9873
G6 | step  1600/2000 | best 2167.0 | acc 99.4949% | success 0/128 | gamma 0.25010 | |rz| 0.9879
G6 | step  1650/2000 | best 2167.0 | acc 99.4949% | success 0/128 | gamma 0.21052 | |rz| 0.9895
G6 | step  1700/2000 | best 2167.0 | acc 99.4949% | success 0/128 | gamma 0.16261 | |rz| 0.9910
G6 | step  1750/2000 | best 2167.0 | acc 99.4949% | success 0/128 | gamma 0.12728 | |rz| 0.9919
G6 | step  1800/2000 | best 2167.0 | acc 99.4949% | success 0/128 | gamma 0.10025 | |rz| 0.9925
G6 | step  1850/2000 | best 2167.0 | acc 99.4949% | success 0/128 | gamma 0.07505 | |rz| 0.9929
G6 | step  1900/2000 | best 2167.0 | acc 99.4949% | success 0/128 | gamma 0.05003 | |rz| 0.9933
G6 | step  1950/2000 | best 2167.0 | acc 99.4949% | success 0/128 | gamma 0.02501 | |rz| 0.9936
G6 | step  2000/2000 | best 2167.0 | acc 99.4949% | success 0/128 | gamma 0.00000 | |rz| 0.9947

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G6
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644250e-05,0.000044,0.000016,1.639791e-05,0.002190
1,theta_grad_mean_abs,6.274053e-07,0.000003,0.000004,2.504376e-07,0.001161
2,raw_R_step_mean_abs,2.999592e-02,0.002000,0.001536,1.535711e-03,0.057127
3,theta_step_mean_abs,2.865303e-02,0.000323,0.000487,2.807398e-04,0.056344
4,raw_R_grad_norm,2.446161e-02,0.015738,0.005607,5.606712e-03,0.770946
5,theta_grad_norm,2.517722e-04,0.002976,0.004625,1.011659e-04,0.537346
6,raw_R_step_norm,9.598694e+00,0.655349,0.529406,5.294057e-01,18.346132
7,theta_step_norm,9.208717e+00,0.218006,0.727135,2.180056e-01,18.645466

--------------------------------------------------------------------------------
RESULT SUMMARY: G6
--------------------------------------------------------------------------------
historical_best: 2178.0

V1:
v1_best: 2173.0
v1_gap: 5.0
v1_percent_accuracy: 99.7704315886134

V2:
v2_best: 2167.0
v2_gap: 11.0
v2_percent_accuracy: 99.4949494949495
v2_best_step: 500
v2_best_replica: 59

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 14.31351613998413

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/logs/G6_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/best_spins/G6_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/partial_group_results.csv

################################################################################
RUNNING G7 | dense | seed=13
################################################################################
G7 | step     1/2000 | best 58.0 | acc 2.8913% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G7 | step    50/2000 | best 412.0 | acc 20.5384% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G7 | step   100/2000 | best 1929.0 | acc 96.1615% | success 0/128 | gamma 0.95048 | |rz| 0.2558
G7 | step   150/2000 | best 1979.0 | acc 98.6540% | success 0/128 | gamma 0.92546 | |rz| 0.8455
G7 | step   200/2000 | best 1981.0 | acc 98.7537% | success 0/128 | gamma 0.90045 | |rz| 0.9044
G7 | step   250/2000 | best 1981.0 | acc 98.7537% | success 0/128 | gamma 0.87544 | |rz| 0.9206
G7 | step   300/2000 | best 1981.0 | acc 98.7537% | success 0/128 | gamma 0.85043 | |rz| 0.9289
G7 | step   350/2000 | best 1981.0 | acc 98.7537% | success 0/128 | gamma 0.82541 | |rz| 0.9347
G7 | step   400/2000 | best 1989.0 | acc 99.1525% | success 0/128 | gamma 0.80040 | |rz| 0.9394
G7 | step   450/2000 | best 1997.0 | acc 99.5513% | success 0/128 | gamma 0.77539 | |rz| 0.9432
G7 | step   500/2000 | best 1998.0 | acc 99.6012% | success 0/128 | gamma 0.75038 | |rz| 0.9466
G7 | step   550/2000 | best 1998.0 | acc 99.6012% | success 0/128 | gamma 0.72536 | |rz| 0.9497
G7 | step   600/2000 | best 1998.0 | acc 99.6012% | success 0/128 | gamma 0.70035 | |rz| 0.9526
G7 | step   650/2000 | best 1998.0 | acc 99.6012% | success 0/128 | gamma 0.67534 | |rz| 0.9552
G7 | step   700/2000 | best 1998.0 | acc 99.6012% | success 0/128 | gamma 0.65033 | |rz| 0.9579
G7 | step   750/2000 | best 1998.0 | acc 99.6012% | success 0/128 | gamma 0.62531 | |rz| 0.9603
G7 | step   800/2000 | best 1998.0 | acc 99.6012% | success 0/128 | gamma 0.60030 | |rz| 0.9626
G7 | step   850/2000 | best 1998.0 | acc 99.6012% | success 0/128 | gamma 0.57529 | |rz| 0.9649
G7 | step   900/2000 | best 1998.0 | acc 99.6012% | success 0/128 | gamma 0.55028 | |rz| 0.9671
G7 | step   950/2000 | best 1998.0 | acc 99.6012% | success 0/128 | gamma 0.52526 | |rz| 0.9692
G7 | step  1000/2000 | best 1998.0 | acc 99.6012% | success 0/128 | gamma 0.50025 | |rz| 0.9711
G7 | step  1050/2000 | best 1998.0 | acc 99.6012% | success 0/128 | gamma 0.47524 | |rz| 0.9731
G7 | step  1100/2000 | best 1998.0 | acc 99.6012% | success 0/128 | gamma 0.45023 | |rz| 0.9749
G7 | step  1150/2000 | best 1998.0 | acc 99.6012% | success 0/128 | gamma 0.42521 | |rz| 0.9767
G7 | step  1200/2000 | best 1998.0 | acc 99.6012% | success 0/128 | gamma 0.40020 | |rz| 0.9784
G7 | step  1250/2000 | best 1998.0 | acc 99.6012% | success 0/128 | gamma 0.37519 | |rz| 0.9801
G7 | step  1300/2000 | best 1998.0 | acc 99.6012% | success 0/128 | gamma 0.35018 | |rz| 0.9816
G7 | step  1350/2000 | best 1998.0 | acc 99.6012% | success 0/128 | gamma 0.32517 | |rz| 0.9831
G7 | step  1400/2000 | best 1998.0 | acc 99.6012% | success 0/128 | gamma 0.30034 | |rz| 0.9845
G7 | step  1450/2000 | best 1998.0 | acc 99.6012% | success 0/128 | gamma 0.27732 | |rz| 0.9857
G7 | step  1500/2000 | best 1998.0 | acc 99.6012% | success 0/128 | gamma 0.26252 | |rz| 0.9866
G7 | step  1550/2000 | best 1998.0 | acc 99.6012% | success 0/128 | gamma 0.26035 | |rz| 0.9869
G7 | step  1600/2000 | best 1998.0 | acc 99.6012% | success 0/128 | gamma 0.25010 | |rz| 0.9876
G7 | step  1650/2000 | best 1998.0 | acc 99.6012% | success 0/128 | gamma 0.21052 | |rz| 0.9891
G7 | step  1700/2000 | best 1998.0 | acc 99.6012% | success 0/128 | gamma 0.16261 | |rz| 0.9906
G7 | step  1750/2000 | best 1998.0 | acc 99.6012% | success 0/128 | gamma 0.12728 | |rz| 0.9915
G7 | step  1800/2000 | best 1998.0 | acc 99.6012% | success 0/128 | gamma 0.10025 | |rz| 0.9921
G7 | step  1850/2000 | best 1998.0 | acc 99.6012% | success 0/128 | gamma 0.07505 | |rz| 0.9925
G7 | step  1900/2000 | best 1998.0 | acc 99.6012% | success 0/128 | gamma 0.05003 | |rz| 0.9929
G7 | step  1950/2000 | best 1998.0 | acc 99.6012% | success 0/128 | gamma 0.02501 | |rz| 0.9932
G7 | step  2000/2000 | best 1998.0 | acc 99.6012% | success 0/128 | gamma 0.00000 | |rz| 0.9944

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G7
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644293e-05,0.000044,0.000016,1.625287e-05,0.002143
1,theta_grad_mean_abs,6.273027e-07,0.000003,0.000004,2.508650e-07,0.001148
2,raw_R_step_mean_abs,2.999592e-02,0.002005,0.001536,1.535999e-03,0.056894
3,theta_step_mean_abs,2.865674e-02,0.000323,0.000502,2.795851e-04,0.056231
4,raw_R_grad_norm,2.446175e-02,0.015596,0.005562,5.562443e-03,0.754332
5,theta_grad_norm,2.515534e-04,0.002992,0.004695,1.011500e-04,0.534778
6,raw_R_step_norm,9.598694e+00,0.658524,0.528559,5.285588e-01,18.270689
7,theta_step_norm,9.209130e+00,0.220037,0.750978,2.183960e-01,18.603661

--------------------------------------------------------------------------------
RESULT SUMMARY: G7
--------------------------------------------------------------------------------
historical_best: 2006.0

V1:
v1_best: 1992.0
v1_gap: 14.0
v1_percent_accuracy: 99.30209371884348

V2:
v2_best: 1998.0
v2_gap: 8.0
v2_percent_accuracy: 99.6011964107677
v2_best_step: 451
v2_best_replica: 8

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 14.150901079177856

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/logs/G7_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/best_spins/G7_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/partial_group_results.csv

################################################################################
RUNNING G8 | dense | seed=14
################################################################################
G8 | step     1/2000 | best 45.0 | acc 2.2444% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G8 | step    50/2000 | best 411.0 | acc 20.4988% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G8 | step   100/2000 | best 1941.0 | acc 96.8080% | success 0/128 | gamma 0.95048 | |rz| 0.2604
G8 | step   150/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.92546 | |rz| 0.8469
G8 | step   200/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.90045 | |rz| 0.9055
G8 | step   250/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.87544 | |rz| 0.9210
G8 | step   300/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.85043 | |rz| 0.9295
G8 | step   350/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.82541 | |rz| 0.9353
G8 | step   400/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.80040 | |rz| 0.9398
G8 | step   450/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.77539 | |rz| 0.9436
G8 | step   500/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.75038 | |rz| 0.9469
G8 | step   550/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.72536 | |rz| 0.9500
G8 | step   600/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.70035 | |rz| 0.9529
G8 | step   650/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.67534 | |rz| 0.9557
G8 | step   700/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.65033 | |rz| 0.9582
G8 | step   750/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.62531 | |rz| 0.9607
G8 | step   800/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.60030 | |rz| 0.9630
G8 | step   850/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.57529 | |rz| 0.9653
G8 | step   900/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.55028 | |rz| 0.9675
G8 | step   950/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.52526 | |rz| 0.9696
G8 | step  1000/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.50025 | |rz| 0.9715
G8 | step  1050/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.47524 | |rz| 0.9735
G8 | step  1100/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.45023 | |rz| 0.9753
G8 | step  1150/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.42521 | |rz| 0.9771
G8 | step  1200/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.40020 | |rz| 0.9788
G8 | step  1250/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.37519 | |rz| 0.9804
G8 | step  1300/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.35018 | |rz| 0.9820
G8 | step  1350/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.32517 | |rz| 0.9834
G8 | step  1400/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.30034 | |rz| 0.9848
G8 | step  1450/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.27732 | |rz| 0.9860
G8 | step  1500/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.26252 | |rz| 0.9868
G8 | step  1550/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.26035 | |rz| 0.9872
G8 | step  1600/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.25010 | |rz| 0.9879
G8 | step  1650/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.21052 | |rz| 0.9894
G8 | step  1700/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.16261 | |rz| 0.9909
G8 | step  1750/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.12728 | |rz| 0.9918
G8 | step  1800/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.10025 | |rz| 0.9924
G8 | step  1850/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.07505 | |rz| 0.9928
G8 | step  1900/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.05003 | |rz| 0.9932
G8 | step  1950/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.02501 | |rz| 0.9935
G8 | step  2000/2000 | best 1994.0 | acc 99.4514% | success 0/128 | gamma 0.00000 | |rz| 0.9946

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G8
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644234e-05,0.000044,0.000016,1.638863e-05,0.002200
1,theta_grad_mean_abs,6.248145e-07,0.000003,0.000004,2.503447e-07,0.001157
2,raw_R_step_mean_abs,2.999592e-02,0.002002,0.001534,1.533834e-03,0.057153
3,theta_step_mean_abs,2.865395e-02,0.000329,0.000490,2.879707e-04,0.056322
4,raw_R_grad_norm,2.446156e-02,0.015781,0.005608,5.607903e-03,0.776360
5,theta_grad_norm,2.504456e-04,0.003025,0.004650,1.011888e-04,0.539022
6,raw_R_step_norm,9.598694e+00,0.658237,0.528266,5.282664e-01,18.355185
7,theta_step_norm,9.208614e+00,0.235231,0.716018,2.220102e-01,18.634871

--------------------------------------------------------------------------------
RESULT SUMMARY: G8
--------------------------------------------------------------------------------
historical_best: 2005.0

V1:
v1_best: 1991.0
v1_gap: 14.0
v1_percent_accuracy: 99.30174563591022

V2:
v2_best: 1994.0
v2_gap: 11.0
v2_percent_accuracy: 99.45137157107231
v2_best_step: 142
v2_best_replica: 38

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 14.256134748458862

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/logs/G8_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/best_spins/G8_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/partial_group_results.csv

################################################################################
RUNNING G9 | dense | seed=15
################################################################################
G9 | step     1/2000 | best 170.0 | acc 8.2765% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G9 | step    50/2000 | best 474.0 | acc 23.0769% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G9 | step   100/2000 | best 2009.0 | acc 97.8092% | success 0/128 | gamma 0.95048 | |rz| 0.2589
G9 | step   150/2000 | best 2025.0 | acc 98.5881% | success 0/128 | gamma 0.92546 | |rz| 0.8463
G9 | step   200/2000 | best 2028.0 | acc 98.7342% | success 0/128 | gamma 0.90045 | |rz| 0.9048
G9 | step   250/2000 | best 2034.0 | acc 99.0263% | success 0/128 | gamma 0.87544 | |rz| 0.9209
G9 | step   300/2000 | best 2034.0 | acc 99.0263% | success 0/128 | gamma 0.85043 | |rz| 0.9294
G9 | step   350/2000 | best 2035.0 | acc 99.0750% | success 0/128 | gamma 0.82541 | |rz| 0.9352
G9 | step   400/2000 | best 2035.0 | acc 99.0750% | success 0/128 | gamma 0.80040 | |rz| 0.9397
G9 | step   450/2000 | best 2035.0 | acc 99.0750% | success 0/128 | gamma 0.77539 | |rz| 0.9435
G9 | step   500/2000 | best 2035.0 | acc 99.0750% | success 0/128 | gamma 0.75038 | |rz| 0.9469
G9 | step   550/2000 | best 2035.0 | acc 99.0750% | success 0/128 | gamma 0.72536 | |rz| 0.9501
G9 | step   600/2000 | best 2035.0 | acc 99.0750% | success 0/128 | gamma 0.70035 | |rz| 0.9530
G9 | step   650/2000 | best 2035.0 | acc 99.0750% | success 0/128 | gamma 0.67534 | |rz| 0.9558
G9 | step   700/2000 | best 2036.0 | acc 99.1237% | success 0/128 | gamma 0.65033 | |rz| 0.9584
G9 | step   750/2000 | best 2036.0 | acc 99.1237% | success 0/128 | gamma 0.62531 | |rz| 0.9609
G9 | step   800/2000 | best 2036.0 | acc 99.1237% | success 0/128 | gamma 0.60030 | |rz| 0.9632
G9 | step   850/2000 | best 2036.0 | acc 99.1237% | success 0/128 | gamma 0.57529 | |rz| 0.9655
G9 | step   900/2000 | best 2036.0 | acc 99.1237% | success 0/128 | gamma 0.55028 | |rz| 0.9676
G9 | step   950/2000 | best 2036.0 | acc 99.1237% | success 0/128 | gamma 0.52526 | |rz| 0.9697
G9 | step  1000/2000 | best 2036.0 | acc 99.1237% | success 0/128 | gamma 0.50025 | |rz| 0.9716
G9 | step  1050/2000 | best 2036.0 | acc 99.1237% | success 0/128 | gamma 0.47524 | |rz| 0.9735
G9 | step  1100/2000 | best 2036.0 | acc 99.1237% | success 0/128 | gamma 0.45023 | |rz| 0.9754
G9 | step  1150/2000 | best 2036.0 | acc 99.1237% | success 0/128 | gamma 0.42521 | |rz| 0.9771
G9 | step  1200/2000 | best 2036.0 | acc 99.1237% | success 0/128 | gamma 0.40020 | |rz| 0.9788
G9 | step  1250/2000 | best 2036.0 | acc 99.1237% | success 0/128 | gamma 0.37519 | |rz| 0.9804
G9 | step  1300/2000 | best 2036.0 | acc 99.1237% | success 0/128 | gamma 0.35018 | |rz| 0.9819
G9 | step  1350/2000 | best 2036.0 | acc 99.1237% | success 0/128 | gamma 0.32517 | |rz| 0.9833
G9 | step  1400/2000 | best 2036.0 | acc 99.1237% | success 0/128 | gamma 0.30034 | |rz| 0.9847
G9 | step  1450/2000 | best 2036.0 | acc 99.1237% | success 0/128 | gamma 0.27732 | |rz| 0.9859
G9 | step  1500/2000 | best 2036.0 | acc 99.1237% | success 0/128 | gamma 0.26252 | |rz| 0.9867
G9 | step  1550/2000 | best 2036.0 | acc 99.1237% | success 0/128 | gamma 0.26035 | |rz| 0.9871
G9 | step  1600/2000 | best 2036.0 | acc 99.1237% | success 0/128 | gamma 0.25010 | |rz| 0.9877
G9 | step  1650/2000 | best 2036.0 | acc 99.1237% | success 0/128 | gamma 0.21052 | |rz| 0.9893
G9 | step  1700/2000 | best 2036.0 | acc 99.1237% | success 0/128 | gamma 0.16261 | |rz| 0.9907
G9 | step  1750/2000 | best 2036.0 | acc 99.1237% | success 0/128 | gamma 0.12728 | |rz| 0.9916
G9 | step  1800/2000 | best 2036.0 | acc 99.1237% | success 0/128 | gamma 0.10025 | |rz| 0.9922
G9 | step  1850/2000 | best 2036.0 | acc 99.1237% | success 0/128 | gamma 0.07505 | |rz| 0.9926
G9 | step  1900/2000 | best 2036.0 | acc 99.1237% | success 0/128 | gamma 0.05003 | |rz| 0.9930
G9 | step  1950/2000 | best 2036.0 | acc 99.1237% | success 0/128 | gamma 0.02501 | |rz| 0.9933
G9 | step  2000/2000 | best 2036.0 | acc 99.1237% | success 0/128 | gamma 0.00000 | |rz| 0.9945

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G9
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644263e-05,0.000044,0.000016,1.631537e-05,0.002179
1,theta_grad_mean_abs,6.215672e-07,0.000004,0.000004,2.498946e-07,0.001152
2,raw_R_step_mean_abs,2.999592e-02,0.002012,0.001533,1.533197e-03,0.057061
3,theta_step_mean_abs,2.863736e-02,0.000348,0.000508,2.833021e-04,0.056343
4,raw_R_grad_norm,2.446165e-02,0.015783,0.005587,5.586603e-03,0.768553
5,theta_grad_norm,2.490829e-04,0.003746,0.004636,1.010458e-04,0.537945
6,raw_R_step_norm,9.598694e+00,0.674308,0.527323,5.273232e-01,18.324615
7,theta_step_norm,9.204316e+00,0.382973,0.757334,2.229961e-01,18.637402

--------------------------------------------------------------------------------
RESULT SUMMARY: G9
--------------------------------------------------------------------------------
historical_best: 2054.0

V1:
v1_best: 2041.0
v1_gap: 13.0
v1_percent_accuracy: 99.36708860759494

V2:
v2_best: 2036.0
v2_gap: 18.0
v2_percent_accuracy: 99.1236611489776
v2_best_step: 656
v2_best_replica: 21

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 13.954205989837646

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/logs/G9_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/best_spins/G9_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/partial_group_results.csv

################################################################################
RUNNING G10 | dense | seed=16
################################################################################
G10 | step     1/2000 | best 96.0 | acc 4.8000% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G10 | step    50/2000 | best 418.0 | acc 20.9000% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G10 | step   100/2000 | best 1947.0 | acc 97.3500% | success 0/128 | gamma 0.95048 | |rz| 0.2564
G10 | step   150/2000 | best 1987.0 | acc 99.3500% | success 0/128 | gamma 0.92546 | |rz| 0.8456
G10 | step   200/2000 | best 1990.0 | acc 99.5000% | success 0/128 | gamma 0.90045 | |rz| 0.9043
G10 | step   250/2000 | best 1993.0 | acc 99.6500% | success 0/128 | gamma 0.87544 | |rz| 0.9201
G10 | step   300/2000 | best 1993.0 | acc 99.6500% | success 0/128 | gamma 0.85043 | |rz| 0.9287
G10 | step   350/2000 | best 1994.0 | acc 99.7000% | success 0/128 | gamma 0.82541 | |rz| 0.9347
G10 | step   400/2000 | best 1995.0 | acc 99.7500% | success 0/128 | gamma 0.80040 | |rz| 0.9393
G10 | step   450/2000 | best 1995.0 | acc 99.7500% | success 0/128 | gamma 0.77539 | |rz| 0.9430
G10 | step   500/2000 | best 1995.0 | acc 99.7500% | success 0/128 | gamma 0.75038 | |rz| 0.9465
G10 | step   550/2000 | best 1995.0 | acc 99.7500% | success 0/128 | gamma 0.72536 | |rz| 0.9497
G10 | step   600/2000 | best 1995.0 | acc 99.7500% | success 0/128 | gamma 0.70035 | |rz| 0.9526
G10 | step   650/2000 | best 1996.0 | acc 99.8000% | success 0/128 | gamma 0.67534 | |rz| 0.9553
G10 | step   700/2000 | best 1996.0 | acc 99.8000% | success 0/128 | gamma 0.65033 | |rz| 0.9579
G10 | step   750/2000 | best 1996.0 | acc 99.8000% | success 0/128 | gamma 0.62531 | |rz| 0.9604
G10 | step   800/2000 | best 1996.0 | acc 99.8000% | success 0/128 | gamma 0.60030 | |rz| 0.9627
G10 | step   850/2000 | best 1996.0 | acc 99.8000% | success 0/128 | gamma 0.57529 | |rz| 0.9650
G10 | step   900/2000 | best 1996.0 | acc 99.8000% | success 0/128 | gamma 0.55028 | |rz| 0.9671
G10 | step   950/2000 | best 1996.0 | acc 99.8000% | success 0/128 | gamma 0.52526 | |rz| 0.9692
G10 | step  1000/2000 | best 1996.0 | acc 99.8000% | success 0/128 | gamma 0.50025 | |rz| 0.9712
G10 | step  1050/2000 | best 1996.0 | acc 99.8000% | success 0/128 | gamma 0.47524 | |rz| 0.9731
G10 | step  1100/2000 | best 1996.0 | acc 99.8000% | success 0/128 | gamma 0.45023 | |rz| 0.9749
G10 | step  1150/2000 | best 1996.0 | acc 99.8000% | success 0/128 | gamma 0.42521 | |rz| 0.9767
G10 | step  1200/2000 | best 1996.0 | acc 99.8000% | success 0/128 | gamma 0.40020 | |rz| 0.9784
G10 | step  1250/2000 | best 1996.0 | acc 99.8000% | success 0/128 | gamma 0.37519 | |rz| 0.9800
G10 | step  1300/2000 | best 1996.0 | acc 99.8000% | success 0/128 | gamma 0.35018 | |rz| 0.9815
G10 | step  1350/2000 | best 1996.0 | acc 99.8000% | success 0/128 | gamma 0.32517 | |rz| 0.9829
G10 | step  1400/2000 | best 1996.0 | acc 99.8000% | success 0/128 | gamma 0.30034 | |rz| 0.9843
G10 | step  1450/2000 | best 1996.0 | acc 99.8000% | success 0/128 | gamma 0.27732 | |rz| 0.9855
G10 | step  1500/2000 | best 1996.0 | acc 99.8000% | success 0/128 | gamma 0.26252 | |rz| 0.9863
G10 | step  1550/2000 | best 1996.0 | acc 99.8000% | success 0/128 | gamma 0.26035 | |rz| 0.9867
G10 | step  1600/2000 | best 1996.0 | acc 99.8000% | success 0/128 | gamma 0.25010 | |rz| 0.9873
G10 | step  1650/2000 | best 1996.0 | acc 99.8000% | success 0/128 | gamma 0.21052 | |rz| 0.9889
G10 | step  1700/2000 | best 1996.0 | acc 99.8000% | success 0/128 | gamma 0.16261 | |rz| 0.9903
G10 | step  1750/2000 | best 1996.0 | acc 99.8000% | success 0/128 | gamma 0.12728 | |rz| 0.9912
G10 | step  1800/2000 | best 1996.0 | acc 99.8000% | success 0/128 | gamma 0.10025 | |rz| 0.9918
G10 | step  1850/2000 | best 1996.0 | acc 99.8000% | success 0/128 | gamma 0.07505 | |rz| 0.9922
G10 | step  1900/2000 | best 1996.0 | acc 99.8000% | success 0/128 | gamma 0.05003 | |rz| 0.9926
G10 | step  1950/2000 | best 1996.0 | acc 99.8000% | success 0/128 | gamma 0.02501 | |rz| 0.9929
G10 | step  2000/2000 | best 1996.0 | acc 99.8000% | success 0/128 | gamma 0.00000 | |rz| 0.9941

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G10
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644297e-05,0.000044,0.000016,1.623814e-05,0.002146
1,theta_grad_mean_abs,6.245581e-07,0.000004,0.000004,2.502136e-07,0.001142
2,raw_R_step_mean_abs,2.999592e-02,0.002010,0.001535,1.534969e-03,0.056922
3,theta_step_mean_abs,2.863432e-02,0.000337,0.000504,2.834668e-04,0.056252
4,raw_R_grad_norm,2.446176e-02,0.015611,0.005558,5.558460e-03,0.755086
5,theta_grad_norm,2.505497e-04,0.003221,0.004599,1.010577e-04,0.532283
6,raw_R_step_norm,9.598694e+00,0.668095,0.527603,5.276028e-01,18.279551
7,theta_step_norm,9.203420e+00,0.266336,0.743370,2.191458e-01,18.607616

--------------------------------------------------------------------------------
RESULT SUMMARY: G10
--------------------------------------------------------------------------------
historical_best: 2000.0

V1:
v1_best: 1992.0
v1_gap: 8.0
v1_percent_accuracy: 99.6

V2:
v2_best: 1996.0
v2_gap: 4.0
v2_percent_accuracy: 99.8
v2_best_step: 628
v2_best_replica: 38

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 13.853336811065674

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/logs/G10_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/best_spins/G10_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/partial_group_results.csv

################################################################################
RUNNING G11 | dense | seed=17
################################################################################
G11 | step     1/2000 | best 64.0 | acc 11.3475% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G11 | step    50/2000 | best 116.0 | acc 20.5674% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G11 | step   100/2000 | best 130.0 | acc 23.0496% | success 0/128 | gamma 0.95048 | |rz| 0.0010
G11 | step   150/2000 | best 554.0 | acc 98.2270% | success 0/128 | gamma 0.92546 | |rz| 0.3373
G11 | step   200/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.90045 | |rz| 0.4711
G11 | step   250/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.87544 | |rz| 0.5278
G11 | step   300/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.85043 | |rz| 0.5621
G11 | step   350/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.82541 | |rz| 0.5903
G11 | step   400/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.80040 | |rz| 0.6156
G11 | step   450/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.77539 | |rz| 0.6390
G11 | step   500/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.75038 | |rz| 0.6608
G11 | step   550/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.72536 | |rz| 0.6811
G11 | step   600/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.70035 | |rz| 0.7001
G11 | step   650/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.67534 | |rz| 0.7179
G11 | step   700/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.65033 | |rz| 0.7345
G11 | step   750/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.62531 | |rz| 0.7501
G11 | step   800/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.60030 | |rz| 0.7647
G11 | step   850/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.57529 | |rz| 0.7783
G11 | step   900/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.55028 | |rz| 0.7911
G11 | step   950/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.52526 | |rz| 0.8030
G11 | step  1000/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.50025 | |rz| 0.8142
G11 | step  1050/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.47524 | |rz| 0.8247
G11 | step  1100/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.45023 | |rz| 0.8344
G11 | step  1150/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.42521 | |rz| 0.8435
G11 | step  1200/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.40020 | |rz| 0.8520
G11 | step  1250/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.37519 | |rz| 0.8599
G11 | step  1300/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.35018 | |rz| 0.8673
G11 | step  1350/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.32517 | |rz| 0.8741
G11 | step  1400/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.30034 | |rz| 0.8803
G11 | step  1450/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.27732 | |rz| 0.8857
G11 | step  1500/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.26252 | |rz| 0.8893
G11 | step  1550/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.26035 | |rz| 0.8908
G11 | step  1600/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.25010 | |rz| 0.8936
G11 | step  1650/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.21052 | |rz| 0.8999
G11 | step  1700/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.16261 | |rz| 0.9057
G11 | step  1750/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.12728 | |rz| 0.9088
G11 | step  1800/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.10025 | |rz| 0.9103
G11 | step  1850/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.07505 | |rz| 0.9108
G11 | step  1900/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.05003 | |rz| 0.9113
G11 | step  1950/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.02501 | |rz| 0.9123
G11 | step  2000/2000 | best 556.0 | acc 98.5816% | success 0/128 | gamma 0.00000 | |rz| 0.9216

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G11
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644286e-05,0.000017,0.000008,7.824297e-06,0.000933
1,theta_grad_mean_abs,6.217214e-07,0.000004,0.000004,2.600651e-07,0.000117
2,raw_R_step_mean_abs,2.999592e-02,0.002995,0.002671,2.185788e-03,0.048871
3,theta_step_mean_abs,2.864527e-02,0.000799,0.002198,7.376932e-04,0.028645
4,raw_R_grad_norm,2.446173e-02,0.005851,0.002658,2.658162e-03,0.298539
5,theta_grad_norm,2.495715e-04,0.001979,0.003751,9.869978e-05,0.066168
6,raw_R_step_norm,9.598694e+00,1.025515,0.918067,7.770185e-01,15.638873
7,theta_step_norm,9.206842e+00,0.382036,2.335874,3.182232e-01,9.206842

--------------------------------------------------------------------------------
RESULT SUMMARY: G11
--------------------------------------------------------------------------------
historical_best: 564.0

V1:
v1_best: 556.0
v1_gap: 8.0
v1_percent_accuracy: 98.58156028368796

V2:
v2_best: 556.0
v2_gap: 8.0
v2_percent_accuracy: 98.58156028368795
v2_best_step: 162
v2_best_replica: 78

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 13.849397897720337

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/logs/G11_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/best_spins/G11_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/partial_group_results.csv

################################################################################
RUNNING G12 | dense | seed=18
################################################################################
G12 | step     1/2000 | best 48.0 | acc 8.6331% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G12 | step    50/2000 | best 100.0 | acc 17.9856% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G12 | step   100/2000 | best 106.0 | acc 19.0647% | success 0/128 | gamma 0.95048 | |rz| 0.0010
G12 | step   150/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.92546 | |rz| 0.3557
G12 | step   200/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.90045 | |rz| 0.4970
G12 | step   250/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.87544 | |rz| 0.5517
G12 | step   300/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.85043 | |rz| 0.5842
G12 | step   350/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.82541 | |rz| 0.6107
G12 | step   400/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.80040 | |rz| 0.6344
G12 | step   450/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.77539 | |rz| 0.6562
G12 | step   500/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.75038 | |rz| 0.6765
G12 | step   550/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.72536 | |rz| 0.6954
G12 | step   600/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.70035 | |rz| 0.7131
G12 | step   650/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.67534 | |rz| 0.7296
G12 | step   700/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.65033 | |rz| 0.7451
G12 | step   750/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.62531 | |rz| 0.7596
G12 | step   800/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.60030 | |rz| 0.7732
G12 | step   850/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.57529 | |rz| 0.7860
G12 | step   900/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.55028 | |rz| 0.7981
G12 | step   950/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.52526 | |rz| 0.8094
G12 | step  1000/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.50025 | |rz| 0.8200
G12 | step  1050/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.47524 | |rz| 0.8299
G12 | step  1100/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.45023 | |rz| 0.8392
G12 | step  1150/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.42521 | |rz| 0.8479
G12 | step  1200/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.40020 | |rz| 0.8560
G12 | step  1250/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.37519 | |rz| 0.8636
G12 | step  1300/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.35018 | |rz| 0.8707
G12 | step  1350/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.32517 | |rz| 0.8773
G12 | step  1400/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.30034 | |rz| 0.8833
G12 | step  1450/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.27732 | |rz| 0.8886
G12 | step  1500/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.26252 | |rz| 0.8922
G12 | step  1550/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.26035 | |rz| 0.8937
G12 | step  1600/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.25010 | |rz| 0.8964
G12 | step  1650/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.21052 | |rz| 0.9027
G12 | step  1700/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.16261 | |rz| 0.9082
G12 | step  1750/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.12728 | |rz| 0.9109
G12 | step  1800/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.10025 | |rz| 0.9121
G12 | step  1850/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.07505 | |rz| 0.9125
G12 | step  1900/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.05003 | |rz| 0.9130
G12 | step  1950/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.02501 | |rz| 0.9140
G12 | step  2000/2000 | best 552.0 | acc 99.2806% | success 0/128 | gamma 0.00000 | |rz| 0.9246

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G12
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644259e-05,0.000017,0.000008,7.783441e-06,0.000933
1,theta_grad_mean_abs,6.239028e-07,0.000003,0.000005,2.603121e-07,0.000116
2,raw_R_step_mean_abs,2.999592e-02,0.002967,0.002643,2.206916e-03,0.048872
3,theta_step_mean_abs,2.863885e-02,0.000763,0.002379,6.998978e-04,0.028639
4,raw_R_grad_norm,2.446164e-02,0.005827,0.002640,2.640177e-03,0.298540
5,theta_grad_norm,2.503346e-04,0.001914,0.004008,9.869816e-05,0.065883
6,raw_R_step_norm,9.598694e+00,1.013520,0.908822,7.811480e-01,15.638886
7,theta_step_norm,9.204852e+00,0.367332,2.500924,3.016901e-01,9.204852

--------------------------------------------------------------------------------
RESULT SUMMARY: G12
--------------------------------------------------------------------------------
historical_best: 556.0

V1:
v1_best: 550.0
v1_gap: 6.0
v1_percent_accuracy: 98.92086330935253

V2:
v2_best: 552.0
v2_gap: 4.0
v2_percent_accuracy: 99.28057553956835
v2_best_step: 150
v2_best_replica: 56

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 13.875171661376953

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/logs/G12_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/best_spins/G12_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/partial_group_results.csv

################################################################################
RUNNING G13 | dense | seed=19
################################################################################
G13 | step     1/2000 | best 70.0 | acc 12.0275% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G13 | step    50/2000 | best 116.0 | acc 19.9313% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G13 | step   100/2000 | best 118.0 | acc 20.2749% | success 0/128 | gamma 0.95048 | |rz| 0.0010
G13 | step   150/2000 | best 574.0 | acc 98.6254% | success 0/128 | gamma 0.92546 | |rz| 0.3557
G13 | step   200/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.90045 | |rz| 0.5034
G13 | step   250/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.87544 | |rz| 0.5573
G13 | step   300/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.85043 | |rz| 0.5896
G13 | step   350/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.82541 | |rz| 0.6158
G13 | step   400/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.80040 | |rz| 0.6394
G13 | step   450/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.77539 | |rz| 0.6612
G13 | step   500/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.75038 | |rz| 0.6814
G13 | step   550/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.72536 | |rz| 0.7002
G13 | step   600/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.70035 | |rz| 0.7179
G13 | step   650/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.67534 | |rz| 0.7345
G13 | step   700/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.65033 | |rz| 0.7500
G13 | step   750/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.62531 | |rz| 0.7646
G13 | step   800/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.60030 | |rz| 0.7782
G13 | step   850/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.57529 | |rz| 0.7910
G13 | step   900/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.55028 | |rz| 0.8030
G13 | step   950/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.52526 | |rz| 0.8143
G13 | step  1000/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.50025 | |rz| 0.8249
G13 | step  1050/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.47524 | |rz| 0.8347
G13 | step  1100/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.45023 | |rz| 0.8440
G13 | step  1150/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.42521 | |rz| 0.8526
G13 | step  1200/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.40020 | |rz| 0.8607
G13 | step  1250/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.37519 | |rz| 0.8683
G13 | step  1300/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.35018 | |rz| 0.8754
G13 | step  1350/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.32517 | |rz| 0.8819
G13 | step  1400/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.30034 | |rz| 0.8880
G13 | step  1450/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.27732 | |rz| 0.8933
G13 | step  1500/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.26252 | |rz| 0.8969
G13 | step  1550/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.26035 | |rz| 0.8983
G13 | step  1600/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.25010 | |rz| 0.9010
G13 | step  1650/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.21052 | |rz| 0.9072
G13 | step  1700/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.16261 | |rz| 0.9126
G13 | step  1750/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.12728 | |rz| 0.9152
G13 | step  1800/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.10025 | |rz| 0.9161
G13 | step  1850/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.07505 | |rz| 0.9166
G13 | step  1900/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.05003 | |rz| 0.9170
G13 | step  1950/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.02501 | |rz| 0.9181
G13 | step  2000/2000 | best 576.0 | acc 98.9691% | success 0/128 | gamma 0.00000 | |rz| 0.9294

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G13
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644271e-05,0.000017,0.000008,7.807876e-06,0.000933
1,theta_grad_mean_abs,6.231799e-07,0.000003,0.000005,2.602347e-07,0.000106
2,raw_R_step_mean_abs,2.999592e-02,0.002971,0.002646,2.213421e-03,0.048871
3,theta_step_mean_abs,2.862638e-02,0.000743,0.002495,6.854498e-04,0.028626
4,raw_R_grad_norm,2.446168e-02,0.005839,0.002641,2.641261e-03,0.298539
5,theta_grad_norm,2.502638e-04,0.001882,0.004039,9.875121e-05,0.062185
6,raw_R_step_norm,9.598694e+00,1.012471,0.907964,7.825865e-01,15.638880
7,theta_step_norm,9.202263e+00,0.356701,2.565191,2.992256e-01,9.202263

--------------------------------------------------------------------------------
RESULT SUMMARY: G13
--------------------------------------------------------------------------------
historical_best: 582.0

V1:
v1_best: 580.0
v1_gap: 2.0
v1_percent_accuracy: 99.65635738831617

V2:
v2_best: 576.0
v2_gap: 6.0
v2_percent_accuracy: 98.96907216494846
v2_best_step: 155
v2_best_replica: 59

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 13.84877610206604

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/logs/G13_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/best_spins/G13_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/partial_group_results.csv

################################################################################
RUNNING G14 | dense | seed=20
################################################################################
G14 | step     1/2000 | best 2435.0 | acc 79.4713% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G14 | step    50/2000 | best 2518.0 | acc 82.1802% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G14 | step   100/2000 | best 2800.0 | acc 91.3838% | success 0/128 | gamma 0.95048 | |rz| 0.0032
G14 | step   150/2000 | best 3018.0 | acc 98.4987% | success 0/128 | gamma 0.92546 | |rz| 0.4882
G14 | step   200/2000 | best 3028.0 | acc 98.8251% | success 0/128 | gamma 0.90045 | |rz| 0.5701
G14 | step   250/2000 | best 3031.0 | acc 98.9230% | success 0/128 | gamma 0.87544 | |rz| 0.5965
G14 | step   300/2000 | best 3034.0 | acc 99.0209% | success 0/128 | gamma 0.85043 | |rz| 0.6152
G14 | step   350/2000 | best 3036.0 | acc 99.0862% | success 0/128 | gamma 0.82541 | |rz| 0.6318
G14 | step   400/2000 | best 3037.0 | acc 99.1188% | success 0/128 | gamma 0.80040 | |rz| 0.6475
G14 | step   450/2000 | best 3037.0 | acc 99.1188% | success 0/128 | gamma 0.77539 | |rz| 0.6627
G14 | step   500/2000 | best 3037.0 | acc 99.1188% | success 0/128 | gamma 0.75038 | |rz| 0.6778
G14 | step   550/2000 | best 3037.0 | acc 99.1188% | success 0/128 | gamma 0.72536 | |rz| 0.6926
G14 | step   600/2000 | best 3038.0 | acc 99.1514% | success 0/128 | gamma 0.70035 | |rz| 0.7073
G14 | step   650/2000 | best 3040.0 | acc 99.2167% | success 0/128 | gamma 0.67534 | |rz| 0.7217
G14 | step   700/2000 | best 3040.0 | acc 99.2167% | success 0/128 | gamma 0.65033 | |rz| 0.7359
G14 | step   750/2000 | best 3041.0 | acc 99.2493% | success 0/128 | gamma 0.62531 | |rz| 0.7498
G14 | step   800/2000 | best 3041.0 | acc 99.2493% | success 0/128 | gamma 0.60030 | |rz| 0.7635
G14 | step   850/2000 | best 3042.0 | acc 99.2820% | success 0/128 | gamma 0.57529 | |rz| 0.7768
G14 | step   900/2000 | best 3043.0 | acc 99.3146% | success 0/128 | gamma 0.55028 | |rz| 0.7897
G14 | step   950/2000 | best 3043.0 | acc 99.3146% | success 0/128 | gamma 0.52526 | |rz| 0.8023
G14 | step  1000/2000 | best 3043.0 | acc 99.3146% | success 0/128 | gamma 0.50025 | |rz| 0.8145
G14 | step  1050/2000 | best 3043.0 | acc 99.3146% | success 0/128 | gamma 0.47524 | |rz| 0.8262
G14 | step  1100/2000 | best 3043.0 | acc 99.3146% | success 0/128 | gamma 0.45023 | |rz| 0.8375
G14 | step  1150/2000 | best 3043.0 | acc 99.3146% | success 0/128 | gamma 0.42521 | |rz| 0.8483
G14 | step  1200/2000 | best 3043.0 | acc 99.3146% | success 0/128 | gamma 0.40020 | |rz| 0.8584
G14 | step  1250/2000 | best 3043.0 | acc 99.3146% | success 0/128 | gamma 0.37519 | |rz| 0.8682
G14 | step  1300/2000 | best 3043.0 | acc 99.3146% | success 0/128 | gamma 0.35018 | |rz| 0.8775
G14 | step  1350/2000 | best 3043.0 | acc 99.3146% | success 0/128 | gamma 0.32517 | |rz| 0.8864
G14 | step  1400/2000 | best 3043.0 | acc 99.3146% | success 0/128 | gamma 0.30034 | |rz| 0.8945
G14 | step  1450/2000 | best 3044.0 | acc 99.3473% | success 0/128 | gamma 0.27732 | |rz| 0.9016
G14 | step  1500/2000 | best 3044.0 | acc 99.3473% | success 0/128 | gamma 0.26252 | |rz| 0.9067
G14 | step  1550/2000 | best 3044.0 | acc 99.3473% | success 0/128 | gamma 0.26035 | |rz| 0.9091
G14 | step  1600/2000 | best 3044.0 | acc 99.3473% | success 0/128 | gamma 0.25010 | |rz| 0.9129
G14 | step  1650/2000 | best 3044.0 | acc 99.3473% | success 0/128 | gamma 0.21052 | |rz| 0.9212
G14 | step  1700/2000 | best 3044.0 | acc 99.3473% | success 0/128 | gamma 0.16261 | |rz| 0.9287
G14 | step  1750/2000 | best 3044.0 | acc 99.3473% | success 0/128 | gamma 0.12728 | |rz| 0.9329
G14 | step  1800/2000 | best 3044.0 | acc 99.3473% | success 0/128 | gamma 0.10025 | |rz| 0.9355
G14 | step  1850/2000 | best 3044.0 | acc 99.3473% | success 0/128 | gamma 0.07505 | |rz| 0.9375
G14 | step  1900/2000 | best 3044.0 | acc 99.3473% | success 0/128 | gamma 0.05003 | |rz| 0.9390
G14 | step  1950/2000 | best 3044.0 | acc 99.3473% | success 0/128 | gamma 0.02501 | |rz| 0.9405
G14 | step  2000/2000 | best 3044.0 | acc 99.3473% | success 0/128 | gamma 0.00000 | |rz| 0.9489

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G14
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644272e-05,0.000018,0.000009,9.332145e-06,0.000933
1,theta_grad_mean_abs,6.257526e-07,0.000004,0.000005,2.551535e-07,0.000094
2,raw_R_step_mean_abs,2.999592e-02,0.002663,0.002766,1.982447e-03,0.048872
3,theta_step_mean_abs,2.865140e-02,0.000802,0.002058,6.570519e-04,0.028651
4,raw_R_grad_norm,2.446168e-02,0.006817,0.003205,3.204789e-03,0.298584
5,theta_grad_norm,2.510489e-04,0.002719,0.003841,9.932840e-05,0.141433
6,raw_R_step_norm,9.598694e+00,0.926029,0.966596,7.571650e-01,15.639063
7,theta_step_norm,9.207963e+00,0.436619,1.946105,3.379933e-01,9.207963

--------------------------------------------------------------------------------
RESULT SUMMARY: G14
--------------------------------------------------------------------------------
historical_best: 3064.0

V1:
v1_best: 3040.0
v1_gap: 24.0
v1_percent_accuracy: 99.21671018276764

V2:
v2_best: 3044.0
v2_gap: 20.0
v2_percent_accuracy: 99.34725848563968
v2_best_step: 1402
v2_best_replica: 118

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 15.714704990386963

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/logs/G14_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/best_spins/G14_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/partial_group_results.csv

################################################################################
RUNNING G15 | dense | seed=21
################################################################################
G15 | step     1/2000 | best 2413.0 | acc 79.1148% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G15 | step    50/2000 | best 2501.0 | acc 82.0000% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G15 | step   100/2000 | best 2734.0 | acc 89.6393% | success 0/128 | gamma 0.95048 | |rz| 0.0046
G15 | step   150/2000 | best 3004.0 | acc 98.4918% | success 0/128 | gamma 0.92546 | |rz| 0.4921
G15 | step   200/2000 | best 3016.0 | acc 98.8852% | success 0/128 | gamma 0.90045 | |rz| 0.5727
G15 | step   250/2000 | best 3018.0 | acc 98.9508% | success 0/128 | gamma 0.87544 | |rz| 0.5986
G15 | step   300/2000 | best 3021.0 | acc 99.0492% | success 0/128 | gamma 0.85043 | |rz| 0.6168
G15 | step   350/2000 | best 3023.0 | acc 99.1148% | success 0/128 | gamma 0.82541 | |rz| 0.6329
G15 | step   400/2000 | best 3024.0 | acc 99.1475% | success 0/128 | gamma 0.80040 | |rz| 0.6484
G15 | step   450/2000 | best 3027.0 | acc 99.2459% | success 0/128 | gamma 0.77539 | |rz| 0.6634
G15 | step   500/2000 | best 3027.0 | acc 99.2459% | success 0/128 | gamma 0.75038 | |rz| 0.6782
G15 | step   550/2000 | best 3027.0 | acc 99.2459% | success 0/128 | gamma 0.72536 | |rz| 0.6929
G15 | step   600/2000 | best 3029.0 | acc 99.3115% | success 0/128 | gamma 0.70035 | |rz| 0.7074
G15 | step   650/2000 | best 3030.0 | acc 99.3443% | success 0/128 | gamma 0.67534 | |rz| 0.7217
G15 | step   700/2000 | best 3030.0 | acc 99.3443% | success 0/128 | gamma 0.65033 | |rz| 0.7357
G15 | step   750/2000 | best 3031.0 | acc 99.3770% | success 0/128 | gamma 0.62531 | |rz| 0.7495
G15 | step   800/2000 | best 3032.0 | acc 99.4098% | success 0/128 | gamma 0.60030 | |rz| 0.7630
G15 | step   850/2000 | best 3034.0 | acc 99.4754% | success 0/128 | gamma 0.57529 | |rz| 0.7762
G15 | step   900/2000 | best 3035.0 | acc 99.5082% | success 0/128 | gamma 0.55028 | |rz| 0.7892
G15 | step   950/2000 | best 3035.0 | acc 99.5082% | success 0/128 | gamma 0.52526 | |rz| 0.8018
G15 | step  1000/2000 | best 3035.0 | acc 99.5082% | success 0/128 | gamma 0.50025 | |rz| 0.8139
G15 | step  1050/2000 | best 3035.0 | acc 99.5082% | success 0/128 | gamma 0.47524 | |rz| 0.8256
G15 | step  1100/2000 | best 3035.0 | acc 99.5082% | success 0/128 | gamma 0.45023 | |rz| 0.8367
G15 | step  1150/2000 | best 3035.0 | acc 99.5082% | success 0/128 | gamma 0.42521 | |rz| 0.8473
G15 | step  1200/2000 | best 3035.0 | acc 99.5082% | success 0/128 | gamma 0.40020 | |rz| 0.8573
G15 | step  1250/2000 | best 3035.0 | acc 99.5082% | success 0/128 | gamma 0.37519 | |rz| 0.8669
G15 | step  1300/2000 | best 3035.0 | acc 99.5082% | success 0/128 | gamma 0.35018 | |rz| 0.8760
G15 | step  1350/2000 | best 3035.0 | acc 99.5082% | success 0/128 | gamma 0.32517 | |rz| 0.8847
G15 | step  1400/2000 | best 3035.0 | acc 99.5082% | success 0/128 | gamma 0.30034 | |rz| 0.8927
G15 | step  1450/2000 | best 3035.0 | acc 99.5082% | success 0/128 | gamma 0.27732 | |rz| 0.8996
G15 | step  1500/2000 | best 3035.0 | acc 99.5082% | success 0/128 | gamma 0.26252 | |rz| 0.9046
G15 | step  1550/2000 | best 3035.0 | acc 99.5082% | success 0/128 | gamma 0.26035 | |rz| 0.9070
G15 | step  1600/2000 | best 3035.0 | acc 99.5082% | success 0/128 | gamma 0.25010 | |rz| 0.9107
G15 | step  1650/2000 | best 3035.0 | acc 99.5082% | success 0/128 | gamma 0.21052 | |rz| 0.9188
G15 | step  1700/2000 | best 3035.0 | acc 99.5082% | success 0/128 | gamma 0.16261 | |rz| 0.9263
G15 | step  1750/2000 | best 3035.0 | acc 99.5082% | success 0/128 | gamma 0.12728 | |rz| 0.9306
G15 | step  1800/2000 | best 3035.0 | acc 99.5082% | success 0/128 | gamma 0.10025 | |rz| 0.9332
G15 | step  1850/2000 | best 3035.0 | acc 99.5082% | success 0/128 | gamma 0.07505 | |rz| 0.9351
G15 | step  1900/2000 | best 3035.0 | acc 99.5082% | success 0/128 | gamma 0.05003 | |rz| 0.9366
G15 | step  1950/2000 | best 3035.0 | acc 99.5082% | success 0/128 | gamma 0.02501 | |rz| 0.9381
G15 | step  2000/2000 | best 3035.0 | acc 99.5082% | success 0/128 | gamma 0.00000 | |rz| 0.9463

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G15
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644269e-05,0.000019,0.000009,9.336130e-06,0.000933
1,theta_grad_mean_abs,6.253694e-07,0.000004,0.000005,2.561625e-07,0.000091
2,raw_R_step_mean_abs,2.999592e-02,0.002657,0.002750,1.968744e-03,0.048873
3,theta_step_mean_abs,2.865761e-02,0.000786,0.002004,6.242037e-04,0.028658
4,raw_R_grad_norm,2.446168e-02,0.007021,0.003217,3.217190e-03,0.298651
5,theta_grad_norm,2.504814e-04,0.003432,0.003703,9.960697e-05,0.129608
6,raw_R_step_norm,9.598694e+00,0.941636,0.962256,7.466974e-01,15.639441
7,theta_step_norm,9.209601e+00,0.436847,1.917836,3.083068e-01,9.209601

--------------------------------------------------------------------------------
RESULT SUMMARY: G15
--------------------------------------------------------------------------------
historical_best: 3050.0

V1:
v1_best: 3025.0
v1_gap: 25.0
v1_percent_accuracy: 99.18032786885246

V2:
v2_best: 3035.0
v2_gap: 15.0
v2_percent_accuracy: 99.50819672131148
v2_best_step: 878
v2_best_replica: 57

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 15.2307870388031

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/logs/G15_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/best_spins/G15_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/partial_group_results.csv

################################################################################
RUNNING G16 | dense | seed=22
################################################################################
G16 | step     1/2000 | best 2403.0 | acc 78.7353% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G16 | step    50/2000 | best 2529.0 | acc 82.8637% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G16 | step   100/2000 | best 2788.0 | acc 91.3499% | success 0/128 | gamma 0.95048 | |rz| 0.0040
G16 | step   150/2000 | best 3007.0 | acc 98.5256% | success 0/128 | gamma 0.92546 | |rz| 0.4883
G16 | step   200/2000 | best 3014.0 | acc 98.7549% | success 0/128 | gamma 0.90045 | |rz| 0.5701
G16 | step   250/2000 | best 3016.0 | acc 98.8204% | success 0/128 | gamma 0.87544 | |rz| 0.5964
G16 | step   300/2000 | best 3016.0 | acc 98.8204% | success 0/128 | gamma 0.85043 | |rz| 0.6153
G16 | step   350/2000 | best 3017.0 | acc 98.8532% | success 0/128 | gamma 0.82541 | |rz| 0.6318
G16 | step   400/2000 | best 3017.0 | acc 98.8532% | success 0/128 | gamma 0.80040 | |rz| 0.6474
G16 | step   450/2000 | best 3017.0 | acc 98.8532% | success 0/128 | gamma 0.77539 | |rz| 0.6626
G16 | step   500/2000 | best 3018.0 | acc 98.8860% | success 0/128 | gamma 0.75038 | |rz| 0.6773
G16 | step   550/2000 | best 3019.0 | acc 98.9187% | success 0/128 | gamma 0.72536 | |rz| 0.6918
G16 | step   600/2000 | best 3023.0 | acc 99.0498% | success 0/128 | gamma 0.70035 | |rz| 0.7059
G16 | step   650/2000 | best 3024.0 | acc 99.0826% | success 0/128 | gamma 0.67534 | |rz| 0.7197
G16 | step   700/2000 | best 3027.0 | acc 99.1809% | success 0/128 | gamma 0.65033 | |rz| 0.7333
G16 | step   750/2000 | best 3027.0 | acc 99.1809% | success 0/128 | gamma 0.62531 | |rz| 0.7466
G16 | step   800/2000 | best 3028.0 | acc 99.2136% | success 0/128 | gamma 0.60030 | |rz| 0.7595
G16 | step   850/2000 | best 3029.0 | acc 99.2464% | success 0/128 | gamma 0.57529 | |rz| 0.7722
G16 | step   900/2000 | best 3029.0 | acc 99.2464% | success 0/128 | gamma 0.55028 | |rz| 0.7846
G16 | step   950/2000 | best 3029.0 | acc 99.2464% | success 0/128 | gamma 0.52526 | |rz| 0.7966
G16 | step  1000/2000 | best 3029.0 | acc 99.2464% | success 0/128 | gamma 0.50025 | |rz| 0.8080
G16 | step  1050/2000 | best 3029.0 | acc 99.2464% | success 0/128 | gamma 0.47524 | |rz| 0.8191
G16 | step  1100/2000 | best 3029.0 | acc 99.2464% | success 0/128 | gamma 0.45023 | |rz| 0.8298
G16 | step  1150/2000 | best 3029.0 | acc 99.2464% | success 0/128 | gamma 0.42521 | |rz| 0.8400
G16 | step  1200/2000 | best 3029.0 | acc 99.2464% | success 0/128 | gamma 0.40020 | |rz| 0.8499
G16 | step  1250/2000 | best 3029.0 | acc 99.2464% | success 0/128 | gamma 0.37519 | |rz| 0.8592
G16 | step  1300/2000 | best 3029.0 | acc 99.2464% | success 0/128 | gamma 0.35018 | |rz| 0.8681
G16 | step  1350/2000 | best 3029.0 | acc 99.2464% | success 0/128 | gamma 0.32517 | |rz| 0.8765
G16 | step  1400/2000 | best 3029.0 | acc 99.2464% | success 0/128 | gamma 0.30034 | |rz| 0.8843
G16 | step  1450/2000 | best 3029.0 | acc 99.2464% | success 0/128 | gamma 0.27732 | |rz| 0.8912
G16 | step  1500/2000 | best 3029.0 | acc 99.2464% | success 0/128 | gamma 0.26252 | |rz| 0.8960
G16 | step  1550/2000 | best 3029.0 | acc 99.2464% | success 0/128 | gamma 0.26035 | |rz| 0.8983
G16 | step  1600/2000 | best 3029.0 | acc 99.2464% | success 0/128 | gamma 0.25010 | |rz| 0.9021
G16 | step  1650/2000 | best 3029.0 | acc 99.2464% | success 0/128 | gamma 0.21052 | |rz| 0.9100
G16 | step  1700/2000 | best 3029.0 | acc 99.2464% | success 0/128 | gamma 0.16261 | |rz| 0.9171
G16 | step  1750/2000 | best 3029.0 | acc 99.2464% | success 0/128 | gamma 0.12728 | |rz| 0.9210
G16 | step  1800/2000 | best 3029.0 | acc 99.2464% | success 0/128 | gamma 0.10025 | |rz| 0.9234
G16 | step  1850/2000 | best 3029.0 | acc 99.2464% | success 0/128 | gamma 0.07505 | |rz| 0.9252
G16 | step  1900/2000 | best 3029.0 | acc 99.2464% | success 0/128 | gamma 0.05003 | |rz| 0.9267
G16 | step  1950/2000 | best 3029.0 | acc 99.2464% | success 0/128 | gamma 0.02501 | |rz| 0.9281
G16 | step  2000/2000 | best 3029.0 | acc 99.2464% | success 0/128 | gamma 0.00000 | |rz| 0.9375

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G16
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644245e-05,0.000018,0.000009,9.172163e-06,0.000933
1,theta_grad_mean_abs,6.232708e-07,0.000004,0.000005,2.557629e-07,0.000087
2,raw_R_step_mean_abs,2.999592e-02,0.002632,0.002704,1.988029e-03,0.048873
3,theta_step_mean_abs,2.864698e-02,0.000751,0.002201,6.740245e-04,0.028647
4,raw_R_grad_norm,2.446160e-02,0.006835,0.003168,3.168053e-03,0.298620
5,theta_grad_norm,2.499092e-04,0.002587,0.003782,9.958048e-05,0.119143
6,raw_R_step_norm,9.598694e+00,0.925053,0.949791,7.544121e-01,15.639275
7,theta_step_norm,9.206577e+00,0.456183,2.098700,3.537347e-01,9.206577

--------------------------------------------------------------------------------
RESULT SUMMARY: G16
--------------------------------------------------------------------------------
historical_best: 3052.0

V1:
v1_best: 3027.0
v1_gap: 25.0
v1_percent_accuracy: 99.18086500655308

V2:
v2_best: 3029.0
v2_gap: 23.0
v2_percent_accuracy: 99.24639580602883
v2_best_step: 802
v2_best_replica: 87

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 17.457791090011597

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/logs/G16_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/best_spins/G16_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/partial_group_results.csv

################################################################################
RUNNING G17 | dense | seed=23
################################################################################
G17 | step     1/2000 | best 2401.0 | acc 78.7988% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G17 | step    50/2000 | best 2512.0 | acc 82.4417% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G17 | step   100/2000 | best 2735.0 | acc 89.7604% | success 0/128 | gamma 0.95048 | |rz| 0.0031
G17 | step   150/2000 | best 3000.0 | acc 98.4575% | success 0/128 | gamma 0.92546 | |rz| 0.4862
G17 | step   200/2000 | best 3005.0 | acc 98.6216% | success 0/128 | gamma 0.90045 | |rz| 0.5686
G17 | step   250/2000 | best 3007.0 | acc 98.6872% | success 0/128 | gamma 0.87544 | |rz| 0.5945
G17 | step   300/2000 | best 3013.0 | acc 98.8841% | success 0/128 | gamma 0.85043 | |rz| 0.6129
G17 | step   350/2000 | best 3013.0 | acc 98.8841% | success 0/128 | gamma 0.82541 | |rz| 0.6291
G17 | step   400/2000 | best 3017.0 | acc 99.0154% | success 0/128 | gamma 0.80040 | |rz| 0.6446
G17 | step   450/2000 | best 3017.0 | acc 99.0154% | success 0/128 | gamma 0.77539 | |rz| 0.6596
G17 | step   500/2000 | best 3018.0 | acc 99.0482% | success 0/128 | gamma 0.75038 | |rz| 0.6743
G17 | step   550/2000 | best 3019.0 | acc 99.0811% | success 0/128 | gamma 0.72536 | |rz| 0.6889
G17 | step   600/2000 | best 3021.0 | acc 99.1467% | success 0/128 | gamma 0.70035 | |rz| 0.7033
G17 | step   650/2000 | best 3022.0 | acc 99.1795% | success 0/128 | gamma 0.67534 | |rz| 0.7176
G17 | step   700/2000 | best 3023.0 | acc 99.2123% | success 0/128 | gamma 0.65033 | |rz| 0.7315
G17 | step   750/2000 | best 3023.0 | acc 99.2123% | success 0/128 | gamma 0.62531 | |rz| 0.7453
G17 | step   800/2000 | best 3023.0 | acc 99.2123% | success 0/128 | gamma 0.60030 | |rz| 0.7587
G17 | step   850/2000 | best 3025.0 | acc 99.2780% | success 0/128 | gamma 0.57529 | |rz| 0.7718
G17 | step   900/2000 | best 3029.0 | acc 99.4093% | success 0/128 | gamma 0.55028 | |rz| 0.7846
G17 | step   950/2000 | best 3030.0 | acc 99.4421% | success 0/128 | gamma 0.52526 | |rz| 0.7970
G17 | step  1000/2000 | best 3030.0 | acc 99.4421% | success 0/128 | gamma 0.50025 | |rz| 0.8090
G17 | step  1050/2000 | best 3030.0 | acc 99.4421% | success 0/128 | gamma 0.47524 | |rz| 0.8206
G17 | step  1100/2000 | best 3030.0 | acc 99.4421% | success 0/128 | gamma 0.45023 | |rz| 0.8317
G17 | step  1150/2000 | best 3030.0 | acc 99.4421% | success 0/128 | gamma 0.42521 | |rz| 0.8422
G17 | step  1200/2000 | best 3030.0 | acc 99.4421% | success 0/128 | gamma 0.40020 | |rz| 0.8522
G17 | step  1250/2000 | best 3030.0 | acc 99.4421% | success 0/128 | gamma 0.37519 | |rz| 0.8616
G17 | step  1300/2000 | best 3030.0 | acc 99.4421% | success 0/128 | gamma 0.35018 | |rz| 0.8706
G17 | step  1350/2000 | best 3030.0 | acc 99.4421% | success 0/128 | gamma 0.32517 | |rz| 0.8791
G17 | step  1400/2000 | best 3030.0 | acc 99.4421% | success 0/128 | gamma 0.30034 | |rz| 0.8869
G17 | step  1450/2000 | best 3030.0 | acc 99.4421% | success 0/128 | gamma 0.27732 | |rz| 0.8937
G17 | step  1500/2000 | best 3030.0 | acc 99.4421% | success 0/128 | gamma 0.26252 | |rz| 0.8985
G17 | step  1550/2000 | best 3030.0 | acc 99.4421% | success 0/128 | gamma 0.26035 | |rz| 0.9008
G17 | step  1600/2000 | best 3030.0 | acc 99.4421% | success 0/128 | gamma 0.25010 | |rz| 0.9045
G17 | step  1650/2000 | best 3030.0 | acc 99.4421% | success 0/128 | gamma 0.21052 | |rz| 0.9124
G17 | step  1700/2000 | best 3030.0 | acc 99.4421% | success 0/128 | gamma 0.16261 | |rz| 0.9197
G17 | step  1750/2000 | best 3030.0 | acc 99.4421% | success 0/128 | gamma 0.12728 | |rz| 0.9238
G17 | step  1800/2000 | best 3030.0 | acc 99.4421% | success 0/128 | gamma 0.10025 | |rz| 0.9263
G17 | step  1850/2000 | best 3030.0 | acc 99.4421% | success 0/128 | gamma 0.07505 | |rz| 0.9282
G17 | step  1900/2000 | best 3030.0 | acc 99.4421% | success 0/128 | gamma 0.05003 | |rz| 0.9297
G17 | step  1950/2000 | best 3030.0 | acc 99.4421% | success 0/128 | gamma 0.02501 | |rz| 0.9311
G17 | step  2000/2000 | best 3030.0 | acc 99.4421% | success 0/128 | gamma 0.00000 | |rz| 0.9396

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G17
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644323e-05,0.000018,0.000009,9.191032e-06,0.000933
1,theta_grad_mean_abs,6.253754e-07,0.000004,0.000005,2.554028e-07,0.000097
2,raw_R_step_mean_abs,2.999592e-02,0.002652,0.002725,1.968173e-03,0.048872
3,theta_step_mean_abs,2.864430e-02,0.000752,0.002042,6.786453e-04,0.028644
4,raw_R_grad_norm,2.446184e-02,0.006743,0.003164,3.163513e-03,0.298588
5,theta_grad_norm,2.505548e-04,0.002484,0.003599,9.946191e-05,0.134661
6,raw_R_step_norm,9.598694e+00,0.927591,0.956816,7.403512e-01,15.639064
7,theta_step_norm,9.205760e+00,0.407078,1.918820,3.520560e-01,9.205760

--------------------------------------------------------------------------------
RESULT SUMMARY: G17
--------------------------------------------------------------------------------
historical_best: 3047.0

V1:
v1_best: 3021.0
v1_gap: 26.0
v1_percent_accuracy: 99.14670167377749

V2:
v2_best: 3030.0
v2_gap: 17.0
v2_percent_accuracy: 99.44207417131605
v2_best_step: 936
v2_best_replica: 77

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 13.381572961807251

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/logs/G17_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/best_spins/G17_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/partial_group_results.csv

################################################################################
RUNNING G18 | dense | seed=24
################################################################################
G18 | step     1/2000 | best 108.0 | acc 10.8871% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G18 | step    50/2000 | best 236.0 | acc 23.7903% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G18 | step   100/2000 | best 911.0 | acc 91.8347% | success 0/128 | gamma 0.95048 | |rz| 0.1071
G18 | step   150/2000 | best 964.0 | acc 97.1774% | success 0/128 | gamma 0.92546 | |rz| 0.6202
G18 | step   200/2000 | best 966.0 | acc 97.3790% | success 0/128 | gamma 0.90045 | |rz| 0.6903
G18 | step   250/2000 | best 968.0 | acc 97.5806% | success 0/128 | gamma 0.87544 | |rz| 0.7119
G18 | step   300/2000 | best 968.0 | acc 97.5806% | success 0/128 | gamma 0.85043 | |rz| 0.7264
G18 | step   350/2000 | best 969.0 | acc 97.6815% | success 0/128 | gamma 0.82541 | |rz| 0.7385
G18 | step   400/2000 | best 969.0 | acc 97.6815% | success 0/128 | gamma 0.80040 | |rz| 0.7494
G18 | step   450/2000 | best 970.0 | acc 97.7823% | success 0/128 | gamma 0.77539 | |rz| 0.7598
G18 | step   500/2000 | best 970.0 | acc 97.7823% | success 0/128 | gamma 0.75038 | |rz| 0.7698
G18 | step   550/2000 | best 970.0 | acc 97.7823% | success 0/128 | gamma 0.72536 | |rz| 0.7796
G18 | step   600/2000 | best 970.0 | acc 97.7823% | success 0/128 | gamma 0.70035 | |rz| 0.7892
G18 | step   650/2000 | best 973.0 | acc 98.0847% | success 0/128 | gamma 0.67534 | |rz| 0.7987
G18 | step   700/2000 | best 973.0 | acc 98.0847% | success 0/128 | gamma 0.65033 | |rz| 0.8080
G18 | step   750/2000 | best 973.0 | acc 98.0847% | success 0/128 | gamma 0.62531 | |rz| 0.8172
G18 | step   800/2000 | best 973.0 | acc 98.0847% | success 0/128 | gamma 0.60030 | |rz| 0.8261
G18 | step   850/2000 | best 973.0 | acc 98.0847% | success 0/128 | gamma 0.57529 | |rz| 0.8349
G18 | step   900/2000 | best 973.0 | acc 98.0847% | success 0/128 | gamma 0.55028 | |rz| 0.8435
G18 | step   950/2000 | best 973.0 | acc 98.0847% | success 0/128 | gamma 0.52526 | |rz| 0.8519
G18 | step  1000/2000 | best 974.0 | acc 98.1855% | success 0/128 | gamma 0.50025 | |rz| 0.8602
G18 | step  1050/2000 | best 974.0 | acc 98.1855% | success 0/128 | gamma 0.47524 | |rz| 0.8682
G18 | step  1100/2000 | best 974.0 | acc 98.1855% | success 0/128 | gamma 0.45023 | |rz| 0.8759
G18 | step  1150/2000 | best 974.0 | acc 98.1855% | success 0/128 | gamma 0.42521 | |rz| 0.8833
G18 | step  1200/2000 | best 974.0 | acc 98.1855% | success 0/128 | gamma 0.40020 | |rz| 0.8905
G18 | step  1250/2000 | best 975.0 | acc 98.2863% | success 0/128 | gamma 0.37519 | |rz| 0.8973
G18 | step  1300/2000 | best 975.0 | acc 98.2863% | success 0/128 | gamma 0.35018 | |rz| 0.9040
G18 | step  1350/2000 | best 977.0 | acc 98.4879% | success 0/128 | gamma 0.32517 | |rz| 0.9104
G18 | step  1400/2000 | best 977.0 | acc 98.4879% | success 0/128 | gamma 0.30034 | |rz| 0.9164
G18 | step  1450/2000 | best 977.0 | acc 98.4879% | success 0/128 | gamma 0.27732 | |rz| 0.9217
G18 | step  1500/2000 | best 977.0 | acc 98.4879% | success 0/128 | gamma 0.26252 | |rz| 0.9254
G18 | step  1550/2000 | best 977.0 | acc 98.4879% | success 0/128 | gamma 0.26035 | |rz| 0.9272
G18 | step  1600/2000 | best 977.0 | acc 98.4879% | success 0/128 | gamma 0.25010 | |rz| 0.9300
G18 | step  1650/2000 | best 977.0 | acc 98.4879% | success 0/128 | gamma 0.21052 | |rz| 0.9363
G18 | step  1700/2000 | best 977.0 | acc 98.4879% | success 0/128 | gamma 0.16261 | |rz| 0.9421
G18 | step  1750/2000 | best 977.0 | acc 98.4879% | success 0/128 | gamma 0.12728 | |rz| 0.9454
G18 | step  1800/2000 | best 977.0 | acc 98.4879% | success 0/128 | gamma 0.10025 | |rz| 0.9474
G18 | step  1850/2000 | best 977.0 | acc 98.4879% | success 0/128 | gamma 0.07505 | |rz| 0.9490
G18 | step  1900/2000 | best 977.0 | acc 98.4879% | success 0/128 | gamma 0.05003 | |rz| 0.9502
G18 | step  1950/2000 | best 977.0 | acc 98.4879% | success 0/128 | gamma 0.02501 | |rz| 0.9513
G18 | step  2000/2000 | best 977.0 | acc 98.4879% | success 0/128 | gamma 0.00000 | |rz| 0.9573

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G18
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644266e-05,0.000023,0.000010,1.043636e-05,0.001082
1,theta_grad_mean_abs,6.240951e-07,0.000007,0.000006,2.569849e-07,0.000177
2,raw_R_step_mean_abs,2.999592e-02,0.002412,0.002433,2.152889e-03,0.049969
3,theta_step_mean_abs,2.864177e-02,0.000961,0.001705,8.762174e-04,0.034597
4,raw_R_grad_norm,2.446166e-02,0.008913,0.003684,3.683655e-03,0.369192
5,theta_grad_norm,2.502357e-04,0.003523,0.004474,1.002028e-04,0.239446
6,raw_R_step_norm,9.598694e+00,0.820985,0.864280,7.542022e-01,16.003065
7,theta_step_norm,9.205907e+00,0.442021,1.661578,3.525657e-01,12.629560

--------------------------------------------------------------------------------
RESULT SUMMARY: G18
--------------------------------------------------------------------------------
historical_best: 992.0

V1:
v1_best: 978.0
v1_gap: 14.0
v1_percent_accuracy: 98.58870967741936

V2:
v2_best: 977.0
v2_gap: 15.0
v2_percent_accuracy: 98.48790322580645
v2_best_step: 1348
v2_best_replica: 76

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 13.29335331916809

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/logs/G18_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/best_spins/G18_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/partial_group_results.csv

################################################################################
RUNNING G19 | dense | seed=25
################################################################################
G19 | step     1/2000 | best 24.0 | acc 2.6490% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G19 | step    50/2000 | best 149.0 | acc 16.4459% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G19 | step   100/2000 | best 825.0 | acc 91.0596% | success 0/128 | gamma 0.95048 | |rz| 0.1112
G19 | step   150/2000 | best 869.0 | acc 95.9161% | success 0/128 | gamma 0.92546 | |rz| 0.6128
G19 | step   200/2000 | best 872.0 | acc 96.2472% | success 0/128 | gamma 0.90045 | |rz| 0.6813
G19 | step   250/2000 | best 876.0 | acc 96.6887% | success 0/128 | gamma 0.87544 | |rz| 0.7024
G19 | step   300/2000 | best 876.0 | acc 96.6887% | success 0/128 | gamma 0.85043 | |rz| 0.7165
G19 | step   350/2000 | best 877.0 | acc 96.7991% | success 0/128 | gamma 0.82541 | |rz| 0.7283
G19 | step   400/2000 | best 878.0 | acc 96.9095% | success 0/128 | gamma 0.80040 | |rz| 0.7391
G19 | step   450/2000 | best 880.0 | acc 97.1302% | success 0/128 | gamma 0.77539 | |rz| 0.7493
G19 | step   500/2000 | best 880.0 | acc 97.1302% | success 0/128 | gamma 0.75038 | |rz| 0.7592
G19 | step   550/2000 | best 880.0 | acc 97.1302% | success 0/128 | gamma 0.72536 | |rz| 0.7689
G19 | step   600/2000 | best 881.0 | acc 97.2406% | success 0/128 | gamma 0.70035 | |rz| 0.7785
G19 | step   650/2000 | best 882.0 | acc 97.3510% | success 0/128 | gamma 0.67534 | |rz| 0.7879
G19 | step   700/2000 | best 882.0 | acc 97.3510% | success 0/128 | gamma 0.65033 | |rz| 0.7972
G19 | step   750/2000 | best 882.0 | acc 97.3510% | success 0/128 | gamma 0.62531 | |rz| 0.8064
G19 | step   800/2000 | best 882.0 | acc 97.3510% | success 0/128 | gamma 0.60030 | |rz| 0.8153
G19 | step   850/2000 | best 882.0 | acc 97.3510% | success 0/128 | gamma 0.57529 | |rz| 0.8241
G19 | step   900/2000 | best 883.0 | acc 97.4614% | success 0/128 | gamma 0.55028 | |rz| 0.8326
G19 | step   950/2000 | best 883.0 | acc 97.4614% | success 0/128 | gamma 0.52526 | |rz| 0.8410
G19 | step  1000/2000 | best 885.0 | acc 97.6821% | success 0/128 | gamma 0.50025 | |rz| 0.8493
G19 | step  1050/2000 | best 885.0 | acc 97.6821% | success 0/128 | gamma 0.47524 | |rz| 0.8573
G19 | step  1100/2000 | best 885.0 | acc 97.6821% | success 0/128 | gamma 0.45023 | |rz| 0.8650
G19 | step  1150/2000 | best 885.0 | acc 97.6821% | success 0/128 | gamma 0.42521 | |rz| 0.8725
G19 | step  1200/2000 | best 885.0 | acc 97.6821% | success 0/128 | gamma 0.40020 | |rz| 0.8797
G19 | step  1250/2000 | best 885.0 | acc 97.6821% | success 0/128 | gamma 0.37519 | |rz| 0.8866
G19 | step  1300/2000 | best 885.0 | acc 97.6821% | success 0/128 | gamma 0.35018 | |rz| 0.8933
G19 | step  1350/2000 | best 885.0 | acc 97.6821% | success 0/128 | gamma 0.32517 | |rz| 0.8996
G19 | step  1400/2000 | best 885.0 | acc 97.6821% | success 0/128 | gamma 0.30034 | |rz| 0.9056
G19 | step  1450/2000 | best 885.0 | acc 97.6821% | success 0/128 | gamma 0.27732 | |rz| 0.9108
G19 | step  1500/2000 | best 885.0 | acc 97.6821% | success 0/128 | gamma 0.26252 | |rz| 0.9145
G19 | step  1550/2000 | best 885.0 | acc 97.6821% | success 0/128 | gamma 0.26035 | |rz| 0.9162
G19 | step  1600/2000 | best 885.0 | acc 97.6821% | success 0/128 | gamma 0.25010 | |rz| 0.9191
G19 | step  1650/2000 | best 885.0 | acc 97.6821% | success 0/128 | gamma 0.21052 | |rz| 0.9252
G19 | step  1700/2000 | best 885.0 | acc 97.6821% | success 0/128 | gamma 0.16261 | |rz| 0.9309
G19 | step  1750/2000 | best 885.0 | acc 97.6821% | success 0/128 | gamma 0.12728 | |rz| 0.9341
G19 | step  1800/2000 | best 885.0 | acc 97.6821% | success 0/128 | gamma 0.10025 | |rz| 0.9360
G19 | step  1850/2000 | best 885.0 | acc 97.6821% | success 0/128 | gamma 0.07505 | |rz| 0.9374
G19 | step  1900/2000 | best 885.0 | acc 97.6821% | success 0/128 | gamma 0.05003 | |rz| 0.9385
G19 | step  1950/2000 | best 885.0 | acc 97.6821% | success 0/128 | gamma 0.02501 | |rz| 0.9396
G19 | step  2000/2000 | best 885.0 | acc 97.6821% | success 0/128 | gamma 0.00000 | |rz| 0.9461

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G19
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644264e-05,0.000023,0.000010,1.030767e-05,0.001100
1,theta_grad_mean_abs,6.221565e-07,0.000007,0.000006,2.570926e-07,0.000185
2,raw_R_step_mean_abs,2.999592e-02,0.002406,0.002386,2.132162e-03,0.050099
3,theta_step_mean_abs,2.862880e-02,0.000941,0.001802,8.785201e-04,0.034450
4,raw_R_grad_norm,2.446166e-02,0.009037,0.003679,3.678869e-03,0.381516
5,theta_grad_norm,2.499518e-04,0.003576,0.004751,1.001664e-04,0.256924
6,raw_R_step_norm,9.598694e+00,0.828940,0.854038,7.471603e-01,16.046824
7,theta_step_norm,9.202282e+00,0.426387,1.725041,3.542704e-01,12.654664

--------------------------------------------------------------------------------
RESULT SUMMARY: G19
--------------------------------------------------------------------------------
historical_best: 906.0

V1:
v1_best: 876.0
v1_gap: 30.0
v1_percent_accuracy: 96.6887417218543

V2:
v2_best: 885.0
v2_gap: 21.0
v2_percent_accuracy: 97.68211920529801
v2_best_step: 990
v2_best_replica: 38

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 14.043474912643433

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/logs/G19_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/best_spins/G19_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/partial_group_results.csv

################################################################################
RUNNING G20 | dense | seed=26
################################################################################
G20 | step     1/2000 | best 42.0 | acc 4.4633% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G20 | step    50/2000 | best 157.0 | acc 16.6844% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G20 | step   100/2000 | best 868.0 | acc 92.2423% | success 0/128 | gamma 0.95048 | |rz| 0.1088
G20 | step   150/2000 | best 909.0 | acc 96.5994% | success 0/128 | gamma 0.92546 | |rz| 0.6223
G20 | step   200/2000 | best 914.0 | acc 97.1307% | success 0/128 | gamma 0.90045 | |rz| 0.6906
G20 | step   250/2000 | best 916.0 | acc 97.3433% | success 0/128 | gamma 0.87544 | |rz| 0.7115
G20 | step   300/2000 | best 918.0 | acc 97.5558% | success 0/128 | gamma 0.85043 | |rz| 0.7254
G20 | step   350/2000 | best 920.0 | acc 97.7683% | success 0/128 | gamma 0.82541 | |rz| 0.7371
G20 | step   400/2000 | best 920.0 | acc 97.7683% | success 0/128 | gamma 0.80040 | |rz| 0.7479
G20 | step   450/2000 | best 921.0 | acc 97.8746% | success 0/128 | gamma 0.77539 | |rz| 0.7580
G20 | step   500/2000 | best 923.0 | acc 98.0871% | success 0/128 | gamma 0.75038 | |rz| 0.7678
G20 | step   550/2000 | best 924.0 | acc 98.1934% | success 0/128 | gamma 0.72536 | |rz| 0.7773
G20 | step   600/2000 | best 925.0 | acc 98.2997% | success 0/128 | gamma 0.70035 | |rz| 0.7866
G20 | step   650/2000 | best 925.0 | acc 98.2997% | success 0/128 | gamma 0.67534 | |rz| 0.7959
G20 | step   700/2000 | best 925.0 | acc 98.2997% | success 0/128 | gamma 0.65033 | |rz| 0.8050
G20 | step   750/2000 | best 925.0 | acc 98.2997% | success 0/128 | gamma 0.62531 | |rz| 0.8140
G20 | step   800/2000 | best 925.0 | acc 98.2997% | success 0/128 | gamma 0.60030 | |rz| 0.8228
G20 | step   850/2000 | best 925.0 | acc 98.2997% | success 0/128 | gamma 0.57529 | |rz| 0.8314
G20 | step   900/2000 | best 925.0 | acc 98.2997% | success 0/128 | gamma 0.55028 | |rz| 0.8398
G20 | step   950/2000 | best 925.0 | acc 98.2997% | success 0/128 | gamma 0.52526 | |rz| 0.8481
G20 | step  1000/2000 | best 925.0 | acc 98.2997% | success 0/128 | gamma 0.50025 | |rz| 0.8561
G20 | step  1050/2000 | best 926.0 | acc 98.4060% | success 0/128 | gamma 0.47524 | |rz| 0.8639
G20 | step  1100/2000 | best 926.0 | acc 98.4060% | success 0/128 | gamma 0.45023 | |rz| 0.8714
G20 | step  1150/2000 | best 926.0 | acc 98.4060% | success 0/128 | gamma 0.42521 | |rz| 0.8786
G20 | step  1200/2000 | best 926.0 | acc 98.4060% | success 0/128 | gamma 0.40020 | |rz| 0.8855
G20 | step  1250/2000 | best 926.0 | acc 98.4060% | success 0/128 | gamma 0.37519 | |rz| 0.8921
G20 | step  1300/2000 | best 926.0 | acc 98.4060% | success 0/128 | gamma 0.35018 | |rz| 0.8986
G20 | step  1350/2000 | best 926.0 | acc 98.4060% | success 0/128 | gamma 0.32517 | |rz| 0.9048
G20 | step  1400/2000 | best 926.0 | acc 98.4060% | success 0/128 | gamma 0.30034 | |rz| 0.9106
G20 | step  1450/2000 | best 926.0 | acc 98.4060% | success 0/128 | gamma 0.27732 | |rz| 0.9157
G20 | step  1500/2000 | best 926.0 | acc 98.4060% | success 0/128 | gamma 0.26252 | |rz| 0.9193
G20 | step  1550/2000 | best 926.0 | acc 98.4060% | success 0/128 | gamma 0.26035 | |rz| 0.9209
G20 | step  1600/2000 | best 926.0 | acc 98.4060% | success 0/128 | gamma 0.25010 | |rz| 0.9236
G20 | step  1650/2000 | best 926.0 | acc 98.4060% | success 0/128 | gamma 0.21052 | |rz| 0.9295
G20 | step  1700/2000 | best 926.0 | acc 98.4060% | success 0/128 | gamma 0.16261 | |rz| 0.9349
G20 | step  1750/2000 | best 926.0 | acc 98.4060% | success 0/128 | gamma 0.12728 | |rz| 0.9379
G20 | step  1800/2000 | best 926.0 | acc 98.4060% | success 0/128 | gamma 0.10025 | |rz| 0.9398
G20 | step  1850/2000 | best 926.0 | acc 98.4060% | success 0/128 | gamma 0.07505 | |rz| 0.9413
G20 | step  1900/2000 | best 926.0 | acc 98.4060% | success 0/128 | gamma 0.05003 | |rz| 0.9424
G20 | step  1950/2000 | best 926.0 | acc 98.4060% | success 0/128 | gamma 0.02501 | |rz| 0.9434
G20 | step  2000/2000 | best 926.0 | acc 98.4060% | success 0/128 | gamma 0.00000 | |rz| 0.9494

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G20
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644294e-05,0.000023,0.000010,1.031418e-05,0.001083
1,theta_grad_mean_abs,6.216786e-07,0.000007,0.000006,2.566046e-07,0.000181
2,raw_R_step_mean_abs,2.999592e-02,0.002421,0.002366,2.162386e-03,0.049987
3,theta_step_mean_abs,2.865847e-02,0.000940,0.001712,8.697056e-04,0.035300
4,raw_R_grad_norm,2.446175e-02,0.008967,0.003646,3.646205e-03,0.368672
5,theta_grad_norm,2.491156e-04,0.003404,0.004504,1.000111e-04,0.239809
6,raw_R_step_norm,9.598694e+00,0.834134,0.844270,7.528895e-01,16.008369
7,theta_step_norm,9.209709e+00,0.430779,1.628215,3.532462e-01,12.853171

--------------------------------------------------------------------------------
RESULT SUMMARY: G20
--------------------------------------------------------------------------------
historical_best: 941.0

V1:
v1_best: 930.0
v1_gap: 11.0
v1_percent_accuracy: 98.83103081827842

V2:
v2_best: 926.0
v2_gap: 15.0
v2_percent_accuracy: 98.40595111583421
v2_best_step: 1012
v2_best_replica: 14

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 13.847681045532227

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/logs/G20_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/best_spins/G20_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/partial_group_results.csv

################################################################################
RUNNING G21 | dense | seed=27
################################################################################
G21 | step     1/2000 | best 31.0 | acc 3.3298% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G21 | step    50/2000 | best 144.0 | acc 15.4672% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G21 | step   100/2000 | best 857.0 | acc 92.0516% | success 0/128 | gamma 0.95048 | |rz| 0.1050
G21 | step   150/2000 | best 902.0 | acc 96.8851% | success 0/128 | gamma 0.92546 | |rz| 0.6158
G21 | step   200/2000 | best 912.0 | acc 97.9592% | success 0/128 | gamma 0.90045 | |rz| 0.6860
G21 | step   250/2000 | best 912.0 | acc 97.9592% | success 0/128 | gamma 0.87544 | |rz| 0.7078
G21 | step   300/2000 | best 912.0 | acc 97.9592% | success 0/128 | gamma 0.85043 | |rz| 0.7222
G21 | step   350/2000 | best 912.0 | acc 97.9592% | success 0/128 | gamma 0.82541 | |rz| 0.7343
G21 | step   400/2000 | best 913.0 | acc 98.0666% | success 0/128 | gamma 0.80040 | |rz| 0.7453
G21 | step   450/2000 | best 913.0 | acc 98.0666% | success 0/128 | gamma 0.77539 | |rz| 0.7556
G21 | step   500/2000 | best 914.0 | acc 98.1740% | success 0/128 | gamma 0.75038 | |rz| 0.7655
G21 | step   550/2000 | best 914.0 | acc 98.1740% | success 0/128 | gamma 0.72536 | |rz| 0.7752
G21 | step   600/2000 | best 914.0 | acc 98.1740% | success 0/128 | gamma 0.70035 | |rz| 0.7847
G21 | step   650/2000 | best 914.0 | acc 98.1740% | success 0/128 | gamma 0.67534 | |rz| 0.7940
G21 | step   700/2000 | best 914.0 | acc 98.1740% | success 0/128 | gamma 0.65033 | |rz| 0.8032
G21 | step   750/2000 | best 914.0 | acc 98.1740% | success 0/128 | gamma 0.62531 | |rz| 0.8123
G21 | step   800/2000 | best 914.0 | acc 98.1740% | success 0/128 | gamma 0.60030 | |rz| 0.8213
G21 | step   850/2000 | best 914.0 | acc 98.1740% | success 0/128 | gamma 0.57529 | |rz| 0.8300
G21 | step   900/2000 | best 914.0 | acc 98.1740% | success 0/128 | gamma 0.55028 | |rz| 0.8387
G21 | step   950/2000 | best 914.0 | acc 98.1740% | success 0/128 | gamma 0.52526 | |rz| 0.8471
G21 | step  1000/2000 | best 914.0 | acc 98.1740% | success 0/128 | gamma 0.50025 | |rz| 0.8553
G21 | step  1050/2000 | best 914.0 | acc 98.1740% | success 0/128 | gamma 0.47524 | |rz| 0.8633
G21 | step  1100/2000 | best 914.0 | acc 98.1740% | success 0/128 | gamma 0.45023 | |rz| 0.8710
G21 | step  1150/2000 | best 914.0 | acc 98.1740% | success 0/128 | gamma 0.42521 | |rz| 0.8784
G21 | step  1200/2000 | best 914.0 | acc 98.1740% | success 0/128 | gamma 0.40020 | |rz| 0.8855
G21 | step  1250/2000 | best 914.0 | acc 98.1740% | success 0/128 | gamma 0.37519 | |rz| 0.8924
G21 | step  1300/2000 | best 914.0 | acc 98.1740% | success 0/128 | gamma 0.35018 | |rz| 0.8991
G21 | step  1350/2000 | best 914.0 | acc 98.1740% | success 0/128 | gamma 0.32517 | |rz| 0.9055
G21 | step  1400/2000 | best 914.0 | acc 98.1740% | success 0/128 | gamma 0.30034 | |rz| 0.9114
G21 | step  1450/2000 | best 914.0 | acc 98.1740% | success 0/128 | gamma 0.27732 | |rz| 0.9166
G21 | step  1500/2000 | best 914.0 | acc 98.1740% | success 0/128 | gamma 0.26252 | |rz| 0.9202
G21 | step  1550/2000 | best 914.0 | acc 98.1740% | success 0/128 | gamma 0.26035 | |rz| 0.9219
G21 | step  1600/2000 | best 914.0 | acc 98.1740% | success 0/128 | gamma 0.25010 | |rz| 0.9247
G21 | step  1650/2000 | best 914.0 | acc 98.1740% | success 0/128 | gamma 0.21052 | |rz| 0.9308
G21 | step  1700/2000 | best 914.0 | acc 98.1740% | success 0/128 | gamma 0.16261 | |rz| 0.9365
G21 | step  1750/2000 | best 914.0 | acc 98.1740% | success 0/128 | gamma 0.12728 | |rz| 0.9397
G21 | step  1800/2000 | best 914.0 | acc 98.1740% | success 0/128 | gamma 0.10025 | |rz| 0.9416
G21 | step  1850/2000 | best 914.0 | acc 98.1740% | success 0/128 | gamma 0.07505 | |rz| 0.9431
G21 | step  1900/2000 | best 914.0 | acc 98.1740% | success 0/128 | gamma 0.05003 | |rz| 0.9442
G21 | step  1950/2000 | best 914.0 | acc 98.1740% | success 0/128 | gamma 0.02501 | |rz| 0.9452
G21 | step  2000/2000 | best 914.0 | acc 98.1740% | success 0/128 | gamma 0.00000 | |rz| 0.9515

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G21
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644266e-05,0.000023,0.000010,1.031246e-05,0.001075
1,theta_grad_mean_abs,6.256636e-07,0.000007,0.000006,2.563144e-07,0.000174
2,raw_R_step_mean_abs,2.999592e-02,0.002425,0.002406,2.150360e-03,0.049924
3,theta_step_mean_abs,2.864449e-02,0.000946,0.001750,8.819583e-04,0.034213
4,raw_R_grad_norm,2.446166e-02,0.009042,0.003670,3.669586e-03,0.366019
5,theta_grad_norm,2.511248e-04,0.004451,0.004438,9.971737e-05,0.242312
6,raw_R_step_norm,9.598694e+00,0.844867,0.855827,7.609860e-01,15.987286
7,theta_step_norm,9.205796e+00,0.435697,1.728667,3.541535e-01,12.550605

--------------------------------------------------------------------------------
RESULT SUMMARY: G21
--------------------------------------------------------------------------------
historical_best: 931.0

V1:
v1_best: 915.0
v1_gap: 16.0
v1_percent_accuracy: 98.28141783029

V2:
v2_best: 914.0
v2_gap: 17.0
v2_percent_accuracy: 98.17400644468313
v2_best_step: 460
v2_best_replica: 61

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 13.592578887939453

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/logs/G21_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/best_spins/G21_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/partial_group_results.csv

================================================================================
RUN GROUP COMPLETE
================================================================================
run_group: small_1_3
graphs: 21

Group results:

,run_group,partition,instance,graph_type,storage_mode,nodes,edges,n_steps,replicas,lr,...,final_best,final_gap,final_percent_accuracy,best_step_success_count,best_step_success_probability,ever_success_count,ever_success_probability,final_success_count,final_success_probability,v2_runtime_sec
0,small_1_3,1,G1,random,dense,800,19176,2000,128,0.03,...,11608.0,16.0,99.862354,0,0.0,0,0.0,0,0.0,14.494951
1,small_1_3,1,G2,random,dense,800,19176,2000,128,0.03,...,11604.0,16.0,99.862306,0,0.0,0,0.0,0,0.0,13.602812
2,small_1_3,1,G3,random,dense,800,19176,2000,128,0.03,...,11619.0,3.0,99.974187,0,0.0,0,0.0,0,0.0,13.859736
3,small_1_3,1,G4,random,dense,800,19176,2000,128,0.03,...,11636.0,10.0,99.914134,0,0.0,0,0.0,0,0.0,14.753981
4,small_1_3,1,G5,random,dense,800,19176,2000,128,0.03,...,11619.0,12.0,99.896827,0,0.0,0,0.0,0,0.0,14.187588
5,small_1_3,1,G6,random,dense,800,19176,2000,128,0.03,...,2167.0,11.0,99.494949,0,0.0,0,0.0,0,0.0,14.313516
6,small_1_3,1,G7,random,dense,800,19176,2000,128,0.03,...,1998.0,8.0,99.601196,0,0.0,0,0.0,0,0.0,14.150901
7,small_1_3,1,G8,random,dense,800,19176,2000,128,0.03,...,1994.0,11.0,99.451372,0,0.0,0,0.0,0,0.0,14.256135
8,small_1_3,1,G9,random,dense,800,19176,2000,128,0.03,...,2036.0,18.0,99.123661,0,0.0,0,0.0,0,0.0,13.954206
9,small_1_3,1,G10,random,dense,800,19176,2000,128,0.03,...,1996.0,4.0,99.800000,0,0.0,0,0.0,0,0.0,13.853337
10,small_1_3,2,G11,toroidal,dense,800,1600,2000,128,0.03,...,556.0,8.0,98.581560,0,0.0,0,0.0,0,0.0,13.849398
11,small_1_3,2,G12,toroidal,dense,800,1600,2000,128,0.03,...,552.0,4.0,99.280576,0,0.0,0,0.0,0,0.0,13.875172
12,small_1_3,2,G13,toroidal,dense,800,1600,2000,128,0.03,...,576.0,6.0,98.969072,0,0.0,0,0.0,0,0.0,13.848776
13,small_1_3,3,G14,plain,dense,800,4694,2000,128,0.03,...,3044.0,20.0,99.347258,0,0.0,0,0.0,0,0.0,15.714705
14,small_1_3,3,G15,plain,dense,800,4661,2000,128,0.03,...,3035.0,15.0,99.508197,0,0.0,0,0.0,0,0.0,15.230787
15,small_1_3,3,G16,plain,dense,800,4672,2000,128,0.03,...,3029.0,23.0,99.246396,0,0.0,0,0.0,0,0.0,17.457791
16,small_1_3,3,G17,plain,dense,800,4667,2000,128,0.03,...,3030.0,17.0,99.442074,0,0.0,0,0.0,0,0.0,13.381573
17,small_1_3,3,G18,plain,dense,800,4694,2000,128,0.03,...,977.0,15.0,98.487903,0,0.0,0,0.0,0,0.0,13.293353
18,small_1_3,3,G19,plain,dense,800,4661,2000,128,0.03,...,885.0,21.0,97.682119,0,0.0,0,0.0,0,0.0,14.043475
19,small_1_3,3,G20,plain,dense,800,4672,2000,128,0.03,...,926.0,15.0,98.405951,0,0.0,0,0.0,0,0.0,13.847681
20,small_1_3,3,G21,plain,dense,800,4667,2000,128,0.03,...,914.0,17.0,98.174006,0,0.0,0,0.0,0,0.0,13.592579

Compact group results:

,instance,historical_best,v1_best,v1_gap,v1_percent_accuracy,v2_best,v2_gap,v2_percent_accuracy,v2_best_step,v2_best_replica,ever_success_count,ever_success_probability,final_best,final_gap,final_percent_accuracy,final_success_count,final_success_probability,v2_runtime_sec
0,G1,11624.0,11611.0,13.0,99.888162,11608.0,16.0,99.862354,675,49,0,0.0,11608.0,16.0,99.862354,0,0.0,14.494951
1,G2,11620.0,11610.0,10.0,99.913941,11604.0,16.0,99.862306,352,120,0,0.0,11604.0,16.0,99.862306,0,0.0,13.602812
2,G3,11622.0,11610.0,12.0,99.896748,11619.0,3.0,99.974187,280,104,0,0.0,11619.0,3.0,99.974187,0,0.0,13.859736
3,G4,11646.0,11637.0,9.0,99.922720,11636.0,10.0,99.914134,799,67,0,0.0,11636.0,10.0,99.914134,0,0.0,14.753981
4,G5,11631.0,11622.0,9.0,99.922621,11619.0,12.0,99.896827,476,10,0,0.0,11619.0,12.0,99.896827,0,0.0,14.187588
5,G6,2178.0,2173.0,5.0,99.770432,2167.0,11.0,99.494949,500,59,0,0.0,2167.0,11.0,99.494949,0,0.0,14.313516
6,G7,2006.0,1992.0,14.0,99.302094,1998.0,8.0,99.601196,451,8,0,0.0,1998.0,8.0,99.601196,0,0.0,14.150901
7,G8,2005.0,1991.0,14.0,99.301746,1994.0,11.0,99.451372,142,38,0,0.0,1994.0,11.0,99.451372,0,0.0,14.256135
8,G9,2054.0,2041.0,13.0,99.367089,2036.0,18.0,99.123661,656,21,0,0.0,2036.0,18.0,99.123661,0,0.0,13.954206
9,G10,2000.0,1992.0,8.0,99.600000,1996.0,4.0,99.800000,628,38,0,0.0,1996.0,4.0,99.800000,0,0.0,13.853337
10,G11,564.0,556.0,8.0,98.581560,556.0,8.0,98.581560,162,78,0,0.0,556.0,8.0,98.581560,0,0.0,13.849398
11,G12,556.0,550.0,6.0,98.920863,552.0,4.0,99.280576,150,56,0,0.0,552.0,4.0,99.280576,0,0.0,13.875172
12,G13,582.0,580.0,2.0,99.656357,576.0,6.0,98.969072,155,59,0,0.0,576.0,6.0,98.969072,0,0.0,13.848776
13,G14,3064.0,3040.0,24.0,99.216710,3044.0,20.0,99.347258,1402,118,0,0.0,3044.0,20.0,99.347258,0,0.0,15.714705
14,G15,3050.0,3025.0,25.0,99.180328,3035.0,15.0,99.508197,878,57,0,0.0,3035.0,15.0,99.508197,0,0.0,15.230787
15,G16,3052.0,3027.0,25.0,99.180865,3029.0,23.0,99.246396,802,87,0,0.0,3029.0,23.0,99.246396,0,0.0,17.457791
16,G17,3047.0,3021.0,26.0,99.146702,3030.0,17.0,99.442074,936,77,0,0.0,3030.0,17.0,99.442074,0,0.0,13.381573
17,G18,992.0,978.0,14.0,98.588710,977.0,15.0,98.487903,1348,76,0,0.0,977.0,15.0,98.487903,0,0.0,13.293353
18,G19,906.0,876.0,30.0,96.688742,885.0,21.0,97.682119,990,38,0,0.0,885.0,21.0,97.682119,0,0.0,14.043475
19,G20,941.0,930.0,11.0,98.831031,926.0,15.0,98.405951,1012,14,0,0.0,926.0,15.0,98.405951,0,0.0,13.847681
20,G21,931.0,915.0,16.0,98.281418,914.0,17.0,98.174006,460,61,0,0.0,914.0,17.0,98.174006,0,0.0,13.592579

Saved group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/group_results.csv

Saved group logs:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_1_3/group_training_logs.csv

================================================================================
COMPACT GROUP RESULT
================================================================================

,instance,historical_best,v1_best,v1_gap,v1_percent_accuracy,v2_best,v2_gap,v2_percent_accuracy,v2_best_step,v2_best_replica,ever_success_count,ever_success_probability,final_best,final_gap,final_percent_accuracy,final_success_count,final_success_probability,v2_runtime_sec
0,G1,11624.0,11611.0,13.0,99.888162,11608.0,16.0,99.862354,675,49,0,0.0,11608.0,16.0,99.862354,0,0.0,14.494951
1,G2,11620.0,11610.0,10.0,99.913941,11604.0,16.0,99.862306,352,120,0,0.0,11604.0,16.0,99.862306,0,0.0,13.602812
2,G3,11622.0,11610.0,12.0,99.896748,11619.0,3.0,99.974187,280,104,0,0.0,11619.0,3.0,99.974187,0,0.0,13.859736
3,G4,11646.0,11637.0,9.0,99.922720,11636.0,10.0,99.914134,799,67,0,0.0,11636.0,10.0,99.914134,0,0.0,14.753981
4,G5,11631.0,11622.0,9.0,99.922621,11619.0,12.0,99.896827,476,10,0,0.0,11619.0,12.0,99.896827,0,0.0,14.187588
5,G6,2178.0,2173.0,5.0,99.770432,2167.0,11.0,99.494949,500,59,0,0.0,2167.0,11.0,99.494949,0,0.0,14.313516
6,G7,2006.0,1992.0,14.0,99.302094,1998.0,8.0,99.601196,451,8,0,0.0,1998.0,8.0,99.601196,0,0.0,14.150901
7,G8,2005.0,1991.0,14.0,99.301746,1994.0,11.0,99.451372,142,38,0,0.0,1994.0,11.0,99.451372,0,0.0,14.256135
8,G9,2054.0,2041.0,13.0,99.367089,2036.0,18.0,99.123661,656,21,0,0.0,2036.0,18.0,99.123661,0,0.0,13.954206
9,G10,2000.0,1992.0,8.0,99.600000,1996.0,4.0,99.800000,628,38,0,0.0,1996.0,4.0,99.800000,0,0.0,13.853337
10,G11,564.0,556.0,8.0,98.581560,556.0,8.0,98.581560,162,78,0,0.0,556.0,8.0,98.581560,0,0.0,13.849398
11,G12,556.0,550.0,6.0,98.920863,552.0,4.0,99.280576,150,56,0,0.0,552.0,4.0,99.280576,0,0.0,13.875172
12,G13,582.0,580.0,2.0,99.656357,576.0,6.0,98.969072,155,59,0,0.0,576.0,6.0,98.969072,0,0.0,13.848776
13,G14,3064.0,3040.0,24.0,99.216710,3044.0,20.0,99.347258,1402,118,0,0.0,3044.0,20.0,99.347258,0,0.0,15.714705
14,G15,3050.0,3025.0,25.0,99.180328,3035.0,15.0,99.508197,878,57,0,0.0,3035.0,15.0,99.508197,0,0.0,15.230787
15,G16,3052.0,3027.0,25.0,99.180865,3029.0,23.0,99.246396,802,87,0,0.0,3029.0,23.0,99.246396,0,0.0,17.457791
16,G17,3047.0,3021.0,26.0,99.146702,3030.0,17.0,99.442074,936,77,0,0.0,3030.0,17.0,99.442074,0,0.0,13.381573
17,G18,992.0,978.0,14.0,98.588710,977.0,15.0,98.487903,1348,76,0,0.0,977.0,15.0,98.487903,0,0.0,13.293353
18,G19,906.0,876.0,30.0,96.688742,885.0,21.0,97.682119,990,38,0,0.0,885.0,21.0,97.682119,0,0.0,14.043475
19,G20,941.0,930.0,11.0,98.831031,926.0,15.0,98.405951,1012,14,0,0.0,926.0,15.0,98.405951,0,0.0,13.847681
20,G21,931.0,915.0,16.0,98.281418,914.0,17.0,98.174006,460,61,0,0.0,914.0,17.0,98.174006,0,0.0,13.592579

In [93]:
print("\nGroup summary:")
print("graphs:", len(group_results_df))
print("mean v1 accuracy %:", float(group_results_df["v1_percent_accuracy"].mean()))
print("mean v2 accuracy %:", float(group_results_df["v2_percent_accuracy"].mean()))
print("v1 gap-zero count:", int((group_results_df["v1_gap"] == 0).sum()))
print("v2 gap-zero count:", int((group_results_df["v2_gap"] == 0).sum()))
print("total v2 runtime sec:", float(group_results_df["v2_runtime_sec"].sum()))

Group summary:
graphs: 21
mean v1 accuracy %: 99.19803988537457
mean v2 accuracy %: 99.2431476118107
v1 gap-zero count: 0
v2 gap-zero count: 0
total v2 runtime sec: 299.5624532699585

In [94]:
# ============================================================
# Quick inspection: where did V2 improve over V1?
# ============================================================

inspection_df = group_results_df[
    [
        "instance",
        "historical_best",
        "v1_best",
        "v1_gap",
        "v1_percent_accuracy",
        "v2_best",
        "v2_gap",
        "v2_percent_accuracy",
        "v2_best_step",
        "ever_success_count",
        "ever_success_probability",
        "final_best",
        "final_gap",
        "final_percent_accuracy",
    ]
].copy()

inspection_df["gap_improvement"] = (
    inspection_df["v1_gap"] - inspection_df["v2_gap"]
)

inspection_df["accuracy_improvement"] = (
    inspection_df["v2_percent_accuracy"] - inspection_df["v1_percent_accuracy"]
)

inspection_df = inspection_df.sort_values(
    "gap_improvement",
    ascending=False,
).reset_index(drop=True)

print("=" * 80)
print("V2 IMPROVEMENT INSPECTION")
print("=" * 80)

display(inspection_df)

print("\nSummary:")
print("graphs:", len(inspection_df))
print("improved gap count:", int((inspection_df["gap_improvement"] > 0).sum()))
print("same gap count    :", int((inspection_df["gap_improvement"] == 0).sum()))
print("worse gap count   :", int((inspection_df["gap_improvement"] < 0).sum()))

print("\nGap improvement:")
print("mean:", float(inspection_df["gap_improvement"].mean()))
print("min :", float(inspection_df["gap_improvement"].min()))
print("max :", float(inspection_df["gap_improvement"].max()))

print("\nAccuracy improvement:")
print("mean:", float(inspection_df["accuracy_improvement"].mean()))
print("min :", float(inspection_df["accuracy_improvement"].min()))
print("max :", float(inspection_df["accuracy_improvement"].max()))

print("\nClosest V2 gaps:")
display(
    inspection_df.sort_values("v2_gap")[
        [
            "instance",
            "historical_best",
            "v2_best",
            "v2_gap",
            "v2_percent_accuracy",
            "v2_best_step",
            "ever_success_count",
            "final_gap",
        ]
    ].head(10)
)

================================================================================
V2 IMPROVEMENT INSPECTION
================================================================================

,instance,historical_best,v1_best,v1_gap,v1_percent_accuracy,v2_best,v2_gap,v2_percent_accuracy,v2_best_step,ever_success_count,ever_success_probability,final_best,final_gap,final_percent_accuracy,gap_improvement,accuracy_improvement
0,G15,3050.0,3025.0,25.0,99.180328,3035.0,15.0,99.508197,878,0,0.0,3035.0,15.0,99.508197,10.0,3.278689e-01
1,G3,11622.0,11610.0,12.0,99.896748,11619.0,3.0,99.974187,280,0,0.0,11619.0,3.0,99.974187,9.0,7.743934e-02
2,G19,906.0,876.0,30.0,96.688742,885.0,21.0,97.682119,990,0,0.0,885.0,21.0,97.682119,9.0,9.933775e-01
3,G17,3047.0,3021.0,26.0,99.146702,3030.0,17.0,99.442074,936,0,0.0,3030.0,17.0,99.442074,9.0,2.953725e-01
4,G7,2006.0,1992.0,14.0,99.302094,1998.0,8.0,99.601196,451,0,0.0,1998.0,8.0,99.601196,6.0,2.991027e-01
5,G14,3064.0,3040.0,24.0,99.216710,3044.0,20.0,99.347258,1402,0,0.0,3044.0,20.0,99.347258,4.0,1.305483e-01
6,G10,2000.0,1992.0,8.0,99.600000,1996.0,4.0,99.800000,628,0,0.0,1996.0,4.0,99.800000,4.0,2.000000e-01
7,G8,2005.0,1991.0,14.0,99.301746,1994.0,11.0,99.451372,142,0,0.0,1994.0,11.0,99.451372,3.0,1.496259e-01
8,G16,3052.0,3027.0,25.0,99.180865,3029.0,23.0,99.246396,802,0,0.0,3029.0,23.0,99.246396,2.0,6.553080e-02
9,G12,556.0,550.0,6.0,98.920863,552.0,4.0,99.280576,150,0,0.0,552.0,4.0,99.280576,2.0,3.597122e-01
10,G11,564.0,556.0,8.0,98.581560,556.0,8.0,98.581560,162,0,0.0,556.0,8.0,98.581560,0.0,-1.421085e-14
11,G18,992.0,978.0,14.0,98.588710,977.0,15.0,98.487903,1348,0,0.0,977.0,15.0,98.487903,-1.0,-1.008065e-01
12,G21,931.0,915.0,16.0,98.281418,914.0,17.0,98.174006,460,0,0.0,914.0,17.0,98.174006,-1.0,-1.074114e-01
13,G4,11646.0,11637.0,9.0,99.922720,11636.0,10.0,99.914134,799,0,0.0,11636.0,10.0,99.914134,-1.0,-8.586639e-03
14,G5,11631.0,11622.0,9.0,99.922621,11619.0,12.0,99.896827,476,0,0.0,11619.0,12.0,99.896827,-3.0,-2.579314e-02
15,G1,11624.0,11611.0,13.0,99.888162,11608.0,16.0,99.862354,675,0,0.0,11608.0,16.0,99.862354,-3.0,-2.580867e-02
16,G13,582.0,580.0,2.0,99.656357,576.0,6.0,98.969072,155,0,0.0,576.0,6.0,98.969072,-4.0,-6.872852e-01
17,G20,941.0,930.0,11.0,98.831031,926.0,15.0,98.405951,1012,0,0.0,926.0,15.0,98.405951,-4.0,-4.250797e-01
18,G9,2054.0,2041.0,13.0,99.367089,2036.0,18.0,99.123661,656,0,0.0,2036.0,18.0,99.123661,-5.0,-2.434275e-01
19,G2,11620.0,11610.0,10.0,99.913941,11604.0,16.0,99.862306,352,0,0.0,11604.0,16.0,99.862306,-6.0,-5.163511e-02
20,G6,2178.0,2173.0,5.0,99.770432,2167.0,11.0,99.494949,500,0,0.0,2167.0,11.0,99.494949,-6.0,-2.754821e-01

Summary:
graphs: 21
improved gap count: 10
same gap count    : 1
worse gap count   : 10

Gap improvement:
mean: 1.1428571428571428
min : -6.0
max : 10.0

Accuracy improvement:
mean: 0.04510772643611257
min : -0.6872852233677094
max : 0.9933774834437088

Closest V2 gaps:

,instance,historical_best,v2_best,v2_gap,v2_percent_accuracy,v2_best_step,ever_success_count,final_gap
1,G3,11622.0,11619.0,3.0,99.974187,280,0,3.0
9,G12,556.0,552.0,4.0,99.280576,150,0,4.0
6,G10,2000.0,1996.0,4.0,99.800000,628,0,4.0
16,G13,582.0,576.0,6.0,98.969072,155,0,6.0
10,G11,564.0,556.0,8.0,98.581560,162,0,8.0
4,G7,2006.0,1998.0,8.0,99.601196,451,0,8.0
13,G4,11646.0,11636.0,10.0,99.914134,799,0,10.0
20,G6,2178.0,2167.0,11.0,99.494949,500,0,11.0
7,G8,2005.0,1994.0,11.0,99.451372,142,0,11.0
14,G5,11631.0,11619.0,12.0,99.896827,476,0,12.0

# 1

In [95]:
# ============================================================
# Cell 10: Select run group and run QEFEM v2
# ============================================================

# ------------------------------------------------------------
# Choose run group here
# ------------------------------------------------------------
# 0 -> small_1_3   : G1-G21
# 1 -> small_4_6   : G22-G42
# 2 -> small_7_9   : G43-G54
# 3 -> big_10_12   : G55-G59
# 4 -> big_13_15   : G60-G64
# 5 -> big_16_18   : G65, G66, G67, G72
# 6 -> big_19_21   : G70, G77, G81

RUN_GROUP_INDEX = 1


# ------------------------------------------------------------
# Preview selected group
# ------------------------------------------------------------

selected_group_row = run_group_summary_df.iloc[RUN_GROUP_INDEX]

print("=" * 80)
print("SELECTED RUN GROUP")
print("=" * 80)

print("RUN_GROUP_INDEX:", RUN_GROUP_INDEX)
print("run_group:", selected_group_row["run_group"])
print("partitions:", selected_group_row["partitions"])
print("graphs_start:", selected_group_row["graphs_start"])
print("graphs_end:", selected_group_row["graphs_end"])
print("num_graphs:", selected_group_row["num_graphs"])
print("graph_types:", selected_group_row["graph_types"])
print("storage_modes:", selected_group_row["storage_modes"])
print("graphs:", selected_group_row["graphs"])


# ------------------------------------------------------------
# Run selected group
# ------------------------------------------------------------

group_results_df, group_logs_df = run_qefem_run_group(
    run_group_index=RUN_GROUP_INDEX
)


# ------------------------------------------------------------
# Final compact display
# ------------------------------------------------------------

compact_group_results_df = group_results_df[
    [
        "instance",
        "historical_best",
        "v1_best",
        "v1_gap",
        "v1_percent_accuracy",
        "v2_best",
        "v2_gap",
        "v2_percent_accuracy",
        "v2_best_step",
        "v2_best_replica",
        "ever_success_count",
        "ever_success_probability",
        "final_best",
        "final_gap",
        "final_percent_accuracy",
        "final_success_count",
        "final_success_probability",
        "v2_runtime_sec",
    ]
].copy()

print("\n" + "=" * 80)
print("COMPACT GROUP RESULT")
print("=" * 80)

display(compact_group_results_df)

================================================================================
SELECTED RUN GROUP
================================================================================
RUN_GROUP_INDEX: 1
run_group: small_4_6
partitions: [4, 5, 6]
graphs_start: G22
graphs_end: G42
num_graphs: 21
graph_types: ['plain', 'random', 'toroidal']
storage_modes: ['dense']
graphs: ['G22', 'G23', 'G24', 'G25', 'G26', 'G27', 'G28', 'G29', 'G30', 'G31', 'G32', 'G33', 'G34', 'G35', 'G36', 'G37', 'G38', 'G39', 'G40', 'G41', 'G42']
================================================================================
RUNNING QEFEM V2 RUN GROUP
================================================================================
run_group_index: 1
run_group: small_4_6
graphs: ['G22', 'G23', 'G24', 'G25', 'G26', 'G27', 'G28', 'G29', 'G30', 'G31', 'G32', 'G33', 'G34', 'G35', 'G36', 'G37', 'G38', 'G39', 'G40', 'G41', 'G42']
num graphs: 21

Output directory:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6

Selected benchmark rows:

,partition,instance,graph_type,storage_mode,nodes,edges,n_steps,replicas,lr,v1_best,historical_best,v1_gap,v1_percent_accuracy,v1_best_replica,v1_runtime_sec
0,4,G22,random,dense,2000,19990,1000,128,0.01,13312.0,13359.0,47.0,99.648177,62,28.868857
1,4,G23,random,dense,2000,19990,1000,128,0.01,13303.0,13344.0,41.0,99.692746,126,27.262093
2,4,G24,random,dense,2000,19990,1000,128,0.01,13290.0,13337.0,47.0,99.647597,115,27.161593
3,4,G25,random,dense,2000,19990,1000,128,0.01,13284.0,13340.0,56.0,99.580210,37,17.130322
4,4,G26,random,dense,2000,19990,1000,128,0.01,13270.0,13328.0,58.0,99.564826,60,27.052540
5,4,G27,random,dense,2000,19990,1000,128,0.01,3310.0,3341.0,31.0,99.072134,12,27.190325
6,4,G28,random,dense,2000,19990,1000,128,0.01,3275.0,3298.0,23.0,99.302608,41,27.077625
7,4,G29,random,dense,2000,19990,1000,128,0.01,3351.0,3405.0,54.0,98.414097,21,27.510255
8,4,G30,random,dense,2000,19990,1000,128,0.01,3367.0,3413.0,46.0,98.652212,37,28.035532
9,4,G31,random,dense,2000,19990,1000,128,0.01,3282.0,3310.0,28.0,99.154079,13,28.277718
10,5,G32,toroidal,dense,2000,4000,1000,128,0.01,1388.0,1410.0,22.0,98.439716,91,27.570102
11,5,G33,toroidal,dense,2000,4000,1000,128,0.01,1364.0,1382.0,18.0,98.697540,26,27.213099
12,5,G34,toroidal,dense,2000,4000,1000,128,0.01,1362.0,1384.0,22.0,98.410405,102,170.757319
13,6,G35,plain,dense,2000,11778,1000,128,0.01,7612.0,7687.0,75.0,99.024327,121,29.317037
14,6,G36,plain,dense,2000,11766,1000,128,0.01,7599.0,7680.0,81.0,98.945312,27,29.132177
15,6,G37,plain,dense,2000,11785,1000,128,0.01,7619.0,7691.0,72.0,99.063841,17,29.592312
16,6,G38,plain,dense,2000,11779,1000,128,0.01,7616.0,7688.0,72.0,99.063476,113,29.740165
17,6,G39,plain,dense,2000,11778,1000,128,0.01,2336.0,2408.0,72.0,97.009967,122,29.883690
18,6,G40,plain,dense,2000,11766,1000,128,0.01,2296.0,2400.0,104.0,95.666667,17,29.288478
19,6,G41,plain,dense,2000,11785,1000,128,0.01,2289.0,2405.0,116.0,95.176715,10,27.716142
20,6,G42,plain,dense,2000,11779,1000,128,0.01,2381.0,2481.0,100.0,95.969367,122,27.405643

################################################################################
RUNNING G22 | dense | seed=7
################################################################################
G22 | step     1/2000 | best 10112.0 | acc 75.6943% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G22 | step    50/2000 | best 10649.0 | acc 79.7141% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G22 | step   100/2000 | best 12775.0 | acc 95.6284% | success 0/128 | gamma 0.95048 | |rz| 0.0086
G22 | step   150/2000 | best 13260.0 | acc 99.2589% | success 0/128 | gamma 0.92546 | |rz| 0.7607
G22 | step   200/2000 | best 13277.0 | acc 99.3862% | success 0/128 | gamma 0.90045 | |rz| 0.8357
G22 | step   250/2000 | best 13284.0 | acc 99.4386% | success 0/128 | gamma 0.87544 | |rz| 0.8552
G22 | step   300/2000 | best 13284.0 | acc 99.4386% | success 0/128 | gamma 0.85043 | |rz| 0.8663
G22 | step   350/2000 | best 13287.0 | acc 99.4610% | success 0/128 | gamma 0.82541 | |rz| 0.8746
G22 | step   400/2000 | best 13287.0 | acc 99.4610% | success 0/128 | gamma 0.80040 | |rz| 0.8818
G22 | step   450/2000 | best 13289.0 | acc 99.4760% | success 0/128 | gamma 0.77539 | |rz| 0.8883
G22 | step   500/2000 | best 13290.0 | acc 99.4835% | success 0/128 | gamma 0.75038 | |rz| 0.8942
G22 | step   550/2000 | best 13290.0 | acc 99.4835% | success 0/128 | gamma 0.72536 | |rz| 0.8998
G22 | step   600/2000 | best 13291.0 | acc 99.4910% | success 0/128 | gamma 0.70035 | |rz| 0.9051
G22 | step   650/2000 | best 13292.0 | acc 99.4985% | success 0/128 | gamma 0.67534 | |rz| 0.9103
G22 | step   700/2000 | best 13292.0 | acc 99.4985% | success 0/128 | gamma 0.65033 | |rz| 0.9152
G22 | step   750/2000 | best 13292.0 | acc 99.4985% | success 0/128 | gamma 0.62531 | |rz| 0.9200
G22 | step   800/2000 | best 13292.0 | acc 99.4985% | success 0/128 | gamma 0.60030 | |rz| 0.9245
G22 | step   850/2000 | best 13292.0 | acc 99.4985% | success 0/128 | gamma 0.57529 | |rz| 0.9289
G22 | step   900/2000 | best 13292.0 | acc 99.4985% | success 0/128 | gamma 0.55028 | |rz| 0.9331
G22 | step   950/2000 | best 13293.0 | acc 99.5060% | success 0/128 | gamma 0.52526 | |rz| 0.9372
G22 | step  1000/2000 | best 13293.0 | acc 99.5060% | success 0/128 | gamma 0.50025 | |rz| 0.9411
G22 | step  1050/2000 | best 13293.0 | acc 99.5060% | success 0/128 | gamma 0.47524 | |rz| 0.9449
G22 | step  1100/2000 | best 13294.0 | acc 99.5134% | success 0/128 | gamma 0.45023 | |rz| 0.9485
G22 | step  1150/2000 | best 13294.0 | acc 99.5134% | success 0/128 | gamma 0.42521 | |rz| 0.9520
G22 | step  1200/2000 | best 13294.0 | acc 99.5134% | success 0/128 | gamma 0.40020 | |rz| 0.9554
G22 | step  1250/2000 | best 13294.0 | acc 99.5134% | success 0/128 | gamma 0.37519 | |rz| 0.9586
G22 | step  1300/2000 | best 13294.0 | acc 99.5134% | success 0/128 | gamma 0.35018 | |rz| 0.9618
G22 | step  1350/2000 | best 13294.0 | acc 99.5134% | success 0/128 | gamma 0.32517 | |rz| 0.9647
G22 | step  1400/2000 | best 13294.0 | acc 99.5134% | success 0/128 | gamma 0.30034 | |rz| 0.9675
G22 | step  1450/2000 | best 13294.0 | acc 99.5134% | success 0/128 | gamma 0.27732 | |rz| 0.9700
G22 | step  1500/2000 | best 13294.0 | acc 99.5134% | success 0/128 | gamma 0.26252 | |rz| 0.9717
G22 | step  1550/2000 | best 13294.0 | acc 99.5134% | success 0/128 | gamma 0.26035 | |rz| 0.9724
G22 | step  1600/2000 | best 13294.0 | acc 99.5134% | success 0/128 | gamma 0.25010 | |rz| 0.9737
G22 | step  1650/2000 | best 13294.0 | acc 99.5134% | success 0/128 | gamma 0.21052 | |rz| 0.9768
G22 | step  1700/2000 | best 13294.0 | acc 99.5134% | success 0/128 | gamma 0.16261 | |rz| 0.9797
G22 | step  1750/2000 | best 13294.0 | acc 99.5134% | success 0/128 | gamma 0.12728 | |rz| 0.9814
G22 | step  1800/2000 | best 13294.0 | acc 99.5134% | success 0/128 | gamma 0.10025 | |rz| 0.9825
G22 | step  1850/2000 | best 13294.0 | acc 99.5134% | success 0/128 | gamma 0.07505 | |rz| 0.9834
G22 | step  1900/2000 | best 13294.0 | acc 99.5134% | success 0/128 | gamma 0.05003 | |rz| 0.9840
G22 | step  1950/2000 | best 13294.0 | acc 99.5134% | success 0/128 | gamma 0.02501 | |rz| 0.9846
G22 | step  2000/2000 | best 13294.0 | acc 99.5134% | success 0/128 | gamma 0.00000 | |rz| 0.9864

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G22
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644291e-05,0.000026,0.000011,1.088242e-05,0.001052
1,theta_grad_mean_abs,6.238754e-07,0.000002,0.000002,2.529572e-07,0.000386
2,raw_R_step_mean_abs,2.999592e-02,0.002253,0.001914,1.914120e-03,0.048874
3,theta_step_mean_abs,2.865444e-02,0.000338,0.000592,2.316277e-04,0.028654
4,raw_R_grad_norm,3.867741e-02,0.014414,0.005754,5.754185e-03,0.628221
5,theta_grad_norm,3.951626e-04,0.004864,0.004552,1.599795e-04,0.302240
6,raw_R_step_norm,1.517687e+01,1.214647,1.056663,1.056663e+00,24.728487
7,theta_step_norm,1.456032e+01,0.507620,1.280615,3.320543e-01,14.560323

--------------------------------------------------------------------------------
RESULT SUMMARY: G22
--------------------------------------------------------------------------------
historical_best: 13359.0

V1:
v1_best: 13312.0
v1_gap: 47.0
v1_percent_accuracy: 99.64817725877684

V2:
v2_best: 13294.0
v2_gap: 65.0
v2_percent_accuracy: 99.51343663447862
v2_best_step: 1099
v2_best_replica: 99

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 25.044713258743286

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/logs/G22_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/best_spins/G22_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/partial_group_results.csv

################################################################################
RUNNING G23 | dense | seed=8
################################################################################
G23 | step     1/2000 | best 10088.0 | acc 75.5995% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G23 | step    50/2000 | best 10629.0 | acc 79.6538% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G23 | step   100/2000 | best 12805.0 | acc 95.9607% | success 0/128 | gamma 0.95048 | |rz| 0.0088
G23 | step   150/2000 | best 13244.0 | acc 99.2506% | success 0/128 | gamma 0.92546 | |rz| 0.7619
G23 | step   200/2000 | best 13271.0 | acc 99.4529% | success 0/128 | gamma 0.90045 | |rz| 0.8365
G23 | step   250/2000 | best 13278.0 | acc 99.5054% | success 0/128 | gamma 0.87544 | |rz| 0.8563
G23 | step   300/2000 | best 13279.0 | acc 99.5129% | success 0/128 | gamma 0.85043 | |rz| 0.8676
G23 | step   350/2000 | best 13284.0 | acc 99.5504% | success 0/128 | gamma 0.82541 | |rz| 0.8761
G23 | step   400/2000 | best 13285.0 | acc 99.5579% | success 0/128 | gamma 0.80040 | |rz| 0.8832
G23 | step   450/2000 | best 13287.0 | acc 99.5728% | success 0/128 | gamma 0.77539 | |rz| 0.8895
G23 | step   500/2000 | best 13287.0 | acc 99.5728% | success 0/128 | gamma 0.75038 | |rz| 0.8954
G23 | step   550/2000 | best 13292.0 | acc 99.6103% | success 0/128 | gamma 0.72536 | |rz| 0.9009
G23 | step   600/2000 | best 13292.0 | acc 99.6103% | success 0/128 | gamma 0.70035 | |rz| 0.9062
G23 | step   650/2000 | best 13292.0 | acc 99.6103% | success 0/128 | gamma 0.67534 | |rz| 0.9113
G23 | step   700/2000 | best 13292.0 | acc 99.6103% | success 0/128 | gamma 0.65033 | |rz| 0.9161
G23 | step   750/2000 | best 13292.0 | acc 99.6103% | success 0/128 | gamma 0.62531 | |rz| 0.9208
G23 | step   800/2000 | best 13295.0 | acc 99.6328% | success 0/128 | gamma 0.60030 | |rz| 0.9253
G23 | step   850/2000 | best 13295.0 | acc 99.6328% | success 0/128 | gamma 0.57529 | |rz| 0.9296
G23 | step   900/2000 | best 13295.0 | acc 99.6328% | success 0/128 | gamma 0.55028 | |rz| 0.9338
G23 | step   950/2000 | best 13295.0 | acc 99.6328% | success 0/128 | gamma 0.52526 | |rz| 0.9378
G23 | step  1000/2000 | best 13295.0 | acc 99.6328% | success 0/128 | gamma 0.50025 | |rz| 0.9417
G23 | step  1050/2000 | best 13295.0 | acc 99.6328% | success 0/128 | gamma 0.47524 | |rz| 0.9454
G23 | step  1100/2000 | best 13295.0 | acc 99.6328% | success 0/128 | gamma 0.45023 | |rz| 0.9490
G23 | step  1150/2000 | best 13295.0 | acc 99.6328% | success 0/128 | gamma 0.42521 | |rz| 0.9524
G23 | step  1200/2000 | best 13295.0 | acc 99.6328% | success 0/128 | gamma 0.40020 | |rz| 0.9557
G23 | step  1250/2000 | best 13295.0 | acc 99.6328% | success 0/128 | gamma 0.37519 | |rz| 0.9589
G23 | step  1300/2000 | best 13295.0 | acc 99.6328% | success 0/128 | gamma 0.35018 | |rz| 0.9620
G23 | step  1350/2000 | best 13295.0 | acc 99.6328% | success 0/128 | gamma 0.32517 | |rz| 0.9648
G23 | step  1400/2000 | best 13295.0 | acc 99.6328% | success 0/128 | gamma 0.30034 | |rz| 0.9676
G23 | step  1450/2000 | best 13295.0 | acc 99.6328% | success 0/128 | gamma 0.27732 | |rz| 0.9699
G23 | step  1500/2000 | best 13295.0 | acc 99.6328% | success 0/128 | gamma 0.26252 | |rz| 0.9716
G23 | step  1550/2000 | best 13295.0 | acc 99.6328% | success 0/128 | gamma 0.26035 | |rz| 0.9724
G23 | step  1600/2000 | best 13295.0 | acc 99.6328% | success 0/128 | gamma 0.25010 | |rz| 0.9736
G23 | step  1650/2000 | best 13295.0 | acc 99.6328% | success 0/128 | gamma 0.21052 | |rz| 0.9766
G23 | step  1700/2000 | best 13295.0 | acc 99.6328% | success 0/128 | gamma 0.16261 | |rz| 0.9795
G23 | step  1750/2000 | best 13295.0 | acc 99.6328% | success 0/128 | gamma 0.12728 | |rz| 0.9811
G23 | step  1800/2000 | best 13295.0 | acc 99.6328% | success 0/128 | gamma 0.10025 | |rz| 0.9822
G23 | step  1850/2000 | best 13295.0 | acc 99.6328% | success 0/128 | gamma 0.07505 | |rz| 0.9830
G23 | step  1900/2000 | best 13295.0 | acc 99.6328% | success 0/128 | gamma 0.05003 | |rz| 0.9837
G23 | step  1950/2000 | best 13295.0 | acc 99.6328% | success 0/128 | gamma 0.02501 | |rz| 0.9842
G23 | step  2000/2000 | best 13295.0 | acc 99.6328% | success 0/128 | gamma 0.00000 | |rz| 0.9861

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G23
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644274e-05,0.000026,0.000011,1.085901e-05,0.001052
1,theta_grad_mean_abs,6.253092e-07,0.000002,0.000002,2.529429e-07,0.000387
2,raw_R_step_mean_abs,2.999592e-02,0.002252,0.001907,1.906935e-03,0.048874
3,theta_step_mean_abs,2.864832e-02,0.000331,0.000599,2.295798e-04,0.028648
4,raw_R_grad_norm,3.867732e-02,0.014339,0.005738,5.737794e-03,0.626821
5,theta_grad_norm,3.962156e-04,0.003443,0.004638,1.597442e-04,0.301802
6,raw_R_step_norm,1.517687e+01,1.210719,1.051570,1.051570e+00,24.728617
7,theta_step_norm,1.455825e+01,0.420631,1.306330,3.279331e-01,14.558254

--------------------------------------------------------------------------------
RESULT SUMMARY: G23
--------------------------------------------------------------------------------
historical_best: 13344.0

V1:
v1_best: 13303.0
v1_gap: 41.0
v1_percent_accuracy: 99.69274580335733

V2:
v2_best: 13295.0
v2_gap: 49.0
v2_percent_accuracy: 99.63279376498801
v2_best_step: 768
v2_best_replica: 9

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 27.267494916915894

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/logs/G23_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/best_spins/G23_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/partial_group_results.csv

################################################################################
RUNNING G24 | dense | seed=9
################################################################################
G24 | step     1/2000 | best 10088.0 | acc 75.6392% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G24 | step    50/2000 | best 10602.0 | acc 79.4931% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G24 | step   100/2000 | best 12803.0 | acc 95.9961% | success 0/128 | gamma 0.95048 | |rz| 0.0087
G24 | step   150/2000 | best 13239.0 | acc 99.2652% | success 0/128 | gamma 0.92546 | |rz| 0.7612
G24 | step   200/2000 | best 13255.0 | acc 99.3852% | success 0/128 | gamma 0.90045 | |rz| 0.8362
G24 | step   250/2000 | best 13264.0 | acc 99.4527% | success 0/128 | gamma 0.87544 | |rz| 0.8559
G24 | step   300/2000 | best 13269.0 | acc 99.4901% | success 0/128 | gamma 0.85043 | |rz| 0.8672
G24 | step   350/2000 | best 13277.0 | acc 99.5501% | success 0/128 | gamma 0.82541 | |rz| 0.8756
G24 | step   400/2000 | best 13281.0 | acc 99.5801% | success 0/128 | gamma 0.80040 | |rz| 0.8827
G24 | step   450/2000 | best 13282.0 | acc 99.5876% | success 0/128 | gamma 0.77539 | |rz| 0.8891
G24 | step   500/2000 | best 13282.0 | acc 99.5876% | success 0/128 | gamma 0.75038 | |rz| 0.8950
G24 | step   550/2000 | best 13282.0 | acc 99.5876% | success 0/128 | gamma 0.72536 | |rz| 0.9006
G24 | step   600/2000 | best 13282.0 | acc 99.5876% | success 0/128 | gamma 0.70035 | |rz| 0.9059
G24 | step   650/2000 | best 13282.0 | acc 99.5876% | success 0/128 | gamma 0.67534 | |rz| 0.9109
G24 | step   700/2000 | best 13283.0 | acc 99.5951% | success 0/128 | gamma 0.65033 | |rz| 0.9158
G24 | step   750/2000 | best 13283.0 | acc 99.5951% | success 0/128 | gamma 0.62531 | |rz| 0.9204
G24 | step   800/2000 | best 13283.0 | acc 99.5951% | success 0/128 | gamma 0.60030 | |rz| 0.9249
G24 | step   850/2000 | best 13283.0 | acc 99.5951% | success 0/128 | gamma 0.57529 | |rz| 0.9292
G24 | step   900/2000 | best 13283.0 | acc 99.5951% | success 0/128 | gamma 0.55028 | |rz| 0.9334
G24 | step   950/2000 | best 13283.0 | acc 99.5951% | success 0/128 | gamma 0.52526 | |rz| 0.9374
G24 | step  1000/2000 | best 13283.0 | acc 99.5951% | success 0/128 | gamma 0.50025 | |rz| 0.9413
G24 | step  1050/2000 | best 13283.0 | acc 99.5951% | success 0/128 | gamma 0.47524 | |rz| 0.9451
G24 | step  1100/2000 | best 13283.0 | acc 99.5951% | success 0/128 | gamma 0.45023 | |rz| 0.9486
G24 | step  1150/2000 | best 13283.0 | acc 99.5951% | success 0/128 | gamma 0.42521 | |rz| 0.9521
G24 | step  1200/2000 | best 13283.0 | acc 99.5951% | success 0/128 | gamma 0.40020 | |rz| 0.9554
G24 | step  1250/2000 | best 13283.0 | acc 99.5951% | success 0/128 | gamma 0.37519 | |rz| 0.9587
G24 | step  1300/2000 | best 13283.0 | acc 99.5951% | success 0/128 | gamma 0.35018 | |rz| 0.9618
G24 | step  1350/2000 | best 13283.0 | acc 99.5951% | success 0/128 | gamma 0.32517 | |rz| 0.9647
G24 | step  1400/2000 | best 13283.0 | acc 99.5951% | success 0/128 | gamma 0.30034 | |rz| 0.9674
G24 | step  1450/2000 | best 13283.0 | acc 99.5951% | success 0/128 | gamma 0.27732 | |rz| 0.9699
G24 | step  1500/2000 | best 13283.0 | acc 99.5951% | success 0/128 | gamma 0.26252 | |rz| 0.9716
G24 | step  1550/2000 | best 13283.0 | acc 99.5951% | success 0/128 | gamma 0.26035 | |rz| 0.9723
G24 | step  1600/2000 | best 13283.0 | acc 99.5951% | success 0/128 | gamma 0.25010 | |rz| 0.9736
G24 | step  1650/2000 | best 13283.0 | acc 99.5951% | success 0/128 | gamma 0.21052 | |rz| 0.9766
G24 | step  1700/2000 | best 13283.0 | acc 99.5951% | success 0/128 | gamma 0.16261 | |rz| 0.9795
G24 | step  1750/2000 | best 13283.0 | acc 99.5951% | success 0/128 | gamma 0.12728 | |rz| 0.9812
G24 | step  1800/2000 | best 13283.0 | acc 99.5951% | success 0/128 | gamma 0.10025 | |rz| 0.9823
G24 | step  1850/2000 | best 13283.0 | acc 99.5951% | success 0/128 | gamma 0.07505 | |rz| 0.9832
G24 | step  1900/2000 | best 13283.0 | acc 99.5951% | success 0/128 | gamma 0.05003 | |rz| 0.9838
G24 | step  1950/2000 | best 13283.0 | acc 99.5951% | success 0/128 | gamma 0.02501 | |rz| 0.9844
G24 | step  2000/2000 | best 13283.0 | acc 99.5951% | success 0/128 | gamma 0.00000 | |rz| 0.9861

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G24
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644279e-05,0.000026,0.000011,1.086677e-05,0.001051
1,theta_grad_mean_abs,6.245788e-07,0.000002,0.000002,2.531528e-07,0.000385
2,raw_R_step_mean_abs,2.999592e-02,0.002246,0.001910,1.910453e-03,0.048874
3,theta_step_mean_abs,2.864361e-02,0.000322,0.000583,2.332470e-04,0.028644
4,raw_R_grad_norm,3.867735e-02,0.014237,0.005745,5.744726e-03,0.626372
5,theta_grad_norm,3.961581e-04,0.003233,0.004529,1.598323e-04,0.300679
6,raw_R_step_norm,1.517687e+01,1.195961,1.054494,1.054494e+00,24.728531
7,theta_step_norm,1.455664e+01,0.346170,1.252823,3.248158e-01,14.556641

--------------------------------------------------------------------------------
RESULT SUMMARY: G24
--------------------------------------------------------------------------------
historical_best: 13337.0

V1:
v1_best: 13290.0
v1_gap: 47.0
v1_percent_accuracy: 99.64759691084951

V2:
v2_best: 13283.0
v2_gap: 54.0
v2_percent_accuracy: 99.5951113443803
v2_best_step: 685
v2_best_replica: 11

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 24.199018001556396

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/logs/G24_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/best_spins/G24_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/partial_group_results.csv

################################################################################
RUNNING G25 | dense | seed=10
################################################################################
G25 | step     1/2000 | best 10164.0 | acc 76.1919% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G25 | step    50/2000 | best 10573.0 | acc 79.2579% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G25 | step   100/2000 | best 12779.0 | acc 95.7946% | success 0/128 | gamma 0.95048 | |rz| 0.0088
G25 | step   150/2000 | best 13237.0 | acc 99.2279% | success 0/128 | gamma 0.92546 | |rz| 0.7614
G25 | step   200/2000 | best 13258.0 | acc 99.3853% | success 0/128 | gamma 0.90045 | |rz| 0.8366
G25 | step   250/2000 | best 13264.0 | acc 99.4303% | success 0/128 | gamma 0.87544 | |rz| 0.8560
G25 | step   300/2000 | best 13272.0 | acc 99.4903% | success 0/128 | gamma 0.85043 | |rz| 0.8673
G25 | step   350/2000 | best 13272.0 | acc 99.4903% | success 0/128 | gamma 0.82541 | |rz| 0.8758
G25 | step   400/2000 | best 13272.0 | acc 99.4903% | success 0/128 | gamma 0.80040 | |rz| 0.8829
G25 | step   450/2000 | best 13275.0 | acc 99.5127% | success 0/128 | gamma 0.77539 | |rz| 0.8893
G25 | step   500/2000 | best 13277.0 | acc 99.5277% | success 0/128 | gamma 0.75038 | |rz| 0.8952
G25 | step   550/2000 | best 13279.0 | acc 99.5427% | success 0/128 | gamma 0.72536 | |rz| 0.9008
G25 | step   600/2000 | best 13279.0 | acc 99.5427% | success 0/128 | gamma 0.70035 | |rz| 0.9061
G25 | step   650/2000 | best 13279.0 | acc 99.5427% | success 0/128 | gamma 0.67534 | |rz| 0.9111
G25 | step   700/2000 | best 13279.0 | acc 99.5427% | success 0/128 | gamma 0.65033 | |rz| 0.9160
G25 | step   750/2000 | best 13279.0 | acc 99.5427% | success 0/128 | gamma 0.62531 | |rz| 0.9207
G25 | step   800/2000 | best 13280.0 | acc 99.5502% | success 0/128 | gamma 0.60030 | |rz| 0.9252
G25 | step   850/2000 | best 13280.0 | acc 99.5502% | success 0/128 | gamma 0.57529 | |rz| 0.9296
G25 | step   900/2000 | best 13280.0 | acc 99.5502% | success 0/128 | gamma 0.55028 | |rz| 0.9337
G25 | step   950/2000 | best 13280.0 | acc 99.5502% | success 0/128 | gamma 0.52526 | |rz| 0.9377
G25 | step  1000/2000 | best 13281.0 | acc 99.5577% | success 0/128 | gamma 0.50025 | |rz| 0.9416
G25 | step  1050/2000 | best 13281.0 | acc 99.5577% | success 0/128 | gamma 0.47524 | |rz| 0.9453
G25 | step  1100/2000 | best 13281.0 | acc 99.5577% | success 0/128 | gamma 0.45023 | |rz| 0.9489
G25 | step  1150/2000 | best 13281.0 | acc 99.5577% | success 0/128 | gamma 0.42521 | |rz| 0.9524
G25 | step  1200/2000 | best 13281.0 | acc 99.5577% | success 0/128 | gamma 0.40020 | |rz| 0.9558
G25 | step  1250/2000 | best 13281.0 | acc 99.5577% | success 0/128 | gamma 0.37519 | |rz| 0.9590
G25 | step  1300/2000 | best 13281.0 | acc 99.5577% | success 0/128 | gamma 0.35018 | |rz| 0.9620
G25 | step  1350/2000 | best 13281.0 | acc 99.5577% | success 0/128 | gamma 0.32517 | |rz| 0.9650
G25 | step  1400/2000 | best 13281.0 | acc 99.5577% | success 0/128 | gamma 0.30034 | |rz| 0.9677
G25 | step  1450/2000 | best 13281.0 | acc 99.5577% | success 0/128 | gamma 0.27732 | |rz| 0.9701
G25 | step  1500/2000 | best 13281.0 | acc 99.5577% | success 0/128 | gamma 0.26252 | |rz| 0.9718
G25 | step  1550/2000 | best 13281.0 | acc 99.5577% | success 0/128 | gamma 0.26035 | |rz| 0.9725
G25 | step  1600/2000 | best 13281.0 | acc 99.5577% | success 0/128 | gamma 0.25010 | |rz| 0.9738
G25 | step  1650/2000 | best 13281.0 | acc 99.5577% | success 0/128 | gamma 0.21052 | |rz| 0.9768
G25 | step  1700/2000 | best 13281.0 | acc 99.5577% | success 0/128 | gamma 0.16261 | |rz| 0.9796
G25 | step  1750/2000 | best 13281.0 | acc 99.5577% | success 0/128 | gamma 0.12728 | |rz| 0.9814
G25 | step  1800/2000 | best 13281.0 | acc 99.5577% | success 0/128 | gamma 0.10025 | |rz| 0.9824
G25 | step  1850/2000 | best 13281.0 | acc 99.5577% | success 0/128 | gamma 0.07505 | |rz| 0.9833
G25 | step  1900/2000 | best 13281.0 | acc 99.5577% | success 0/128 | gamma 0.05003 | |rz| 0.9839
G25 | step  1950/2000 | best 13281.0 | acc 99.5577% | success 0/128 | gamma 0.02501 | |rz| 0.9844
G25 | step  2000/2000 | best 13281.0 | acc 99.5577% | success 0/128 | gamma 0.00000 | |rz| 0.9862

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G25
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644264e-05,0.000026,0.000011,1.086234e-05,0.001051
1,theta_grad_mean_abs,6.229705e-07,0.000002,0.000002,2.530425e-07,0.000385
2,raw_R_step_mean_abs,2.999592e-02,0.002249,0.001909,1.909464e-03,0.048874
3,theta_step_mean_abs,2.863598e-02,0.000331,0.000587,2.305708e-04,0.028636
4,raw_R_grad_norm,3.867728e-02,0.014424,0.005743,5.742521e-03,0.626811
5,theta_grad_norm,3.948345e-04,0.004906,0.004552,1.599080e-04,0.300085
6,raw_R_step_norm,1.517687e+01,1.209468,1.053082,1.053082e+00,24.728668
7,theta_step_norm,1.455373e+01,0.429402,1.259576,3.386926e-01,14.553732

--------------------------------------------------------------------------------
RESULT SUMMARY: G25
--------------------------------------------------------------------------------
historical_best: 13340.0

V1:
v1_best: 13284.0
v1_gap: 56.0
v1_percent_accuracy: 99.58020989505248

V2:
v2_best: 13281.0
v2_gap: 59.0
v2_percent_accuracy: 99.55772113943029
v2_best_step: 989
v2_best_replica: 0

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 25.79948616027832

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/logs/G25_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/best_spins/G25_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/partial_group_results.csv

################################################################################
RUNNING G26 | dense | seed=11
################################################################################
G26 | step     1/2000 | best 10145.0 | acc 76.1179% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G26 | step    50/2000 | best 10615.0 | acc 79.6444% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G26 | step   100/2000 | best 12775.0 | acc 95.8508% | success 0/128 | gamma 0.95048 | |rz| 0.0082
G26 | step   150/2000 | best 13220.0 | acc 99.1897% | success 0/128 | gamma 0.92546 | |rz| 0.7613
G26 | step   200/2000 | best 13249.0 | acc 99.4073% | success 0/128 | gamma 0.90045 | |rz| 0.8361
G26 | step   250/2000 | best 13255.0 | acc 99.4523% | success 0/128 | gamma 0.87544 | |rz| 0.8557
G26 | step   300/2000 | best 13263.0 | acc 99.5123% | success 0/128 | gamma 0.85043 | |rz| 0.8671
G26 | step   350/2000 | best 13265.0 | acc 99.5273% | success 0/128 | gamma 0.82541 | |rz| 0.8757
G26 | step   400/2000 | best 13270.0 | acc 99.5648% | success 0/128 | gamma 0.80040 | |rz| 0.8827
G26 | step   450/2000 | best 13271.0 | acc 99.5723% | success 0/128 | gamma 0.77539 | |rz| 0.8890
G26 | step   500/2000 | best 13271.0 | acc 99.5723% | success 0/128 | gamma 0.75038 | |rz| 0.8949
G26 | step   550/2000 | best 13273.0 | acc 99.5873% | success 0/128 | gamma 0.72536 | |rz| 0.9006
G26 | step   600/2000 | best 13273.0 | acc 99.5873% | success 0/128 | gamma 0.70035 | |rz| 0.9059
G26 | step   650/2000 | best 13273.0 | acc 99.5873% | success 0/128 | gamma 0.67534 | |rz| 0.9109
G26 | step   700/2000 | best 13273.0 | acc 99.5873% | success 0/128 | gamma 0.65033 | |rz| 0.9157
G26 | step   750/2000 | best 13273.0 | acc 99.5873% | success 0/128 | gamma 0.62531 | |rz| 0.9204
G26 | step   800/2000 | best 13273.0 | acc 99.5873% | success 0/128 | gamma 0.60030 | |rz| 0.9249
G26 | step   850/2000 | best 13273.0 | acc 99.5873% | success 0/128 | gamma 0.57529 | |rz| 0.9293
G26 | step   900/2000 | best 13276.0 | acc 99.6098% | success 0/128 | gamma 0.55028 | |rz| 0.9335
G26 | step   950/2000 | best 13276.0 | acc 99.6098% | success 0/128 | gamma 0.52526 | |rz| 0.9375
G26 | step  1000/2000 | best 13277.0 | acc 99.6173% | success 0/128 | gamma 0.50025 | |rz| 0.9414
G26 | step  1050/2000 | best 13277.0 | acc 99.6173% | success 0/128 | gamma 0.47524 | |rz| 0.9452
G26 | step  1100/2000 | best 13277.0 | acc 99.6173% | success 0/128 | gamma 0.45023 | |rz| 0.9488
G26 | step  1150/2000 | best 13277.0 | acc 99.6173% | success 0/128 | gamma 0.42521 | |rz| 0.9523
G26 | step  1200/2000 | best 13277.0 | acc 99.6173% | success 0/128 | gamma 0.40020 | |rz| 0.9556
G26 | step  1250/2000 | best 13277.0 | acc 99.6173% | success 0/128 | gamma 0.37519 | |rz| 0.9588
G26 | step  1300/2000 | best 13277.0 | acc 99.6173% | success 0/128 | gamma 0.35018 | |rz| 0.9619
G26 | step  1350/2000 | best 13277.0 | acc 99.6173% | success 0/128 | gamma 0.32517 | |rz| 0.9648
G26 | step  1400/2000 | best 13277.0 | acc 99.6173% | success 0/128 | gamma 0.30034 | |rz| 0.9675
G26 | step  1450/2000 | best 13277.0 | acc 99.6173% | success 0/128 | gamma 0.27732 | |rz| 0.9699
G26 | step  1500/2000 | best 13277.0 | acc 99.6173% | success 0/128 | gamma 0.26252 | |rz| 0.9716
G26 | step  1550/2000 | best 13277.0 | acc 99.6173% | success 0/128 | gamma 0.26035 | |rz| 0.9723
G26 | step  1600/2000 | best 13277.0 | acc 99.6173% | success 0/128 | gamma 0.25010 | |rz| 0.9736
G26 | step  1650/2000 | best 13277.0 | acc 99.6173% | success 0/128 | gamma 0.21052 | |rz| 0.9766
G26 | step  1700/2000 | best 13277.0 | acc 99.6173% | success 0/128 | gamma 0.16261 | |rz| 0.9795
G26 | step  1750/2000 | best 13277.0 | acc 99.6173% | success 0/128 | gamma 0.12728 | |rz| 0.9812
G26 | step  1800/2000 | best 13277.0 | acc 99.6173% | success 0/128 | gamma 0.10025 | |rz| 0.9823
G26 | step  1850/2000 | best 13277.0 | acc 99.6173% | success 0/128 | gamma 0.07505 | |rz| 0.9832
G26 | step  1900/2000 | best 13277.0 | acc 99.6173% | success 0/128 | gamma 0.05003 | |rz| 0.9838
G26 | step  1950/2000 | best 13277.0 | acc 99.6173% | success 0/128 | gamma 0.02501 | |rz| 0.9843
G26 | step  2000/2000 | best 13277.0 | acc 99.6173% | success 0/128 | gamma 0.00000 | |rz| 0.9862

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G26
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644267e-05,0.000026,0.000011,1.084246e-05,0.001049
1,theta_grad_mean_abs,6.235949e-07,0.000002,0.000002,2.530184e-07,0.000384
2,raw_R_step_mean_abs,2.999592e-02,0.002256,0.001912,1.912424e-03,0.048873
3,theta_step_mean_abs,2.863724e-02,0.000332,0.000591,2.349231e-04,0.028637
4,raw_R_grad_norm,3.867729e-02,0.014302,0.005730,5.729956e-03,0.625186
5,theta_grad_norm,3.954222e-04,0.003418,0.004511,1.597982e-04,0.299230
6,raw_R_step_norm,1.517687e+01,1.212032,1.055052,1.055052e+00,24.728252
7,theta_step_norm,1.455409e+01,0.427726,1.296551,3.380271e-01,14.554093

--------------------------------------------------------------------------------
RESULT SUMMARY: G26
--------------------------------------------------------------------------------
historical_best: 13328.0

V1:
v1_best: 13270.0
v1_gap: 58.0
v1_percent_accuracy: 99.56482593037217

V2:
v2_best: 13277.0
v2_gap: 51.0
v2_percent_accuracy: 99.61734693877551
v2_best_step: 972
v2_best_replica: 26

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 25.16667103767395

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/logs/G26_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/best_spins/G26_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/partial_group_results.csv

################################################################################
RUNNING G27 | dense | seed=12
################################################################################
G27 | step     1/2000 | best 41.0 | acc 1.2272% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G27 | step    50/2000 | best 562.0 | acc 16.8213% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G27 | step   100/2000 | best 3047.0 | acc 91.2002% | success 0/128 | gamma 0.95048 | |rz| 0.0808
G27 | step   150/2000 | best 3254.0 | acc 97.3960% | success 0/128 | gamma 0.92546 | |rz| 0.7660
G27 | step   200/2000 | best 3263.0 | acc 97.6654% | success 0/128 | gamma 0.90045 | |rz| 0.8370
G27 | step   250/2000 | best 3266.0 | acc 97.7552% | success 0/128 | gamma 0.87544 | |rz| 0.8562
G27 | step   300/2000 | best 3270.0 | acc 97.8749% | success 0/128 | gamma 0.85043 | |rz| 0.8674
G27 | step   350/2000 | best 3271.0 | acc 97.9048% | success 0/128 | gamma 0.82541 | |rz| 0.8759
G27 | step   400/2000 | best 3272.0 | acc 97.9348% | success 0/128 | gamma 0.80040 | |rz| 0.8831
G27 | step   450/2000 | best 3273.0 | acc 97.9647% | success 0/128 | gamma 0.77539 | |rz| 0.8896
G27 | step   500/2000 | best 3274.0 | acc 97.9946% | success 0/128 | gamma 0.75038 | |rz| 0.8955
G27 | step   550/2000 | best 3275.0 | acc 98.0245% | success 0/128 | gamma 0.72536 | |rz| 0.9010
G27 | step   600/2000 | best 3275.0 | acc 98.0245% | success 0/128 | gamma 0.70035 | |rz| 0.9062
G27 | step   650/2000 | best 3276.0 | acc 98.0545% | success 0/128 | gamma 0.67534 | |rz| 0.9112
G27 | step   700/2000 | best 3276.0 | acc 98.0545% | success 0/128 | gamma 0.65033 | |rz| 0.9160
G27 | step   750/2000 | best 3276.0 | acc 98.0545% | success 0/128 | gamma 0.62531 | |rz| 0.9207
G27 | step   800/2000 | best 3276.0 | acc 98.0545% | success 0/128 | gamma 0.60030 | |rz| 0.9252
G27 | step   850/2000 | best 3277.0 | acc 98.0844% | success 0/128 | gamma 0.57529 | |rz| 0.9296
G27 | step   900/2000 | best 3277.0 | acc 98.0844% | success 0/128 | gamma 0.55028 | |rz| 0.9337
G27 | step   950/2000 | best 3277.0 | acc 98.0844% | success 0/128 | gamma 0.52526 | |rz| 0.9377
G27 | step  1000/2000 | best 3277.0 | acc 98.0844% | success 0/128 | gamma 0.50025 | |rz| 0.9416
G27 | step  1050/2000 | best 3277.0 | acc 98.0844% | success 0/128 | gamma 0.47524 | |rz| 0.9454
G27 | step  1100/2000 | best 3277.0 | acc 98.0844% | success 0/128 | gamma 0.45023 | |rz| 0.9490
G27 | step  1150/2000 | best 3277.0 | acc 98.0844% | success 0/128 | gamma 0.42521 | |rz| 0.9524
G27 | step  1200/2000 | best 3277.0 | acc 98.0844% | success 0/128 | gamma 0.40020 | |rz| 0.9557
G27 | step  1250/2000 | best 3277.0 | acc 98.0844% | success 0/128 | gamma 0.37519 | |rz| 0.9589
G27 | step  1300/2000 | best 3277.0 | acc 98.0844% | success 0/128 | gamma 0.35018 | |rz| 0.9620
G27 | step  1350/2000 | best 3277.0 | acc 98.0844% | success 0/128 | gamma 0.32517 | |rz| 0.9649
G27 | step  1400/2000 | best 3277.0 | acc 98.0844% | success 0/128 | gamma 0.30034 | |rz| 0.9676
G27 | step  1450/2000 | best 3277.0 | acc 98.0844% | success 0/128 | gamma 0.27732 | |rz| 0.9701
G27 | step  1500/2000 | best 3277.0 | acc 98.0844% | success 0/128 | gamma 0.26252 | |rz| 0.9717
G27 | step  1550/2000 | best 3277.0 | acc 98.0844% | success 0/128 | gamma 0.26035 | |rz| 0.9725
G27 | step  1600/2000 | best 3277.0 | acc 98.0844% | success 0/128 | gamma 0.25010 | |rz| 0.9738
G27 | step  1650/2000 | best 3277.0 | acc 98.0844% | success 0/128 | gamma 0.21052 | |rz| 0.9768
G27 | step  1700/2000 | best 3277.0 | acc 98.0844% | success 0/128 | gamma 0.16261 | |rz| 0.9797
G27 | step  1750/2000 | best 3277.0 | acc 98.0844% | success 0/128 | gamma 0.12728 | |rz| 0.9814
G27 | step  1800/2000 | best 3277.0 | acc 98.0844% | success 0/128 | gamma 0.10025 | |rz| 0.9825
G27 | step  1850/2000 | best 3277.0 | acc 98.0844% | success 0/128 | gamma 0.07505 | |rz| 0.9833
G27 | step  1900/2000 | best 3277.0 | acc 98.0844% | success 0/128 | gamma 0.05003 | |rz| 0.9839
G27 | step  1950/2000 | best 3277.0 | acc 98.0844% | success 0/128 | gamma 0.02501 | |rz| 0.9845
G27 | step  2000/2000 | best 3277.0 | acc 98.0844% | success 0/128 | gamma 0.00000 | |rz| 0.9867

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G27
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644286e-05,0.000028,0.000011,1.134859e-05,0.001019
1,theta_grad_mean_abs,6.246734e-07,0.000004,0.000004,2.532221e-07,0.000237
2,raw_R_step_mean_abs,2.999592e-02,0.002233,0.001902,1.902369e-03,0.049325
3,theta_step_mean_abs,2.864958e-02,0.000478,0.000779,4.083445e-04,0.041155
4,raw_R_grad_norm,3.867738e-02,0.015112,0.005994,5.994093e-03,0.609791
5,theta_grad_norm,3.959925e-04,0.004944,0.005920,1.599383e-04,0.196327
6,raw_R_step_norm,1.517687e+01,1.185436,1.050736,1.050736e+00,24.957945
7,theta_step_norm,1.455858e+01,0.553140,1.643065,4.209131e-01,22.321918

--------------------------------------------------------------------------------
RESULT SUMMARY: G27
--------------------------------------------------------------------------------
historical_best: 3341.0

V1:
v1_best: 3310.0
v1_gap: 31.0
v1_percent_accuracy: 99.07213409158936

V2:
v2_best: 3277.0
v2_gap: 64.0
v2_percent_accuracy: 98.08440586650704
v2_best_step: 850
v2_best_replica: 124

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 25.130725860595703

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/logs/G27_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/best_spins/G27_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/partial_group_results.csv

################################################################################
RUNNING G28 | dense | seed=13
################################################################################
G28 | step     1/2000 | best 32.0 | acc 0.9703% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G28 | step    50/2000 | best 549.0 | acc 16.6465% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G28 | step   100/2000 | best 3024.0 | acc 91.6919% | success 0/128 | gamma 0.95048 | |rz| 0.0794
G28 | step   150/2000 | best 3216.0 | acc 97.5136% | success 0/128 | gamma 0.92546 | |rz| 0.7671
G28 | step   200/2000 | best 3231.0 | acc 97.9685% | success 0/128 | gamma 0.90045 | |rz| 0.8379
G28 | step   250/2000 | best 3236.0 | acc 98.1201% | success 0/128 | gamma 0.87544 | |rz| 0.8570
G28 | step   300/2000 | best 3237.0 | acc 98.1504% | success 0/128 | gamma 0.85043 | |rz| 0.8682
G28 | step   350/2000 | best 3245.0 | acc 98.3930% | success 0/128 | gamma 0.82541 | |rz| 0.8767
G28 | step   400/2000 | best 3246.0 | acc 98.4233% | success 0/128 | gamma 0.80040 | |rz| 0.8837
G28 | step   450/2000 | best 3249.0 | acc 98.5143% | success 0/128 | gamma 0.77539 | |rz| 0.8901
G28 | step   500/2000 | best 3251.0 | acc 98.5749% | success 0/128 | gamma 0.75038 | |rz| 0.8959
G28 | step   550/2000 | best 3251.0 | acc 98.5749% | success 0/128 | gamma 0.72536 | |rz| 0.9013
G28 | step   600/2000 | best 3251.0 | acc 98.5749% | success 0/128 | gamma 0.70035 | |rz| 0.9066
G28 | step   650/2000 | best 3251.0 | acc 98.5749% | success 0/128 | gamma 0.67534 | |rz| 0.9115
G28 | step   700/2000 | best 3251.0 | acc 98.5749% | success 0/128 | gamma 0.65033 | |rz| 0.9163
G28 | step   750/2000 | best 3251.0 | acc 98.5749% | success 0/128 | gamma 0.62531 | |rz| 0.9209
G28 | step   800/2000 | best 3251.0 | acc 98.5749% | success 0/128 | gamma 0.60030 | |rz| 0.9254
G28 | step   850/2000 | best 3251.0 | acc 98.5749% | success 0/128 | gamma 0.57529 | |rz| 0.9297
G28 | step   900/2000 | best 3251.0 | acc 98.5749% | success 0/128 | gamma 0.55028 | |rz| 0.9338
G28 | step   950/2000 | best 3251.0 | acc 98.5749% | success 0/128 | gamma 0.52526 | |rz| 0.9378
G28 | step  1000/2000 | best 3251.0 | acc 98.5749% | success 0/128 | gamma 0.50025 | |rz| 0.9416
G28 | step  1050/2000 | best 3251.0 | acc 98.5749% | success 0/128 | gamma 0.47524 | |rz| 0.9453
G28 | step  1100/2000 | best 3251.0 | acc 98.5749% | success 0/128 | gamma 0.45023 | |rz| 0.9489
G28 | step  1150/2000 | best 3251.0 | acc 98.5749% | success 0/128 | gamma 0.42521 | |rz| 0.9523
G28 | step  1200/2000 | best 3251.0 | acc 98.5749% | success 0/128 | gamma 0.40020 | |rz| 0.9556
G28 | step  1250/2000 | best 3251.0 | acc 98.5749% | success 0/128 | gamma 0.37519 | |rz| 0.9588
G28 | step  1300/2000 | best 3251.0 | acc 98.5749% | success 0/128 | gamma 0.35018 | |rz| 0.9619
G28 | step  1350/2000 | best 3251.0 | acc 98.5749% | success 0/128 | gamma 0.32517 | |rz| 0.9648
G28 | step  1400/2000 | best 3251.0 | acc 98.5749% | success 0/128 | gamma 0.30034 | |rz| 0.9675
G28 | step  1450/2000 | best 3251.0 | acc 98.5749% | success 0/128 | gamma 0.27732 | |rz| 0.9699
G28 | step  1500/2000 | best 3251.0 | acc 98.5749% | success 0/128 | gamma 0.26252 | |rz| 0.9716
G28 | step  1550/2000 | best 3251.0 | acc 98.5749% | success 0/128 | gamma 0.26035 | |rz| 0.9723
G28 | step  1600/2000 | best 3251.0 | acc 98.5749% | success 0/128 | gamma 0.25010 | |rz| 0.9736
G28 | step  1650/2000 | best 3251.0 | acc 98.5749% | success 0/128 | gamma 0.21052 | |rz| 0.9766
G28 | step  1700/2000 | best 3251.0 | acc 98.5749% | success 0/128 | gamma 0.16261 | |rz| 0.9795
G28 | step  1750/2000 | best 3251.0 | acc 98.5749% | success 0/128 | gamma 0.12728 | |rz| 0.9812
G28 | step  1800/2000 | best 3251.0 | acc 98.5749% | success 0/128 | gamma 0.10025 | |rz| 0.9822
G28 | step  1850/2000 | best 3251.0 | acc 98.5749% | success 0/128 | gamma 0.07505 | |rz| 0.9831
G28 | step  1900/2000 | best 3251.0 | acc 98.5749% | success 0/128 | gamma 0.05003 | |rz| 0.9837
G28 | step  1950/2000 | best 3251.0 | acc 98.5749% | success 0/128 | gamma 0.02501 | |rz| 0.9842
G28 | step  2000/2000 | best 3251.0 | acc 98.5749% | success 0/128 | gamma 0.00000 | |rz| 0.9864

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G28
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644269e-05,0.000028,0.000011,1.132459e-05,0.001017
1,theta_grad_mean_abs,6.239540e-07,0.000004,0.000003,2.532542e-07,0.000231
2,raw_R_step_mean_abs,2.999592e-02,0.002238,0.001901,1.900842e-03,0.049302
3,theta_step_mean_abs,2.864543e-02,0.000468,0.000773,4.080577e-04,0.041054
4,raw_R_grad_norm,3.867730e-02,0.015048,0.005977,5.977399e-03,0.607104
5,theta_grad_norm,3.956390e-04,0.004250,0.005854,1.599964e-04,0.190224
6,raw_R_step_norm,1.517687e+01,1.201953,1.049566,1.049566e+00,24.946007
7,theta_step_norm,1.455704e+01,0.458636,1.627628,4.279756e-01,22.257883

--------------------------------------------------------------------------------
RESULT SUMMARY: G28
--------------------------------------------------------------------------------
historical_best: 3298.0

V1:
v1_best: 3275.0
v1_gap: 23.0
v1_percent_accuracy: 99.30260764099454

V2:
v2_best: 3251.0
v2_gap: 47.0
v2_percent_accuracy: 98.5748938750758
v2_best_step: 486
v2_best_replica: 85

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 24.54987597465515

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/logs/G28_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/best_spins/G28_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/partial_group_results.csv

################################################################################
RUNNING G29 | dense | seed=14
################################################################################
G29 | step     1/2000 | best 165.0 | acc 4.8458% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G29 | step    50/2000 | best 663.0 | acc 19.4714% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G29 | step   100/2000 | best 3118.0 | acc 91.5712% | success 0/128 | gamma 0.95048 | |rz| 0.0812
G29 | step   150/2000 | best 3309.0 | acc 97.1806% | success 0/128 | gamma 0.92546 | |rz| 0.7671
G29 | step   200/2000 | best 3342.0 | acc 98.1498% | success 0/128 | gamma 0.90045 | |rz| 0.8376
G29 | step   250/2000 | best 3347.0 | acc 98.2966% | success 0/128 | gamma 0.87544 | |rz| 0.8566
G29 | step   300/2000 | best 3357.0 | acc 98.5903% | success 0/128 | gamma 0.85043 | |rz| 0.8677
G29 | step   350/2000 | best 3357.0 | acc 98.5903% | success 0/128 | gamma 0.82541 | |rz| 0.8762
G29 | step   400/2000 | best 3357.0 | acc 98.5903% | success 0/128 | gamma 0.80040 | |rz| 0.8833
G29 | step   450/2000 | best 3359.0 | acc 98.6490% | success 0/128 | gamma 0.77539 | |rz| 0.8896
G29 | step   500/2000 | best 3360.0 | acc 98.6784% | success 0/128 | gamma 0.75038 | |rz| 0.8955
G29 | step   550/2000 | best 3361.0 | acc 98.7078% | success 0/128 | gamma 0.72536 | |rz| 0.9010
G29 | step   600/2000 | best 3363.0 | acc 98.7665% | success 0/128 | gamma 0.70035 | |rz| 0.9062
G29 | step   650/2000 | best 3363.0 | acc 98.7665% | success 0/128 | gamma 0.67534 | |rz| 0.9112
G29 | step   700/2000 | best 3363.0 | acc 98.7665% | success 0/128 | gamma 0.65033 | |rz| 0.9160
G29 | step   750/2000 | best 3363.0 | acc 98.7665% | success 0/128 | gamma 0.62531 | |rz| 0.9206
G29 | step   800/2000 | best 3363.0 | acc 98.7665% | success 0/128 | gamma 0.60030 | |rz| 0.9250
G29 | step   850/2000 | best 3363.0 | acc 98.7665% | success 0/128 | gamma 0.57529 | |rz| 0.9293
G29 | step   900/2000 | best 3363.0 | acc 98.7665% | success 0/128 | gamma 0.55028 | |rz| 0.9334
G29 | step   950/2000 | best 3363.0 | acc 98.7665% | success 0/128 | gamma 0.52526 | |rz| 0.9375
G29 | step  1000/2000 | best 3363.0 | acc 98.7665% | success 0/128 | gamma 0.50025 | |rz| 0.9413
G29 | step  1050/2000 | best 3363.0 | acc 98.7665% | success 0/128 | gamma 0.47524 | |rz| 0.9451
G29 | step  1100/2000 | best 3363.0 | acc 98.7665% | success 0/128 | gamma 0.45023 | |rz| 0.9486
G29 | step  1150/2000 | best 3363.0 | acc 98.7665% | success 0/128 | gamma 0.42521 | |rz| 0.9521
G29 | step  1200/2000 | best 3363.0 | acc 98.7665% | success 0/128 | gamma 0.40020 | |rz| 0.9554
G29 | step  1250/2000 | best 3363.0 | acc 98.7665% | success 0/128 | gamma 0.37519 | |rz| 0.9586
G29 | step  1300/2000 | best 3363.0 | acc 98.7665% | success 0/128 | gamma 0.35018 | |rz| 0.9617
G29 | step  1350/2000 | best 3363.0 | acc 98.7665% | success 0/128 | gamma 0.32517 | |rz| 0.9646
G29 | step  1400/2000 | best 3363.0 | acc 98.7665% | success 0/128 | gamma 0.30034 | |rz| 0.9673
G29 | step  1450/2000 | best 3363.0 | acc 98.7665% | success 0/128 | gamma 0.27732 | |rz| 0.9698
G29 | step  1500/2000 | best 3363.0 | acc 98.7665% | success 0/128 | gamma 0.26252 | |rz| 0.9715
G29 | step  1550/2000 | best 3363.0 | acc 98.7665% | success 0/128 | gamma 0.26035 | |rz| 0.9722
G29 | step  1600/2000 | best 3363.0 | acc 98.7665% | success 0/128 | gamma 0.25010 | |rz| 0.9735
G29 | step  1650/2000 | best 3363.0 | acc 98.7665% | success 0/128 | gamma 0.21052 | |rz| 0.9765
G29 | step  1700/2000 | best 3363.0 | acc 98.7665% | success 0/128 | gamma 0.16261 | |rz| 0.9794
G29 | step  1750/2000 | best 3363.0 | acc 98.7665% | success 0/128 | gamma 0.12728 | |rz| 0.9811
G29 | step  1800/2000 | best 3363.0 | acc 98.7665% | success 0/128 | gamma 0.10025 | |rz| 0.9822
G29 | step  1850/2000 | best 3363.0 | acc 98.7665% | success 0/128 | gamma 0.07505 | |rz| 0.9830
G29 | step  1900/2000 | best 3363.0 | acc 98.7665% | success 0/128 | gamma 0.05003 | |rz| 0.9836
G29 | step  1950/2000 | best 3363.0 | acc 98.7665% | success 0/128 | gamma 0.02501 | |rz| 0.9842
G29 | step  2000/2000 | best 3363.0 | acc 98.7665% | success 0/128 | gamma 0.00000 | |rz| 0.9863

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G29
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644280e-05,0.000028,0.000011,1.134817e-05,0.001020
1,theta_grad_mean_abs,6.240113e-07,0.000004,0.000003,2.531135e-07,0.000238
2,raw_R_step_mean_abs,2.999592e-02,0.002241,0.001901,1.901091e-03,0.049329
3,theta_step_mean_abs,2.863941e-02,0.000485,0.000773,4.081191e-04,0.041270
4,raw_R_grad_norm,3.867736e-02,0.015211,0.005991,5.991217e-03,0.610207
5,theta_grad_norm,3.957573e-04,0.005314,0.005827,1.598102e-04,0.197160
6,raw_R_step_norm,1.517687e+01,1.214025,1.050512,1.050512e+00,24.960068
7,theta_step_norm,1.455474e+01,0.522225,1.610162,4.285155e-01,22.371119

--------------------------------------------------------------------------------
RESULT SUMMARY: G29
--------------------------------------------------------------------------------
historical_best: 3405.0

V1:
v1_best: 3351.0
v1_gap: 54.0
v1_percent_accuracy: 98.41409691629956

V2:
v2_best: 3363.0
v2_gap: 42.0
v2_percent_accuracy: 98.76651982378854
v2_best_step: 593
v2_best_replica: 74

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 25.460381031036377

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/logs/G29_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/best_spins/G29_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/partial_group_results.csv

################################################################################
RUNNING G30 | dense | seed=15
################################################################################
G30 | step     1/2000 | best 178.0 | acc 5.2154% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G30 | step    50/2000 | best 615.0 | acc 18.0193% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G30 | step   100/2000 | best 3157.0 | acc 92.4993% | success 0/128 | gamma 0.95048 | |rz| 0.0811
G30 | step   150/2000 | best 3330.0 | acc 97.5681% | success 0/128 | gamma 0.92546 | |rz| 0.7670
G30 | step   200/2000 | best 3344.0 | acc 97.9783% | success 0/128 | gamma 0.90045 | |rz| 0.8376
G30 | step   250/2000 | best 3351.0 | acc 98.1834% | success 0/128 | gamma 0.87544 | |rz| 0.8567
G30 | step   300/2000 | best 3354.0 | acc 98.2713% | success 0/128 | gamma 0.85043 | |rz| 0.8679
G30 | step   350/2000 | best 3354.0 | acc 98.2713% | success 0/128 | gamma 0.82541 | |rz| 0.8763
G30 | step   400/2000 | best 3355.0 | acc 98.3006% | success 0/128 | gamma 0.80040 | |rz| 0.8834
G30 | step   450/2000 | best 3355.0 | acc 98.3006% | success 0/128 | gamma 0.77539 | |rz| 0.8899
G30 | step   500/2000 | best 3356.0 | acc 98.3299% | success 0/128 | gamma 0.75038 | |rz| 0.8957
G30 | step   550/2000 | best 3358.0 | acc 98.3885% | success 0/128 | gamma 0.72536 | |rz| 0.9012
G30 | step   600/2000 | best 3361.0 | acc 98.4764% | success 0/128 | gamma 0.70035 | |rz| 0.9064
G30 | step   650/2000 | best 3362.0 | acc 98.5057% | success 0/128 | gamma 0.67534 | |rz| 0.9115
G30 | step   700/2000 | best 3363.0 | acc 98.5350% | success 0/128 | gamma 0.65033 | |rz| 0.9163
G30 | step   750/2000 | best 3363.0 | acc 98.5350% | success 0/128 | gamma 0.62531 | |rz| 0.9209
G30 | step   800/2000 | best 3363.0 | acc 98.5350% | success 0/128 | gamma 0.60030 | |rz| 0.9253
G30 | step   850/2000 | best 3363.0 | acc 98.5350% | success 0/128 | gamma 0.57529 | |rz| 0.9296
G30 | step   900/2000 | best 3363.0 | acc 98.5350% | success 0/128 | gamma 0.55028 | |rz| 0.9338
G30 | step   950/2000 | best 3363.0 | acc 98.5350% | success 0/128 | gamma 0.52526 | |rz| 0.9377
G30 | step  1000/2000 | best 3363.0 | acc 98.5350% | success 0/128 | gamma 0.50025 | |rz| 0.9416
G30 | step  1050/2000 | best 3363.0 | acc 98.5350% | success 0/128 | gamma 0.47524 | |rz| 0.9453
G30 | step  1100/2000 | best 3363.0 | acc 98.5350% | success 0/128 | gamma 0.45023 | |rz| 0.9488
G30 | step  1150/2000 | best 3363.0 | acc 98.5350% | success 0/128 | gamma 0.42521 | |rz| 0.9522
G30 | step  1200/2000 | best 3363.0 | acc 98.5350% | success 0/128 | gamma 0.40020 | |rz| 0.9555
G30 | step  1250/2000 | best 3364.0 | acc 98.5643% | success 0/128 | gamma 0.37519 | |rz| 0.9587
G30 | step  1300/2000 | best 3364.0 | acc 98.5643% | success 0/128 | gamma 0.35018 | |rz| 0.9618
G30 | step  1350/2000 | best 3364.0 | acc 98.5643% | success 0/128 | gamma 0.32517 | |rz| 0.9646
G30 | step  1400/2000 | best 3364.0 | acc 98.5643% | success 0/128 | gamma 0.30034 | |rz| 0.9674
G30 | step  1450/2000 | best 3364.0 | acc 98.5643% | success 0/128 | gamma 0.27732 | |rz| 0.9698
G30 | step  1500/2000 | best 3364.0 | acc 98.5643% | success 0/128 | gamma 0.26252 | |rz| 0.9714
G30 | step  1550/2000 | best 3364.0 | acc 98.5643% | success 0/128 | gamma 0.26035 | |rz| 0.9722
G30 | step  1600/2000 | best 3364.0 | acc 98.5643% | success 0/128 | gamma 0.25010 | |rz| 0.9734
G30 | step  1650/2000 | best 3364.0 | acc 98.5643% | success 0/128 | gamma 0.21052 | |rz| 0.9764
G30 | step  1700/2000 | best 3364.0 | acc 98.5643% | success 0/128 | gamma 0.16261 | |rz| 0.9792
G30 | step  1750/2000 | best 3364.0 | acc 98.5643% | success 0/128 | gamma 0.12728 | |rz| 0.9809
G30 | step  1800/2000 | best 3364.0 | acc 98.5643% | success 0/128 | gamma 0.10025 | |rz| 0.9820
G30 | step  1850/2000 | best 3364.0 | acc 98.5643% | success 0/128 | gamma 0.07505 | |rz| 0.9828
G30 | step  1900/2000 | best 3364.0 | acc 98.5643% | success 0/128 | gamma 0.05003 | |rz| 0.9834
G30 | step  1950/2000 | best 3364.0 | acc 98.5643% | success 0/128 | gamma 0.02501 | |rz| 0.9840
G30 | step  2000/2000 | best 3364.0 | acc 98.5643% | success 0/128 | gamma 0.00000 | |rz| 0.9862

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G30
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644272e-05,0.000028,0.000011,1.135279e-05,0.001021
1,theta_grad_mean_abs,6.218669e-07,0.000004,0.000004,2.526257e-07,0.000239
2,raw_R_step_mean_abs,2.999592e-02,0.002234,0.001898,1.897837e-03,0.049328
3,theta_step_mean_abs,2.864330e-02,0.000477,0.000780,4.131343e-04,0.041250
4,raw_R_grad_norm,3.867731e-02,0.015117,0.005998,5.997957e-03,0.610939
5,theta_grad_norm,3.941578e-04,0.004463,0.005873,1.596011e-04,0.197462
6,raw_R_step_norm,1.517687e+01,1.194639,1.047833,1.047833e+00,24.959764
7,theta_step_norm,1.455566e+01,0.484094,1.626743,4.292904e-01,22.363111

--------------------------------------------------------------------------------
RESULT SUMMARY: G30
--------------------------------------------------------------------------------
historical_best: 3413.0

V1:
v1_best: 3367.0
v1_gap: 46.0
v1_percent_accuracy: 98.65221213009085

V2:
v2_best: 3364.0
v2_gap: 49.0
v2_percent_accuracy: 98.56431292118371
v2_best_step: 1225
v2_best_replica: 40

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 24.23093891143799

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/logs/G30_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/best_spins/G30_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/partial_group_results.csv

################################################################################
RUNNING G31 | dense | seed=16
################################################################################
G31 | step     1/2000 | best 78.0 | acc 2.3565% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G31 | step    50/2000 | best 527.0 | acc 15.9215% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G31 | step   100/2000 | best 3045.0 | acc 91.9940% | success 0/128 | gamma 0.95048 | |rz| 0.0818
G31 | step   150/2000 | best 3221.0 | acc 97.3112% | success 0/128 | gamma 0.92546 | |rz| 0.7667
G31 | step   200/2000 | best 3236.0 | acc 97.7644% | success 0/128 | gamma 0.90045 | |rz| 0.8375
G31 | step   250/2000 | best 3245.0 | acc 98.0363% | success 0/128 | gamma 0.87544 | |rz| 0.8564
G31 | step   300/2000 | best 3251.0 | acc 98.2175% | success 0/128 | gamma 0.85043 | |rz| 0.8676
G31 | step   350/2000 | best 3257.0 | acc 98.3988% | success 0/128 | gamma 0.82541 | |rz| 0.8760
G31 | step   400/2000 | best 3257.0 | acc 98.3988% | success 0/128 | gamma 0.80040 | |rz| 0.8832
G31 | step   450/2000 | best 3261.0 | acc 98.5196% | success 0/128 | gamma 0.77539 | |rz| 0.8896
G31 | step   500/2000 | best 3262.0 | acc 98.5498% | success 0/128 | gamma 0.75038 | |rz| 0.8954
G31 | step   550/2000 | best 3263.0 | acc 98.5801% | success 0/128 | gamma 0.72536 | |rz| 0.9010
G31 | step   600/2000 | best 3265.0 | acc 98.6405% | success 0/128 | gamma 0.70035 | |rz| 0.9061
G31 | step   650/2000 | best 3265.0 | acc 98.6405% | success 0/128 | gamma 0.67534 | |rz| 0.9112
G31 | step   700/2000 | best 3265.0 | acc 98.6405% | success 0/128 | gamma 0.65033 | |rz| 0.9159
G31 | step   750/2000 | best 3265.0 | acc 98.6405% | success 0/128 | gamma 0.62531 | |rz| 0.9205
G31 | step   800/2000 | best 3265.0 | acc 98.6405% | success 0/128 | gamma 0.60030 | |rz| 0.9250
G31 | step   850/2000 | best 3265.0 | acc 98.6405% | success 0/128 | gamma 0.57529 | |rz| 0.9293
G31 | step   900/2000 | best 3265.0 | acc 98.6405% | success 0/128 | gamma 0.55028 | |rz| 0.9335
G31 | step   950/2000 | best 3265.0 | acc 98.6405% | success 0/128 | gamma 0.52526 | |rz| 0.9375
G31 | step  1000/2000 | best 3265.0 | acc 98.6405% | success 0/128 | gamma 0.50025 | |rz| 0.9414
G31 | step  1050/2000 | best 3265.0 | acc 98.6405% | success 0/128 | gamma 0.47524 | |rz| 0.9451
G31 | step  1100/2000 | best 3265.0 | acc 98.6405% | success 0/128 | gamma 0.45023 | |rz| 0.9487
G31 | step  1150/2000 | best 3265.0 | acc 98.6405% | success 0/128 | gamma 0.42521 | |rz| 0.9522
G31 | step  1200/2000 | best 3265.0 | acc 98.6405% | success 0/128 | gamma 0.40020 | |rz| 0.9555
G31 | step  1250/2000 | best 3265.0 | acc 98.6405% | success 0/128 | gamma 0.37519 | |rz| 0.9587
G31 | step  1300/2000 | best 3265.0 | acc 98.6405% | success 0/128 | gamma 0.35018 | |rz| 0.9618
G31 | step  1350/2000 | best 3265.0 | acc 98.6405% | success 0/128 | gamma 0.32517 | |rz| 0.9647
G31 | step  1400/2000 | best 3265.0 | acc 98.6405% | success 0/128 | gamma 0.30034 | |rz| 0.9674
G31 | step  1450/2000 | best 3265.0 | acc 98.6405% | success 0/128 | gamma 0.27732 | |rz| 0.9698
G31 | step  1500/2000 | best 3265.0 | acc 98.6405% | success 0/128 | gamma 0.26252 | |rz| 0.9715
G31 | step  1550/2000 | best 3265.0 | acc 98.6405% | success 0/128 | gamma 0.26035 | |rz| 0.9723
G31 | step  1600/2000 | best 3265.0 | acc 98.6405% | success 0/128 | gamma 0.25010 | |rz| 0.9736
G31 | step  1650/2000 | best 3265.0 | acc 98.6405% | success 0/128 | gamma 0.21052 | |rz| 0.9766
G31 | step  1700/2000 | best 3265.0 | acc 98.6405% | success 0/128 | gamma 0.16261 | |rz| 0.9794
G31 | step  1750/2000 | best 3265.0 | acc 98.6405% | success 0/128 | gamma 0.12728 | |rz| 0.9812
G31 | step  1800/2000 | best 3265.0 | acc 98.6405% | success 0/128 | gamma 0.10025 | |rz| 0.9822
G31 | step  1850/2000 | best 3265.0 | acc 98.6405% | success 0/128 | gamma 0.07505 | |rz| 0.9831
G31 | step  1900/2000 | best 3265.0 | acc 98.6405% | success 0/128 | gamma 0.05003 | |rz| 0.9837
G31 | step  1950/2000 | best 3265.0 | acc 98.6405% | success 0/128 | gamma 0.02501 | |rz| 0.9842
G31 | step  2000/2000 | best 3265.0 | acc 98.6405% | success 0/128 | gamma 0.00000 | |rz| 0.9865

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G31
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644275e-05,0.000028,0.000011,1.133081e-05,0.001017
1,theta_grad_mean_abs,6.230096e-07,0.000004,0.000004,2.532029e-07,0.000238
2,raw_R_step_mean_abs,2.999592e-02,0.002239,0.001904,1.904153e-03,0.049339
3,theta_step_mean_abs,2.863182e-02,0.000481,0.000789,4.149481e-04,0.041339
4,raw_R_grad_norm,3.867732e-02,0.015100,0.005982,5.981548e-03,0.608379
5,theta_grad_norm,3.951257e-04,0.005363,0.005902,1.599974e-04,0.198824
6,raw_R_step_norm,1.517687e+01,1.198647,1.051679,1.051679e+00,24.965277
7,theta_step_norm,1.455136e+01,0.526760,1.661535,4.344380e-01,22.407269

--------------------------------------------------------------------------------
RESULT SUMMARY: G31
--------------------------------------------------------------------------------
historical_best: 3310.0

V1:
v1_best: 3282.0
v1_gap: 28.0
v1_percent_accuracy: 99.15407854984896

V2:
v2_best: 3265.0
v2_gap: 45.0
v2_percent_accuracy: 98.6404833836858
v2_best_step: 555
v2_best_replica: 20

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 24.584394931793213

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/logs/G31_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/best_spins/G31_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/partial_group_results.csv

################################################################################
RUNNING G32 | dense | seed=17
################################################################################
G32 | step     1/2000 | best 84.0 | acc 5.9574% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G32 | step    50/2000 | best 218.0 | acc 15.4610% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G32 | step   100/2000 | best 222.0 | acc 15.7447% | success 0/128 | gamma 0.95048 | |rz| 0.0010
G32 | step   150/2000 | best 1380.0 | acc 97.8723% | success 0/128 | gamma 0.92546 | |rz| 0.3538
G32 | step   200/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.90045 | |rz| 0.4934
G32 | step   250/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.87544 | |rz| 0.5488
G32 | step   300/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.85043 | |rz| 0.5818
G32 | step   350/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.82541 | |rz| 0.6088
G32 | step   400/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.80040 | |rz| 0.6330
G32 | step   450/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.77539 | |rz| 0.6554
G32 | step   500/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.75038 | |rz| 0.6762
G32 | step   550/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.72536 | |rz| 0.6958
G32 | step   600/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.70035 | |rz| 0.7140
G32 | step   650/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.67534 | |rz| 0.7311
G32 | step   700/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.65033 | |rz| 0.7471
G32 | step   750/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.62531 | |rz| 0.7621
G32 | step   800/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.60030 | |rz| 0.7762
G32 | step   850/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.57529 | |rz| 0.7893
G32 | step   900/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.55028 | |rz| 0.8016
G32 | step   950/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.52526 | |rz| 0.8132
G32 | step  1000/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.50025 | |rz| 0.8240
G32 | step  1050/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.47524 | |rz| 0.8341
G32 | step  1100/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.45023 | |rz| 0.8436
G32 | step  1150/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.42521 | |rz| 0.8524
G32 | step  1200/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.40020 | |rz| 0.8607
G32 | step  1250/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.37519 | |rz| 0.8684
G32 | step  1300/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.35018 | |rz| 0.8755
G32 | step  1350/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.32517 | |rz| 0.8822
G32 | step  1400/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.30034 | |rz| 0.8883
G32 | step  1450/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.27732 | |rz| 0.8936
G32 | step  1500/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.26252 | |rz| 0.8971
G32 | step  1550/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.26035 | |rz| 0.8986
G32 | step  1600/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.25010 | |rz| 0.9013
G32 | step  1650/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.21052 | |rz| 0.9076
G32 | step  1700/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.16261 | |rz| 0.9131
G32 | step  1750/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.12728 | |rz| 0.9158
G32 | step  1800/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.10025 | |rz| 0.9170
G32 | step  1850/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.07505 | |rz| 0.9176
G32 | step  1900/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.05003 | |rz| 0.9182
G32 | step  1950/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.02501 | |rz| 0.9192
G32 | step  2000/2000 | best 1386.0 | acc 98.2979% | success 0/128 | gamma 0.00000 | |rz| 0.9295

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G32
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644269e-05,0.000017,0.000008,7.833873e-06,0.000933
1,theta_grad_mean_abs,6.222854e-07,0.000003,0.000004,2.600473e-07,0.000121
2,raw_R_step_mean_abs,2.999592e-02,0.002990,0.002665,2.203736e-03,0.048872
3,theta_step_mean_abs,2.864121e-02,0.000750,0.002342,7.076142e-04,0.028641
4,raw_R_grad_norm,3.867730e-02,0.009228,0.004187,4.186675e-03,0.472032
5,theta_grad_norm,3.947665e-04,0.002932,0.006121,1.560190e-04,0.107817
6,raw_R_step_norm,1.517687e+01,1.608083,1.442308,1.233519e+00,24.727243
7,theta_step_norm,1.455502e+01,0.566175,3.885270,4.816875e-01,14.555017

--------------------------------------------------------------------------------
RESULT SUMMARY: G32
--------------------------------------------------------------------------------
historical_best: 1410.0

V1:
v1_best: 1388.0
v1_gap: 22.0
v1_percent_accuracy: 98.43971631205672

V2:
v2_best: 1386.0
v2_gap: 24.0
v2_percent_accuracy: 98.29787234042553
v2_best_step: 166
v2_best_replica: 28

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 27.17272138595581

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/logs/G32_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/best_spins/G32_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/partial_group_results.csv

################################################################################
RUNNING G33 | dense | seed=18
################################################################################
G33 | step     1/2000 | best 74.0 | acc 5.3546% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G33 | step    50/2000 | best 180.0 | acc 13.0246% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G33 | step   100/2000 | best 180.0 | acc 13.0246% | success 0/128 | gamma 0.95048 | |rz| 0.0010
G33 | step   150/2000 | best 1352.0 | acc 97.8292% | success 0/128 | gamma 0.92546 | |rz| 0.3490
G33 | step   200/2000 | best 1360.0 | acc 98.4081% | success 0/128 | gamma 0.90045 | |rz| 0.4904
G33 | step   250/2000 | best 1364.0 | acc 98.6975% | success 0/128 | gamma 0.87544 | |rz| 0.5459
G33 | step   300/2000 | best 1364.0 | acc 98.6975% | success 0/128 | gamma 0.85043 | |rz| 0.5795
G33 | step   350/2000 | best 1364.0 | acc 98.6975% | success 0/128 | gamma 0.82541 | |rz| 0.6069
G33 | step   400/2000 | best 1366.0 | acc 98.8423% | success 0/128 | gamma 0.80040 | |rz| 0.6316
G33 | step   450/2000 | best 1366.0 | acc 98.8423% | success 0/128 | gamma 0.77539 | |rz| 0.6545
G33 | step   500/2000 | best 1366.0 | acc 98.8423% | success 0/128 | gamma 0.75038 | |rz| 0.6758
G33 | step   550/2000 | best 1366.0 | acc 98.8423% | success 0/128 | gamma 0.72536 | |rz| 0.6956
G33 | step   600/2000 | best 1366.0 | acc 98.8423% | success 0/128 | gamma 0.70035 | |rz| 0.7142
G33 | step   650/2000 | best 1366.0 | acc 98.8423% | success 0/128 | gamma 0.67534 | |rz| 0.7316
G33 | step   700/2000 | best 1366.0 | acc 98.8423% | success 0/128 | gamma 0.65033 | |rz| 0.7479
G33 | step   750/2000 | best 1366.0 | acc 98.8423% | success 0/128 | gamma 0.62531 | |rz| 0.7631
G33 | step   800/2000 | best 1366.0 | acc 98.8423% | success 0/128 | gamma 0.60030 | |rz| 0.7774
G33 | step   850/2000 | best 1366.0 | acc 98.8423% | success 0/128 | gamma 0.57529 | |rz| 0.7908
G33 | step   900/2000 | best 1366.0 | acc 98.8423% | success 0/128 | gamma 0.55028 | |rz| 0.8034
G33 | step   950/2000 | best 1366.0 | acc 98.8423% | success 0/128 | gamma 0.52526 | |rz| 0.8152
G33 | step  1000/2000 | best 1366.0 | acc 98.8423% | success 0/128 | gamma 0.50025 | |rz| 0.8263
G33 | step  1050/2000 | best 1366.0 | acc 98.8423% | success 0/128 | gamma 0.47524 | |rz| 0.8367
G33 | step  1100/2000 | best 1366.0 | acc 98.8423% | success 0/128 | gamma 0.45023 | |rz| 0.8464
G33 | step  1150/2000 | best 1366.0 | acc 98.8423% | success 0/128 | gamma 0.42521 | |rz| 0.8554
G33 | step  1200/2000 | best 1366.0 | acc 98.8423% | success 0/128 | gamma 0.40020 | |rz| 0.8639
G33 | step  1250/2000 | best 1366.0 | acc 98.8423% | success 0/128 | gamma 0.37519 | |rz| 0.8718
G33 | step  1300/2000 | best 1366.0 | acc 98.8423% | success 0/128 | gamma 0.35018 | |rz| 0.8792
G33 | step  1350/2000 | best 1366.0 | acc 98.8423% | success 0/128 | gamma 0.32517 | |rz| 0.8861
G33 | step  1400/2000 | best 1366.0 | acc 98.8423% | success 0/128 | gamma 0.30034 | |rz| 0.8924
G33 | step  1450/2000 | best 1366.0 | acc 98.8423% | success 0/128 | gamma 0.27732 | |rz| 0.8979
G33 | step  1500/2000 | best 1366.0 | acc 98.8423% | success 0/128 | gamma 0.26252 | |rz| 0.9016
G33 | step  1550/2000 | best 1366.0 | acc 98.8423% | success 0/128 | gamma 0.26035 | |rz| 0.9031
G33 | step  1600/2000 | best 1366.0 | acc 98.8423% | success 0/128 | gamma 0.25010 | |rz| 0.9059
G33 | step  1650/2000 | best 1366.0 | acc 98.8423% | success 0/128 | gamma 0.21052 | |rz| 0.9124
G33 | step  1700/2000 | best 1366.0 | acc 98.8423% | success 0/128 | gamma 0.16261 | |rz| 0.9182
G33 | step  1750/2000 | best 1366.0 | acc 98.8423% | success 0/128 | gamma 0.12728 | |rz| 0.9209
G33 | step  1800/2000 | best 1366.0 | acc 98.8423% | success 0/128 | gamma 0.10025 | |rz| 0.9221
G33 | step  1850/2000 | best 1366.0 | acc 98.8423% | success 0/128 | gamma 0.07505 | |rz| 0.9225
G33 | step  1900/2000 | best 1366.0 | acc 98.8423% | success 0/128 | gamma 0.05003 | |rz| 0.9230
G33 | step  1950/2000 | best 1366.0 | acc 98.8423% | success 0/128 | gamma 0.02501 | |rz| 0.9240
G33 | step  2000/2000 | best 1366.0 | acc 98.8423% | success 0/128 | gamma 0.00000 | |rz| 0.9345

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G33
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644251e-05,0.000017,0.000008,7.905900e-06,0.000933
1,theta_grad_mean_abs,6.221076e-07,0.000003,0.000005,2.608894e-07,0.000112
2,raw_R_step_mean_abs,2.999592e-02,0.003002,0.002690,2.217310e-03,0.048872
3,theta_step_mean_abs,2.864021e-02,0.000769,0.002358,7.134234e-04,0.028640
4,raw_R_grad_norm,3.867721e-02,0.009260,0.004216,4.215651e-03,0.472033
5,theta_grad_norm,3.947154e-04,0.003042,0.006200,1.564137e-04,0.102930
6,raw_R_step_norm,1.517687e+01,1.613206,1.453181,1.240945e+00,24.727262
7,theta_step_norm,1.455467e+01,0.581495,3.953438,5.026600e-01,14.554672

--------------------------------------------------------------------------------
RESULT SUMMARY: G33
--------------------------------------------------------------------------------
historical_best: 1382.0

V1:
v1_best: 1364.0
v1_gap: 18.0
v1_percent_accuracy: 98.69753979739508

V2:
v2_best: 1366.0
v2_gap: 16.0
v2_percent_accuracy: 98.84225759768451
v2_best_step: 383
v2_best_replica: 6

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 26.464083909988403

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/logs/G33_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/best_spins/G33_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/partial_group_results.csv

################################################################################
RUNNING G34 | dense | seed=19
################################################################################
G34 | step     1/2000 | best 52.0 | acc 3.7572% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G34 | step    50/2000 | best 202.0 | acc 14.5954% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G34 | step   100/2000 | best 202.0 | acc 14.5954% | success 0/128 | gamma 0.95048 | |rz| 0.0010
G34 | step   150/2000 | best 1356.0 | acc 97.9769% | success 0/128 | gamma 0.92546 | |rz| 0.3557
G34 | step   200/2000 | best 1362.0 | acc 98.4104% | success 0/128 | gamma 0.90045 | |rz| 0.4999
G34 | step   250/2000 | best 1362.0 | acc 98.4104% | success 0/128 | gamma 0.87544 | |rz| 0.5545
G34 | step   300/2000 | best 1362.0 | acc 98.4104% | success 0/128 | gamma 0.85043 | |rz| 0.5872
G34 | step   350/2000 | best 1366.0 | acc 98.6994% | success 0/128 | gamma 0.82541 | |rz| 0.6138
G34 | step   400/2000 | best 1368.0 | acc 98.8439% | success 0/128 | gamma 0.80040 | |rz| 0.6377
G34 | step   450/2000 | best 1368.0 | acc 98.8439% | success 0/128 | gamma 0.77539 | |rz| 0.6597
G34 | step   500/2000 | best 1370.0 | acc 98.9884% | success 0/128 | gamma 0.75038 | |rz| 0.6802
G34 | step   550/2000 | best 1370.0 | acc 98.9884% | success 0/128 | gamma 0.72536 | |rz| 0.6993
G34 | step   600/2000 | best 1370.0 | acc 98.9884% | success 0/128 | gamma 0.70035 | |rz| 0.7172
G34 | step   650/2000 | best 1370.0 | acc 98.9884% | success 0/128 | gamma 0.67534 | |rz| 0.7340
G34 | step   700/2000 | best 1370.0 | acc 98.9884% | success 0/128 | gamma 0.65033 | |rz| 0.7497
G34 | step   750/2000 | best 1370.0 | acc 98.9884% | success 0/128 | gamma 0.62531 | |rz| 0.7644
G34 | step   800/2000 | best 1370.0 | acc 98.9884% | success 0/128 | gamma 0.60030 | |rz| 0.7782
G34 | step   850/2000 | best 1370.0 | acc 98.9884% | success 0/128 | gamma 0.57529 | |rz| 0.7911
G34 | step   900/2000 | best 1370.0 | acc 98.9884% | success 0/128 | gamma 0.55028 | |rz| 0.8032
G34 | step   950/2000 | best 1370.0 | acc 98.9884% | success 0/128 | gamma 0.52526 | |rz| 0.8146
G34 | step  1000/2000 | best 1370.0 | acc 98.9884% | success 0/128 | gamma 0.50025 | |rz| 0.8252
G34 | step  1050/2000 | best 1370.0 | acc 98.9884% | success 0/128 | gamma 0.47524 | |rz| 0.8352
G34 | step  1100/2000 | best 1370.0 | acc 98.9884% | success 0/128 | gamma 0.45023 | |rz| 0.8446
G34 | step  1150/2000 | best 1370.0 | acc 98.9884% | success 0/128 | gamma 0.42521 | |rz| 0.8534
G34 | step  1200/2000 | best 1370.0 | acc 98.9884% | success 0/128 | gamma 0.40020 | |rz| 0.8616
G34 | step  1250/2000 | best 1370.0 | acc 98.9884% | success 0/128 | gamma 0.37519 | |rz| 0.8693
G34 | step  1300/2000 | best 1370.0 | acc 98.9884% | success 0/128 | gamma 0.35018 | |rz| 0.8765
G34 | step  1350/2000 | best 1370.0 | acc 98.9884% | success 0/128 | gamma 0.32517 | |rz| 0.8831
G34 | step  1400/2000 | best 1370.0 | acc 98.9884% | success 0/128 | gamma 0.30034 | |rz| 0.8893
G34 | step  1450/2000 | best 1370.0 | acc 98.9884% | success 0/128 | gamma 0.27732 | |rz| 0.8946
G34 | step  1500/2000 | best 1370.0 | acc 98.9884% | success 0/128 | gamma 0.26252 | |rz| 0.8982
G34 | step  1550/2000 | best 1370.0 | acc 98.9884% | success 0/128 | gamma 0.26035 | |rz| 0.8996
G34 | step  1600/2000 | best 1370.0 | acc 98.9884% | success 0/128 | gamma 0.25010 | |rz| 0.9023
G34 | step  1650/2000 | best 1370.0 | acc 98.9884% | success 0/128 | gamma 0.21052 | |rz| 0.9084
G34 | step  1700/2000 | best 1370.0 | acc 98.9884% | success 0/128 | gamma 0.16261 | |rz| 0.9140
G34 | step  1750/2000 | best 1370.0 | acc 98.9884% | success 0/128 | gamma 0.12728 | |rz| 0.9168
G34 | step  1800/2000 | best 1370.0 | acc 98.9884% | success 0/128 | gamma 0.10025 | |rz| 0.9181
G34 | step  1850/2000 | best 1370.0 | acc 98.9884% | success 0/128 | gamma 0.07505 | |rz| 0.9187
G34 | step  1900/2000 | best 1370.0 | acc 98.9884% | success 0/128 | gamma 0.05003 | |rz| 0.9192
G34 | step  1950/2000 | best 1370.0 | acc 98.9884% | success 0/128 | gamma 0.02501 | |rz| 0.9202
G34 | step  2000/2000 | best 1370.0 | acc 98.9884% | success 0/128 | gamma 0.00000 | |rz| 0.9296

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G34
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644269e-05,0.000017,0.000008,7.839615e-06,0.000933
1,theta_grad_mean_abs,6.228672e-07,0.000003,0.000004,2.600963e-07,0.000112
2,raw_R_step_mean_abs,2.999592e-02,0.002982,0.002659,2.221239e-03,0.048872
3,theta_step_mean_abs,2.862817e-02,0.000756,0.002194,7.050341e-04,0.028628
4,raw_R_grad_norm,3.867730e-02,0.009238,0.004194,4.193960e-03,0.472032
5,theta_grad_norm,3.952930e-04,0.003000,0.006067,1.560086e-04,0.101590
6,raw_R_step_norm,1.517687e+01,1.604984,1.440783,1.241297e+00,24.727243
7,theta_step_norm,1.455073e+01,0.573142,3.721646,4.787402e-01,14.550734

--------------------------------------------------------------------------------
RESULT SUMMARY: G34
--------------------------------------------------------------------------------
historical_best: 1384.0

V1:
v1_best: 1362.0
v1_gap: 22.0
v1_percent_accuracy: 98.41040462427746

V2:
v2_best: 1370.0
v2_gap: 14.0
v2_percent_accuracy: 98.98843930635839
v2_best_step: 456
v2_best_replica: 123

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 24.3583722114563

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/logs/G34_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/best_spins/G34_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/partial_group_results.csv

################################################################################
RUNNING G35 | dense | seed=20
################################################################################
G35 | step     1/2000 | best 6005.0 | acc 78.1189% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G35 | step    50/2000 | best 6244.0 | acc 81.2280% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G35 | step   100/2000 | best 7046.0 | acc 91.6612% | success 0/128 | gamma 0.95048 | |rz| 0.0162
G35 | step   150/2000 | best 7536.0 | acc 98.0356% | success 0/128 | gamma 0.92546 | |rz| 0.4862
G35 | step   200/2000 | best 7555.0 | acc 98.2828% | success 0/128 | gamma 0.90045 | |rz| 0.5646
G35 | step   250/2000 | best 7557.0 | acc 98.3088% | success 0/128 | gamma 0.87544 | |rz| 0.5907
G35 | step   300/2000 | best 7569.0 | acc 98.4649% | success 0/128 | gamma 0.85043 | |rz| 0.6095
G35 | step   350/2000 | best 7571.0 | acc 98.4910% | success 0/128 | gamma 0.82541 | |rz| 0.6261
G35 | step   400/2000 | best 7576.0 | acc 98.5560% | success 0/128 | gamma 0.80040 | |rz| 0.6420
G35 | step   450/2000 | best 7578.0 | acc 98.5820% | success 0/128 | gamma 0.77539 | |rz| 0.6573
G35 | step   500/2000 | best 7584.0 | acc 98.6601% | success 0/128 | gamma 0.75038 | |rz| 0.6723
G35 | step   550/2000 | best 7587.0 | acc 98.6991% | success 0/128 | gamma 0.72536 | |rz| 0.6871
G35 | step   600/2000 | best 7590.0 | acc 98.7381% | success 0/128 | gamma 0.70035 | |rz| 0.7016
G35 | step   650/2000 | best 7592.0 | acc 98.7641% | success 0/128 | gamma 0.67534 | |rz| 0.7159
G35 | step   700/2000 | best 7595.0 | acc 98.8032% | success 0/128 | gamma 0.65033 | |rz| 0.7300
G35 | step   750/2000 | best 7597.0 | acc 98.8292% | success 0/128 | gamma 0.62531 | |rz| 0.7438
G35 | step   800/2000 | best 7603.0 | acc 98.9072% | success 0/128 | gamma 0.60030 | |rz| 0.7574
G35 | step   850/2000 | best 7606.0 | acc 98.9463% | success 0/128 | gamma 0.57529 | |rz| 0.7706
G35 | step   900/2000 | best 7607.0 | acc 98.9593% | success 0/128 | gamma 0.55028 | |rz| 0.7834
G35 | step   950/2000 | best 7609.0 | acc 98.9853% | success 0/128 | gamma 0.52526 | |rz| 0.7959
G35 | step  1000/2000 | best 7609.0 | acc 98.9853% | success 0/128 | gamma 0.50025 | |rz| 0.8079
G35 | step  1050/2000 | best 7610.0 | acc 98.9983% | success 0/128 | gamma 0.47524 | |rz| 0.8194
G35 | step  1100/2000 | best 7612.0 | acc 99.0243% | success 0/128 | gamma 0.45023 | |rz| 0.8305
G35 | step  1150/2000 | best 7612.0 | acc 99.0243% | success 0/128 | gamma 0.42521 | |rz| 0.8410
G35 | step  1200/2000 | best 7612.0 | acc 99.0243% | success 0/128 | gamma 0.40020 | |rz| 0.8510
G35 | step  1250/2000 | best 7613.0 | acc 99.0373% | success 0/128 | gamma 0.37519 | |rz| 0.8606
G35 | step  1300/2000 | best 7613.0 | acc 99.0373% | success 0/128 | gamma 0.35018 | |rz| 0.8698
G35 | step  1350/2000 | best 7613.0 | acc 99.0373% | success 0/128 | gamma 0.32517 | |rz| 0.8785
G35 | step  1400/2000 | best 7613.0 | acc 99.0373% | success 0/128 | gamma 0.30034 | |rz| 0.8866
G35 | step  1450/2000 | best 7615.0 | acc 99.0634% | success 0/128 | gamma 0.27732 | |rz| 0.8937
G35 | step  1500/2000 | best 7615.0 | acc 99.0634% | success 0/128 | gamma 0.26252 | |rz| 0.8986
G35 | step  1550/2000 | best 7615.0 | acc 99.0634% | success 0/128 | gamma 0.26035 | |rz| 0.9010
G35 | step  1600/2000 | best 7616.0 | acc 99.0764% | success 0/128 | gamma 0.25010 | |rz| 0.9048
G35 | step  1650/2000 | best 7616.0 | acc 99.0764% | success 0/128 | gamma 0.21052 | |rz| 0.9129
G35 | step  1700/2000 | best 7616.0 | acc 99.0764% | success 0/128 | gamma 0.16261 | |rz| 0.9203
G35 | step  1750/2000 | best 7616.0 | acc 99.0764% | success 0/128 | gamma 0.12728 | |rz| 0.9245
G35 | step  1800/2000 | best 7616.0 | acc 99.0764% | success 0/128 | gamma 0.10025 | |rz| 0.9270
G35 | step  1850/2000 | best 7616.0 | acc 99.0764% | success 0/128 | gamma 0.07505 | |rz| 0.9290
G35 | step  1900/2000 | best 7616.0 | acc 99.0764% | success 0/128 | gamma 0.05003 | |rz| 0.9305
G35 | step  1950/2000 | best 7616.0 | acc 99.0764% | success 0/128 | gamma 0.02501 | |rz| 0.9319
G35 | step  2000/2000 | best 7616.0 | acc 99.0764% | success 0/128 | gamma 0.00000 | |rz| 0.9408

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G35
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644275e-05,0.000019,0.000009,9.358268e-06,0.000937
1,theta_grad_mean_abs,6.246794e-07,0.000004,0.000005,2.558198e-07,0.000071
2,raw_R_step_mean_abs,2.999592e-02,0.002649,0.002740,1.965628e-03,0.048897
3,theta_step_mean_abs,2.864441e-02,0.000761,0.002112,5.857695e-04,0.028644
4,raw_R_grad_norm,3.867732e-02,0.011580,0.005189,5.189198e-03,0.474677
5,theta_grad_norm,3.962046e-04,0.006638,0.006283,1.573915e-04,0.182866
6,raw_R_step_norm,1.517687e+01,1.486158,1.519967,1.179570e+00,24.740641
7,theta_step_norm,1.455675e+01,0.687951,3.084028,5.000442e-01,14.556748

--------------------------------------------------------------------------------
RESULT SUMMARY: G35
--------------------------------------------------------------------------------
historical_best: 7687.0

V1:
v1_best: 7612.0
v1_gap: 75.0
v1_percent_accuracy: 99.024326785482

V2:
v2_best: 7616.0
v2_gap: 71.0
v2_percent_accuracy: 99.07636269025627
v2_best_step: 1558
v2_best_replica: 59

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 24.133266925811768

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/logs/G35_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/best_spins/G35_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/partial_group_results.csv

################################################################################
RUNNING G36 | dense | seed=21
################################################################################
G36 | step     1/2000 | best 5985.0 | acc 77.9297% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G36 | step    50/2000 | best 6263.0 | acc 81.5495% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G36 | step   100/2000 | best 7084.0 | acc 92.2396% | success 0/128 | gamma 0.95048 | |rz| 0.0246
G36 | step   150/2000 | best 7522.0 | acc 97.9427% | success 0/128 | gamma 0.92546 | |rz| 0.4873
G36 | step   200/2000 | best 7544.0 | acc 98.2292% | success 0/128 | gamma 0.90045 | |rz| 0.5665
G36 | step   250/2000 | best 7554.0 | acc 98.3594% | success 0/128 | gamma 0.87544 | |rz| 0.5931
G36 | step   300/2000 | best 7562.0 | acc 98.4635% | success 0/128 | gamma 0.85043 | |rz| 0.6120
G36 | step   350/2000 | best 7565.0 | acc 98.5026% | success 0/128 | gamma 0.82541 | |rz| 0.6287
G36 | step   400/2000 | best 7569.0 | acc 98.5547% | success 0/128 | gamma 0.80040 | |rz| 0.6446
G36 | step   450/2000 | best 7573.0 | acc 98.6068% | success 0/128 | gamma 0.77539 | |rz| 0.6600
G36 | step   500/2000 | best 7579.0 | acc 98.6849% | success 0/128 | gamma 0.75038 | |rz| 0.6752
G36 | step   550/2000 | best 7584.0 | acc 98.7500% | success 0/128 | gamma 0.72536 | |rz| 0.6901
G36 | step   600/2000 | best 7592.0 | acc 98.8542% | success 0/128 | gamma 0.70035 | |rz| 0.7048
G36 | step   650/2000 | best 7593.0 | acc 98.8672% | success 0/128 | gamma 0.67534 | |rz| 0.7193
G36 | step   700/2000 | best 7595.0 | acc 98.8932% | success 0/128 | gamma 0.65033 | |rz| 0.7335
G36 | step   750/2000 | best 7596.0 | acc 98.9062% | success 0/128 | gamma 0.62531 | |rz| 0.7474
G36 | step   800/2000 | best 7597.0 | acc 98.9193% | success 0/128 | gamma 0.60030 | |rz| 0.7611
G36 | step   850/2000 | best 7598.0 | acc 98.9323% | success 0/128 | gamma 0.57529 | |rz| 0.7745
G36 | step   900/2000 | best 7600.0 | acc 98.9583% | success 0/128 | gamma 0.55028 | |rz| 0.7875
G36 | step   950/2000 | best 7601.0 | acc 98.9714% | success 0/128 | gamma 0.52526 | |rz| 0.8001
G36 | step  1000/2000 | best 7601.0 | acc 98.9714% | success 0/128 | gamma 0.50025 | |rz| 0.8122
G36 | step  1050/2000 | best 7601.0 | acc 98.9714% | success 0/128 | gamma 0.47524 | |rz| 0.8239
G36 | step  1100/2000 | best 7601.0 | acc 98.9714% | success 0/128 | gamma 0.45023 | |rz| 0.8351
G36 | step  1150/2000 | best 7601.0 | acc 98.9714% | success 0/128 | gamma 0.42521 | |rz| 0.8457
G36 | step  1200/2000 | best 7601.0 | acc 98.9714% | success 0/128 | gamma 0.40020 | |rz| 0.8558
G36 | step  1250/2000 | best 7601.0 | acc 98.9714% | success 0/128 | gamma 0.37519 | |rz| 0.8653
G36 | step  1300/2000 | best 7601.0 | acc 98.9714% | success 0/128 | gamma 0.35018 | |rz| 0.8743
G36 | step  1350/2000 | best 7602.0 | acc 98.9844% | success 0/128 | gamma 0.32517 | |rz| 0.8828
G36 | step  1400/2000 | best 7602.0 | acc 98.9844% | success 0/128 | gamma 0.30034 | |rz| 0.8906
G36 | step  1450/2000 | best 7602.0 | acc 98.9844% | success 0/128 | gamma 0.27732 | |rz| 0.8975
G36 | step  1500/2000 | best 7602.0 | acc 98.9844% | success 0/128 | gamma 0.26252 | |rz| 0.9024
G36 | step  1550/2000 | best 7602.0 | acc 98.9844% | success 0/128 | gamma 0.26035 | |rz| 0.9048
G36 | step  1600/2000 | best 7602.0 | acc 98.9844% | success 0/128 | gamma 0.25010 | |rz| 0.9085
G36 | step  1650/2000 | best 7602.0 | acc 98.9844% | success 0/128 | gamma 0.21052 | |rz| 0.9165
G36 | step  1700/2000 | best 7602.0 | acc 98.9844% | success 0/128 | gamma 0.16261 | |rz| 0.9238
G36 | step  1750/2000 | best 7602.0 | acc 98.9844% | success 0/128 | gamma 0.12728 | |rz| 0.9279
G36 | step  1800/2000 | best 7602.0 | acc 98.9844% | success 0/128 | gamma 0.10025 | |rz| 0.9304
G36 | step  1850/2000 | best 7602.0 | acc 98.9844% | success 0/128 | gamma 0.07505 | |rz| 0.9323
G36 | step  1900/2000 | best 7602.0 | acc 98.9844% | success 0/128 | gamma 0.05003 | |rz| 0.9338
G36 | step  1950/2000 | best 7602.0 | acc 98.9844% | success 0/128 | gamma 0.02501 | |rz| 0.9352
G36 | step  2000/2000 | best 7602.0 | acc 98.9844% | success 0/128 | gamma 0.00000 | |rz| 0.9439

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G36
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644283e-05,0.000019,0.000009,9.395182e-06,0.000943
1,theta_grad_mean_abs,6.243845e-07,0.000005,0.000005,2.551214e-07,0.000061
2,raw_R_step_mean_abs,2.999592e-02,0.002662,0.002747,1.963919e-03,0.048930
3,theta_step_mean_abs,2.864516e-02,0.000908,0.002091,6.415960e-04,0.028645
4,raw_R_grad_norm,3.867737e-02,0.011633,0.005231,5.230689e-03,0.481057
5,theta_grad_norm,3.960315e-04,0.005403,0.006514,1.570320e-04,0.164580
6,raw_R_step_norm,1.517687e+01,1.475737,1.518869,1.182650e+00,24.757357
7,theta_step_norm,1.455680e+01,0.773219,3.011498,5.384666e-01,14.556800

--------------------------------------------------------------------------------
RESULT SUMMARY: G36
--------------------------------------------------------------------------------
historical_best: 7680.0

V1:
v1_best: 7599.0
v1_gap: 81.0
v1_percent_accuracy: 98.9453125

V2:
v2_best: 7602.0
v2_gap: 78.0
v2_percent_accuracy: 98.984375
v2_best_step: 1343
v2_best_replica: 108

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 24.66663408279419

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/logs/G36_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/best_spins/G36_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/partial_group_results.csv

################################################################################
RUNNING G37 | dense | seed=22
################################################################################
G37 | step     1/2000 | best 5974.0 | acc 77.6752% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G37 | step    50/2000 | best 6230.0 | acc 81.0038% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G37 | step   100/2000 | best 7059.0 | acc 91.7826% | success 0/128 | gamma 0.95048 | |rz| 0.0188
G37 | step   150/2000 | best 7540.0 | acc 98.0367% | success 0/128 | gamma 0.92546 | |rz| 0.4853
G37 | step   200/2000 | best 7557.0 | acc 98.2577% | success 0/128 | gamma 0.90045 | |rz| 0.5637
G37 | step   250/2000 | best 7566.0 | acc 98.3747% | success 0/128 | gamma 0.87544 | |rz| 0.5902
G37 | step   300/2000 | best 7571.0 | acc 98.4397% | success 0/128 | gamma 0.85043 | |rz| 0.6091
G37 | step   350/2000 | best 7579.0 | acc 98.5438% | success 0/128 | gamma 0.82541 | |rz| 0.6259
G37 | step   400/2000 | best 7580.0 | acc 98.5568% | success 0/128 | gamma 0.80040 | |rz| 0.6419
G37 | step   450/2000 | best 7582.0 | acc 98.5828% | success 0/128 | gamma 0.77539 | |rz| 0.6574
G37 | step   500/2000 | best 7586.0 | acc 98.6348% | success 0/128 | gamma 0.75038 | |rz| 0.6727
G37 | step   550/2000 | best 7591.0 | acc 98.6998% | success 0/128 | gamma 0.72536 | |rz| 0.6877
G37 | step   600/2000 | best 7596.0 | acc 98.7648% | success 0/128 | gamma 0.70035 | |rz| 0.7025
G37 | step   650/2000 | best 7598.0 | acc 98.7908% | success 0/128 | gamma 0.67534 | |rz| 0.7170
G37 | step   700/2000 | best 7602.0 | acc 98.8428% | success 0/128 | gamma 0.65033 | |rz| 0.7312
G37 | step   750/2000 | best 7607.0 | acc 98.9078% | success 0/128 | gamma 0.62531 | |rz| 0.7452
G37 | step   800/2000 | best 7608.0 | acc 98.9208% | success 0/128 | gamma 0.60030 | |rz| 0.7589
G37 | step   850/2000 | best 7609.0 | acc 98.9338% | success 0/128 | gamma 0.57529 | |rz| 0.7722
G37 | step   900/2000 | best 7609.0 | acc 98.9338% | success 0/128 | gamma 0.55028 | |rz| 0.7852
G37 | step   950/2000 | best 7610.0 | acc 98.9468% | success 0/128 | gamma 0.52526 | |rz| 0.7978
G37 | step  1000/2000 | best 7611.0 | acc 98.9598% | success 0/128 | gamma 0.50025 | |rz| 0.8098
G37 | step  1050/2000 | best 7615.0 | acc 99.0118% | success 0/128 | gamma 0.47524 | |rz| 0.8214
G37 | step  1100/2000 | best 7615.0 | acc 99.0118% | success 0/128 | gamma 0.45023 | |rz| 0.8324
G37 | step  1150/2000 | best 7615.0 | acc 99.0118% | success 0/128 | gamma 0.42521 | |rz| 0.8429
G37 | step  1200/2000 | best 7615.0 | acc 99.0118% | success 0/128 | gamma 0.40020 | |rz| 0.8528
G37 | step  1250/2000 | best 7615.0 | acc 99.0118% | success 0/128 | gamma 0.37519 | |rz| 0.8623
G37 | step  1300/2000 | best 7615.0 | acc 99.0118% | success 0/128 | gamma 0.35018 | |rz| 0.8714
G37 | step  1350/2000 | best 7615.0 | acc 99.0118% | success 0/128 | gamma 0.32517 | |rz| 0.8800
G37 | step  1400/2000 | best 7615.0 | acc 99.0118% | success 0/128 | gamma 0.30034 | |rz| 0.8879
G37 | step  1450/2000 | best 7615.0 | acc 99.0118% | success 0/128 | gamma 0.27732 | |rz| 0.8948
G37 | step  1500/2000 | best 7615.0 | acc 99.0118% | success 0/128 | gamma 0.26252 | |rz| 0.8996
G37 | step  1550/2000 | best 7615.0 | acc 99.0118% | success 0/128 | gamma 0.26035 | |rz| 0.9020
G37 | step  1600/2000 | best 7615.0 | acc 99.0118% | success 0/128 | gamma 0.25010 | |rz| 0.9057
G37 | step  1650/2000 | best 7615.0 | acc 99.0118% | success 0/128 | gamma 0.21052 | |rz| 0.9137
G37 | step  1700/2000 | best 7615.0 | acc 99.0118% | success 0/128 | gamma 0.16261 | |rz| 0.9210
G37 | step  1750/2000 | best 7615.0 | acc 99.0118% | success 0/128 | gamma 0.12728 | |rz| 0.9250
G37 | step  1800/2000 | best 7615.0 | acc 99.0118% | success 0/128 | gamma 0.10025 | |rz| 0.9275
G37 | step  1850/2000 | best 7615.0 | acc 99.0118% | success 0/128 | gamma 0.07505 | |rz| 0.9293
G37 | step  1900/2000 | best 7615.0 | acc 99.0118% | success 0/128 | gamma 0.05003 | |rz| 0.9308
G37 | step  1950/2000 | best 7615.0 | acc 99.0118% | success 0/128 | gamma 0.02501 | |rz| 0.9322
G37 | step  2000/2000 | best 7615.0 | acc 99.0118% | success 0/128 | gamma 0.00000 | |rz| 0.9410

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G37
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644278e-05,0.000019,0.000009,9.337567e-06,0.000938
1,theta_grad_mean_abs,6.232248e-07,0.000004,0.000005,2.556879e-07,0.000066
2,raw_R_step_mean_abs,2.999592e-02,0.002656,0.002735,1.974123e-03,0.048905
3,theta_step_mean_abs,2.863738e-02,0.000729,0.002116,6.565860e-04,0.028637
4,raw_R_grad_norm,3.867735e-02,0.011497,0.005191,5.191109e-03,0.476118
5,theta_grad_norm,3.953096e-04,0.003817,0.006456,1.573619e-04,0.177862
6,raw_R_step_norm,1.517687e+01,1.467516,1.514386,1.196698e+00,24.744535
7,theta_step_norm,1.455369e+01,0.583696,3.065157,5.577116e-01,14.553693

--------------------------------------------------------------------------------
RESULT SUMMARY: G37
--------------------------------------------------------------------------------
historical_best: 7691.0

V1:
v1_best: 7619.0
v1_gap: 72.0
v1_percent_accuracy: 99.063840852945

V2:
v2_best: 7615.0
v2_gap: 76.0
v2_percent_accuracy: 99.01183201144194
v2_best_step: 1040
v2_best_replica: 60

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 24.918983936309814

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/logs/G37_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/best_spins/G37_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/partial_group_results.csv

################################################################################
RUNNING G38 | dense | seed=23
################################################################################
G38 | step     1/2000 | best 5989.0 | acc 77.9006% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G38 | step    50/2000 | best 6236.0 | acc 81.1134% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G38 | step   100/2000 | best 7029.0 | acc 91.4282% | success 0/128 | gamma 0.95048 | |rz| 0.0161
G38 | step   150/2000 | best 7541.0 | acc 98.0879% | success 0/128 | gamma 0.92546 | |rz| 0.4879
G38 | step   200/2000 | best 7566.0 | acc 98.4131% | success 0/128 | gamma 0.90045 | |rz| 0.5680
G38 | step   250/2000 | best 7572.0 | acc 98.4912% | success 0/128 | gamma 0.87544 | |rz| 0.5948
G38 | step   300/2000 | best 7578.0 | acc 98.5692% | success 0/128 | gamma 0.85043 | |rz| 0.6138
G38 | step   350/2000 | best 7586.0 | acc 98.6733% | success 0/128 | gamma 0.82541 | |rz| 0.6306
G38 | step   400/2000 | best 7588.0 | acc 98.6993% | success 0/128 | gamma 0.80040 | |rz| 0.6464
G38 | step   450/2000 | best 7589.0 | acc 98.7123% | success 0/128 | gamma 0.77539 | |rz| 0.6618
G38 | step   500/2000 | best 7592.0 | acc 98.7513% | success 0/128 | gamma 0.75038 | |rz| 0.6769
G38 | step   550/2000 | best 7598.0 | acc 98.8293% | success 0/128 | gamma 0.72536 | |rz| 0.6916
G38 | step   600/2000 | best 7600.0 | acc 98.8554% | success 0/128 | gamma 0.70035 | |rz| 0.7062
G38 | step   650/2000 | best 7604.0 | acc 98.9074% | success 0/128 | gamma 0.67534 | |rz| 0.7204
G38 | step   700/2000 | best 7609.0 | acc 98.9724% | success 0/128 | gamma 0.65033 | |rz| 0.7345
G38 | step   750/2000 | best 7610.0 | acc 98.9854% | success 0/128 | gamma 0.62531 | |rz| 0.7482
G38 | step   800/2000 | best 7611.0 | acc 98.9984% | success 0/128 | gamma 0.60030 | |rz| 0.7616
G38 | step   850/2000 | best 7617.0 | acc 99.0765% | success 0/128 | gamma 0.57529 | |rz| 0.7747
G38 | step   900/2000 | best 7620.0 | acc 99.1155% | success 0/128 | gamma 0.55028 | |rz| 0.7875
G38 | step   950/2000 | best 7621.0 | acc 99.1285% | success 0/128 | gamma 0.52526 | |rz| 0.7999
G38 | step  1000/2000 | best 7623.0 | acc 99.1545% | success 0/128 | gamma 0.50025 | |rz| 0.8118
G38 | step  1050/2000 | best 7623.0 | acc 99.1545% | success 0/128 | gamma 0.47524 | |rz| 0.8232
G38 | step  1100/2000 | best 7624.0 | acc 99.1675% | success 0/128 | gamma 0.45023 | |rz| 0.8342
G38 | step  1150/2000 | best 7624.0 | acc 99.1675% | success 0/128 | gamma 0.42521 | |rz| 0.8446
G38 | step  1200/2000 | best 7624.0 | acc 99.1675% | success 0/128 | gamma 0.40020 | |rz| 0.8545
G38 | step  1250/2000 | best 7624.0 | acc 99.1675% | success 0/128 | gamma 0.37519 | |rz| 0.8640
G38 | step  1300/2000 | best 7624.0 | acc 99.1675% | success 0/128 | gamma 0.35018 | |rz| 0.8730
G38 | step  1350/2000 | best 7624.0 | acc 99.1675% | success 0/128 | gamma 0.32517 | |rz| 0.8815
G38 | step  1400/2000 | best 7624.0 | acc 99.1675% | success 0/128 | gamma 0.30034 | |rz| 0.8894
G38 | step  1450/2000 | best 7624.0 | acc 99.1675% | success 0/128 | gamma 0.27732 | |rz| 0.8963
G38 | step  1500/2000 | best 7624.0 | acc 99.1675% | success 0/128 | gamma 0.26252 | |rz| 0.9011
G38 | step  1550/2000 | best 7624.0 | acc 99.1675% | success 0/128 | gamma 0.26035 | |rz| 0.9034
G38 | step  1600/2000 | best 7624.0 | acc 99.1675% | success 0/128 | gamma 0.25010 | |rz| 0.9071
G38 | step  1650/2000 | best 7624.0 | acc 99.1675% | success 0/128 | gamma 0.21052 | |rz| 0.9151
G38 | step  1700/2000 | best 7624.0 | acc 99.1675% | success 0/128 | gamma 0.16261 | |rz| 0.9224
G38 | step  1750/2000 | best 7624.0 | acc 99.1675% | success 0/128 | gamma 0.12728 | |rz| 0.9264
G38 | step  1800/2000 | best 7624.0 | acc 99.1675% | success 0/128 | gamma 0.10025 | |rz| 0.9289
G38 | step  1850/2000 | best 7624.0 | acc 99.1675% | success 0/128 | gamma 0.07505 | |rz| 0.9308
G38 | step  1900/2000 | best 7624.0 | acc 99.1675% | success 0/128 | gamma 0.05003 | |rz| 0.9322
G38 | step  1950/2000 | best 7624.0 | acc 99.1675% | success 0/128 | gamma 0.02501 | |rz| 0.9337
G38 | step  2000/2000 | best 7624.0 | acc 99.1675% | success 0/128 | gamma 0.00000 | |rz| 0.9422

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G38
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644316e-05,0.000019,0.000009,9.330847e-06,0.000937
1,theta_grad_mean_abs,6.238596e-07,0.000004,0.000005,2.552993e-07,0.000068
2,raw_R_step_mean_abs,2.999592e-02,0.002659,0.002733,1.986460e-03,0.048896
3,theta_step_mean_abs,2.864237e-02,0.000707,0.002069,6.814984e-04,0.028642
4,raw_R_grad_norm,3.867754e-02,0.011501,0.005180,5.179819e-03,0.474671
5,theta_grad_norm,3.952434e-04,0.003956,0.006391,1.572238e-04,0.179154
6,raw_R_step_norm,1.517687e+01,1.470325,1.513284,1.196852e+00,24.740042
7,theta_step_norm,1.455557e+01,0.619462,3.025859,5.498455e-01,14.555571

--------------------------------------------------------------------------------
RESULT SUMMARY: G38
--------------------------------------------------------------------------------
historical_best: 7688.0

V1:
v1_best: 7616.0
v1_gap: 72.0
v1_percent_accuracy: 99.06347554630594

V2:
v2_best: 7624.0
v2_gap: 64.0
v2_percent_accuracy: 99.16753381893861
v2_best_step: 1066
v2_best_replica: 102

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 24.463583946228027

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/logs/G38_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/best_spins/G38_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/partial_group_results.csv

################################################################################
RUNNING G39 | dense | seed=24
################################################################################
G39 | step     1/2000 | best 168.0 | acc 6.9767% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G39 | step    50/2000 | best 389.0 | acc 16.1545% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G39 | step   100/2000 | best 2144.0 | acc 89.0365% | success 0/128 | gamma 0.95048 | |rz| 0.1301
G39 | step   150/2000 | best 2302.0 | acc 95.5980% | success 0/128 | gamma 0.92546 | |rz| 0.6127
G39 | step   200/2000 | best 2307.0 | acc 95.8056% | success 0/128 | gamma 0.90045 | |rz| 0.6824
G39 | step   250/2000 | best 2312.0 | acc 96.0133% | success 0/128 | gamma 0.87544 | |rz| 0.7040
G39 | step   300/2000 | best 2316.0 | acc 96.1794% | success 0/128 | gamma 0.85043 | |rz| 0.7184
G39 | step   350/2000 | best 2318.0 | acc 96.2625% | success 0/128 | gamma 0.82541 | |rz| 0.7305
G39 | step   400/2000 | best 2318.0 | acc 96.2625% | success 0/128 | gamma 0.80040 | |rz| 0.7415
G39 | step   450/2000 | best 2318.0 | acc 96.2625% | success 0/128 | gamma 0.77539 | |rz| 0.7519
G39 | step   500/2000 | best 2320.0 | acc 96.3455% | success 0/128 | gamma 0.75038 | |rz| 0.7620
G39 | step   550/2000 | best 2322.0 | acc 96.4286% | success 0/128 | gamma 0.72536 | |rz| 0.7718
G39 | step   600/2000 | best 2323.0 | acc 96.4701% | success 0/128 | gamma 0.70035 | |rz| 0.7815
G39 | step   650/2000 | best 2327.0 | acc 96.6362% | success 0/128 | gamma 0.67534 | |rz| 0.7909
G39 | step   700/2000 | best 2329.0 | acc 96.7193% | success 0/128 | gamma 0.65033 | |rz| 0.8002
G39 | step   750/2000 | best 2329.0 | acc 96.7193% | success 0/128 | gamma 0.62531 | |rz| 0.8094
G39 | step   800/2000 | best 2329.0 | acc 96.7193% | success 0/128 | gamma 0.60030 | |rz| 0.8184
G39 | step   850/2000 | best 2329.0 | acc 96.7193% | success 0/128 | gamma 0.57529 | |rz| 0.8272
G39 | step   900/2000 | best 2329.0 | acc 96.7193% | success 0/128 | gamma 0.55028 | |rz| 0.8359
G39 | step   950/2000 | best 2329.0 | acc 96.7193% | success 0/128 | gamma 0.52526 | |rz| 0.8443
G39 | step  1000/2000 | best 2330.0 | acc 96.7608% | success 0/128 | gamma 0.50025 | |rz| 0.8525
G39 | step  1050/2000 | best 2330.0 | acc 96.7608% | success 0/128 | gamma 0.47524 | |rz| 0.8604
G39 | step  1100/2000 | best 2330.0 | acc 96.7608% | success 0/128 | gamma 0.45023 | |rz| 0.8681
G39 | step  1150/2000 | best 2330.0 | acc 96.7608% | success 0/128 | gamma 0.42521 | |rz| 0.8755
G39 | step  1200/2000 | best 2330.0 | acc 96.7608% | success 0/128 | gamma 0.40020 | |rz| 0.8826
G39 | step  1250/2000 | best 2331.0 | acc 96.8023% | success 0/128 | gamma 0.37519 | |rz| 0.8895
G39 | step  1300/2000 | best 2331.0 | acc 96.8023% | success 0/128 | gamma 0.35018 | |rz| 0.8962
G39 | step  1350/2000 | best 2331.0 | acc 96.8023% | success 0/128 | gamma 0.32517 | |rz| 0.9026
G39 | step  1400/2000 | best 2331.0 | acc 96.8023% | success 0/128 | gamma 0.30034 | |rz| 0.9085
G39 | step  1450/2000 | best 2331.0 | acc 96.8023% | success 0/128 | gamma 0.27732 | |rz| 0.9137
G39 | step  1500/2000 | best 2331.0 | acc 96.8023% | success 0/128 | gamma 0.26252 | |rz| 0.9174
G39 | step  1550/2000 | best 2331.0 | acc 96.8023% | success 0/128 | gamma 0.26035 | |rz| 0.9192
G39 | step  1600/2000 | best 2331.0 | acc 96.8023% | success 0/128 | gamma 0.25010 | |rz| 0.9220
G39 | step  1650/2000 | best 2331.0 | acc 96.8023% | success 0/128 | gamma 0.21052 | |rz| 0.9281
G39 | step  1700/2000 | best 2331.0 | acc 96.8023% | success 0/128 | gamma 0.16261 | |rz| 0.9337
G39 | step  1750/2000 | best 2331.0 | acc 96.8023% | success 0/128 | gamma 0.12728 | |rz| 0.9369
G39 | step  1800/2000 | best 2331.0 | acc 96.8023% | success 0/128 | gamma 0.10025 | |rz| 0.9389
G39 | step  1850/2000 | best 2331.0 | acc 96.8023% | success 0/128 | gamma 0.07505 | |rz| 0.9404
G39 | step  1900/2000 | best 2331.0 | acc 96.8023% | success 0/128 | gamma 0.05003 | |rz| 0.9415
G39 | step  1950/2000 | best 2331.0 | acc 96.8023% | success 0/128 | gamma 0.02501 | |rz| 0.9425
G39 | step  2000/2000 | best 2331.0 | acc 96.8023% | success 0/128 | gamma 0.00000 | |rz| 0.9489

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G39
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644272e-05,0.000023,0.000010,1.036090e-05,0.001174
1,theta_grad_mean_abs,6.235362e-07,0.000007,0.000006,2.568032e-07,0.000163
2,raw_R_step_mean_abs,2.999592e-02,0.002411,0.002400,2.143455e-03,0.050585
3,theta_step_mean_abs,2.864082e-02,0.000989,0.001800,9.150046e-04,0.033493
4,raw_R_grad_norm,3.867731e-02,0.015165,0.006019,6.019300e-03,0.719532
5,theta_grad_norm,3.957466e-04,0.005965,0.007818,1.580722e-04,0.460446
6,raw_R_step_norm,1.517687e+01,1.304032,1.352355,1.191650e+00,25.629749
7,theta_step_norm,1.455490e+01,0.695072,2.731476,5.579928e-01,19.472540

--------------------------------------------------------------------------------
RESULT SUMMARY: G39
--------------------------------------------------------------------------------
historical_best: 2408.0

V1:
v1_best: 2336.0
v1_gap: 72.0
v1_percent_accuracy: 97.00996677740864

V2:
v2_best: 2331.0
v2_gap: 77.0
v2_percent_accuracy: 96.80232558139535
v2_best_step: 1220
v2_best_replica: 13

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 24.441082000732422

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/logs/G39_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/best_spins/G39_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/partial_group_results.csv

################################################################################
RUNNING G40 | dense | seed=25
################################################################################
G40 | step     1/2000 | best 51.0 | acc 2.1250% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G40 | step    50/2000 | best 368.0 | acc 15.3333% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G40 | step   100/2000 | best 2132.0 | acc 88.8333% | success 0/128 | gamma 0.95048 | |rz| 0.1381
G40 | step   150/2000 | best 2288.0 | acc 95.3333% | success 0/128 | gamma 0.92546 | |rz| 0.6192
G40 | step   200/2000 | best 2293.0 | acc 95.5417% | success 0/128 | gamma 0.90045 | |rz| 0.6891
G40 | step   250/2000 | best 2298.0 | acc 95.7500% | success 0/128 | gamma 0.87544 | |rz| 0.7110
G40 | step   300/2000 | best 2310.0 | acc 96.2500% | success 0/128 | gamma 0.85043 | |rz| 0.7258
G40 | step   350/2000 | best 2311.0 | acc 96.2917% | success 0/128 | gamma 0.82541 | |rz| 0.7381
G40 | step   400/2000 | best 2316.0 | acc 96.5000% | success 0/128 | gamma 0.80040 | |rz| 0.7498
G40 | step   450/2000 | best 2317.0 | acc 96.5417% | success 0/128 | gamma 0.77539 | |rz| 0.7611
G40 | step   500/2000 | best 2321.0 | acc 96.7083% | success 0/128 | gamma 0.75038 | |rz| 0.7714
G40 | step   550/2000 | best 2324.0 | acc 96.8333% | success 0/128 | gamma 0.72536 | |rz| 0.7812
G40 | step   600/2000 | best 2324.0 | acc 96.8333% | success 0/128 | gamma 0.70035 | |rz| 0.7905
G40 | step   650/2000 | best 2324.0 | acc 96.8333% | success 0/128 | gamma 0.67534 | |rz| 0.7997
G40 | step   700/2000 | best 2324.0 | acc 96.8333% | success 0/128 | gamma 0.65033 | |rz| 0.8087
G40 | step   750/2000 | best 2324.0 | acc 96.8333% | success 0/128 | gamma 0.62531 | |rz| 0.8176
G40 | step   800/2000 | best 2326.0 | acc 96.9167% | success 0/128 | gamma 0.60030 | |rz| 0.8263
G40 | step   850/2000 | best 2326.0 | acc 96.9167% | success 0/128 | gamma 0.57529 | |rz| 0.8348
G40 | step   900/2000 | best 2326.0 | acc 96.9167% | success 0/128 | gamma 0.55028 | |rz| 0.8430
G40 | step   950/2000 | best 2327.0 | acc 96.9583% | success 0/128 | gamma 0.52526 | |rz| 0.8510
G40 | step  1000/2000 | best 2327.0 | acc 96.9583% | success 0/128 | gamma 0.50025 | |rz| 0.8588
G40 | step  1050/2000 | best 2327.0 | acc 96.9583% | success 0/128 | gamma 0.47524 | |rz| 0.8663
G40 | step  1100/2000 | best 2327.0 | acc 96.9583% | success 0/128 | gamma 0.45023 | |rz| 0.8735
G40 | step  1150/2000 | best 2327.0 | acc 96.9583% | success 0/128 | gamma 0.42521 | |rz| 0.8805
G40 | step  1200/2000 | best 2328.0 | acc 97.0000% | success 0/128 | gamma 0.40020 | |rz| 0.8872
G40 | step  1250/2000 | best 2328.0 | acc 97.0000% | success 0/128 | gamma 0.37519 | |rz| 0.8936
G40 | step  1300/2000 | best 2328.0 | acc 97.0000% | success 0/128 | gamma 0.35018 | |rz| 0.8999
G40 | step  1350/2000 | best 2328.0 | acc 97.0000% | success 0/128 | gamma 0.32517 | |rz| 0.9058
G40 | step  1400/2000 | best 2328.0 | acc 97.0000% | success 0/128 | gamma 0.30034 | |rz| 0.9114
G40 | step  1450/2000 | best 2328.0 | acc 97.0000% | success 0/128 | gamma 0.27732 | |rz| 0.9163
G40 | step  1500/2000 | best 2328.0 | acc 97.0000% | success 0/128 | gamma 0.26252 | |rz| 0.9198
G40 | step  1550/2000 | best 2328.0 | acc 97.0000% | success 0/128 | gamma 0.26035 | |rz| 0.9214
G40 | step  1600/2000 | best 2328.0 | acc 97.0000% | success 0/128 | gamma 0.25010 | |rz| 0.9240
G40 | step  1650/2000 | best 2328.0 | acc 97.0000% | success 0/128 | gamma 0.21052 | |rz| 0.9299
G40 | step  1700/2000 | best 2328.0 | acc 97.0000% | success 0/128 | gamma 0.16261 | |rz| 0.9353
G40 | step  1750/2000 | best 2328.0 | acc 97.0000% | success 0/128 | gamma 0.12728 | |rz| 0.9384
G40 | step  1800/2000 | best 2328.0 | acc 97.0000% | success 0/128 | gamma 0.10025 | |rz| 0.9403
G40 | step  1850/2000 | best 2328.0 | acc 97.0000% | success 0/128 | gamma 0.07505 | |rz| 0.9417
G40 | step  1900/2000 | best 2328.0 | acc 97.0000% | success 0/128 | gamma 0.05003 | |rz| 0.9428
G40 | step  1950/2000 | best 2328.0 | acc 97.0000% | success 0/128 | gamma 0.02501 | |rz| 0.9438
G40 | step  2000/2000 | best 2328.0 | acc 97.0000% | success 0/128 | gamma 0.00000 | |rz| 0.9499

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G40
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644263e-05,0.000023,0.000010,1.042446e-05,0.001207
1,theta_grad_mean_abs,6.228004e-07,0.000007,0.000007,2.565526e-07,0.000161
2,raw_R_step_mean_abs,2.999592e-02,0.002412,0.002374,2.183774e-03,0.050838
3,theta_step_mean_abs,2.863028e-02,0.000974,0.001743,9.189206e-04,0.033572
4,raw_R_grad_norm,3.867727e-02,0.015649,0.006087,6.087268e-03,0.770432
5,theta_grad_norm,3.952241e-04,0.007455,0.008001,1.581135e-04,0.445858
6,raw_R_step_norm,1.517687e+01,1.325881,1.336504,1.206193e+00,25.764635
7,theta_step_norm,1.455124e+01,0.781764,2.635402,5.590107e-01,19.485462

--------------------------------------------------------------------------------
RESULT SUMMARY: G40
--------------------------------------------------------------------------------
historical_best: 2400.0

V1:
v1_best: 2296.0
v1_gap: 104.0
v1_percent_accuracy: 95.66666666666669

V2:
v2_best: 2328.0
v2_gap: 72.0
v2_percent_accuracy: 97.0
v2_best_step: 1190
v2_best_replica: 3

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 24.113385915756226

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/logs/G40_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/best_spins/G40_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/partial_group_results.csv

################################################################################
RUNNING G41 | dense | seed=26
################################################################################
G41 | step     1/2000 | best 107.0 | acc 4.4491% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G41 | step    50/2000 | best 365.0 | acc 15.1767% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G41 | step   100/2000 | best 2111.0 | acc 87.7755% | success 0/128 | gamma 0.95048 | |rz| 0.1284
G41 | step   150/2000 | best 2284.0 | acc 94.9688% | success 0/128 | gamma 0.92546 | |rz| 0.6118
G41 | step   200/2000 | best 2294.0 | acc 95.3846% | success 0/128 | gamma 0.90045 | |rz| 0.6821
G41 | step   250/2000 | best 2296.0 | acc 95.4678% | success 0/128 | gamma 0.87544 | |rz| 0.7040
G41 | step   300/2000 | best 2298.0 | acc 95.5509% | success 0/128 | gamma 0.85043 | |rz| 0.7185
G41 | step   350/2000 | best 2299.0 | acc 95.5925% | success 0/128 | gamma 0.82541 | |rz| 0.7307
G41 | step   400/2000 | best 2302.0 | acc 95.7173% | success 0/128 | gamma 0.80040 | |rz| 0.7418
G41 | step   450/2000 | best 2302.0 | acc 95.7173% | success 0/128 | gamma 0.77539 | |rz| 0.7522
G41 | step   500/2000 | best 2302.0 | acc 95.7173% | success 0/128 | gamma 0.75038 | |rz| 0.7623
G41 | step   550/2000 | best 2304.0 | acc 95.8004% | success 0/128 | gamma 0.72536 | |rz| 0.7721
G41 | step   600/2000 | best 2304.0 | acc 95.8004% | success 0/128 | gamma 0.70035 | |rz| 0.7816
G41 | step   650/2000 | best 2304.0 | acc 95.8004% | success 0/128 | gamma 0.67534 | |rz| 0.7910
G41 | step   700/2000 | best 2305.0 | acc 95.8420% | success 0/128 | gamma 0.65033 | |rz| 0.8001
G41 | step   750/2000 | best 2308.0 | acc 95.9667% | success 0/128 | gamma 0.62531 | |rz| 0.8091
G41 | step   800/2000 | best 2309.0 | acc 96.0083% | success 0/128 | gamma 0.60030 | |rz| 0.8180
G41 | step   850/2000 | best 2310.0 | acc 96.0499% | success 0/128 | gamma 0.57529 | |rz| 0.8266
G41 | step   900/2000 | best 2310.0 | acc 96.0499% | success 0/128 | gamma 0.55028 | |rz| 0.8351
G41 | step   950/2000 | best 2310.0 | acc 96.0499% | success 0/128 | gamma 0.52526 | |rz| 0.8434
G41 | step  1000/2000 | best 2310.0 | acc 96.0499% | success 0/128 | gamma 0.50025 | |rz| 0.8515
G41 | step  1050/2000 | best 2310.0 | acc 96.0499% | success 0/128 | gamma 0.47524 | |rz| 0.8593
G41 | step  1100/2000 | best 2311.0 | acc 96.0915% | success 0/128 | gamma 0.45023 | |rz| 0.8669
G41 | step  1150/2000 | best 2311.0 | acc 96.0915% | success 0/128 | gamma 0.42521 | |rz| 0.8742
G41 | step  1200/2000 | best 2311.0 | acc 96.0915% | success 0/128 | gamma 0.40020 | |rz| 0.8811
G41 | step  1250/2000 | best 2311.0 | acc 96.0915% | success 0/128 | gamma 0.37519 | |rz| 0.8879
G41 | step  1300/2000 | best 2311.0 | acc 96.0915% | success 0/128 | gamma 0.35018 | |rz| 0.8944
G41 | step  1350/2000 | best 2311.0 | acc 96.0915% | success 0/128 | gamma 0.32517 | |rz| 0.9005
G41 | step  1400/2000 | best 2311.0 | acc 96.0915% | success 0/128 | gamma 0.30034 | |rz| 0.9063
G41 | step  1450/2000 | best 2311.0 | acc 96.0915% | success 0/128 | gamma 0.27732 | |rz| 0.9114
G41 | step  1500/2000 | best 2311.0 | acc 96.0915% | success 0/128 | gamma 0.26252 | |rz| 0.9149
G41 | step  1550/2000 | best 2311.0 | acc 96.0915% | success 0/128 | gamma 0.26035 | |rz| 0.9167
G41 | step  1600/2000 | best 2311.0 | acc 96.0915% | success 0/128 | gamma 0.25010 | |rz| 0.9194
G41 | step  1650/2000 | best 2311.0 | acc 96.0915% | success 0/128 | gamma 0.21052 | |rz| 0.9254
G41 | step  1700/2000 | best 2311.0 | acc 96.0915% | success 0/128 | gamma 0.16261 | |rz| 0.9309
G41 | step  1750/2000 | best 2311.0 | acc 96.0915% | success 0/128 | gamma 0.12728 | |rz| 0.9339
G41 | step  1800/2000 | best 2311.0 | acc 96.0915% | success 0/128 | gamma 0.10025 | |rz| 0.9358
G41 | step  1850/2000 | best 2311.0 | acc 96.0915% | success 0/128 | gamma 0.07505 | |rz| 0.9372
G41 | step  1900/2000 | best 2311.0 | acc 96.0915% | success 0/128 | gamma 0.05003 | |rz| 0.9383
G41 | step  1950/2000 | best 2311.0 | acc 96.0915% | success 0/128 | gamma 0.02501 | |rz| 0.9393
G41 | step  2000/2000 | best 2311.0 | acc 96.0915% | success 0/128 | gamma 0.00000 | |rz| 0.9461

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G41
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644267e-05,0.000023,0.000010,1.027435e-05,0.001169
1,theta_grad_mean_abs,6.233020e-07,0.000007,0.000007,2.572310e-07,0.000158
2,raw_R_step_mean_abs,2.999592e-02,0.002413,0.002382,2.155620e-03,0.050556
3,theta_step_mean_abs,2.864977e-02,0.000991,0.001867,9.125405e-04,0.033123
4,raw_R_grad_norm,3.867728e-02,0.015041,0.005966,5.965684e-03,0.719615
5,theta_grad_norm,3.950202e-04,0.006127,0.008066,1.581766e-04,0.440317
6,raw_R_step_norm,1.517687e+01,1.318814,1.342937,1.203805e+00,25.615431
7,theta_step_norm,1.455855e+01,0.695642,2.852947,5.583130e-01,19.284443

--------------------------------------------------------------------------------
RESULT SUMMARY: G41
--------------------------------------------------------------------------------
historical_best: 2405.0

V1:
v1_best: 2289.0
v1_gap: 116.0
v1_percent_accuracy: 95.17671517671518

V2:
v2_best: 2311.0
v2_gap: 94.0
v2_percent_accuracy: 96.0914760914761
v2_best_step: 1087
v2_best_replica: 6

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 24.93043303489685

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/logs/G41_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/best_spins/G41_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/partial_group_results.csv

################################################################################
RUNNING G42 | dense | seed=27
################################################################################
G42 | step     1/2000 | best 202.0 | acc 8.1419% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G42 | step    50/2000 | best 434.0 | acc 17.4929% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G42 | step   100/2000 | best 2225.0 | acc 89.6816% | success 0/128 | gamma 0.95048 | |rz| 0.1317
G42 | step   150/2000 | best 2363.0 | acc 95.2439% | success 0/128 | gamma 0.92546 | |rz| 0.6153
G42 | step   200/2000 | best 2371.0 | acc 95.5663% | success 0/128 | gamma 0.90045 | |rz| 0.6857
G42 | step   250/2000 | best 2374.0 | acc 95.6872% | success 0/128 | gamma 0.87544 | |rz| 0.7076
G42 | step   300/2000 | best 2377.0 | acc 95.8081% | success 0/128 | gamma 0.85043 | |rz| 0.7221
G42 | step   350/2000 | best 2377.0 | acc 95.8081% | success 0/128 | gamma 0.82541 | |rz| 0.7341
G42 | step   400/2000 | best 2380.0 | acc 95.9291% | success 0/128 | gamma 0.80040 | |rz| 0.7450
G42 | step   450/2000 | best 2381.0 | acc 95.9694% | success 0/128 | gamma 0.77539 | |rz| 0.7554
G42 | step   500/2000 | best 2384.0 | acc 96.0903% | success 0/128 | gamma 0.75038 | |rz| 0.7655
G42 | step   550/2000 | best 2384.0 | acc 96.0903% | success 0/128 | gamma 0.72536 | |rz| 0.7753
G42 | step   600/2000 | best 2384.0 | acc 96.0903% | success 0/128 | gamma 0.70035 | |rz| 0.7849
G42 | step   650/2000 | best 2384.0 | acc 96.0903% | success 0/128 | gamma 0.67534 | |rz| 0.7943
G42 | step   700/2000 | best 2386.0 | acc 96.1709% | success 0/128 | gamma 0.65033 | |rz| 0.8036
G42 | step   750/2000 | best 2387.0 | acc 96.2112% | success 0/128 | gamma 0.62531 | |rz| 0.8127
G42 | step   800/2000 | best 2387.0 | acc 96.2112% | success 0/128 | gamma 0.60030 | |rz| 0.8215
G42 | step   850/2000 | best 2389.0 | acc 96.2918% | success 0/128 | gamma 0.57529 | |rz| 0.8302
G42 | step   900/2000 | best 2391.0 | acc 96.3724% | success 0/128 | gamma 0.55028 | |rz| 0.8388
G42 | step   950/2000 | best 2391.0 | acc 96.3724% | success 0/128 | gamma 0.52526 | |rz| 0.8472
G42 | step  1000/2000 | best 2393.0 | acc 96.4530% | success 0/128 | gamma 0.50025 | |rz| 0.8554
G42 | step  1050/2000 | best 2393.0 | acc 96.4530% | success 0/128 | gamma 0.47524 | |rz| 0.8633
G42 | step  1100/2000 | best 2393.0 | acc 96.4530% | success 0/128 | gamma 0.45023 | |rz| 0.8708
G42 | step  1150/2000 | best 2393.0 | acc 96.4530% | success 0/128 | gamma 0.42521 | |rz| 0.8781
G42 | step  1200/2000 | best 2393.0 | acc 96.4530% | success 0/128 | gamma 0.40020 | |rz| 0.8851
G42 | step  1250/2000 | best 2393.0 | acc 96.4530% | success 0/128 | gamma 0.37519 | |rz| 0.8918
G42 | step  1300/2000 | best 2394.0 | acc 96.4933% | success 0/128 | gamma 0.35018 | |rz| 0.8983
G42 | step  1350/2000 | best 2394.0 | acc 96.4933% | success 0/128 | gamma 0.32517 | |rz| 0.9045
G42 | step  1400/2000 | best 2394.0 | acc 96.4933% | success 0/128 | gamma 0.30034 | |rz| 0.9102
G42 | step  1450/2000 | best 2394.0 | acc 96.4933% | success 0/128 | gamma 0.27732 | |rz| 0.9153
G42 | step  1500/2000 | best 2394.0 | acc 96.4933% | success 0/128 | gamma 0.26252 | |rz| 0.9188
G42 | step  1550/2000 | best 2394.0 | acc 96.4933% | success 0/128 | gamma 0.26035 | |rz| 0.9205
G42 | step  1600/2000 | best 2394.0 | acc 96.4933% | success 0/128 | gamma 0.25010 | |rz| 0.9233
G42 | step  1650/2000 | best 2394.0 | acc 96.4933% | success 0/128 | gamma 0.21052 | |rz| 0.9292
G42 | step  1700/2000 | best 2394.0 | acc 96.4933% | success 0/128 | gamma 0.16261 | |rz| 0.9348
G42 | step  1750/2000 | best 2394.0 | acc 96.4933% | success 0/128 | gamma 0.12728 | |rz| 0.9378
G42 | step  1800/2000 | best 2394.0 | acc 96.4933% | success 0/128 | gamma 0.10025 | |rz| 0.9396
G42 | step  1850/2000 | best 2394.0 | acc 96.4933% | success 0/128 | gamma 0.07505 | |rz| 0.9410
G42 | step  1900/2000 | best 2394.0 | acc 96.4933% | success 0/128 | gamma 0.05003 | |rz| 0.9421
G42 | step  1950/2000 | best 2394.0 | acc 96.4933% | success 0/128 | gamma 0.02501 | |rz| 0.9431
G42 | step  2000/2000 | best 2394.0 | acc 96.4933% | success 0/128 | gamma 0.00000 | |rz| 0.9497

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G42
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644288e-05,0.000023,0.000010,1.035713e-05,0.001181
1,theta_grad_mean_abs,6.243338e-07,0.000008,0.000007,2.570995e-07,0.000162
2,raw_R_step_mean_abs,2.999592e-02,0.002423,0.002388,2.161985e-03,0.050637
3,theta_step_mean_abs,2.863578e-02,0.001007,0.001841,9.148431e-04,0.033265
4,raw_R_grad_norm,3.867739e-02,0.015201,0.006002,6.002359e-03,0.729882
5,theta_grad_norm,3.961719e-04,0.007503,0.008021,1.583338e-04,0.447911
6,raw_R_step_norm,1.517687e+01,1.321191,1.342933,1.216133e+00,25.657434
7,theta_step_norm,1.455313e+01,0.772899,2.851629,5.600271e-01,19.319265

--------------------------------------------------------------------------------
RESULT SUMMARY: G42
--------------------------------------------------------------------------------
historical_best: 2481.0

V1:
v1_best: 2381.0
v1_gap: 100.0
v1_percent_accuracy: 95.96936719064894

V2:
v2_best: 2394.0
v2_gap: 87.0
v2_percent_accuracy: 96.49334945586457
v2_best_step: 1272
v2_best_replica: 21

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 23.903892993927002

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/logs/G42_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/best_spins/G42_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/partial_group_results.csv

================================================================================
RUN GROUP COMPLETE
================================================================================
run_group: small_4_6
graphs: 21

Group results:

,run_group,partition,instance,graph_type,storage_mode,nodes,edges,n_steps,replicas,lr,...,final_best,final_gap,final_percent_accuracy,best_step_success_count,best_step_success_probability,ever_success_count,ever_success_probability,final_success_count,final_success_probability,v2_runtime_sec
0,small_4_6,4,G22,random,dense,2000,19990,2000,128,0.03,...,13294.0,65.0,99.513437,0,0.0,0,0.0,0,0.0,25.044713
1,small_4_6,4,G23,random,dense,2000,19990,2000,128,0.03,...,13295.0,49.0,99.632794,0,0.0,0,0.0,0,0.0,27.267495
2,small_4_6,4,G24,random,dense,2000,19990,2000,128,0.03,...,13283.0,54.0,99.595111,0,0.0,0,0.0,0,0.0,24.199018
3,small_4_6,4,G25,random,dense,2000,19990,2000,128,0.03,...,13281.0,59.0,99.557721,0,0.0,0,0.0,0,0.0,25.799486
4,small_4_6,4,G26,random,dense,2000,19990,2000,128,0.03,...,13277.0,51.0,99.617347,0,0.0,0,0.0,0,0.0,25.166671
5,small_4_6,4,G27,random,dense,2000,19990,2000,128,0.03,...,3277.0,64.0,98.084406,0,0.0,0,0.0,0,0.0,25.130726
6,small_4_6,4,G28,random,dense,2000,19990,2000,128,0.03,...,3251.0,47.0,98.574894,0,0.0,0,0.0,0,0.0,24.549876
7,small_4_6,4,G29,random,dense,2000,19990,2000,128,0.03,...,3363.0,42.0,98.766520,0,0.0,0,0.0,0,0.0,25.460381
8,small_4_6,4,G30,random,dense,2000,19990,2000,128,0.03,...,3364.0,49.0,98.564313,0,0.0,0,0.0,0,0.0,24.230939
9,small_4_6,4,G31,random,dense,2000,19990,2000,128,0.03,...,3265.0,45.0,98.640483,0,0.0,0,0.0,0,0.0,24.584395
10,small_4_6,5,G32,toroidal,dense,2000,4000,2000,128,0.03,...,1386.0,24.0,98.297872,0,0.0,0,0.0,0,0.0,27.172721
11,small_4_6,5,G33,toroidal,dense,2000,4000,2000,128,0.03,...,1366.0,16.0,98.842258,0,0.0,0,0.0,0,0.0,26.464084
12,small_4_6,5,G34,toroidal,dense,2000,4000,2000,128,0.03,...,1370.0,14.0,98.988439,0,0.0,0,0.0,0,0.0,24.358372
13,small_4_6,6,G35,plain,dense,2000,11778,2000,128,0.03,...,7616.0,71.0,99.076363,0,0.0,0,0.0,0,0.0,24.133267
14,small_4_6,6,G36,plain,dense,2000,11766,2000,128,0.03,...,7602.0,78.0,98.984375,0,0.0,0,0.0,0,0.0,24.666634
15,small_4_6,6,G37,plain,dense,2000,11785,2000,128,0.03,...,7615.0,76.0,99.011832,0,0.0,0,0.0,0,0.0,24.918984
16,small_4_6,6,G38,plain,dense,2000,11779,2000,128,0.03,...,7624.0,64.0,99.167534,0,0.0,0,0.0,0,0.0,24.463584
17,small_4_6,6,G39,plain,dense,2000,11778,2000,128,0.03,...,2331.0,77.0,96.802326,0,0.0,0,0.0,0,0.0,24.441082
18,small_4_6,6,G40,plain,dense,2000,11766,2000,128,0.03,...,2328.0,72.0,97.000000,0,0.0,0,0.0,0,0.0,24.113386
19,small_4_6,6,G41,plain,dense,2000,11785,2000,128,0.03,...,2311.0,94.0,96.091476,0,0.0,0,0.0,0,0.0,24.930433
20,small_4_6,6,G42,plain,dense,2000,11779,2000,128,0.03,...,2394.0,87.0,96.493349,0,0.0,0,0.0,0,0.0,23.903893

Compact group results:

,instance,historical_best,v1_best,v1_gap,v1_percent_accuracy,v2_best,v2_gap,v2_percent_accuracy,v2_best_step,v2_best_replica,ever_success_count,ever_success_probability,final_best,final_gap,final_percent_accuracy,final_success_count,final_success_probability,v2_runtime_sec
0,G22,13359.0,13312.0,47.0,99.648177,13294.0,65.0,99.513437,1099,99,0,0.0,13294.0,65.0,99.513437,0,0.0,25.044713
1,G23,13344.0,13303.0,41.0,99.692746,13295.0,49.0,99.632794,768,9,0,0.0,13295.0,49.0,99.632794,0,0.0,27.267495
2,G24,13337.0,13290.0,47.0,99.647597,13283.0,54.0,99.595111,685,11,0,0.0,13283.0,54.0,99.595111,0,0.0,24.199018
3,G25,13340.0,13284.0,56.0,99.580210,13281.0,59.0,99.557721,989,0,0,0.0,13281.0,59.0,99.557721,0,0.0,25.799486
4,G26,13328.0,13270.0,58.0,99.564826,13277.0,51.0,99.617347,972,26,0,0.0,13277.0,51.0,99.617347,0,0.0,25.166671
5,G27,3341.0,3310.0,31.0,99.072134,3277.0,64.0,98.084406,850,124,0,0.0,3277.0,64.0,98.084406,0,0.0,25.130726
6,G28,3298.0,3275.0,23.0,99.302608,3251.0,47.0,98.574894,486,85,0,0.0,3251.0,47.0,98.574894,0,0.0,24.549876
7,G29,3405.0,3351.0,54.0,98.414097,3363.0,42.0,98.766520,593,74,0,0.0,3363.0,42.0,98.766520,0,0.0,25.460381
8,G30,3413.0,3367.0,46.0,98.652212,3364.0,49.0,98.564313,1225,40,0,0.0,3364.0,49.0,98.564313,0,0.0,24.230939
9,G31,3310.0,3282.0,28.0,99.154079,3265.0,45.0,98.640483,555,20,0,0.0,3265.0,45.0,98.640483,0,0.0,24.584395
10,G32,1410.0,1388.0,22.0,98.439716,1386.0,24.0,98.297872,166,28,0,0.0,1386.0,24.0,98.297872,0,0.0,27.172721
11,G33,1382.0,1364.0,18.0,98.697540,1366.0,16.0,98.842258,383,6,0,0.0,1366.0,16.0,98.842258,0,0.0,26.464084
12,G34,1384.0,1362.0,22.0,98.410405,1370.0,14.0,98.988439,456,123,0,0.0,1370.0,14.0,98.988439,0,0.0,24.358372
13,G35,7687.0,7612.0,75.0,99.024327,7616.0,71.0,99.076363,1558,59,0,0.0,7616.0,71.0,99.076363,0,0.0,24.133267
14,G36,7680.0,7599.0,81.0,98.945312,7602.0,78.0,98.984375,1343,108,0,0.0,7602.0,78.0,98.984375,0,0.0,24.666634
15,G37,7691.0,7619.0,72.0,99.063841,7615.0,76.0,99.011832,1040,60,0,0.0,7615.0,76.0,99.011832,0,0.0,24.918984
16,G38,7688.0,7616.0,72.0,99.063476,7624.0,64.0,99.167534,1066,102,0,0.0,7624.0,64.0,99.167534,0,0.0,24.463584
17,G39,2408.0,2336.0,72.0,97.009967,2331.0,77.0,96.802326,1220,13,0,0.0,2331.0,77.0,96.802326,0,0.0,24.441082
18,G40,2400.0,2296.0,104.0,95.666667,2328.0,72.0,97.000000,1190,3,0,0.0,2328.0,72.0,97.000000,0,0.0,24.113386
19,G41,2405.0,2289.0,116.0,95.176715,2311.0,94.0,96.091476,1087,6,0,0.0,2311.0,94.0,96.091476,0,0.0,24.930433
20,G42,2481.0,2381.0,100.0,95.969367,2394.0,87.0,96.493349,1272,21,0,0.0,2394.0,87.0,96.493349,0,0.0,23.903893

Saved group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/group_results.csv

Saved group logs:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_4_6/group_training_logs.csv

================================================================================
COMPACT GROUP RESULT
================================================================================

,instance,historical_best,v1_best,v1_gap,v1_percent_accuracy,v2_best,v2_gap,v2_percent_accuracy,v2_best_step,v2_best_replica,ever_success_count,ever_success_probability,final_best,final_gap,final_percent_accuracy,final_success_count,final_success_probability,v2_runtime_sec
0,G22,13359.0,13312.0,47.0,99.648177,13294.0,65.0,99.513437,1099,99,0,0.0,13294.0,65.0,99.513437,0,0.0,25.044713
1,G23,13344.0,13303.0,41.0,99.692746,13295.0,49.0,99.632794,768,9,0,0.0,13295.0,49.0,99.632794,0,0.0,27.267495
2,G24,13337.0,13290.0,47.0,99.647597,13283.0,54.0,99.595111,685,11,0,0.0,13283.0,54.0,99.595111,0,0.0,24.199018
3,G25,13340.0,13284.0,56.0,99.580210,13281.0,59.0,99.557721,989,0,0,0.0,13281.0,59.0,99.557721,0,0.0,25.799486
4,G26,13328.0,13270.0,58.0,99.564826,13277.0,51.0,99.617347,972,26,0,0.0,13277.0,51.0,99.617347,0,0.0,25.166671
5,G27,3341.0,3310.0,31.0,99.072134,3277.0,64.0,98.084406,850,124,0,0.0,3277.0,64.0,98.084406,0,0.0,25.130726
6,G28,3298.0,3275.0,23.0,99.302608,3251.0,47.0,98.574894,486,85,0,0.0,3251.0,47.0,98.574894,0,0.0,24.549876
7,G29,3405.0,3351.0,54.0,98.414097,3363.0,42.0,98.766520,593,74,0,0.0,3363.0,42.0,98.766520,0,0.0,25.460381
8,G30,3413.0,3367.0,46.0,98.652212,3364.0,49.0,98.564313,1225,40,0,0.0,3364.0,49.0,98.564313,0,0.0,24.230939
9,G31,3310.0,3282.0,28.0,99.154079,3265.0,45.0,98.640483,555,20,0,0.0,3265.0,45.0,98.640483,0,0.0,24.584395
10,G32,1410.0,1388.0,22.0,98.439716,1386.0,24.0,98.297872,166,28,0,0.0,1386.0,24.0,98.297872,0,0.0,27.172721
11,G33,1382.0,1364.0,18.0,98.697540,1366.0,16.0,98.842258,383,6,0,0.0,1366.0,16.0,98.842258,0,0.0,26.464084
12,G34,1384.0,1362.0,22.0,98.410405,1370.0,14.0,98.988439,456,123,0,0.0,1370.0,14.0,98.988439,0,0.0,24.358372
13,G35,7687.0,7612.0,75.0,99.024327,7616.0,71.0,99.076363,1558,59,0,0.0,7616.0,71.0,99.076363,0,0.0,24.133267
14,G36,7680.0,7599.0,81.0,98.945312,7602.0,78.0,98.984375,1343,108,0,0.0,7602.0,78.0,98.984375,0,0.0,24.666634
15,G37,7691.0,7619.0,72.0,99.063841,7615.0,76.0,99.011832,1040,60,0,0.0,7615.0,76.0,99.011832,0,0.0,24.918984
16,G38,7688.0,7616.0,72.0,99.063476,7624.0,64.0,99.167534,1066,102,0,0.0,7624.0,64.0,99.167534,0,0.0,24.463584
17,G39,2408.0,2336.0,72.0,97.009967,2331.0,77.0,96.802326,1220,13,0,0.0,2331.0,77.0,96.802326,0,0.0,24.441082
18,G40,2400.0,2296.0,104.0,95.666667,2328.0,72.0,97.000000,1190,3,0,0.0,2328.0,72.0,97.000000,0,0.0,24.113386
19,G41,2405.0,2289.0,116.0,95.176715,2311.0,94.0,96.091476,1087,6,0,0.0,2311.0,94.0,96.091476,0,0.0,24.930433
20,G42,2481.0,2381.0,100.0,95.969367,2394.0,87.0,96.493349,1272,21,0,0.0,2394.0,87.0,96.493349,0,0.0,23.903893

In [96]:
print("\nGroup summary:")
print("graphs:", len(group_results_df))
print("mean v1 accuracy %:", float(group_results_df["v1_percent_accuracy"].mean()))
print("mean v2 accuracy %:", float(group_results_df["v2_percent_accuracy"].mean()))
print("v1 gap-zero count:", int((group_results_df["v1_gap"] == 0).sum()))
print("v2 gap-zero count:", int((group_results_df["v2_gap"] == 0).sum()))
print("total v2 runtime sec:", float(group_results_df["v2_runtime_sec"].sum()))

Group summary:
graphs: 21
mean v1 accuracy %: 98.48552463605397
mean v2 accuracy %: 98.53823093267309
v1 gap-zero count: 0
v2 gap-zero count: 0
total v2 runtime sec: 525.0001404285431

In [99]:
# ============================================================
# Quick inspection: where did V2 improve over V1?
# ============================================================

inspection_df = group_results_df[
    [
        "instance",
        "historical_best",
        "v1_best",
        "v1_gap",
        "v1_percent_accuracy",
        "v2_best",
        "v2_gap",
        "v2_percent_accuracy",
        "v2_best_step",
        "ever_success_count",
        "ever_success_probability",
        "final_best",
        "final_gap",
        "final_percent_accuracy",
    ]
].copy()

inspection_df["gap_improvement"] = (
    inspection_df["v1_gap"] - inspection_df["v2_gap"]
)

inspection_df["accuracy_improvement"] = (
    inspection_df["v2_percent_accuracy"] - inspection_df["v1_percent_accuracy"]
)

inspection_df = inspection_df.sort_values(
    "gap_improvement",
    ascending=False,
).reset_index(drop=True)

print("=" * 80)
print("V2 IMPROVEMENT INSPECTION")
print("=" * 80)

display(inspection_df)

print("\nSummary:")
print("graphs:", len(inspection_df))
print("improved gap count:", int((inspection_df["gap_improvement"] > 0).sum()))
print("same gap count    :", int((inspection_df["gap_improvement"] == 0).sum()))
print("worse gap count   :", int((inspection_df["gap_improvement"] < 0).sum()))

print("\nGap improvement:")
print("mean:", float(inspection_df["gap_improvement"].mean()))
print("min :", float(inspection_df["gap_improvement"].min()))
print("max :", float(inspection_df["gap_improvement"].max()))

print("\nAccuracy improvement:")
print("mean:", float(inspection_df["accuracy_improvement"].mean()))
print("min :", float(inspection_df["accuracy_improvement"].min()))
print("max :", float(inspection_df["accuracy_improvement"].max()))

print("\nClosest V2 gaps:")
display(
    inspection_df.sort_values("v2_gap")[
        [
            "instance",
            "historical_best",
            "v2_best",
            "v2_gap",
            "v2_percent_accuracy",
            "v2_best_step",
            "ever_success_count",
            "final_gap",
        ]
    ].head(10)
)

================================================================================
V2 IMPROVEMENT INSPECTION
================================================================================

,instance,historical_best,v1_best,v1_gap,v1_percent_accuracy,v2_best,v2_gap,v2_percent_accuracy,v2_best_step,ever_success_count,ever_success_probability,final_best,final_gap,final_percent_accuracy,gap_improvement,accuracy_improvement
0,G40,2400.0,2296.0,104.0,95.666667,2328.0,72.0,97.000000,1190,0,0.0,2328.0,72.0,97.000000,32.0,1.333333
1,G41,2405.0,2289.0,116.0,95.176715,2311.0,94.0,96.091476,1087,0,0.0,2311.0,94.0,96.091476,22.0,0.914761
2,G42,2481.0,2381.0,100.0,95.969367,2394.0,87.0,96.493349,1272,0,0.0,2394.0,87.0,96.493349,13.0,0.523982
3,G29,3405.0,3351.0,54.0,98.414097,3363.0,42.0,98.766520,593,0,0.0,3363.0,42.0,98.766520,12.0,0.352423
4,G38,7688.0,7616.0,72.0,99.063476,7624.0,64.0,99.167534,1066,0,0.0,7624.0,64.0,99.167534,8.0,0.104058
5,G34,1384.0,1362.0,22.0,98.410405,1370.0,14.0,98.988439,456,0,0.0,1370.0,14.0,98.988439,8.0,0.578035
6,G26,13328.0,13270.0,58.0,99.564826,13277.0,51.0,99.617347,972,0,0.0,13277.0,51.0,99.617347,7.0,0.052521
7,G35,7687.0,7612.0,75.0,99.024327,7616.0,71.0,99.076363,1558,0,0.0,7616.0,71.0,99.076363,4.0,0.052036
8,G36,7680.0,7599.0,81.0,98.945312,7602.0,78.0,98.984375,1343,0,0.0,7602.0,78.0,98.984375,3.0,0.039062
9,G33,1382.0,1364.0,18.0,98.697540,1366.0,16.0,98.842258,383,0,0.0,1366.0,16.0,98.842258,2.0,0.144718
10,G32,1410.0,1388.0,22.0,98.439716,1386.0,24.0,98.297872,166,0,0.0,1386.0,24.0,98.297872,-2.0,-0.141844
11,G30,3413.0,3367.0,46.0,98.652212,3364.0,49.0,98.564313,1225,0,0.0,3364.0,49.0,98.564313,-3.0,-0.087899
12,G25,13340.0,13284.0,56.0,99.580210,13281.0,59.0,99.557721,989,0,0.0,13281.0,59.0,99.557721,-3.0,-0.022489
13,G37,7691.0,7619.0,72.0,99.063841,7615.0,76.0,99.011832,1040,0,0.0,7615.0,76.0,99.011832,-4.0,-0.052009
14,G39,2408.0,2336.0,72.0,97.009967,2331.0,77.0,96.802326,1220,0,0.0,2331.0,77.0,96.802326,-5.0,-0.207641
15,G24,13337.0,13290.0,47.0,99.647597,13283.0,54.0,99.595111,685,0,0.0,13283.0,54.0,99.595111,-7.0,-0.052486
16,G23,13344.0,13303.0,41.0,99.692746,13295.0,49.0,99.632794,768,0,0.0,13295.0,49.0,99.632794,-8.0,-0.059952
17,G31,3310.0,3282.0,28.0,99.154079,3265.0,45.0,98.640483,555,0,0.0,3265.0,45.0,98.640483,-17.0,-0.513595
18,G22,13359.0,13312.0,47.0,99.648177,13294.0,65.0,99.513437,1099,0,0.0,13294.0,65.0,99.513437,-18.0,-0.134741
19,G28,3298.0,3275.0,23.0,99.302608,3251.0,47.0,98.574894,486,0,0.0,3251.0,47.0,98.574894,-24.0,-0.727714
20,G27,3341.0,3310.0,31.0,99.072134,3277.0,64.0,98.084406,850,0,0.0,3277.0,64.0,98.084406,-33.0,-0.987728

Summary:
graphs: 21
improved gap count: 10
same gap count    : 0
worse gap count   : 11

Gap improvement:
mean: -0.6190476190476191
min : -33.0
max : 32.0

Accuracy improvement:
mean: 0.052706296619127055
min : -0.9877282250823214
max : 1.3333333333333144

Closest V2 gaps:

,instance,historical_best,v2_best,v2_gap,v2_percent_accuracy,v2_best_step,ever_success_count,final_gap
5,G34,1384.0,1370.0,14.0,98.988439,456,0,14.0
9,G33,1382.0,1366.0,16.0,98.842258,383,0,16.0
10,G32,1410.0,1386.0,24.0,98.297872,166,0,24.0
3,G29,3405.0,3363.0,42.0,98.766520,593,0,42.0
17,G31,3310.0,3265.0,45.0,98.640483,555,0,45.0
19,G28,3298.0,3251.0,47.0,98.574894,486,0,47.0
16,G23,13344.0,13295.0,49.0,99.632794,768,0,49.0
11,G30,3413.0,3364.0,49.0,98.564313,1225,0,49.0
6,G26,13328.0,13277.0,51.0,99.617347,972,0,51.0
15,G24,13337.0,13283.0,54.0,99.595111,685,0,54.0

# 2

In [100]:
# ============================================================
# Cell 10: Select run group and run QEFEM v2
# ============================================================

# ------------------------------------------------------------
# Choose run group here
# ------------------------------------------------------------
# 0 -> small_1_3   : G1-G21
# 1 -> small_4_6   : G22-G42
# 2 -> small_7_9   : G43-G54
# 3 -> big_10_12   : G55-G59
# 4 -> big_13_15   : G60-G64
# 5 -> big_16_18   : G65, G66, G67, G72
# 6 -> big_19_21   : G70, G77, G81

RUN_GROUP_INDEX = 2


# ------------------------------------------------------------
# Preview selected group
# ------------------------------------------------------------

selected_group_row = run_group_summary_df.iloc[RUN_GROUP_INDEX]

print("=" * 80)
print("SELECTED RUN GROUP")
print("=" * 80)

print("RUN_GROUP_INDEX:", RUN_GROUP_INDEX)
print("run_group:", selected_group_row["run_group"])
print("partitions:", selected_group_row["partitions"])
print("graphs_start:", selected_group_row["graphs_start"])
print("graphs_end:", selected_group_row["graphs_end"])
print("num_graphs:", selected_group_row["num_graphs"])
print("graph_types:", selected_group_row["graph_types"])
print("storage_modes:", selected_group_row["storage_modes"])
print("graphs:", selected_group_row["graphs"])


# ------------------------------------------------------------
# Run selected group
# ------------------------------------------------------------

group_results_df, group_logs_df = run_qefem_run_group(
    run_group_index=RUN_GROUP_INDEX
)


# ------------------------------------------------------------
# Final compact display
# ------------------------------------------------------------

compact_group_results_df = group_results_df[
    [
        "instance",
        "historical_best",
        "v1_best",
        "v1_gap",
        "v1_percent_accuracy",
        "v2_best",
        "v2_gap",
        "v2_percent_accuracy",
        "v2_best_step",
        "v2_best_replica",
        "ever_success_count",
        "ever_success_probability",
        "final_best",
        "final_gap",
        "final_percent_accuracy",
        "final_success_count",
        "final_success_probability",
        "v2_runtime_sec",
    ]
].copy()

print("\n" + "=" * 80)
print("COMPACT GROUP RESULT")
print("=" * 80)

display(compact_group_results_df)

================================================================================
SELECTED RUN GROUP
================================================================================
RUN_GROUP_INDEX: 2
run_group: small_7_9
partitions: [7, 8, 9]
graphs_start: G43
graphs_end: G54
num_graphs: 12
graph_types: ['plain', 'random', 'toroidal']
storage_modes: ['dense']
graphs: ['G43', 'G44', 'G45', 'G46', 'G47', 'G48', 'G49', 'G50', 'G51', 'G52', 'G53', 'G54']
================================================================================
RUNNING QEFEM V2 RUN GROUP
================================================================================
run_group_index: 2
run_group: small_7_9
graphs: ['G43', 'G44', 'G45', 'G46', 'G47', 'G48', 'G49', 'G50', 'G51', 'G52', 'G53', 'G54']
num graphs: 12

Output directory:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9

Selected benchmark rows:

,partition,instance,graph_type,storage_mode,nodes,edges,n_steps,replicas,lr,v1_best,historical_best,v1_gap,v1_percent_accuracy,v1_best_replica,v1_runtime_sec
0,7,G43,random,dense,1000,9990,1000,128,0.01,6652.0,6660.0,8.0,99.879880,59,21.302996
1,7,G44,random,dense,1000,9990,1000,128,0.01,6638.0,6650.0,12.0,99.819549,60,959.330520
2,7,G45,random,dense,1000,9990,1000,128,0.01,6633.0,6654.0,21.0,99.684400,59,22.633644
3,7,G46,random,dense,1000,9990,1000,128,0.01,6627.0,6649.0,22.0,99.669123,108,22.939234
4,7,G47,random,dense,1000,9990,1000,128,0.01,6638.0,6657.0,19.0,99.714586,79,22.381257
5,8,G48,toroidal,dense,3000,6000,1000,128,0.01,6000.0,6000.0,0.0,100.000000,81,38.435393
6,8,G49,toroidal,dense,3000,6000,1000,128,0.01,6000.0,6000.0,0.0,100.000000,126,35.400141
7,8,G50,toroidal,dense,3000,6000,1000,128,0.01,5852.0,5880.0,28.0,99.523810,50,16.298411
8,9,G51,plain,dense,1000,5909,1000,128,0.01,3819.0,3848.0,29.0,99.246362,107,21.421013
9,9,G52,plain,dense,1000,5916,1000,128,0.01,3825.0,3851.0,26.0,99.324851,96,21.412782
10,9,G53,plain,dense,1000,5914,1000,128,0.01,3828.0,3850.0,22.0,99.428571,27,20.958359
11,9,G54,plain,dense,1000,5916,1000,128,0.01,3820.0,3852.0,32.0,99.169263,21,21.496527

################################################################################
RUNNING G43 | dense | seed=7
################################################################################
G43 | step     1/2000 | best 5124.0 | acc 76.9369% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G43 | step    50/2000 | best 5349.0 | acc 80.3153% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G43 | step   100/2000 | best 6393.0 | acc 95.9910% | success 0/128 | gamma 0.95048 | |rz| 0.0071
G43 | step   150/2000 | best 6628.0 | acc 99.5195% | success 0/128 | gamma 0.92546 | |rz| 0.7610
G43 | step   200/2000 | best 6633.0 | acc 99.5946% | success 0/128 | gamma 0.90045 | |rz| 0.8362
G43 | step   250/2000 | best 6636.0 | acc 99.6396% | success 0/128 | gamma 0.87544 | |rz| 0.8558
G43 | step   300/2000 | best 6638.0 | acc 99.6697% | success 0/128 | gamma 0.85043 | |rz| 0.8672
G43 | step   350/2000 | best 6639.0 | acc 99.6847% | success 0/128 | gamma 0.82541 | |rz| 0.8758
G43 | step   400/2000 | best 6640.0 | acc 99.6997% | success 0/128 | gamma 0.80040 | |rz| 0.8829
G43 | step   450/2000 | best 6641.0 | acc 99.7147% | success 0/128 | gamma 0.77539 | |rz| 0.8894
G43 | step   500/2000 | best 6642.0 | acc 99.7297% | success 0/128 | gamma 0.75038 | |rz| 0.8953
G43 | step   550/2000 | best 6642.0 | acc 99.7297% | success 0/128 | gamma 0.72536 | |rz| 0.9009
G43 | step   600/2000 | best 6642.0 | acc 99.7297% | success 0/128 | gamma 0.70035 | |rz| 0.9063
G43 | step   650/2000 | best 6643.0 | acc 99.7447% | success 0/128 | gamma 0.67534 | |rz| 0.9114
G43 | step   700/2000 | best 6643.0 | acc 99.7447% | success 0/128 | gamma 0.65033 | |rz| 0.9162
G43 | step   750/2000 | best 6643.0 | acc 99.7447% | success 0/128 | gamma 0.62531 | |rz| 0.9209
G43 | step   800/2000 | best 6643.0 | acc 99.7447% | success 0/128 | gamma 0.60030 | |rz| 0.9254
G43 | step   850/2000 | best 6643.0 | acc 99.7447% | success 0/128 | gamma 0.57529 | |rz| 0.9297
G43 | step   900/2000 | best 6643.0 | acc 99.7447% | success 0/128 | gamma 0.55028 | |rz| 0.9339
G43 | step   950/2000 | best 6643.0 | acc 99.7447% | success 0/128 | gamma 0.52526 | |rz| 0.9380
G43 | step  1000/2000 | best 6643.0 | acc 99.7447% | success 0/128 | gamma 0.50025 | |rz| 0.9419
G43 | step  1050/2000 | best 6643.0 | acc 99.7447% | success 0/128 | gamma 0.47524 | |rz| 0.9456
G43 | step  1100/2000 | best 6643.0 | acc 99.7447% | success 0/128 | gamma 0.45023 | |rz| 0.9493
G43 | step  1150/2000 | best 6643.0 | acc 99.7447% | success 0/128 | gamma 0.42521 | |rz| 0.9527
G43 | step  1200/2000 | best 6643.0 | acc 99.7447% | success 0/128 | gamma 0.40020 | |rz| 0.9561
G43 | step  1250/2000 | best 6643.0 | acc 99.7447% | success 0/128 | gamma 0.37519 | |rz| 0.9593
G43 | step  1300/2000 | best 6643.0 | acc 99.7447% | success 0/128 | gamma 0.35018 | |rz| 0.9624
G43 | step  1350/2000 | best 6643.0 | acc 99.7447% | success 0/128 | gamma 0.32517 | |rz| 0.9654
G43 | step  1400/2000 | best 6643.0 | acc 99.7447% | success 0/128 | gamma 0.30034 | |rz| 0.9682
G43 | step  1450/2000 | best 6643.0 | acc 99.7447% | success 0/128 | gamma 0.27732 | |rz| 0.9706
G43 | step  1500/2000 | best 6643.0 | acc 99.7447% | success 0/128 | gamma 0.26252 | |rz| 0.9723
G43 | step  1550/2000 | best 6643.0 | acc 99.7447% | success 0/128 | gamma 0.26035 | |rz| 0.9731
G43 | step  1600/2000 | best 6643.0 | acc 99.7447% | success 0/128 | gamma 0.25010 | |rz| 0.9744
G43 | step  1650/2000 | best 6643.0 | acc 99.7447% | success 0/128 | gamma 0.21052 | |rz| 0.9774
G43 | step  1700/2000 | best 6643.0 | acc 99.7447% | success 0/128 | gamma 0.16261 | |rz| 0.9804
G43 | step  1750/2000 | best 6643.0 | acc 99.7447% | success 0/128 | gamma 0.12728 | |rz| 0.9821
G43 | step  1800/2000 | best 6643.0 | acc 99.7447% | success 0/128 | gamma 0.10025 | |rz| 0.9832
G43 | step  1850/2000 | best 6643.0 | acc 99.7447% | success 0/128 | gamma 0.07505 | |rz| 0.9841
G43 | step  1900/2000 | best 6643.0 | acc 99.7447% | success 0/128 | gamma 0.05003 | |rz| 0.9847
G43 | step  1950/2000 | best 6643.0 | acc 99.7447% | success 0/128 | gamma 0.02501 | |rz| 0.9853
G43 | step  2000/2000 | best 6643.0 | acc 99.7447% | success 0/128 | gamma 0.00000 | |rz| 0.9870

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G43
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644286e-05,0.000026,0.000011,1.081154e-05,0.001045
1,theta_grad_mean_abs,6.240314e-07,0.000002,0.000002,2.529353e-07,0.000379
2,raw_R_step_mean_abs,2.999592e-02,0.002254,0.001921,1.920898e-03,0.048873
3,theta_step_mean_abs,2.866315e-02,0.000325,0.000581,2.373284e-04,0.028663
4,raw_R_grad_norm,2.734904e-02,0.010053,0.004034,4.034272e-03,0.439811
5,theta_grad_norm,2.793409e-04,0.004831,0.003219,1.128929e-04,0.207432
6,raw_R_step_norm,1.073167e+01,0.857906,0.749412,7.494123e-01,17.485361
7,theta_step_norm,1.029810e+01,0.301260,0.875131,2.271137e-01,10.298101

--------------------------------------------------------------------------------
RESULT SUMMARY: G43
--------------------------------------------------------------------------------
historical_best: 6660.0

V1:
v1_best: 6652.0
v1_gap: 8.0
v1_percent_accuracy: 99.87987987987988

V2:
v2_best: 6643.0
v2_gap: 17.0
v2_percent_accuracy: 99.74474474474475
v2_best_step: 635
v2_best_replica: 107

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 17.52125072479248

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/logs/G43_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/best_spins/G43_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/partial_group_results.csv

################################################################################
RUNNING G44 | dense | seed=8
################################################################################
G44 | step     1/2000 | best 5075.0 | acc 76.3158% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G44 | step    50/2000 | best 5319.0 | acc 79.9850% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G44 | step   100/2000 | best 6385.0 | acc 96.0150% | success 0/128 | gamma 0.95048 | |rz| 0.0069
G44 | step   150/2000 | best 6615.0 | acc 99.4737% | success 0/128 | gamma 0.92546 | |rz| 0.7597
G44 | step   200/2000 | best 6631.0 | acc 99.7143% | success 0/128 | gamma 0.90045 | |rz| 0.8352
G44 | step   250/2000 | best 6633.0 | acc 99.7444% | success 0/128 | gamma 0.87544 | |rz| 0.8546
G44 | step   300/2000 | best 6633.0 | acc 99.7444% | success 0/128 | gamma 0.85043 | |rz| 0.8659
G44 | step   350/2000 | best 6633.0 | acc 99.7444% | success 0/128 | gamma 0.82541 | |rz| 0.8743
G44 | step   400/2000 | best 6633.0 | acc 99.7444% | success 0/128 | gamma 0.80040 | |rz| 0.8816
G44 | step   450/2000 | best 6633.0 | acc 99.7444% | success 0/128 | gamma 0.77539 | |rz| 0.8880
G44 | step   500/2000 | best 6633.0 | acc 99.7444% | success 0/128 | gamma 0.75038 | |rz| 0.8938
G44 | step   550/2000 | best 6635.0 | acc 99.7744% | success 0/128 | gamma 0.72536 | |rz| 0.8994
G44 | step   600/2000 | best 6635.0 | acc 99.7744% | success 0/128 | gamma 0.70035 | |rz| 0.9047
G44 | step   650/2000 | best 6635.0 | acc 99.7744% | success 0/128 | gamma 0.67534 | |rz| 0.9098
G44 | step   700/2000 | best 6635.0 | acc 99.7744% | success 0/128 | gamma 0.65033 | |rz| 0.9146
G44 | step   750/2000 | best 6635.0 | acc 99.7744% | success 0/128 | gamma 0.62531 | |rz| 0.9193
G44 | step   800/2000 | best 6635.0 | acc 99.7744% | success 0/128 | gamma 0.60030 | |rz| 0.9238
G44 | step   850/2000 | best 6635.0 | acc 99.7744% | success 0/128 | gamma 0.57529 | |rz| 0.9282
G44 | step   900/2000 | best 6635.0 | acc 99.7744% | success 0/128 | gamma 0.55028 | |rz| 0.9323
G44 | step   950/2000 | best 6635.0 | acc 99.7744% | success 0/128 | gamma 0.52526 | |rz| 0.9364
G44 | step  1000/2000 | best 6635.0 | acc 99.7744% | success 0/128 | gamma 0.50025 | |rz| 0.9403
G44 | step  1050/2000 | best 6635.0 | acc 99.7744% | success 0/128 | gamma 0.47524 | |rz| 0.9441
G44 | step  1100/2000 | best 6635.0 | acc 99.7744% | success 0/128 | gamma 0.45023 | |rz| 0.9478
G44 | step  1150/2000 | best 6635.0 | acc 99.7744% | success 0/128 | gamma 0.42521 | |rz| 0.9513
G44 | step  1200/2000 | best 6635.0 | acc 99.7744% | success 0/128 | gamma 0.40020 | |rz| 0.9546
G44 | step  1250/2000 | best 6635.0 | acc 99.7744% | success 0/128 | gamma 0.37519 | |rz| 0.9578
G44 | step  1300/2000 | best 6635.0 | acc 99.7744% | success 0/128 | gamma 0.35018 | |rz| 0.9609
G44 | step  1350/2000 | best 6635.0 | acc 99.7744% | success 0/128 | gamma 0.32517 | |rz| 0.9639
G44 | step  1400/2000 | best 6635.0 | acc 99.7744% | success 0/128 | gamma 0.30034 | |rz| 0.9666
G44 | step  1450/2000 | best 6635.0 | acc 99.7744% | success 0/128 | gamma 0.27732 | |rz| 0.9690
G44 | step  1500/2000 | best 6635.0 | acc 99.7744% | success 0/128 | gamma 0.26252 | |rz| 0.9707
G44 | step  1550/2000 | best 6635.0 | acc 99.7744% | success 0/128 | gamma 0.26035 | |rz| 0.9715
G44 | step  1600/2000 | best 6635.0 | acc 99.7744% | success 0/128 | gamma 0.25010 | |rz| 0.9728
G44 | step  1650/2000 | best 6635.0 | acc 99.7744% | success 0/128 | gamma 0.21052 | |rz| 0.9758
G44 | step  1700/2000 | best 6635.0 | acc 99.7744% | success 0/128 | gamma 0.16261 | |rz| 0.9787
G44 | step  1750/2000 | best 6635.0 | acc 99.7744% | success 0/128 | gamma 0.12728 | |rz| 0.9804
G44 | step  1800/2000 | best 6635.0 | acc 99.7744% | success 0/128 | gamma 0.10025 | |rz| 0.9815
G44 | step  1850/2000 | best 6635.0 | acc 99.7744% | success 0/128 | gamma 0.07505 | |rz| 0.9823
G44 | step  1900/2000 | best 6635.0 | acc 99.7744% | success 0/128 | gamma 0.05003 | |rz| 0.9829
G44 | step  1950/2000 | best 6635.0 | acc 99.7744% | success 0/128 | gamma 0.02501 | |rz| 0.9835
G44 | step  2000/2000 | best 6635.0 | acc 99.7744% | success 0/128 | gamma 0.00000 | |rz| 0.9854

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G44
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644291e-05,0.000026,0.000011,1.075418e-05,0.001041
1,theta_grad_mean_abs,6.260096e-07,0.000002,0.000002,2.534483e-07,0.000378
2,raw_R_step_mean_abs,2.999592e-02,0.002258,0.001916,1.916252e-03,0.048873
3,theta_step_mean_abs,2.864626e-02,0.000338,0.000604,2.271795e-04,0.028646
4,raw_R_grad_norm,2.734906e-02,0.010096,0.004015,4.014798e-03,0.438213
5,theta_grad_norm,2.806264e-04,0.003345,0.003144,1.132399e-04,0.207918
6,raw_R_step_norm,1.073167e+01,0.856909,0.747300,7.473001e-01,17.485228
7,theta_step_norm,1.029386e+01,0.430307,0.947931,2.342024e-01,10.293859

--------------------------------------------------------------------------------
RESULT SUMMARY: G44
--------------------------------------------------------------------------------
historical_best: 6650.0

V1:
v1_best: 6638.0
v1_gap: 12.0
v1_percent_accuracy: 99.81954887218043

V2:
v2_best: 6635.0
v2_gap: 15.0
v2_percent_accuracy: 99.77443609022556
v2_best_step: 520
v2_best_replica: 58

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 18.14807391166687

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/logs/G44_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/best_spins/G44_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/partial_group_results.csv

################################################################################
RUNNING G45 | dense | seed=9
################################################################################
G45 | step     1/2000 | best 5091.0 | acc 76.5104% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G45 | step    50/2000 | best 5346.0 | acc 80.3427% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G45 | step   100/2000 | best 6387.0 | acc 95.9874% | success 0/128 | gamma 0.95048 | |rz| 0.0072
G45 | step   150/2000 | best 6620.0 | acc 99.4890% | success 0/128 | gamma 0.92546 | |rz| 0.7608
G45 | step   200/2000 | best 6624.0 | acc 99.5491% | success 0/128 | gamma 0.90045 | |rz| 0.8365
G45 | step   250/2000 | best 6626.0 | acc 99.5792% | success 0/128 | gamma 0.87544 | |rz| 0.8560
G45 | step   300/2000 | best 6627.0 | acc 99.5942% | success 0/128 | gamma 0.85043 | |rz| 0.8671
G45 | step   350/2000 | best 6628.0 | acc 99.6093% | success 0/128 | gamma 0.82541 | |rz| 0.8756
G45 | step   400/2000 | best 6628.0 | acc 99.6093% | success 0/128 | gamma 0.80040 | |rz| 0.8827
G45 | step   450/2000 | best 6628.0 | acc 99.6093% | success 0/128 | gamma 0.77539 | |rz| 0.8891
G45 | step   500/2000 | best 6629.0 | acc 99.6243% | success 0/128 | gamma 0.75038 | |rz| 0.8950
G45 | step   550/2000 | best 6630.0 | acc 99.6393% | success 0/128 | gamma 0.72536 | |rz| 0.9006
G45 | step   600/2000 | best 6630.0 | acc 99.6393% | success 0/128 | gamma 0.70035 | |rz| 0.9059
G45 | step   650/2000 | best 6631.0 | acc 99.6543% | success 0/128 | gamma 0.67534 | |rz| 0.9109
G45 | step   700/2000 | best 6631.0 | acc 99.6543% | success 0/128 | gamma 0.65033 | |rz| 0.9158
G45 | step   750/2000 | best 6631.0 | acc 99.6543% | success 0/128 | gamma 0.62531 | |rz| 0.9204
G45 | step   800/2000 | best 6631.0 | acc 99.6543% | success 0/128 | gamma 0.60030 | |rz| 0.9249
G45 | step   850/2000 | best 6631.0 | acc 99.6543% | success 0/128 | gamma 0.57529 | |rz| 0.9292
G45 | step   900/2000 | best 6631.0 | acc 99.6543% | success 0/128 | gamma 0.55028 | |rz| 0.9334
G45 | step   950/2000 | best 6631.0 | acc 99.6543% | success 0/128 | gamma 0.52526 | |rz| 0.9374
G45 | step  1000/2000 | best 6631.0 | acc 99.6543% | success 0/128 | gamma 0.50025 | |rz| 0.9413
G45 | step  1050/2000 | best 6632.0 | acc 99.6694% | success 0/128 | gamma 0.47524 | |rz| 0.9451
G45 | step  1100/2000 | best 6632.0 | acc 99.6694% | success 0/128 | gamma 0.45023 | |rz| 0.9487
G45 | step  1150/2000 | best 6632.0 | acc 99.6694% | success 0/128 | gamma 0.42521 | |rz| 0.9522
G45 | step  1200/2000 | best 6632.0 | acc 99.6694% | success 0/128 | gamma 0.40020 | |rz| 0.9555
G45 | step  1250/2000 | best 6632.0 | acc 99.6694% | success 0/128 | gamma 0.37519 | |rz| 0.9587
G45 | step  1300/2000 | best 6632.0 | acc 99.6694% | success 0/128 | gamma 0.35018 | |rz| 0.9618
G45 | step  1350/2000 | best 6632.0 | acc 99.6694% | success 0/128 | gamma 0.32517 | |rz| 0.9648
G45 | step  1400/2000 | best 6633.0 | acc 99.6844% | success 0/128 | gamma 0.30034 | |rz| 0.9675
G45 | step  1450/2000 | best 6633.0 | acc 99.6844% | success 0/128 | gamma 0.27732 | |rz| 0.9699
G45 | step  1500/2000 | best 6633.0 | acc 99.6844% | success 0/128 | gamma 0.26252 | |rz| 0.9716
G45 | step  1550/2000 | best 6633.0 | acc 99.6844% | success 0/128 | gamma 0.26035 | |rz| 0.9723
G45 | step  1600/2000 | best 6633.0 | acc 99.6844% | success 0/128 | gamma 0.25010 | |rz| 0.9736
G45 | step  1650/2000 | best 6633.0 | acc 99.6844% | success 0/128 | gamma 0.21052 | |rz| 0.9766
G45 | step  1700/2000 | best 6633.0 | acc 99.6844% | success 0/128 | gamma 0.16261 | |rz| 0.9795
G45 | step  1750/2000 | best 6633.0 | acc 99.6844% | success 0/128 | gamma 0.12728 | |rz| 0.9812
G45 | step  1800/2000 | best 6633.0 | acc 99.6844% | success 0/128 | gamma 0.10025 | |rz| 0.9823
G45 | step  1850/2000 | best 6633.0 | acc 99.6844% | success 0/128 | gamma 0.07505 | |rz| 0.9831
G45 | step  1900/2000 | best 6633.0 | acc 99.6844% | success 0/128 | gamma 0.05003 | |rz| 0.9837
G45 | step  1950/2000 | best 6633.0 | acc 99.6844% | success 0/128 | gamma 0.02501 | |rz| 0.9843
G45 | step  2000/2000 | best 6633.0 | acc 99.6844% | success 0/128 | gamma 0.00000 | |rz| 0.9860

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G45
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644318e-05,0.000026,0.000011,1.077401e-05,0.001046
1,theta_grad_mean_abs,6.247430e-07,0.000002,0.000002,2.528756e-07,0.000378
2,raw_R_step_mean_abs,2.999592e-02,0.002249,0.001915,1.914541e-03,0.048873
3,theta_step_mean_abs,2.863879e-02,0.000322,0.000584,2.327305e-04,0.028639
4,raw_R_grad_norm,2.734916e-02,0.009936,0.004021,4.021323e-03,0.440165
5,theta_grad_norm,2.801337e-04,0.002090,0.003201,1.128267e-04,0.207945
6,raw_R_step_norm,1.073167e+01,0.837609,0.746244,7.462439e-01,17.485481
7,theta_step_norm,1.029207e+01,0.243497,0.882989,2.189657e-01,10.292071

--------------------------------------------------------------------------------
RESULT SUMMARY: G45
--------------------------------------------------------------------------------
historical_best: 6654.0

V1:
v1_best: 6633.0
v1_gap: 21.0
v1_percent_accuracy: 99.6844003606853

V2:
v2_best: 6633.0
v2_gap: 21.0
v2_percent_accuracy: 99.6844003606853
v2_best_step: 1395
v2_best_replica: 46

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 17.7753746509552

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/logs/G45_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/best_spins/G45_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/partial_group_results.csv

################################################################################
RUNNING G46 | dense | seed=10
################################################################################
G46 | step     1/2000 | best 5109.0 | acc 76.8386% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G46 | step    50/2000 | best 5339.0 | acc 80.2978% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G46 | step   100/2000 | best 6375.0 | acc 95.8791% | success 0/128 | gamma 0.95048 | |rz| 0.0070
G46 | step   150/2000 | best 6622.0 | acc 99.5939% | success 0/128 | gamma 0.92546 | |rz| 0.7610
G46 | step   200/2000 | best 6625.0 | acc 99.6390% | success 0/128 | gamma 0.90045 | |rz| 0.8360
G46 | step   250/2000 | best 6625.0 | acc 99.6390% | success 0/128 | gamma 0.87544 | |rz| 0.8557
G46 | step   300/2000 | best 6626.0 | acc 99.6541% | success 0/128 | gamma 0.85043 | |rz| 0.8667
G46 | step   350/2000 | best 6626.0 | acc 99.6541% | success 0/128 | gamma 0.82541 | |rz| 0.8751
G46 | step   400/2000 | best 6627.0 | acc 99.6691% | success 0/128 | gamma 0.80040 | |rz| 0.8822
G46 | step   450/2000 | best 6630.0 | acc 99.7142% | success 0/128 | gamma 0.77539 | |rz| 0.8886
G46 | step   500/2000 | best 6633.0 | acc 99.7594% | success 0/128 | gamma 0.75038 | |rz| 0.8946
G46 | step   550/2000 | best 6633.0 | acc 99.7594% | success 0/128 | gamma 0.72536 | |rz| 0.9001
G46 | step   600/2000 | best 6635.0 | acc 99.7894% | success 0/128 | gamma 0.70035 | |rz| 0.9055
G46 | step   650/2000 | best 6635.0 | acc 99.7894% | success 0/128 | gamma 0.67534 | |rz| 0.9106
G46 | step   700/2000 | best 6635.0 | acc 99.7894% | success 0/128 | gamma 0.65033 | |rz| 0.9155
G46 | step   750/2000 | best 6635.0 | acc 99.7894% | success 0/128 | gamma 0.62531 | |rz| 0.9201
G46 | step   800/2000 | best 6635.0 | acc 99.7894% | success 0/128 | gamma 0.60030 | |rz| 0.9246
G46 | step   850/2000 | best 6635.0 | acc 99.7894% | success 0/128 | gamma 0.57529 | |rz| 0.9290
G46 | step   900/2000 | best 6635.0 | acc 99.7894% | success 0/128 | gamma 0.55028 | |rz| 0.9331
G46 | step   950/2000 | best 6635.0 | acc 99.7894% | success 0/128 | gamma 0.52526 | |rz| 0.9372
G46 | step  1000/2000 | best 6635.0 | acc 99.7894% | success 0/128 | gamma 0.50025 | |rz| 0.9411
G46 | step  1050/2000 | best 6635.0 | acc 99.7894% | success 0/128 | gamma 0.47524 | |rz| 0.9449
G46 | step  1100/2000 | best 6635.0 | acc 99.7894% | success 0/128 | gamma 0.45023 | |rz| 0.9485
G46 | step  1150/2000 | best 6635.0 | acc 99.7894% | success 0/128 | gamma 0.42521 | |rz| 0.9520
G46 | step  1200/2000 | best 6635.0 | acc 99.7894% | success 0/128 | gamma 0.40020 | |rz| 0.9553
G46 | step  1250/2000 | best 6635.0 | acc 99.7894% | success 0/128 | gamma 0.37519 | |rz| 0.9586
G46 | step  1300/2000 | best 6635.0 | acc 99.7894% | success 0/128 | gamma 0.35018 | |rz| 0.9616
G46 | step  1350/2000 | best 6635.0 | acc 99.7894% | success 0/128 | gamma 0.32517 | |rz| 0.9646
G46 | step  1400/2000 | best 6635.0 | acc 99.7894% | success 0/128 | gamma 0.30034 | |rz| 0.9673
G46 | step  1450/2000 | best 6635.0 | acc 99.7894% | success 0/128 | gamma 0.27732 | |rz| 0.9698
G46 | step  1500/2000 | best 6635.0 | acc 99.7894% | success 0/128 | gamma 0.26252 | |rz| 0.9715
G46 | step  1550/2000 | best 6635.0 | acc 99.7894% | success 0/128 | gamma 0.26035 | |rz| 0.9722
G46 | step  1600/2000 | best 6635.0 | acc 99.7894% | success 0/128 | gamma 0.25010 | |rz| 0.9735
G46 | step  1650/2000 | best 6635.0 | acc 99.7894% | success 0/128 | gamma 0.21052 | |rz| 0.9765
G46 | step  1700/2000 | best 6635.0 | acc 99.7894% | success 0/128 | gamma 0.16261 | |rz| 0.9794
G46 | step  1750/2000 | best 6635.0 | acc 99.7894% | success 0/128 | gamma 0.12728 | |rz| 0.9812
G46 | step  1800/2000 | best 6635.0 | acc 99.7894% | success 0/128 | gamma 0.10025 | |rz| 0.9823
G46 | step  1850/2000 | best 6635.0 | acc 99.7894% | success 0/128 | gamma 0.07505 | |rz| 0.9831
G46 | step  1900/2000 | best 6635.0 | acc 99.7894% | success 0/128 | gamma 0.05003 | |rz| 0.9837
G46 | step  1950/2000 | best 6635.0 | acc 99.7894% | success 0/128 | gamma 0.02501 | |rz| 0.9843
G46 | step  2000/2000 | best 6635.0 | acc 99.7894% | success 0/128 | gamma 0.00000 | |rz| 0.9861

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G46
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644256e-05,0.000026,0.000011,1.076683e-05,0.001042
1,theta_grad_mean_abs,6.235475e-07,0.000002,0.000002,2.529952e-07,0.000378
2,raw_R_step_mean_abs,2.999592e-02,0.002255,0.001918,1.917770e-03,0.048873
3,theta_step_mean_abs,2.864783e-02,0.000318,0.000590,2.394608e-04,0.028648
4,raw_R_grad_norm,2.734893e-02,0.009985,0.004015,4.015032e-03,0.437675
5,theta_grad_norm,2.794101e-04,0.002089,0.003088,1.129948e-04,0.206479
6,raw_R_step_norm,1.073167e+01,0.858062,0.748191,7.481914e-01,17.485258
7,theta_step_norm,1.029335e+01,0.230052,0.906867,2.300523e-01,10.293354

--------------------------------------------------------------------------------
RESULT SUMMARY: G46
--------------------------------------------------------------------------------
historical_best: 6649.0

V1:
v1_best: 6627.0
v1_gap: 22.0
v1_percent_accuracy: 99.6691231764175

V2:
v2_best: 6635.0
v2_gap: 14.0
v2_percent_accuracy: 99.78944202135659
v2_best_step: 561
v2_best_replica: 81

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 17.709019899368286

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/logs/G46_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/best_spins/G46_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/partial_group_results.csv

################################################################################
RUNNING G47 | dense | seed=11
################################################################################
G47 | step     1/2000 | best 5080.0 | acc 76.3107% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G47 | step    50/2000 | best 5323.0 | acc 79.9609% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G47 | step   100/2000 | best 6388.0 | acc 95.9591% | success 0/128 | gamma 0.95048 | |rz| 0.0075
G47 | step   150/2000 | best 6626.0 | acc 99.5343% | success 0/128 | gamma 0.92546 | |rz| 0.7609
G47 | step   200/2000 | best 6648.0 | acc 99.8648% | success 0/128 | gamma 0.90045 | |rz| 0.8367
G47 | step   250/2000 | best 6648.0 | acc 99.8648% | success 0/128 | gamma 0.87544 | |rz| 0.8563
G47 | step   300/2000 | best 6648.0 | acc 99.8648% | success 0/128 | gamma 0.85043 | |rz| 0.8677
G47 | step   350/2000 | best 6648.0 | acc 99.8648% | success 0/128 | gamma 0.82541 | |rz| 0.8761
G47 | step   400/2000 | best 6648.0 | acc 99.8648% | success 0/128 | gamma 0.80040 | |rz| 0.8832
G47 | step   450/2000 | best 6648.0 | acc 99.8648% | success 0/128 | gamma 0.77539 | |rz| 0.8895
G47 | step   500/2000 | best 6649.0 | acc 99.8798% | success 0/128 | gamma 0.75038 | |rz| 0.8954
G47 | step   550/2000 | best 6649.0 | acc 99.8798% | success 0/128 | gamma 0.72536 | |rz| 0.9009
G47 | step   600/2000 | best 6649.0 | acc 99.8798% | success 0/128 | gamma 0.70035 | |rz| 0.9061
G47 | step   650/2000 | best 6649.0 | acc 99.8798% | success 0/128 | gamma 0.67534 | |rz| 0.9112
G47 | step   700/2000 | best 6649.0 | acc 99.8798% | success 0/128 | gamma 0.65033 | |rz| 0.9162
G47 | step   750/2000 | best 6649.0 | acc 99.8798% | success 0/128 | gamma 0.62531 | |rz| 0.9209
G47 | step   800/2000 | best 6649.0 | acc 99.8798% | success 0/128 | gamma 0.60030 | |rz| 0.9254
G47 | step   850/2000 | best 6649.0 | acc 99.8798% | success 0/128 | gamma 0.57529 | |rz| 0.9298
G47 | step   900/2000 | best 6649.0 | acc 99.8798% | success 0/128 | gamma 0.55028 | |rz| 0.9340
G47 | step   950/2000 | best 6649.0 | acc 99.8798% | success 0/128 | gamma 0.52526 | |rz| 0.9381
G47 | step  1000/2000 | best 6649.0 | acc 99.8798% | success 0/128 | gamma 0.50025 | |rz| 0.9421
G47 | step  1050/2000 | best 6649.0 | acc 99.8798% | success 0/128 | gamma 0.47524 | |rz| 0.9459
G47 | step  1100/2000 | best 6649.0 | acc 99.8798% | success 0/128 | gamma 0.45023 | |rz| 0.9495
G47 | step  1150/2000 | best 6649.0 | acc 99.8798% | success 0/128 | gamma 0.42521 | |rz| 0.9530
G47 | step  1200/2000 | best 6649.0 | acc 99.8798% | success 0/128 | gamma 0.40020 | |rz| 0.9563
G47 | step  1250/2000 | best 6649.0 | acc 99.8798% | success 0/128 | gamma 0.37519 | |rz| 0.9596
G47 | step  1300/2000 | best 6649.0 | acc 99.8798% | success 0/128 | gamma 0.35018 | |rz| 0.9626
G47 | step  1350/2000 | best 6649.0 | acc 99.8798% | success 0/128 | gamma 0.32517 | |rz| 0.9656
G47 | step  1400/2000 | best 6649.0 | acc 99.8798% | success 0/128 | gamma 0.30034 | |rz| 0.9683
G47 | step  1450/2000 | best 6649.0 | acc 99.8798% | success 0/128 | gamma 0.27732 | |rz| 0.9708
G47 | step  1500/2000 | best 6649.0 | acc 99.8798% | success 0/128 | gamma 0.26252 | |rz| 0.9725
G47 | step  1550/2000 | best 6649.0 | acc 99.8798% | success 0/128 | gamma 0.26035 | |rz| 0.9732
G47 | step  1600/2000 | best 6649.0 | acc 99.8798% | success 0/128 | gamma 0.25010 | |rz| 0.9745
G47 | step  1650/2000 | best 6649.0 | acc 99.8798% | success 0/128 | gamma 0.21052 | |rz| 0.9775
G47 | step  1700/2000 | best 6649.0 | acc 99.8798% | success 0/128 | gamma 0.16261 | |rz| 0.9805
G47 | step  1750/2000 | best 6649.0 | acc 99.8798% | success 0/128 | gamma 0.12728 | |rz| 0.9822
G47 | step  1800/2000 | best 6649.0 | acc 99.8798% | success 0/128 | gamma 0.10025 | |rz| 0.9833
G47 | step  1850/2000 | best 6649.0 | acc 99.8798% | success 0/128 | gamma 0.07505 | |rz| 0.9841
G47 | step  1900/2000 | best 6649.0 | acc 99.8798% | success 0/128 | gamma 0.05003 | |rz| 0.9848
G47 | step  1950/2000 | best 6649.0 | acc 99.8798% | success 0/128 | gamma 0.02501 | |rz| 0.9853
G47 | step  2000/2000 | best 6649.0 | acc 99.8798% | success 0/128 | gamma 0.00000 | |rz| 0.9871

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G47
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644289e-05,0.000026,0.000011,1.082802e-05,0.001047
1,theta_grad_mean_abs,6.228116e-07,0.000002,0.000002,2.525692e-07,0.000381
2,raw_R_step_mean_abs,2.999592e-02,0.002262,0.001918,1.917744e-03,0.048873
3,theta_step_mean_abs,2.864280e-02,0.000345,0.000577,2.313699e-04,0.028643
4,raw_R_grad_norm,2.734905e-02,0.010139,0.004042,4.042167e-03,0.440390
5,theta_grad_norm,2.794250e-04,0.006519,0.003202,1.128801e-04,0.209529
6,raw_R_step_norm,1.073167e+01,0.860771,0.747841,7.478411e-01,17.485357
7,theta_step_norm,1.029208e+01,0.405735,0.867604,2.400529e-01,10.292081

--------------------------------------------------------------------------------
RESULT SUMMARY: G47
--------------------------------------------------------------------------------
historical_best: 6657.0

V1:
v1_best: 6638.0
v1_gap: 19.0
v1_percent_accuracy: 99.71458614991738

V2:
v2_best: 6649.0
v2_gap: 8.0
v2_percent_accuracy: 99.87982574733364
v2_best_step: 461
v2_best_replica: 112

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 17.38189196586609

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/logs/G47_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/best_spins/G47_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/partial_group_results.csv

################################################################################
RUNNING G48 | dense | seed=12
################################################################################
G48 | step     1/2000 | best 3076.0 | acc 51.2667% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G48 | step    50/2000 | best 3254.0 | acc 54.2333% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G48 | step   100/2000 | best 3268.0 | acc 54.4667% | success 0/128 | gamma 0.95048 | |rz| 0.0010
G48 | step   150/2000 | best 6070.0 | acc 101.1667% | success 0/128 | gamma 0.92546 | |rz| 0.5382
G48 | step   200/2000 | best 6070.0 | acc 101.1667% | success 0/128 | gamma 0.90045 | |rz| 0.7287
G48 | step   250/2000 | best 6070.0 | acc 101.1667% | success 0/128 | gamma 0.87544 | |rz| 0.7720
G48 | step   300/2000 | best 6070.0 | acc 101.1667% | success 0/128 | gamma 0.85043 | |rz| 0.7959
G48 | step   350/2000 | best 6070.0 | acc 101.1667% | success 0/128 | gamma 0.82541 | |rz| 0.8142
G48 | step   400/2000 | best 6070.0 | acc 101.1667% | success 1/128 | gamma 0.80040 | |rz| 0.8298
G48 | step   450/2000 | best 6070.0 | acc 101.1667% | success 1/128 | gamma 0.77539 | |rz| 0.8436
G48 | step   500/2000 | best 6070.0 | acc 101.1667% | success 1/128 | gamma 0.75038 | |rz| 0.8561
G48 | step   550/2000 | best 6070.0 | acc 101.1667% | success 2/128 | gamma 0.72536 | |rz| 0.8677
G48 | step   600/2000 | best 6070.0 | acc 101.1667% | success 2/128 | gamma 0.70035 | |rz| 0.8783
G48 | step   650/2000 | best 6070.0 | acc 101.1667% | success 2/128 | gamma 0.67534 | |rz| 0.8882
G48 | step   700/2000 | best 6070.0 | acc 101.1667% | success 3/128 | gamma 0.65033 | |rz| 0.8973
G48 | step   750/2000 | best 6070.0 | acc 101.1667% | success 4/128 | gamma 0.62531 | |rz| 0.9058
G48 | step   800/2000 | best 6070.0 | acc 101.1667% | success 4/128 | gamma 0.60030 | |rz| 0.9135
G48 | step   850/2000 | best 6070.0 | acc 101.1667% | success 4/128 | gamma 0.57529 | |rz| 0.9208
G48 | step   900/2000 | best 6070.0 | acc 101.1667% | success 5/128 | gamma 0.55028 | |rz| 0.9275
G48 | step   950/2000 | best 6070.0 | acc 101.1667% | success 6/128 | gamma 0.52526 | |rz| 0.9337
G48 | step  1000/2000 | best 6070.0 | acc 101.1667% | success 7/128 | gamma 0.50025 | |rz| 0.9394
G48 | step  1050/2000 | best 6070.0 | acc 101.1667% | success 7/128 | gamma 0.47524 | |rz| 0.9448
G48 | step  1100/2000 | best 6070.0 | acc 101.1667% | success 8/128 | gamma 0.45023 | |rz| 0.9497
G48 | step  1150/2000 | best 6070.0 | acc 101.1667% | success 9/128 | gamma 0.42521 | |rz| 0.9543
G48 | step  1200/2000 | best 6070.0 | acc 101.1667% | success 9/128 | gamma 0.40020 | |rz| 0.9585
G48 | step  1250/2000 | best 6070.0 | acc 101.1667% | success 9/128 | gamma 0.37519 | |rz| 0.9624
G48 | step  1300/2000 | best 6070.0 | acc 101.1667% | success 10/128 | gamma 0.35018 | |rz| 0.9660
G48 | step  1350/2000 | best 6070.0 | acc 101.1667% | success 10/128 | gamma 0.32517 | |rz| 0.9693
G48 | step  1400/2000 | best 6070.0 | acc 101.1667% | success 12/128 | gamma 0.30034 | |rz| 0.9723
G48 | step  1450/2000 | best 6070.0 | acc 101.1667% | success 12/128 | gamma 0.27732 | |rz| 0.9749
G48 | step  1500/2000 | best 6070.0 | acc 101.1667% | success 12/128 | gamma 0.26252 | |rz| 0.9765
G48 | step  1550/2000 | best 6070.0 | acc 101.1667% | success 12/128 | gamma 0.26035 | |rz| 0.9770
G48 | step  1600/2000 | best 6070.0 | acc 101.1667% | success 12/128 | gamma 0.25010 | |rz| 0.9782
G48 | step  1650/2000 | best 6070.0 | acc 101.1667% | success 12/128 | gamma 0.21052 | |rz| 0.9812
G48 | step  1700/2000 | best 6070.0 | acc 101.1667% | success 12/128 | gamma 0.16261 | |rz| 0.9839
G48 | step  1750/2000 | best 6070.0 | acc 101.1667% | success 12/128 | gamma 0.12728 | |rz| 0.9854
G48 | step  1800/2000 | best 6070.0 | acc 101.1667% | success 12/128 | gamma 0.10025 | |rz| 0.9864
G48 | step  1850/2000 | best 6070.0 | acc 101.1667% | success 12/128 | gamma 0.07505 | |rz| 0.9871
G48 | step  1900/2000 | best 6070.0 | acc 101.1667% | success 12/128 | gamma 0.05003 | |rz| 0.9876
G48 | step  1950/2000 | best 6070.0 | acc 101.1667% | success 12/128 | gamma 0.02501 | |rz| 0.9881
G48 | step  2000/2000 | best 6070.0 | acc 101.1667% | success 12/128 | gamma 0.00000 | |rz| 0.9890

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G48
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644278e-05,0.000022,0.000008,7.653025e-06,0.000933
1,theta_grad_mean_abs,6.245209e-07,0.000002,0.000001,2.605263e-07,0.000311
2,raw_R_step_mean_abs,2.999592e-02,0.003327,0.002282,2.282209e-03,0.048871
3,theta_step_mean_abs,2.864933e-02,0.000543,0.000470,2.260996e-04,0.028649
4,raw_R_grad_norm,4.736988e-02,0.015531,0.004824,4.823989e-03,0.578117
5,theta_grad_norm,4.847535e-04,0.016981,0.003382,1.913261e-04,0.220860
6,raw_R_step_norm,1.858779e+01,2.327992,1.440379,1.440379e+00,30.284536
7,theta_step_norm,1.783022e+01,1.570325,0.892732,4.385811e-01,17.830225

--------------------------------------------------------------------------------
RESULT SUMMARY: G48
--------------------------------------------------------------------------------
historical_best: 6000.0

V1:
v1_best: 6000.0
v1_gap: 0.0
v1_percent_accuracy: 100.0

V2:
v2_best: 6070.0
v2_gap: -70.0
v2_percent_accuracy: 101.16666666666667
v2_best_step: 124
v2_best_replica: 29

Replica success:
ever_success_count: 18
ever_success_probability: 0.140625
best_step_success_count: 10
best_step_success_probability: 0.078125
final_success_count: 12
final_success_probability: 0.09375

Runtime:
v2_runtime_sec: 37.557827949523926

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/logs/G48_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/best_spins/G48_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/partial_group_results.csv

################################################################################
RUNNING G49 | dense | seed=13
################################################################################
G49 | step     1/2000 | best 3074.0 | acc 51.2333% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G49 | step    50/2000 | best 3290.0 | acc 54.8333% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G49 | step   100/2000 | best 3290.0 | acc 54.8333% | success 0/128 | gamma 0.95048 | |rz| 0.0010
G49 | step   150/2000 | best 5894.0 | acc 98.2333% | success 0/128 | gamma 0.92546 | |rz| 0.5374
G49 | step   200/2000 | best 5914.0 | acc 98.5667% | success 0/128 | gamma 0.90045 | |rz| 0.7275
G49 | step   250/2000 | best 5920.0 | acc 98.6667% | success 0/128 | gamma 0.87544 | |rz| 0.7711
G49 | step   300/2000 | best 5920.0 | acc 98.6667% | success 0/128 | gamma 0.85043 | |rz| 0.7954
G49 | step   350/2000 | best 5924.0 | acc 98.7333% | success 0/128 | gamma 0.82541 | |rz| 0.8140
G49 | step   400/2000 | best 5944.0 | acc 99.0667% | success 0/128 | gamma 0.80040 | |rz| 0.8298
G49 | step   450/2000 | best 5984.0 | acc 99.7333% | success 0/128 | gamma 0.77539 | |rz| 0.8441
G49 | step   500/2000 | best 6000.0 | acc 100.0000% | success 1/128 | gamma 0.75038 | |rz| 0.8572
G49 | step   550/2000 | best 6000.0 | acc 100.0000% | success 1/128 | gamma 0.72536 | |rz| 0.8691
G49 | step   600/2000 | best 6000.0 | acc 100.0000% | success 1/128 | gamma 0.70035 | |rz| 0.8802
G49 | step   650/2000 | best 6000.0 | acc 100.0000% | success 1/128 | gamma 0.67534 | |rz| 0.8905
G49 | step   700/2000 | best 6000.0 | acc 100.0000% | success 1/128 | gamma 0.65033 | |rz| 0.8999
G49 | step   750/2000 | best 6000.0 | acc 100.0000% | success 1/128 | gamma 0.62531 | |rz| 0.9086
G49 | step   800/2000 | best 6000.0 | acc 100.0000% | success 2/128 | gamma 0.60030 | |rz| 0.9167
G49 | step   850/2000 | best 6000.0 | acc 100.0000% | success 2/128 | gamma 0.57529 | |rz| 0.9243
G49 | step   900/2000 | best 6000.0 | acc 100.0000% | success 2/128 | gamma 0.55028 | |rz| 0.9313
G49 | step   950/2000 | best 6000.0 | acc 100.0000% | success 2/128 | gamma 0.52526 | |rz| 0.9377
G49 | step  1000/2000 | best 6000.0 | acc 100.0000% | success 3/128 | gamma 0.50025 | |rz| 0.9436
G49 | step  1050/2000 | best 6000.0 | acc 100.0000% | success 3/128 | gamma 0.47524 | |rz| 0.9490
G49 | step  1100/2000 | best 6000.0 | acc 100.0000% | success 3/128 | gamma 0.45023 | |rz| 0.9541
G49 | step  1150/2000 | best 6000.0 | acc 100.0000% | success 3/128 | gamma 0.42521 | |rz| 0.9588
G49 | step  1200/2000 | best 6000.0 | acc 100.0000% | success 4/128 | gamma 0.40020 | |rz| 0.9631
G49 | step  1250/2000 | best 6000.0 | acc 100.0000% | success 4/128 | gamma 0.37519 | |rz| 0.9671
G49 | step  1300/2000 | best 6000.0 | acc 100.0000% | success 4/128 | gamma 0.35018 | |rz| 0.9707
G49 | step  1350/2000 | best 6000.0 | acc 100.0000% | success 4/128 | gamma 0.32517 | |rz| 0.9740
G49 | step  1400/2000 | best 6000.0 | acc 100.0000% | success 4/128 | gamma 0.30034 | |rz| 0.9771
G49 | step  1450/2000 | best 6000.0 | acc 100.0000% | success 5/128 | gamma 0.27732 | |rz| 0.9796
G49 | step  1500/2000 | best 6000.0 | acc 100.0000% | success 6/128 | gamma 0.26252 | |rz| 0.9812
G49 | step  1550/2000 | best 6000.0 | acc 100.0000% | success 6/128 | gamma 0.26035 | |rz| 0.9818
G49 | step  1600/2000 | best 6000.0 | acc 100.0000% | success 6/128 | gamma 0.25010 | |rz| 0.9829
G49 | step  1650/2000 | best 6000.0 | acc 100.0000% | success 7/128 | gamma 0.21052 | |rz| 0.9859
G49 | step  1700/2000 | best 6000.0 | acc 100.0000% | success 7/128 | gamma 0.16261 | |rz| 0.9887
G49 | step  1750/2000 | best 6000.0 | acc 100.0000% | success 7/128 | gamma 0.12728 | |rz| 0.9903
G49 | step  1800/2000 | best 6000.0 | acc 100.0000% | success 7/128 | gamma 0.10025 | |rz| 0.9912
G49 | step  1850/2000 | best 6000.0 | acc 100.0000% | success 7/128 | gamma 0.07505 | |rz| 0.9920
G49 | step  1900/2000 | best 6000.0 | acc 100.0000% | success 7/128 | gamma 0.05003 | |rz| 0.9925
G49 | step  1950/2000 | best 6000.0 | acc 100.0000% | success 7/128 | gamma 0.02501 | |rz| 0.9929
G49 | step  2000/2000 | best 6000.0 | acc 100.0000% | success 7/128 | gamma 0.00000 | |rz| 0.9935

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G49
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644262e-05,0.000021,0.000008,7.665272e-06,0.000933
1,theta_grad_mean_abs,6.235563e-07,0.000003,0.000001,2.606029e-07,0.000308
2,raw_R_step_mean_abs,2.999592e-02,0.003319,0.002284,2.284137e-03,0.048871
3,theta_step_mean_abs,2.863901e-02,0.000567,0.000429,2.423802e-04,0.028639
4,raw_R_grad_norm,4.736979e-02,0.015815,0.004809,4.809020e-03,0.578118
5,theta_grad_norm,4.842959e-04,0.020008,0.003382,1.914442e-04,0.219892
6,raw_R_step_norm,1.858779e+01,2.357263,1.434521,1.434521e+00,30.284554
7,theta_step_norm,1.782549e+01,1.983388,0.682178,4.331356e-01,17.825493

--------------------------------------------------------------------------------
RESULT SUMMARY: G49
--------------------------------------------------------------------------------
historical_best: 6000.0

V1:
v1_best: 6000.0
v1_gap: 0.0
v1_percent_accuracy: 100.0

V2:
v2_best: 6000.0
v2_gap: 0.0
v2_percent_accuracy: 100.0
v2_best_step: 464
v2_best_replica: 14

Replica success:
ever_success_count: 7
ever_success_probability: 0.0546875
best_step_success_count: 1
best_step_success_probability: 0.0078125
final_success_count: 7
final_success_probability: 0.0546875

Runtime:
v2_runtime_sec: 37.35888481140137

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/logs/G49_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/best_spins/G49_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/partial_group_results.csv

################################################################################
RUNNING G50 | dense | seed=14
################################################################################
G50 | step     1/2000 | best 3078.0 | acc 52.3469% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G50 | step    50/2000 | best 3260.0 | acc 55.4422% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G50 | step   100/2000 | best 3288.0 | acc 55.9184% | success 0/128 | gamma 0.95048 | |rz| 0.0010
G50 | step   150/2000 | best 5812.0 | acc 98.8435% | success 0/128 | gamma 0.92546 | |rz| 0.5368
G50 | step   200/2000 | best 5826.0 | acc 99.0816% | success 0/128 | gamma 0.90045 | |rz| 0.7247
G50 | step   250/2000 | best 5830.0 | acc 99.1497% | success 0/128 | gamma 0.87544 | |rz| 0.7664
G50 | step   300/2000 | best 5834.0 | acc 99.2177% | success 0/128 | gamma 0.85043 | |rz| 0.7891
G50 | step   350/2000 | best 5836.0 | acc 99.2517% | success 0/128 | gamma 0.82541 | |rz| 0.8064
G50 | step   400/2000 | best 5836.0 | acc 99.2517% | success 0/128 | gamma 0.80040 | |rz| 0.8211
G50 | step   450/2000 | best 5838.0 | acc 99.2857% | success 0/128 | gamma 0.77539 | |rz| 0.8343
G50 | step   500/2000 | best 5840.0 | acc 99.3197% | success 0/128 | gamma 0.75038 | |rz| 0.8464
G50 | step   550/2000 | best 5842.0 | acc 99.3537% | success 0/128 | gamma 0.72536 | |rz| 0.8575
G50 | step   600/2000 | best 5842.0 | acc 99.3537% | success 0/128 | gamma 0.70035 | |rz| 0.8678
G50 | step   650/2000 | best 5842.0 | acc 99.3537% | success 0/128 | gamma 0.67534 | |rz| 0.8774
G50 | step   700/2000 | best 5844.0 | acc 99.3878% | success 0/128 | gamma 0.65033 | |rz| 0.8863
G50 | step   750/2000 | best 5844.0 | acc 99.3878% | success 0/128 | gamma 0.62531 | |rz| 0.8946
G50 | step   800/2000 | best 5844.0 | acc 99.3878% | success 0/128 | gamma 0.60030 | |rz| 0.9024
G50 | step   850/2000 | best 5846.0 | acc 99.4218% | success 0/128 | gamma 0.57529 | |rz| 0.9096
G50 | step   900/2000 | best 5846.0 | acc 99.4218% | success 0/128 | gamma 0.55028 | |rz| 0.9163
G50 | step   950/2000 | best 5848.0 | acc 99.4558% | success 0/128 | gamma 0.52526 | |rz| 0.9225
G50 | step  1000/2000 | best 5848.0 | acc 99.4558% | success 0/128 | gamma 0.50025 | |rz| 0.9283
G50 | step  1050/2000 | best 5848.0 | acc 99.4558% | success 0/128 | gamma 0.47524 | |rz| 0.9337
G50 | step  1100/2000 | best 5848.0 | acc 99.4558% | success 0/128 | gamma 0.45023 | |rz| 0.9387
G50 | step  1150/2000 | best 5848.0 | acc 99.4558% | success 0/128 | gamma 0.42521 | |rz| 0.9433
G50 | step  1200/2000 | best 5848.0 | acc 99.4558% | success 0/128 | gamma 0.40020 | |rz| 0.9477
G50 | step  1250/2000 | best 5848.0 | acc 99.4558% | success 0/128 | gamma 0.37519 | |rz| 0.9517
G50 | step  1300/2000 | best 5848.0 | acc 99.4558% | success 0/128 | gamma 0.35018 | |rz| 0.9554
G50 | step  1350/2000 | best 7310.2 | acc 124.3240% | success 0/128 | gamma 0.32517 | |rz| 0.9588
G50 | step  1400/2000 | best 7310.2 | acc 124.3240% | success 0/128 | gamma 0.30034 | |rz| 0.9620
G50 | step  1450/2000 | best 7310.2 | acc 124.3240% | success 0/128 | gamma 0.27732 | |rz| 0.9647
G50 | step  1500/2000 | best 7310.2 | acc 124.3240% | success 0/128 | gamma 0.26252 | |rz| 0.9664
G50 | step  1550/2000 | best 7310.2 | acc 124.3240% | success 0/128 | gamma 0.26035 | |rz| 0.9669
G50 | step  1600/2000 | best 7310.2 | acc 124.3240% | success 0/128 | gamma 0.25010 | |rz| 0.9682
G50 | step  1650/2000 | best 7310.2 | acc 124.3240% | success 0/128 | gamma 0.21052 | |rz| 0.9714
G50 | step  1700/2000 | best 7310.2 | acc 124.3240% | success 0/128 | gamma 0.16261 | |rz| 0.9743
G50 | step  1750/2000 | best 7310.2 | acc 124.3240% | success 0/128 | gamma 0.12728 | |rz| 0.9759
G50 | step  1800/2000 | best 7310.2 | acc 124.3240% | success 0/128 | gamma 0.10025 | |rz| 0.9768
G50 | step  1850/2000 | best 7310.2 | acc 124.3240% | success 0/128 | gamma 0.07505 | |rz| 0.9775
G50 | step  1900/2000 | best 7310.2 | acc 124.3240% | success 0/128 | gamma 0.05003 | |rz| 0.9781
G50 | step  1950/2000 | best 7310.2 | acc 124.3240% | success 0/128 | gamma 0.02501 | |rz| 0.9786
G50 | step  2000/2000 | best 7310.2 | acc 124.3240% | success 0/128 | gamma 0.00000 | |rz| 0.9806

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G50
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644280e-05,0.000020,0.000008,7.657038e-06,0.000933
1,theta_grad_mean_abs,6.242593e-07,0.000002,0.000002,2.601386e-07,0.000308
2,raw_R_step_mean_abs,2.999592e-02,0.003167,0.002303,2.303128e-03,0.048871
3,theta_step_mean_abs,2.864071e-02,0.000463,0.000614,2.049113e-04,0.028641
4,raw_R_grad_norm,4.736989e-02,0.013429,0.004864,4.863853e-03,0.578117
5,theta_grad_norm,4.848754e-04,0.005298,0.003649,1.911063e-04,0.219595
6,raw_R_step_norm,1.858779e+01,2.083019,1.468904,1.468904e+00,30.284534
7,theta_step_norm,1.782646e+01,0.741831,1.505042,4.334245e-01,17.826464

--------------------------------------------------------------------------------
RESULT SUMMARY: G50
--------------------------------------------------------------------------------
historical_best: 5880.0

V1:
v1_best: 5852.0
v1_gap: 28.0
v1_percent_accuracy: 99.52380952380952

V2:
v2_best: 7310.25
v2_gap: -1430.25
v2_percent_accuracy: 124.32397959183673
v2_best_step: 1341
v2_best_replica: 47

Replica success:
ever_success_count: 128
ever_success_probability: 1.0
best_step_success_count: 128
best_step_success_probability: 1.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 40.16161298751831

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/logs/G50_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/best_spins/G50_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/partial_group_results.csv

################################################################################
RUNNING G51 | dense | seed=15
################################################################################
G51 | step     1/2000 | best 3049.0 | acc 79.2360% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G51 | step    50/2000 | best 3149.0 | acc 81.8347% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G51 | step   100/2000 | best 3497.0 | acc 90.8784% | success 0/128 | gamma 0.95048 | |rz| 0.0059
G51 | step   150/2000 | best 3782.0 | acc 98.2848% | success 0/128 | gamma 0.92546 | |rz| 0.4862
G51 | step   200/2000 | best 3791.0 | acc 98.5187% | success 0/128 | gamma 0.90045 | |rz| 0.5684
G51 | step   250/2000 | best 3795.0 | acc 98.6227% | success 0/128 | gamma 0.87544 | |rz| 0.5954
G51 | step   300/2000 | best 3800.0 | acc 98.7526% | success 0/128 | gamma 0.85043 | |rz| 0.6146
G51 | step   350/2000 | best 3802.0 | acc 98.8046% | success 0/128 | gamma 0.82541 | |rz| 0.6316
G51 | step   400/2000 | best 3804.0 | acc 98.8565% | success 0/128 | gamma 0.80040 | |rz| 0.6476
G51 | step   450/2000 | best 3806.0 | acc 98.9085% | success 0/128 | gamma 0.77539 | |rz| 0.6630
G51 | step   500/2000 | best 3809.0 | acc 98.9865% | success 0/128 | gamma 0.75038 | |rz| 0.6780
G51 | step   550/2000 | best 3811.0 | acc 99.0385% | success 0/128 | gamma 0.72536 | |rz| 0.6927
G51 | step   600/2000 | best 3812.0 | acc 99.0644% | success 0/128 | gamma 0.70035 | |rz| 0.7072
G51 | step   650/2000 | best 3812.0 | acc 99.0644% | success 0/128 | gamma 0.67534 | |rz| 0.7215
G51 | step   700/2000 | best 3816.0 | acc 99.1684% | success 0/128 | gamma 0.65033 | |rz| 0.7355
G51 | step   750/2000 | best 3816.0 | acc 99.1684% | success 0/128 | gamma 0.62531 | |rz| 0.7492
G51 | step   800/2000 | best 3816.0 | acc 99.1684% | success 0/128 | gamma 0.60030 | |rz| 0.7626
G51 | step   850/2000 | best 3817.0 | acc 99.1944% | success 0/128 | gamma 0.57529 | |rz| 0.7757
G51 | step   900/2000 | best 3817.0 | acc 99.1944% | success 0/128 | gamma 0.55028 | |rz| 0.7883
G51 | step   950/2000 | best 3818.0 | acc 99.2204% | success 0/128 | gamma 0.52526 | |rz| 0.8006
G51 | step  1000/2000 | best 3818.0 | acc 99.2204% | success 0/128 | gamma 0.50025 | |rz| 0.8124
G51 | step  1050/2000 | best 3818.0 | acc 99.2204% | success 0/128 | gamma 0.47524 | |rz| 0.8238
G51 | step  1100/2000 | best 3818.0 | acc 99.2204% | success 0/128 | gamma 0.45023 | |rz| 0.8347
G51 | step  1150/2000 | best 3818.0 | acc 99.2204% | success 0/128 | gamma 0.42521 | |rz| 0.8451
G51 | step  1200/2000 | best 3818.0 | acc 99.2204% | success 0/128 | gamma 0.40020 | |rz| 0.8550
G51 | step  1250/2000 | best 3818.0 | acc 99.2204% | success 0/128 | gamma 0.37519 | |rz| 0.8645
G51 | step  1300/2000 | best 3818.0 | acc 99.2204% | success 0/128 | gamma 0.35018 | |rz| 0.8735
G51 | step  1350/2000 | best 3818.0 | acc 99.2204% | success 0/128 | gamma 0.32517 | |rz| 0.8821
G51 | step  1400/2000 | best 3818.0 | acc 99.2204% | success 0/128 | gamma 0.30034 | |rz| 0.8901
G51 | step  1450/2000 | best 3818.0 | acc 99.2204% | success 0/128 | gamma 0.27732 | |rz| 0.8970
G51 | step  1500/2000 | best 3818.0 | acc 99.2204% | success 0/128 | gamma 0.26252 | |rz| 0.9019
G51 | step  1550/2000 | best 3818.0 | acc 99.2204% | success 0/128 | gamma 0.26035 | |rz| 0.9042
G51 | step  1600/2000 | best 3818.0 | acc 99.2204% | success 0/128 | gamma 0.25010 | |rz| 0.9079
G51 | step  1650/2000 | best 3818.0 | acc 99.2204% | success 0/128 | gamma 0.21052 | |rz| 0.9159
G51 | step  1700/2000 | best 3818.0 | acc 99.2204% | success 0/128 | gamma 0.16261 | |rz| 0.9233
G51 | step  1750/2000 | best 3818.0 | acc 99.2204% | success 0/128 | gamma 0.12728 | |rz| 0.9274
G51 | step  1800/2000 | best 3818.0 | acc 99.2204% | success 0/128 | gamma 0.10025 | |rz| 0.9299
G51 | step  1850/2000 | best 3818.0 | acc 99.2204% | success 0/128 | gamma 0.07505 | |rz| 0.9319
G51 | step  1900/2000 | best 3818.0 | acc 99.2204% | success 0/128 | gamma 0.05003 | |rz| 0.9334
G51 | step  1950/2000 | best 3818.0 | acc 99.2204% | success 0/128 | gamma 0.02501 | |rz| 0.9348
G51 | step  2000/2000 | best 3818.0 | acc 99.2204% | success 0/128 | gamma 0.00000 | |rz| 0.9432

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G51
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644256e-05,0.000019,0.000009,9.283322e-06,0.000933
1,theta_grad_mean_abs,6.214735e-07,0.000004,0.000005,2.559189e-07,0.000079
2,raw_R_step_mean_abs,2.999592e-02,0.002659,0.002742,1.999695e-03,0.048875
3,theta_step_mean_abs,2.864089e-02,0.000828,0.002053,6.234416e-04,0.028641
4,raw_R_grad_norm,2.734893e-02,0.007857,0.003595,3.594853e-03,0.333992
5,theta_grad_norm,2.784621e-04,0.007548,0.004391,1.113599e-04,0.128690
6,raw_R_step_norm,1.073167e+01,1.040296,1.072847,8.465484e-01,17.485943
7,theta_step_norm,1.029205e+01,0.595215,2.115771,3.920645e-01,10.292050

--------------------------------------------------------------------------------
RESULT SUMMARY: G51
--------------------------------------------------------------------------------
historical_best: 3848.0

V1:
v1_best: 3819.0
v1_gap: 29.0
v1_percent_accuracy: 99.24636174636174

V2:
v2_best: 3818.0
v2_gap: 30.0
v2_percent_accuracy: 99.22037422037423
v2_best_step: 934
v2_best_replica: 49

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 16.340144872665405

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/logs/G51_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/best_spins/G51_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/partial_group_results.csv

################################################################################
RUNNING G52 | dense | seed=16
################################################################################
G52 | step     1/2000 | best 3057.0 | acc 79.3820% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G52 | step    50/2000 | best 3168.0 | acc 82.2643% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G52 | step   100/2000 | best 3497.0 | acc 90.8076% | success 0/128 | gamma 0.95048 | |rz| 0.0061
G52 | step   150/2000 | best 3783.0 | acc 98.2342% | success 0/128 | gamma 0.92546 | |rz| 0.4823
G52 | step   200/2000 | best 3793.0 | acc 98.4939% | success 0/128 | gamma 0.90045 | |rz| 0.5631
G52 | step   250/2000 | best 3800.0 | acc 98.6757% | success 0/128 | gamma 0.87544 | |rz| 0.5898
G52 | step   300/2000 | best 3804.0 | acc 98.7795% | success 0/128 | gamma 0.85043 | |rz| 0.6089
G52 | step   350/2000 | best 3808.0 | acc 98.8834% | success 0/128 | gamma 0.82541 | |rz| 0.6257
G52 | step   400/2000 | best 3810.0 | acc 98.9353% | success 0/128 | gamma 0.80040 | |rz| 0.6416
G52 | step   450/2000 | best 3817.0 | acc 99.1171% | success 0/128 | gamma 0.77539 | |rz| 0.6571
G52 | step   500/2000 | best 3819.0 | acc 99.1690% | success 0/128 | gamma 0.75038 | |rz| 0.6724
G52 | step   550/2000 | best 3820.0 | acc 99.1950% | success 0/128 | gamma 0.72536 | |rz| 0.6875
G52 | step   600/2000 | best 3822.0 | acc 99.2469% | success 0/128 | gamma 0.70035 | |rz| 0.7023
G52 | step   650/2000 | best 3824.0 | acc 99.2989% | success 0/128 | gamma 0.67534 | |rz| 0.7169
G52 | step   700/2000 | best 3824.0 | acc 99.2989% | success 0/128 | gamma 0.65033 | |rz| 0.7312
G52 | step   750/2000 | best 3825.0 | acc 99.3249% | success 0/128 | gamma 0.62531 | |rz| 0.7453
G52 | step   800/2000 | best 3827.0 | acc 99.3768% | success 0/128 | gamma 0.60030 | |rz| 0.7590
G52 | step   850/2000 | best 3828.0 | acc 99.4028% | success 0/128 | gamma 0.57529 | |rz| 0.7724
G52 | step   900/2000 | best 3829.0 | acc 99.4287% | success 0/128 | gamma 0.55028 | |rz| 0.7854
G52 | step   950/2000 | best 3829.0 | acc 99.4287% | success 0/128 | gamma 0.52526 | |rz| 0.7980
G52 | step  1000/2000 | best 3830.0 | acc 99.4547% | success 0/128 | gamma 0.50025 | |rz| 0.8102
G52 | step  1050/2000 | best 3830.0 | acc 99.4547% | success 0/128 | gamma 0.47524 | |rz| 0.8220
G52 | step  1100/2000 | best 3830.0 | acc 99.4547% | success 0/128 | gamma 0.45023 | |rz| 0.8331
G52 | step  1150/2000 | best 3830.0 | acc 99.4547% | success 0/128 | gamma 0.42521 | |rz| 0.8438
G52 | step  1200/2000 | best 3830.0 | acc 99.4547% | success 0/128 | gamma 0.40020 | |rz| 0.8539
G52 | step  1250/2000 | best 3830.0 | acc 99.4547% | success 0/128 | gamma 0.37519 | |rz| 0.8635
G52 | step  1300/2000 | best 3830.0 | acc 99.4547% | success 0/128 | gamma 0.35018 | |rz| 0.8727
G52 | step  1350/2000 | best 3830.0 | acc 99.4547% | success 0/128 | gamma 0.32517 | |rz| 0.8814
G52 | step  1400/2000 | best 3830.0 | acc 99.4547% | success 0/128 | gamma 0.30034 | |rz| 0.8894
G52 | step  1450/2000 | best 3830.0 | acc 99.4547% | success 0/128 | gamma 0.27732 | |rz| 0.8964
G52 | step  1500/2000 | best 3830.0 | acc 99.4547% | success 0/128 | gamma 0.26252 | |rz| 0.9013
G52 | step  1550/2000 | best 3830.0 | acc 99.4547% | success 0/128 | gamma 0.26035 | |rz| 0.9037
G52 | step  1600/2000 | best 3830.0 | acc 99.4547% | success 0/128 | gamma 0.25010 | |rz| 0.9075
G52 | step  1650/2000 | best 3830.0 | acc 99.4547% | success 0/128 | gamma 0.21052 | |rz| 0.9156
G52 | step  1700/2000 | best 3830.0 | acc 99.4547% | success 0/128 | gamma 0.16261 | |rz| 0.9230
G52 | step  1750/2000 | best 3830.0 | acc 99.4547% | success 0/128 | gamma 0.12728 | |rz| 0.9271
G52 | step  1800/2000 | best 3830.0 | acc 99.4547% | success 0/128 | gamma 0.10025 | |rz| 0.9296
G52 | step  1850/2000 | best 3830.0 | acc 99.4547% | success 0/128 | gamma 0.07505 | |rz| 0.9315
G52 | step  1900/2000 | best 3830.0 | acc 99.4547% | success 0/128 | gamma 0.05003 | |rz| 0.9330
G52 | step  1950/2000 | best 3830.0 | acc 99.4547% | success 0/128 | gamma 0.02501 | |rz| 0.9344
G52 | step  2000/2000 | best 3830.0 | acc 99.4547% | success 0/128 | gamma 0.00000 | |rz| 0.9434

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G52
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644286e-05,0.000018,0.000009,9.304136e-06,0.000934
1,theta_grad_mean_abs,6.230243e-07,0.000005,0.000005,2.552385e-07,0.000082
2,raw_R_step_mean_abs,2.999592e-02,0.002657,0.002752,1.969469e-03,0.048875
3,theta_step_mean_abs,2.862386e-02,0.000870,0.002129,6.498010e-04,0.028624
4,raw_R_grad_norm,2.734904e-02,0.007756,0.003600,3.599847e-03,0.334011
5,theta_grad_norm,2.794503e-04,0.003588,0.004346,1.112202e-04,0.136435
6,raw_R_step_norm,1.073167e+01,1.042091,1.076953,8.352812e-01,17.486032
7,theta_step_norm,1.028738e+01,0.524848,2.263621,3.947567e-01,10.287376

--------------------------------------------------------------------------------
RESULT SUMMARY: G52
--------------------------------------------------------------------------------
historical_best: 3851.0

V1:
v1_best: 3825.0
v1_gap: 26.0
v1_percent_accuracy: 99.32485068813295

V2:
v2_best: 3830.0
v2_gap: 21.0
v2_percent_accuracy: 99.45468709426123
v2_best_step: 974
v2_best_replica: 123

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 17.597652912139893

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/logs/G52_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/best_spins/G52_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/partial_group_results.csv

################################################################################
RUNNING G53 | dense | seed=17
################################################################################
G53 | step     1/2000 | best 3037.0 | acc 78.8831% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G53 | step    50/2000 | best 3162.0 | acc 82.1299% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G53 | step   100/2000 | best 3491.0 | acc 90.6753% | success 0/128 | gamma 0.95048 | |rz| 0.0043
G53 | step   150/2000 | best 3790.0 | acc 98.4416% | success 0/128 | gamma 0.92546 | |rz| 0.4851
G53 | step   200/2000 | best 3799.0 | acc 98.6753% | success 0/128 | gamma 0.90045 | |rz| 0.5676
G53 | step   250/2000 | best 3801.0 | acc 98.7273% | success 0/128 | gamma 0.87544 | |rz| 0.5945
G53 | step   300/2000 | best 3807.0 | acc 98.8831% | success 0/128 | gamma 0.85043 | |rz| 0.6137
G53 | step   350/2000 | best 3808.0 | acc 98.9091% | success 0/128 | gamma 0.82541 | |rz| 0.6306
G53 | step   400/2000 | best 3808.0 | acc 98.9091% | success 0/128 | gamma 0.80040 | |rz| 0.6467
G53 | step   450/2000 | best 3813.0 | acc 99.0390% | success 0/128 | gamma 0.77539 | |rz| 0.6622
G53 | step   500/2000 | best 3814.0 | acc 99.0649% | success 0/128 | gamma 0.75038 | |rz| 0.6775
G53 | step   550/2000 | best 3814.0 | acc 99.0649% | success 0/128 | gamma 0.72536 | |rz| 0.6925
G53 | step   600/2000 | best 3816.0 | acc 99.1169% | success 0/128 | gamma 0.70035 | |rz| 0.7073
G53 | step   650/2000 | best 3817.0 | acc 99.1429% | success 0/128 | gamma 0.67534 | |rz| 0.7219
G53 | step   700/2000 | best 3820.0 | acc 99.2208% | success 0/128 | gamma 0.65033 | |rz| 0.7362
G53 | step   750/2000 | best 3820.0 | acc 99.2208% | success 0/128 | gamma 0.62531 | |rz| 0.7502
G53 | step   800/2000 | best 3824.0 | acc 99.3247% | success 0/128 | gamma 0.60030 | |rz| 0.7639
G53 | step   850/2000 | best 3826.0 | acc 99.3766% | success 0/128 | gamma 0.57529 | |rz| 0.7772
G53 | step   900/2000 | best 3827.0 | acc 99.4026% | success 0/128 | gamma 0.55028 | |rz| 0.7900
G53 | step   950/2000 | best 3827.0 | acc 99.4026% | success 0/128 | gamma 0.52526 | |rz| 0.8025
G53 | step  1000/2000 | best 3827.0 | acc 99.4026% | success 0/128 | gamma 0.50025 | |rz| 0.8146
G53 | step  1050/2000 | best 3827.0 | acc 99.4026% | success 0/128 | gamma 0.47524 | |rz| 0.8262
G53 | step  1100/2000 | best 3827.0 | acc 99.4026% | success 0/128 | gamma 0.45023 | |rz| 0.8372
G53 | step  1150/2000 | best 3827.0 | acc 99.4026% | success 0/128 | gamma 0.42521 | |rz| 0.8477
G53 | step  1200/2000 | best 3827.0 | acc 99.4026% | success 0/128 | gamma 0.40020 | |rz| 0.8576
G53 | step  1250/2000 | best 3827.0 | acc 99.4026% | success 0/128 | gamma 0.37519 | |rz| 0.8671
G53 | step  1300/2000 | best 3827.0 | acc 99.4026% | success 0/128 | gamma 0.35018 | |rz| 0.8762
G53 | step  1350/2000 | best 3827.0 | acc 99.4026% | success 0/128 | gamma 0.32517 | |rz| 0.8847
G53 | step  1400/2000 | best 3827.0 | acc 99.4026% | success 0/128 | gamma 0.30034 | |rz| 0.8926
G53 | step  1450/2000 | best 3827.0 | acc 99.4026% | success 0/128 | gamma 0.27732 | |rz| 0.8995
G53 | step  1500/2000 | best 3827.0 | acc 99.4026% | success 0/128 | gamma 0.26252 | |rz| 0.9043
G53 | step  1550/2000 | best 3827.0 | acc 99.4026% | success 0/128 | gamma 0.26035 | |rz| 0.9067
G53 | step  1600/2000 | best 3827.0 | acc 99.4026% | success 0/128 | gamma 0.25010 | |rz| 0.9104
G53 | step  1650/2000 | best 3827.0 | acc 99.4026% | success 0/128 | gamma 0.21052 | |rz| 0.9185
G53 | step  1700/2000 | best 3827.0 | acc 99.4026% | success 0/128 | gamma 0.16261 | |rz| 0.9259
G53 | step  1750/2000 | best 3827.0 | acc 99.4026% | success 0/128 | gamma 0.12728 | |rz| 0.9300
G53 | step  1800/2000 | best 3827.0 | acc 99.4026% | success 0/128 | gamma 0.10025 | |rz| 0.9325
G53 | step  1850/2000 | best 3827.0 | acc 99.4026% | success 0/128 | gamma 0.07505 | |rz| 0.9344
G53 | step  1900/2000 | best 3827.0 | acc 99.4026% | success 0/128 | gamma 0.05003 | |rz| 0.9359
G53 | step  1950/2000 | best 3827.0 | acc 99.4026% | success 0/128 | gamma 0.02501 | |rz| 0.9374
G53 | step  2000/2000 | best 3827.0 | acc 99.4026% | success 0/128 | gamma 0.00000 | |rz| 0.9460

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G53
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644275e-05,0.000019,0.000009,9.279965e-06,0.000933
1,theta_grad_mean_abs,6.223083e-07,0.000004,0.000005,2.560703e-07,0.000085
2,raw_R_step_mean_abs,2.999592e-02,0.002686,0.002749,2.009735e-03,0.048873
3,theta_step_mean_abs,2.864423e-02,0.000796,0.002067,6.676049e-04,0.028644
4,raw_R_grad_norm,2.734900e-02,0.007934,0.003576,3.576024e-03,0.333876
5,theta_grad_norm,2.793383e-04,0.005679,0.004345,1.113974e-04,0.141473
6,raw_R_step_norm,1.073167e+01,1.076063,1.073866,8.468597e-01,17.485275
7,theta_step_norm,1.029306e+01,0.622078,2.174712,3.812177e-01,10.293062

--------------------------------------------------------------------------------
RESULT SUMMARY: G53
--------------------------------------------------------------------------------
historical_best: 3850.0

V1:
v1_best: 3828.0
v1_gap: 22.0
v1_percent_accuracy: 99.42857142857144

V2:
v2_best: 3827.0
v2_gap: 23.0
v2_percent_accuracy: 99.40259740259741
v2_best_step: 875
v2_best_replica: 95

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 17.136677265167236

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/logs/G53_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/best_spins/G53_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/partial_group_results.csv

################################################################################
RUNNING G54 | dense | seed=18
################################################################################
G54 | step     1/2000 | best 3059.0 | acc 79.4133% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G54 | step    50/2000 | best 3165.0 | acc 82.1651% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G54 | step   100/2000 | best 3470.0 | acc 90.0831% | success 0/128 | gamma 0.95048 | |rz| 0.0033
G54 | step   150/2000 | best 3782.0 | acc 98.1828% | success 0/128 | gamma 0.92546 | |rz| 0.4827
G54 | step   200/2000 | best 3794.0 | acc 98.4943% | success 0/128 | gamma 0.90045 | |rz| 0.5653
G54 | step   250/2000 | best 3799.0 | acc 98.6241% | success 0/128 | gamma 0.87544 | |rz| 0.5920
G54 | step   300/2000 | best 3800.0 | acc 98.6501% | success 0/128 | gamma 0.85043 | |rz| 0.6110
G54 | step   350/2000 | best 3801.0 | acc 98.6760% | success 0/128 | gamma 0.82541 | |rz| 0.6279
G54 | step   400/2000 | best 3805.0 | acc 98.7799% | success 0/128 | gamma 0.80040 | |rz| 0.6440
G54 | step   450/2000 | best 3806.0 | acc 98.8058% | success 0/128 | gamma 0.77539 | |rz| 0.6596
G54 | step   500/2000 | best 3812.0 | acc 98.9616% | success 0/128 | gamma 0.75038 | |rz| 0.6748
G54 | step   550/2000 | best 3816.0 | acc 99.0654% | success 0/128 | gamma 0.72536 | |rz| 0.6898
G54 | step   600/2000 | best 3817.0 | acc 99.0914% | success 0/128 | gamma 0.70035 | |rz| 0.7045
G54 | step   650/2000 | best 3817.0 | acc 99.0914% | success 0/128 | gamma 0.67534 | |rz| 0.7190
G54 | step   700/2000 | best 3818.0 | acc 99.1173% | success 0/128 | gamma 0.65033 | |rz| 0.7333
G54 | step   750/2000 | best 3818.0 | acc 99.1173% | success 0/128 | gamma 0.62531 | |rz| 0.7472
G54 | step   800/2000 | best 3819.0 | acc 99.1433% | success 0/128 | gamma 0.60030 | |rz| 0.7608
G54 | step   850/2000 | best 3820.0 | acc 99.1693% | success 0/128 | gamma 0.57529 | |rz| 0.7741
G54 | step   900/2000 | best 3823.0 | acc 99.2471% | success 0/128 | gamma 0.55028 | |rz| 0.7870
G54 | step   950/2000 | best 3824.0 | acc 99.2731% | success 0/128 | gamma 0.52526 | |rz| 0.7996
G54 | step  1000/2000 | best 3826.0 | acc 99.3250% | success 0/128 | gamma 0.50025 | |rz| 0.8117
G54 | step  1050/2000 | best 3826.0 | acc 99.3250% | success 0/128 | gamma 0.47524 | |rz| 0.8233
G54 | step  1100/2000 | best 3826.0 | acc 99.3250% | success 0/128 | gamma 0.45023 | |rz| 0.8344
G54 | step  1150/2000 | best 3826.0 | acc 99.3250% | success 0/128 | gamma 0.42521 | |rz| 0.8450
G54 | step  1200/2000 | best 3827.0 | acc 99.3510% | success 0/128 | gamma 0.40020 | |rz| 0.8550
G54 | step  1250/2000 | best 3827.0 | acc 99.3510% | success 0/128 | gamma 0.37519 | |rz| 0.8645
G54 | step  1300/2000 | best 3827.0 | acc 99.3510% | success 0/128 | gamma 0.35018 | |rz| 0.8737
G54 | step  1350/2000 | best 3827.0 | acc 99.3510% | success 0/128 | gamma 0.32517 | |rz| 0.8823
G54 | step  1400/2000 | best 3827.0 | acc 99.3510% | success 0/128 | gamma 0.30034 | |rz| 0.8903
G54 | step  1450/2000 | best 3827.0 | acc 99.3510% | success 0/128 | gamma 0.27732 | |rz| 0.8973
G54 | step  1500/2000 | best 3827.0 | acc 99.3510% | success 0/128 | gamma 0.26252 | |rz| 0.9022
G54 | step  1550/2000 | best 3827.0 | acc 99.3510% | success 0/128 | gamma 0.26035 | |rz| 0.9045
G54 | step  1600/2000 | best 3827.0 | acc 99.3510% | success 0/128 | gamma 0.25010 | |rz| 0.9083
G54 | step  1650/2000 | best 3827.0 | acc 99.3510% | success 0/128 | gamma 0.21052 | |rz| 0.9163
G54 | step  1700/2000 | best 3827.0 | acc 99.3510% | success 0/128 | gamma 0.16261 | |rz| 0.9236
G54 | step  1750/2000 | best 3827.0 | acc 99.3510% | success 0/128 | gamma 0.12728 | |rz| 0.9275
G54 | step  1800/2000 | best 3827.0 | acc 99.3510% | success 0/128 | gamma 0.10025 | |rz| 0.9299
G54 | step  1850/2000 | best 3827.0 | acc 99.3510% | success 0/128 | gamma 0.07505 | |rz| 0.9318
G54 | step  1900/2000 | best 3827.0 | acc 99.3510% | success 0/128 | gamma 0.05003 | |rz| 0.9332
G54 | step  1950/2000 | best 3827.0 | acc 99.3510% | success 0/128 | gamma 0.02501 | |rz| 0.9347
G54 | step  2000/2000 | best 3827.0 | acc 99.3510% | success 0/128 | gamma 0.00000 | |rz| 0.9438

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G54
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644240e-05,0.000018,0.000009,9.224743e-06,0.000933
1,theta_grad_mean_abs,6.230065e-07,0.000003,0.000005,2.558793e-07,0.000092
2,raw_R_step_mean_abs,2.999592e-02,0.002684,0.002739,1.984636e-03,0.048872
3,theta_step_mean_abs,2.864272e-02,0.000713,0.002147,6.738408e-04,0.028643
4,raw_R_grad_norm,2.734887e-02,0.007710,0.003551,3.551179e-03,0.333831
5,theta_grad_norm,2.794463e-04,0.003565,0.004283,1.113213e-04,0.155442
6,raw_R_step_norm,1.073167e+01,1.062680,1.070538,8.440061e-01,17.485048
7,theta_step_norm,1.029247e+01,0.469200,2.262886,3.947171e-01,10.292475

--------------------------------------------------------------------------------
RESULT SUMMARY: G54
--------------------------------------------------------------------------------
historical_best: 3852.0

V1:
v1_best: 3820.0
v1_gap: 32.0
v1_percent_accuracy: 99.1692627206646

V2:
v2_best: 3827.0
v2_gap: 25.0
v2_percent_accuracy: 99.35098650051921
v2_best_step: 1194
v2_best_replica: 3

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 16.726713180541992

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/logs/G54_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/best_spins/G54_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/partial_group_results.csv

================================================================================
RUN GROUP COMPLETE
================================================================================
run_group: small_7_9
graphs: 12

Group results:

,run_group,partition,instance,graph_type,storage_mode,nodes,edges,n_steps,replicas,lr,...,final_best,final_gap,final_percent_accuracy,best_step_success_count,best_step_success_probability,ever_success_count,ever_success_probability,final_success_count,final_success_probability,v2_runtime_sec
0,small_7_9,7,G43,random,dense,1000,9990,2000,128,0.03,...,6643.0,17.0,99.744745,0,0.000000,0,0.000000,0,0.000000,17.521251
1,small_7_9,7,G44,random,dense,1000,9990,2000,128,0.03,...,6635.0,15.0,99.774436,0,0.000000,0,0.000000,0,0.000000,18.148074
2,small_7_9,7,G45,random,dense,1000,9990,2000,128,0.03,...,6633.0,21.0,99.684400,0,0.000000,0,0.000000,0,0.000000,17.775375
3,small_7_9,7,G46,random,dense,1000,9990,2000,128,0.03,...,6635.0,14.0,99.789442,0,0.000000,0,0.000000,0,0.000000,17.709020
4,small_7_9,7,G47,random,dense,1000,9990,2000,128,0.03,...,6649.0,8.0,99.879826,0,0.000000,0,0.000000,0,0.000000,17.381892
5,small_7_9,8,G48,toroidal,dense,3000,6000,2000,128,0.03,...,6000.0,0.0,100.000000,10,0.078125,18,0.140625,12,0.093750,37.557828
6,small_7_9,8,G49,toroidal,dense,3000,6000,2000,128,0.03,...,6000.0,0.0,100.000000,1,0.007812,7,0.054688,7,0.054688,37.358885
7,small_7_9,8,G50,toroidal,dense,3000,6000,2000,128,0.03,...,5848.0,32.0,99.455782,128,1.000000,128,1.000000,0,0.000000,40.161613
8,small_7_9,9,G51,plain,dense,1000,5909,2000,128,0.03,...,3818.0,30.0,99.220374,0,0.000000,0,0.000000,0,0.000000,16.340145
9,small_7_9,9,G52,plain,dense,1000,5916,2000,128,0.03,...,3830.0,21.0,99.454687,0,0.000000,0,0.000000,0,0.000000,17.597653
10,small_7_9,9,G53,plain,dense,1000,5914,2000,128,0.03,...,3827.0,23.0,99.402597,0,0.000000,0,0.000000,0,0.000000,17.136677
11,small_7_9,9,G54,plain,dense,1000,5916,2000,128,0.03,...,3827.0,25.0,99.350987,0,0.000000,0,0.000000,0,0.000000,16.726713

Compact group results:

,instance,historical_best,v1_best,v1_gap,v1_percent_accuracy,v2_best,v2_gap,v2_percent_accuracy,v2_best_step,v2_best_replica,ever_success_count,ever_success_probability,final_best,final_gap,final_percent_accuracy,final_success_count,final_success_probability,v2_runtime_sec
0,G43,6660.0,6652.0,8.0,99.879880,6643.00,17.00,99.744745,635,107,0,0.000000,6643.0,17.0,99.744745,0,0.000000,17.521251
1,G44,6650.0,6638.0,12.0,99.819549,6635.00,15.00,99.774436,520,58,0,0.000000,6635.0,15.0,99.774436,0,0.000000,18.148074
2,G45,6654.0,6633.0,21.0,99.684400,6633.00,21.00,99.684400,1395,46,0,0.000000,6633.0,21.0,99.684400,0,0.000000,17.775375
3,G46,6649.0,6627.0,22.0,99.669123,6635.00,14.00,99.789442,561,81,0,0.000000,6635.0,14.0,99.789442,0,0.000000,17.709020
4,G47,6657.0,6638.0,19.0,99.714586,6649.00,8.00,99.879826,461,112,0,0.000000,6649.0,8.0,99.879826,0,0.000000,17.381892
5,G48,6000.0,6000.0,0.0,100.000000,6070.00,-70.00,101.166667,124,29,18,0.140625,6000.0,0.0,100.000000,12,0.093750,37.557828
6,G49,6000.0,6000.0,0.0,100.000000,6000.00,0.00,100.000000,464,14,7,0.054688,6000.0,0.0,100.000000,7,0.054688,37.358885
7,G50,5880.0,5852.0,28.0,99.523810,7310.25,-1430.25,124.323980,1341,47,128,1.000000,5848.0,32.0,99.455782,0,0.000000,40.161613
8,G51,3848.0,3819.0,29.0,99.246362,3818.00,30.00,99.220374,934,49,0,0.000000,3818.0,30.0,99.220374,0,0.000000,16.340145
9,G52,3851.0,3825.0,26.0,99.324851,3830.00,21.00,99.454687,974,123,0,0.000000,3830.0,21.0,99.454687,0,0.000000,17.597653
10,G53,3850.0,3828.0,22.0,99.428571,3827.00,23.00,99.402597,875,95,0,0.000000,3827.0,23.0,99.402597,0,0.000000,17.136677
11,G54,3852.0,3820.0,32.0,99.169263,3827.00,25.00,99.350987,1194,3,0,0.000000,3827.0,25.0,99.350987,0,0.000000,16.726713

Saved group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/group_results.csv

Saved group logs:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/small_7_9/group_training_logs.csv

================================================================================
COMPACT GROUP RESULT
================================================================================

,instance,historical_best,v1_best,v1_gap,v1_percent_accuracy,v2_best,v2_gap,v2_percent_accuracy,v2_best_step,v2_best_replica,ever_success_count,ever_success_probability,final_best,final_gap,final_percent_accuracy,final_success_count,final_success_probability,v2_runtime_sec
0,G43,6660.0,6652.0,8.0,99.879880,6643.00,17.00,99.744745,635,107,0,0.000000,6643.0,17.0,99.744745,0,0.000000,17.521251
1,G44,6650.0,6638.0,12.0,99.819549,6635.00,15.00,99.774436,520,58,0,0.000000,6635.0,15.0,99.774436,0,0.000000,18.148074
2,G45,6654.0,6633.0,21.0,99.684400,6633.00,21.00,99.684400,1395,46,0,0.000000,6633.0,21.0,99.684400,0,0.000000,17.775375
3,G46,6649.0,6627.0,22.0,99.669123,6635.00,14.00,99.789442,561,81,0,0.000000,6635.0,14.0,99.789442,0,0.000000,17.709020
4,G47,6657.0,6638.0,19.0,99.714586,6649.00,8.00,99.879826,461,112,0,0.000000,6649.0,8.0,99.879826,0,0.000000,17.381892
5,G48,6000.0,6000.0,0.0,100.000000,6070.00,-70.00,101.166667,124,29,18,0.140625,6000.0,0.0,100.000000,12,0.093750,37.557828
6,G49,6000.0,6000.0,0.0,100.000000,6000.00,0.00,100.000000,464,14,7,0.054688,6000.0,0.0,100.000000,7,0.054688,37.358885
7,G50,5880.0,5852.0,28.0,99.523810,7310.25,-1430.25,124.323980,1341,47,128,1.000000,5848.0,32.0,99.455782,0,0.000000,40.161613
8,G51,3848.0,3819.0,29.0,99.246362,3818.00,30.00,99.220374,934,49,0,0.000000,3818.0,30.0,99.220374,0,0.000000,16.340145
9,G52,3851.0,3825.0,26.0,99.324851,3830.00,21.00,99.454687,974,123,0,0.000000,3830.0,21.0,99.454687,0,0.000000,17.597653
10,G53,3850.0,3828.0,22.0,99.428571,3827.00,23.00,99.402597,875,95,0,0.000000,3827.0,23.0,99.402597,0,0.000000,17.136677
11,G54,3852.0,3820.0,32.0,99.169263,3827.00,25.00,99.350987,1194,3,0,0.000000,3827.0,25.0,99.350987,0,0.000000,16.726713

In [101]:
print("\nGroup summary:")
print("graphs:", len(group_results_df))
print("mean v1 accuracy %:", float(group_results_df["v1_percent_accuracy"].mean()))
print("mean v2 accuracy %:", float(group_results_df["v2_percent_accuracy"].mean()))
print("v1 gap-zero count:", int((group_results_df["v1_gap"] == 0).sum()))
print("v2 gap-zero count:", int((group_results_df["v2_gap"] == 0).sum()))
print("total v2 runtime sec:", float(group_results_df["v2_runtime_sec"].sum()))

Group summary:
graphs: 12
mean v1 accuracy %: 99.62169954555173
mean v2 accuracy %: 101.81601170338344
v1 gap-zero count: 2
v2 gap-zero count: 1
total v2 runtime sec: 271.41512513160706

In [102]:
# ============================================================
# Quick inspection: where did V2 improve over V1?
# ============================================================

inspection_df = group_results_df[
    [
        "instance",
        "historical_best",
        "v1_best",
        "v1_gap",
        "v1_percent_accuracy",
        "v2_best",
        "v2_gap",
        "v2_percent_accuracy",
        "v2_best_step",
        "ever_success_count",
        "ever_success_probability",
        "final_best",
        "final_gap",
        "final_percent_accuracy",
    ]
].copy()

inspection_df["gap_improvement"] = (
    inspection_df["v1_gap"] - inspection_df["v2_gap"]
)

inspection_df["accuracy_improvement"] = (
    inspection_df["v2_percent_accuracy"] - inspection_df["v1_percent_accuracy"]
)

inspection_df = inspection_df.sort_values(
    "gap_improvement",
    ascending=False,
).reset_index(drop=True)

print("=" * 80)
print("V2 IMPROVEMENT INSPECTION")
print("=" * 80)

display(inspection_df)

print("\nSummary:")
print("graphs:", len(inspection_df))
print("improved gap count:", int((inspection_df["gap_improvement"] > 0).sum()))
print("same gap count    :", int((inspection_df["gap_improvement"] == 0).sum()))
print("worse gap count   :", int((inspection_df["gap_improvement"] < 0).sum()))

print("\nGap improvement:")
print("mean:", float(inspection_df["gap_improvement"].mean()))
print("min :", float(inspection_df["gap_improvement"].min()))
print("max :", float(inspection_df["gap_improvement"].max()))

print("\nAccuracy improvement:")
print("mean:", float(inspection_df["accuracy_improvement"].mean()))
print("min :", float(inspection_df["accuracy_improvement"].min()))
print("max :", float(inspection_df["accuracy_improvement"].max()))

print("\nClosest V2 gaps:")
display(
    inspection_df.sort_values("v2_gap")[
        [
            "instance",
            "historical_best",
            "v2_best",
            "v2_gap",
            "v2_percent_accuracy",
            "v2_best_step",
            "ever_success_count",
            "final_gap",
        ]
    ].head(10)
)

================================================================================
V2 IMPROVEMENT INSPECTION
================================================================================

,instance,historical_best,v1_best,v1_gap,v1_percent_accuracy,v2_best,v2_gap,v2_percent_accuracy,v2_best_step,ever_success_count,ever_success_probability,final_best,final_gap,final_percent_accuracy,gap_improvement,accuracy_improvement
0,G50,5880.0,5852.0,28.0,99.523810,7310.25,-1430.25,124.323980,1341,128,1.000000,5848.0,32.0,99.455782,1458.25,24.800170
1,G48,6000.0,6000.0,0.0,100.000000,6070.00,-70.00,101.166667,124,18,0.140625,6000.0,0.0,100.000000,70.00,1.166667
2,G47,6657.0,6638.0,19.0,99.714586,6649.00,8.00,99.879826,461,0,0.000000,6649.0,8.0,99.879826,11.00,0.165240
3,G46,6649.0,6627.0,22.0,99.669123,6635.00,14.00,99.789442,561,0,0.000000,6635.0,14.0,99.789442,8.00,0.120319
4,G54,3852.0,3820.0,32.0,99.169263,3827.00,25.00,99.350987,1194,0,0.000000,3827.0,25.0,99.350987,7.00,0.181724
5,G52,3851.0,3825.0,26.0,99.324851,3830.00,21.00,99.454687,974,0,0.000000,3830.0,21.0,99.454687,5.00,0.129836
6,G45,6654.0,6633.0,21.0,99.684400,6633.00,21.00,99.684400,1395,0,0.000000,6633.0,21.0,99.684400,0.00,0.000000
7,G49,6000.0,6000.0,0.0,100.000000,6000.00,0.00,100.000000,464,7,0.054688,6000.0,0.0,100.000000,0.00,0.000000
8,G51,3848.0,3819.0,29.0,99.246362,3818.00,30.00,99.220374,934,0,0.000000,3818.0,30.0,99.220374,-1.00,-0.025988
9,G53,3850.0,3828.0,22.0,99.428571,3827.00,23.00,99.402597,875,0,0.000000,3827.0,23.0,99.402597,-1.00,-0.025974
10,G44,6650.0,6638.0,12.0,99.819549,6635.00,15.00,99.774436,520,0,0.000000,6635.0,15.0,99.774436,-3.00,-0.045113
11,G43,6660.0,6652.0,8.0,99.879880,6643.00,17.00,99.744745,635,0,0.000000,6643.0,17.0,99.744745,-9.00,-0.135135

Summary:
graphs: 12
improved gap count: 6
same gap count    : 2
worse gap count   : 4

Gap improvement:
mean: 128.77083333333334
min : -9.0
max : 1458.25

Accuracy improvement:
mean: 2.194312157831714
min : -0.13513513513512976
max : 24.800170068027214

Closest V2 gaps:

,instance,historical_best,v2_best,v2_gap,v2_percent_accuracy,v2_best_step,ever_success_count,final_gap
0,G50,5880.0,7310.25,-1430.25,124.323980,1341,128,32.0
1,G48,6000.0,6070.00,-70.00,101.166667,124,18,0.0
7,G49,6000.0,6000.00,0.00,100.000000,464,7,0.0
2,G47,6657.0,6649.00,8.00,99.879826,461,0,8.0
3,G46,6649.0,6635.00,14.00,99.789442,561,0,14.0
10,G44,6650.0,6635.00,15.00,99.774436,520,0,15.0
11,G43,6660.0,6643.00,17.00,99.744745,635,0,17.0
5,G52,3851.0,3830.00,21.00,99.454687,974,0,21.0
6,G45,6654.0,6633.00,21.00,99.684400,1395,0,21.0
9,G53,3850.0,3827.00,23.00,99.402597,875,0,23.0

In [106]:
display(inspection_df.drop(columns=["v1_best","v1_gap","v2_best","v2_gap","ever_success_probability","final_best","final_gap","gap_improvement",]))

,instance,historical_best,v1_percent_accuracy,v2_percent_accuracy,v2_best_step,ever_success_count,final_percent_accuracy,accuracy_improvement
0,G50,5880.0,99.523810,124.323980,1341,128,99.455782,24.800170
1,G48,6000.0,100.000000,101.166667,124,18,100.000000,1.166667
2,G47,6657.0,99.714586,99.879826,461,0,99.879826,0.165240
3,G46,6649.0,99.669123,99.789442,561,0,99.789442,0.120319
4,G54,3852.0,99.169263,99.350987,1194,0,99.350987,0.181724
5,G52,3851.0,99.324851,99.454687,974,0,99.454687,0.129836
6,G45,6654.0,99.684400,99.684400,1395,0,99.684400,0.000000
7,G49,6000.0,100.000000,100.000000,464,7,100.000000,0.000000
8,G51,3848.0,99.246362,99.220374,934,0,99.220374,-0.025988
9,G53,3850.0,99.428571,99.402597,875,0,99.402597,-0.025974
10,G44,6650.0,99.819549,99.774436,520,0,99.774436,-0.045113
11,G43,6660.0,99.879880,99.744745,635,0,99.744745,-0.135135

# 3

In [107]:
# ============================================================
# Cell 10: Select run group and run QEFEM v2
# ============================================================

# ------------------------------------------------------------
# Choose run group here
# ------------------------------------------------------------
# 0 -> small_1_3   : G1-G21
# 1 -> small_4_6   : G22-G42
# 2 -> small_7_9   : G43-G54
# 3 -> big_10_12   : G55-G59
# 4 -> big_13_15   : G60-G64
# 5 -> big_16_18   : G65, G66, G67, G72
# 6 -> big_19_21   : G70, G77, G81

RUN_GROUP_INDEX = 3


# ------------------------------------------------------------
# Preview selected group
# ------------------------------------------------------------

selected_group_row = run_group_summary_df.iloc[RUN_GROUP_INDEX]

print("=" * 80)
print("SELECTED RUN GROUP")
print("=" * 80)

print("RUN_GROUP_INDEX:", RUN_GROUP_INDEX)
print("run_group:", selected_group_row["run_group"])
print("partitions:", selected_group_row["partitions"])
print("graphs_start:", selected_group_row["graphs_start"])
print("graphs_end:", selected_group_row["graphs_end"])
print("num_graphs:", selected_group_row["num_graphs"])
print("graph_types:", selected_group_row["graph_types"])
print("storage_modes:", selected_group_row["storage_modes"])
print("graphs:", selected_group_row["graphs"])


# ------------------------------------------------------------
# Run selected group
# ------------------------------------------------------------

group_results_df, group_logs_df = run_qefem_run_group(
    run_group_index=RUN_GROUP_INDEX
)


# ------------------------------------------------------------
# Final compact display
# ------------------------------------------------------------

compact_group_results_df = group_results_df[
    [
        "instance",
        "historical_best",
        "v1_best",
        "v1_gap",
        "v1_percent_accuracy",
        "v2_best",
        "v2_gap",
        "v2_percent_accuracy",
        "v2_best_step",
        "v2_best_replica",
        "ever_success_count",
        "ever_success_probability",
        "final_best",
        "final_gap",
        "final_percent_accuracy",
        "final_success_count",
        "final_success_probability",
        "v2_runtime_sec",
    ]
].copy()

print("\n" + "=" * 80)
print("COMPACT GROUP RESULT")
print("=" * 80)

display(compact_group_results_df)

================================================================================
SELECTED RUN GROUP
================================================================================
RUN_GROUP_INDEX: 3
run_group: big_10_12
partitions: [10, 11, 12]
graphs_start: G55
graphs_end: G59
num_graphs: 5
graph_types: ['plain', 'random', 'toroid']
storage_modes: ['edge_list']
graphs: ['G55', 'G56', 'G57', 'G58', 'G59']
================================================================================
RUNNING QEFEM V2 RUN GROUP
================================================================================
run_group_index: 3
run_group: big_10_12
graphs: ['G55', 'G56', 'G57', 'G58', 'G59']
num graphs: 5

Output directory:
The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_10_12

Selected benchmark rows:

,partition,instance,graph_type,storage_mode,nodes,edges,n_steps,replicas,lr,v1_best,historical_best,v1_gap,v1_percent_accuracy,v1_best_replica,v1_runtime_sec
0,10,G55,plain,edge_list,5000,12498,1000,128,0.01,10195.0,10299.0,104.0,98.990193,43,13.877591
1,10,G56,plain,edge_list,5000,12498,1000,128,0.01,3915.0,4017.0,102.0,97.460792,99,15.026528
2,11,G57,toroid,edge_list,5000,10000,1000,128,0.01,3428.0,3494.0,66.0,98.111048,10,12.622632
3,12,G58,random,edge_list,5000,29570,1000,128,0.01,19084.0,19293.0,209.0,98.916706,94,21.107788
4,12,G59,random,edge_list,5000,29570,1000,128,0.01,5856.0,6086.0,230.0,96.220835,126,20.489040

################################################################################
RUNNING G55 | edge_list | seed=7
################################################################################
G55 | step     1/2000 | best 6363.0 | acc 61.7827% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G55 | step    50/2000 | best 6727.0 | acc 65.3170% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G55 | step   100/2000 | best 6764.0 | acc 65.6763% | success 0/128 | gamma 0.95048 | |rz| 0.0011
G55 | step   150/2000 | best 10085.0 | acc 97.9221% | success 0/128 | gamma 0.92546 | |rz| 0.4532
G55 | step   200/2000 | best 10108.0 | acc 98.1455% | success 0/128 | gamma 0.90045 | |rz| 0.5662
G55 | step   250/2000 | best 10122.0 | acc 98.2814% | success 0/128 | gamma 0.87544 | |rz| 0.5976
G55 | step   300/2000 | best 10128.0 | acc 98.3396% | success 0/128 | gamma 0.85043 | |rz| 0.6181
G55 | step   350/2000 | best 10134.0 | acc 98.3979% | success 0/128 | gamma 0.82541 | |rz| 0.6356
G55 | step   400/2000 | best 10146.0 | acc 98.5144% | success 0/128 | gamma 0.80040 | |rz| 0.6518
G55 | step   450/2000 | best 10152.0 | acc 98.5727% | success 0/128 | gamma 0.77539 | |rz| 0.6672
G55 | step   500/2000 | best 10159.0 | acc 98.6406% | success 0/128 | gamma 0.75038 | |rz| 0.6820
G55 | step   550/2000 | best 10168.0 | acc 98.7280% | success 0/128 | gamma 0.72536 | |rz| 0.6964
G55 | step   600/2000 | best 10174.0 | acc 98.7863% | success 0/128 | gamma 0.70035 | |rz| 0.7105
G55 | step   650/2000 | best 10177.0 | acc 98.8154% | success 0/128 | gamma 0.67534 | |rz| 0.7242
G55 | step   700/2000 | best 10179.0 | acc 98.8348% | success 0/128 | gamma 0.65033 | |rz| 0.7376
G55 | step   750/2000 | best 10184.0 | acc 98.8834% | success 0/128 | gamma 0.62531 | |rz| 0.7507
G55 | step   800/2000 | best 10187.0 | acc 98.9125% | success 0/128 | gamma 0.60030 | |rz| 0.7635
G55 | step   850/2000 | best 10190.0 | acc 98.9416% | success 0/128 | gamma 0.57529 | |rz| 0.7759
G55 | step   900/2000 | best 10192.0 | acc 98.9611% | success 0/128 | gamma 0.55028 | |rz| 0.7879
G55 | step   950/2000 | best 10193.0 | acc 98.9708% | success 0/128 | gamma 0.52526 | |rz| 0.7996
G55 | step  1000/2000 | best 10196.0 | acc 98.9999% | success 0/128 | gamma 0.50025 | |rz| 0.8110
G55 | step  1050/2000 | best 10196.0 | acc 98.9999% | success 0/128 | gamma 0.47524 | |rz| 0.8220
G55 | step  1100/2000 | best 10196.0 | acc 98.9999% | success 0/128 | gamma 0.45023 | |rz| 0.8325
G55 | step  1150/2000 | best 10197.0 | acc 99.0096% | success 0/128 | gamma 0.42521 | |rz| 0.8427
G55 | step  1200/2000 | best 10197.0 | acc 99.0096% | success 0/128 | gamma 0.40020 | |rz| 0.8526
G55 | step  1250/2000 | best 10198.0 | acc 99.0193% | success 0/128 | gamma 0.37519 | |rz| 0.8622
G55 | step  1300/2000 | best 10198.0 | acc 99.0193% | success 0/128 | gamma 0.35018 | |rz| 0.8717
G55 | step  1350/2000 | best 10198.0 | acc 99.0193% | success 0/128 | gamma 0.32517 | |rz| 0.8810
G55 | step  1400/2000 | best 10198.0 | acc 99.0193% | success 0/128 | gamma 0.30034 | |rz| 0.8896
G55 | step  1450/2000 | best 10198.0 | acc 99.0193% | success 0/128 | gamma 0.27732 | |rz| 0.8971
G55 | step  1500/2000 | best 10198.0 | acc 99.0193% | success 0/128 | gamma 0.26252 | |rz| 0.9025
G55 | step  1550/2000 | best 10198.0 | acc 99.0193% | success 0/128 | gamma 0.26035 | |rz| 0.9052
G55 | step  1600/2000 | best 10198.0 | acc 99.0193% | success 0/128 | gamma 0.25010 | |rz| 0.9092
G55 | step  1650/2000 | best 10198.0 | acc 99.0193% | success 0/128 | gamma 0.21052 | |rz| 0.9180
G55 | step  1700/2000 | best 10198.0 | acc 99.0193% | success 0/128 | gamma 0.16261 | |rz| 0.9262
G55 | step  1750/2000 | best 10198.0 | acc 99.0193% | success 0/128 | gamma 0.12728 | |rz| 0.9310
G55 | step  1800/2000 | best 10198.0 | acc 99.0193% | success 0/128 | gamma 0.10025 | |rz| 0.9340
G55 | step  1850/2000 | best 10198.0 | acc 99.0193% | success 0/128 | gamma 0.07505 | |rz| 0.9362
G55 | step  1900/2000 | best 10198.0 | acc 99.0193% | success 0/128 | gamma 0.05003 | |rz| 0.9379
G55 | step  1950/2000 | best 10198.0 | acc 99.0193% | success 0/128 | gamma 0.02501 | |rz| 0.9393
G55 | step  2000/2000 | best 10198.0 | acc 99.0193% | success 0/128 | gamma 0.00000 | |rz| 0.9453

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G55
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644272e-05,0.000017,0.000009,8.853965e-06,0.000933
1,theta_grad_mean_abs,6.236002e-07,0.000003,0.000003,2.596732e-07,0.000134
2,raw_R_step_mean_abs,2.999592e-02,0.002649,0.002793,2.086614e-03,0.048871
3,theta_step_mean_abs,2.864921e-02,0.000756,0.001626,6.926108e-04,0.028649
4,raw_R_grad_norm,6.115421e-02,0.014620,0.007550,7.549990e-03,0.746340
5,theta_grad_norm,6.250525e-04,0.005674,0.007140,2.475363e-04,0.264037
6,raw_R_step_norm,2.399673e+01,2.296466,2.452623,1.984287e+00,39.097073
7,theta_step_norm,2.301870e+01,0.993270,4.390967,8.811639e-01,23.018702

--------------------------------------------------------------------------------
RESULT SUMMARY: G55
--------------------------------------------------------------------------------
historical_best: 10299.0

V1:
v1_best: 10195.0
v1_gap: 104.0
v1_percent_accuracy: 98.99019322264296

V2:
v2_best: 10198.0
v2_gap: 101.0
v2_percent_accuracy: 99.0193222642975
v2_best_step: 1220
v2_best_replica: 38

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 48.72006893157959

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_10_12/logs/G55_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_10_12/best_spins/G55_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_10_12/partial_group_results.csv

################################################################################
RUNNING G56 | edge_list | seed=8
################################################################################
G56 | step     1/2000 | best 80.0 | acc 1.9915% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G56 | step    50/2000 | best 447.0 | acc 11.1277% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G56 | step   100/2000 | best 516.0 | acc 12.8454% | success 0/128 | gamma 0.95048 | |rz| 0.0010
G56 | step   150/2000 | best 3792.0 | acc 94.3988% | success 0/128 | gamma 0.92546 | |rz| 0.4601
G56 | step   200/2000 | best 3815.0 | acc 94.9714% | success 0/128 | gamma 0.90045 | |rz| 0.5662
G56 | step   250/2000 | best 3835.0 | acc 95.4693% | success 0/128 | gamma 0.87544 | |rz| 0.5972
G56 | step   300/2000 | best 3848.0 | acc 95.7929% | success 0/128 | gamma 0.85043 | |rz| 0.6174
G56 | step   350/2000 | best 3858.0 | acc 96.0418% | success 0/128 | gamma 0.82541 | |rz| 0.6348
G56 | step   400/2000 | best 3864.0 | acc 96.1912% | success 0/128 | gamma 0.80040 | |rz| 0.6510
G56 | step   450/2000 | best 3873.0 | acc 96.4152% | success 0/128 | gamma 0.77539 | |rz| 0.6664
G56 | step   500/2000 | best 3881.0 | acc 96.6144% | success 0/128 | gamma 0.75038 | |rz| 0.6812
G56 | step   550/2000 | best 3887.0 | acc 96.7638% | success 0/128 | gamma 0.72536 | |rz| 0.6957
G56 | step   600/2000 | best 3889.0 | acc 96.8135% | success 0/128 | gamma 0.70035 | |rz| 0.7097
G56 | step   650/2000 | best 3891.0 | acc 96.8633% | success 0/128 | gamma 0.67534 | |rz| 0.7235
G56 | step   700/2000 | best 3895.0 | acc 96.9629% | success 0/128 | gamma 0.65033 | |rz| 0.7369
G56 | step   750/2000 | best 3899.0 | acc 97.0625% | success 0/128 | gamma 0.62531 | |rz| 0.7500
G56 | step   800/2000 | best 3900.0 | acc 97.0874% | success 0/128 | gamma 0.60030 | |rz| 0.7627
G56 | step   850/2000 | best 3901.0 | acc 97.1123% | success 0/128 | gamma 0.57529 | |rz| 0.7752
G56 | step   900/2000 | best 3904.0 | acc 97.1870% | success 0/128 | gamma 0.55028 | |rz| 0.7872
G56 | step   950/2000 | best 3906.0 | acc 97.2367% | success 0/128 | gamma 0.52526 | |rz| 0.7990
G56 | step  1000/2000 | best 3906.0 | acc 97.2367% | success 0/128 | gamma 0.50025 | |rz| 0.8104
G56 | step  1050/2000 | best 3907.0 | acc 97.2616% | success 0/128 | gamma 0.47524 | |rz| 0.8213
G56 | step  1100/2000 | best 3907.0 | acc 97.2616% | success 0/128 | gamma 0.45023 | |rz| 0.8319
G56 | step  1150/2000 | best 3908.0 | acc 97.2865% | success 0/128 | gamma 0.42521 | |rz| 0.8421
G56 | step  1200/2000 | best 3908.0 | acc 97.2865% | success 0/128 | gamma 0.40020 | |rz| 0.8520
G56 | step  1250/2000 | best 3908.0 | acc 97.2865% | success 0/128 | gamma 0.37519 | |rz| 0.8617
G56 | step  1300/2000 | best 3908.0 | acc 97.2865% | success 0/128 | gamma 0.35018 | |rz| 0.8712
G56 | step  1350/2000 | best 3908.0 | acc 97.2865% | success 0/128 | gamma 0.32517 | |rz| 0.8805
G56 | step  1400/2000 | best 3908.0 | acc 97.2865% | success 0/128 | gamma 0.30034 | |rz| 0.8891
G56 | step  1450/2000 | best 3908.0 | acc 97.2865% | success 0/128 | gamma 0.27732 | |rz| 0.8967
G56 | step  1500/2000 | best 3908.0 | acc 97.2865% | success 0/128 | gamma 0.26252 | |rz| 0.9021
G56 | step  1550/2000 | best 3908.0 | acc 97.2865% | success 0/128 | gamma 0.26035 | |rz| 0.9047
G56 | step  1600/2000 | best 3908.0 | acc 97.2865% | success 0/128 | gamma 0.25010 | |rz| 0.9088
G56 | step  1650/2000 | best 3908.0 | acc 97.2865% | success 0/128 | gamma 0.21052 | |rz| 0.9176
G56 | step  1700/2000 | best 3908.0 | acc 97.2865% | success 0/128 | gamma 0.16261 | |rz| 0.9258
G56 | step  1750/2000 | best 3908.0 | acc 97.2865% | success 0/128 | gamma 0.12728 | |rz| 0.9307
G56 | step  1800/2000 | best 3908.0 | acc 97.2865% | success 0/128 | gamma 0.10025 | |rz| 0.9336
G56 | step  1850/2000 | best 3908.0 | acc 97.2865% | success 0/128 | gamma 0.07505 | |rz| 0.9359
G56 | step  1900/2000 | best 3908.0 | acc 97.2865% | success 0/128 | gamma 0.05003 | |rz| 0.9376
G56 | step  1950/2000 | best 3908.0 | acc 97.2865% | success 0/128 | gamma 0.02501 | |rz| 0.9390
G56 | step  2000/2000 | best 3908.0 | acc 97.2865% | success 0/128 | gamma 0.00000 | |rz| 0.9449

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G56
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644275e-05,0.000017,0.000009,8.875829e-06,0.000933
1,theta_grad_mean_abs,6.239869e-07,0.000004,0.000004,2.597418e-07,0.000106
2,raw_R_step_mean_abs,2.999592e-02,0.002648,0.002795,2.086481e-03,0.048871
3,theta_step_mean_abs,2.864725e-02,0.000831,0.001653,7.413912e-04,0.028647
4,raw_R_grad_norm,6.115423e-02,0.014725,0.007567,7.567308e-03,0.746347
5,theta_grad_norm,6.254197e-04,0.006344,0.007531,2.475656e-04,0.236450
6,raw_R_step_norm,2.399673e+01,2.301182,2.454041,1.978289e+00,39.097179
7,theta_step_norm,2.301725e+01,1.017279,4.371700,8.805779e-01,23.017254

--------------------------------------------------------------------------------
RESULT SUMMARY: G56
--------------------------------------------------------------------------------
historical_best: 4017.0

V1:
v1_best: 3915.0
v1_gap: 102.0
v1_percent_accuracy: 97.46079163554892

V2:
v2_best: 3908.0
v2_gap: 109.0
v2_percent_accuracy: 97.28653223798855
v2_best_step: 1117
v2_best_replica: 99

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 47.31054878234863

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_10_12/logs/G56_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_10_12/best_spins/G56_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_10_12/partial_group_results.csv

################################################################################
RUNNING G57 | edge_list | seed=9
################################################################################
G57 | step     1/2000 | best 118.0 | acc 3.3772% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G57 | step    50/2000 | best 394.0 | acc 11.2765% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G57 | step   100/2000 | best 404.0 | acc 11.5627% | success 0/128 | gamma 0.95048 | |rz| 0.0010
G57 | step   150/2000 | best 3392.0 | acc 97.0807% | success 0/128 | gamma 0.92546 | |rz| 0.3531
G57 | step   200/2000 | best 3418.0 | acc 97.8248% | success 0/128 | gamma 0.90045 | |rz| 0.4953
G57 | step   250/2000 | best 3422.0 | acc 97.9393% | success 0/128 | gamma 0.87544 | |rz| 0.5501
G57 | step   300/2000 | best 3428.0 | acc 98.1110% | success 0/128 | gamma 0.85043 | |rz| 0.5831
G57 | step   350/2000 | best 3428.0 | acc 98.1110% | success 0/128 | gamma 0.82541 | |rz| 0.6101
G57 | step   400/2000 | best 3430.0 | acc 98.1683% | success 0/128 | gamma 0.80040 | |rz| 0.6343
G57 | step   450/2000 | best 3430.0 | acc 98.1683% | success 0/128 | gamma 0.77539 | |rz| 0.6567
G57 | step   500/2000 | best 3430.0 | acc 98.1683% | success 0/128 | gamma 0.75038 | |rz| 0.6776
G57 | step   550/2000 | best 3432.0 | acc 98.2255% | success 0/128 | gamma 0.72536 | |rz| 0.6971
G57 | step   600/2000 | best 3432.0 | acc 98.2255% | success 0/128 | gamma 0.70035 | |rz| 0.7153
G57 | step   650/2000 | best 3434.0 | acc 98.2828% | success 0/128 | gamma 0.67534 | |rz| 0.7324
G57 | step   700/2000 | best 3434.0 | acc 98.2828% | success 0/128 | gamma 0.65033 | |rz| 0.7484
G57 | step   750/2000 | best 3434.0 | acc 98.2828% | success 0/128 | gamma 0.62531 | |rz| 0.7633
G57 | step   800/2000 | best 3434.0 | acc 98.2828% | success 0/128 | gamma 0.60030 | |rz| 0.7773
G57 | step   850/2000 | best 3434.0 | acc 98.2828% | success 0/128 | gamma 0.57529 | |rz| 0.7904
G57 | step   900/2000 | best 3434.0 | acc 98.2828% | success 0/128 | gamma 0.55028 | |rz| 0.8027
G57 | step   950/2000 | best 3434.0 | acc 98.2828% | success 0/128 | gamma 0.52526 | |rz| 0.8142
G57 | step  1000/2000 | best 3434.0 | acc 98.2828% | success 0/128 | gamma 0.50025 | |rz| 0.8250
G57 | step  1050/2000 | best 3434.0 | acc 98.2828% | success 0/128 | gamma 0.47524 | |rz| 0.8351
G57 | step  1100/2000 | best 3434.0 | acc 98.2828% | success 0/128 | gamma 0.45023 | |rz| 0.8445
G57 | step  1150/2000 | best 3434.0 | acc 98.2828% | success 0/128 | gamma 0.42521 | |rz| 0.8533
G57 | step  1200/2000 | best 3434.0 | acc 98.2828% | success 0/128 | gamma 0.40020 | |rz| 0.8616
G57 | step  1250/2000 | best 3434.0 | acc 98.2828% | success 0/128 | gamma 0.37519 | |rz| 0.8692
G57 | step  1300/2000 | best 3434.0 | acc 98.2828% | success 0/128 | gamma 0.35018 | |rz| 0.8764
G57 | step  1350/2000 | best 3434.0 | acc 98.2828% | success 0/128 | gamma 0.32517 | |rz| 0.8830
G57 | step  1400/2000 | best 3434.0 | acc 98.2828% | success 0/128 | gamma 0.30034 | |rz| 0.8891
G57 | step  1450/2000 | best 3434.0 | acc 98.2828% | success 0/128 | gamma 0.27732 | |rz| 0.8944
G57 | step  1500/2000 | best 3434.0 | acc 98.2828% | success 0/128 | gamma 0.26252 | |rz| 0.8980
G57 | step  1550/2000 | best 3434.0 | acc 98.2828% | success 0/128 | gamma 0.26035 | |rz| 0.8994
G57 | step  1600/2000 | best 3434.0 | acc 98.2828% | success 0/128 | gamma 0.25010 | |rz| 0.9022
G57 | step  1650/2000 | best 3434.0 | acc 98.2828% | success 0/128 | gamma 0.21052 | |rz| 0.9085
G57 | step  1700/2000 | best 3434.0 | acc 98.2828% | success 0/128 | gamma 0.16261 | |rz| 0.9141
G57 | step  1750/2000 | best 3434.0 | acc 98.2828% | success 0/128 | gamma 0.12728 | |rz| 0.9168
G57 | step  1800/2000 | best 3434.0 | acc 98.2828% | success 0/128 | gamma 0.10025 | |rz| 0.9180
G57 | step  1850/2000 | best 3434.0 | acc 98.2828% | success 0/128 | gamma 0.07505 | |rz| 0.9184
G57 | step  1900/2000 | best 3434.0 | acc 98.2828% | success 0/128 | gamma 0.05003 | |rz| 0.9189
G57 | step  1950/2000 | best 3434.0 | acc 98.2828% | success 0/128 | gamma 0.02501 | |rz| 0.9198
G57 | step  2000/2000 | best 3434.0 | acc 98.2828% | success 0/128 | gamma 0.00000 | |rz| 0.9303

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G57
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644269e-05,0.000017,0.000008,7.829416e-06,0.000933
1,theta_grad_mean_abs,6.235056e-07,0.000003,0.000005,2.606679e-07,0.000114
2,raw_R_step_mean_abs,2.999592e-02,0.002990,0.002660,2.215713e-03,0.048872
3,theta_step_mean_abs,2.864308e-02,0.000757,0.002373,7.062450e-04,0.028643
4,raw_R_grad_norm,6.115418e-02,0.014615,0.006611,6.611080e-03,0.746349
5,theta_grad_norm,6.251695e-04,0.004707,0.009820,2.470954e-04,0.164599
6,raw_R_step_norm,2.399673e+01,2.543102,2.275924,1.961065e+00,39.097202
7,theta_step_norm,2.301492e+01,0.903518,6.243667,7.877478e-01,23.014917

--------------------------------------------------------------------------------
RESULT SUMMARY: G57
--------------------------------------------------------------------------------
historical_best: 3494.0

V1:
v1_best: 3428.0
v1_gap: 66.0
v1_percent_accuracy: 98.11104751001716

V2:
v2_best: 3434.0
v2_gap: 60.0
v2_percent_accuracy: 98.28277046365197
v2_best_step: 601
v2_best_replica: 24

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 37.53504705429077

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_10_12/logs/G57_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_10_12/best_spins/G57_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_10_12/partial_group_results.csv

################################################################################
RUNNING G58 | edge_list | seed=10
################################################################################
G58 | step     1/2000 | best 14900.0 | acc 77.2301% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G58 | step    50/2000 | best 15519.0 | acc 80.4385% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G58 | step   100/2000 | best 17830.0 | acc 92.4169% | success 0/128 | gamma 0.95048 | |rz| 0.0375
G58 | step   150/2000 | best 18887.0 | acc 97.8956% | success 0/128 | gamma 0.92546 | |rz| 0.4876
G58 | step   200/2000 | best 18944.0 | acc 98.1911% | success 0/128 | gamma 0.90045 | |rz| 0.5651
G58 | step   250/2000 | best 18959.0 | acc 98.2688% | success 0/128 | gamma 0.87544 | |rz| 0.5917
G58 | step   300/2000 | best 18970.0 | acc 98.3258% | success 0/128 | gamma 0.85043 | |rz| 0.6107
G58 | step   350/2000 | best 18984.0 | acc 98.3984% | success 0/128 | gamma 0.82541 | |rz| 0.6276
G58 | step   400/2000 | best 19003.0 | acc 98.4969% | success 0/128 | gamma 0.80040 | |rz| 0.6436
G58 | step   450/2000 | best 19013.0 | acc 98.5487% | success 0/128 | gamma 0.77539 | |rz| 0.6591
G58 | step   500/2000 | best 19021.0 | acc 98.5902% | success 0/128 | gamma 0.75038 | |rz| 0.6743
G58 | step   550/2000 | best 19034.0 | acc 98.6575% | success 0/128 | gamma 0.72536 | |rz| 0.6893
G58 | step   600/2000 | best 19042.0 | acc 98.6990% | success 0/128 | gamma 0.70035 | |rz| 0.7040
G58 | step   650/2000 | best 19049.0 | acc 98.7353% | success 0/128 | gamma 0.67534 | |rz| 0.7185
G58 | step   700/2000 | best 19057.0 | acc 98.7768% | success 0/128 | gamma 0.65033 | |rz| 0.7327
G58 | step   750/2000 | best 19065.0 | acc 98.8182% | success 0/128 | gamma 0.62531 | |rz| 0.7466
G58 | step   800/2000 | best 19067.0 | acc 98.8286% | success 0/128 | gamma 0.60030 | |rz| 0.7602
G58 | step   850/2000 | best 19070.0 | acc 98.8441% | success 0/128 | gamma 0.57529 | |rz| 0.7735
G58 | step   900/2000 | best 19074.0 | acc 98.8649% | success 0/128 | gamma 0.55028 | |rz| 0.7864
G58 | step   950/2000 | best 19077.0 | acc 98.8804% | success 0/128 | gamma 0.52526 | |rz| 0.7990
G58 | step  1000/2000 | best 19080.0 | acc 98.8960% | success 0/128 | gamma 0.50025 | |rz| 0.8110
G58 | step  1050/2000 | best 19083.0 | acc 98.9115% | success 0/128 | gamma 0.47524 | |rz| 0.8226
G58 | step  1100/2000 | best 19085.0 | acc 98.9219% | success 0/128 | gamma 0.45023 | |rz| 0.8337
G58 | step  1150/2000 | best 19087.0 | acc 98.9323% | success 0/128 | gamma 0.42521 | |rz| 0.8442
G58 | step  1200/2000 | best 19088.0 | acc 98.9374% | success 0/128 | gamma 0.40020 | |rz| 0.8542
G58 | step  1250/2000 | best 19088.0 | acc 98.9374% | success 0/128 | gamma 0.37519 | |rz| 0.8638
G58 | step  1300/2000 | best 19088.0 | acc 98.9374% | success 0/128 | gamma 0.35018 | |rz| 0.8729
G58 | step  1350/2000 | best 19088.0 | acc 98.9374% | success 0/128 | gamma 0.32517 | |rz| 0.8814
G58 | step  1400/2000 | best 19088.0 | acc 98.9374% | success 0/128 | gamma 0.30034 | |rz| 0.8894
G58 | step  1450/2000 | best 19088.0 | acc 98.9374% | success 0/128 | gamma 0.27732 | |rz| 0.8964
G58 | step  1500/2000 | best 19088.0 | acc 98.9374% | success 0/128 | gamma 0.26252 | |rz| 0.9012
G58 | step  1550/2000 | best 19088.0 | acc 98.9374% | success 0/128 | gamma 0.26035 | |rz| 0.9036
G58 | step  1600/2000 | best 19088.0 | acc 98.9374% | success 0/128 | gamma 0.25010 | |rz| 0.9073
G58 | step  1650/2000 | best 19089.0 | acc 98.9426% | success 0/128 | gamma 0.21052 | |rz| 0.9154
G58 | step  1700/2000 | best 19089.0 | acc 98.9426% | success 0/128 | gamma 0.16261 | |rz| 0.9228
G58 | step  1750/2000 | best 19089.0 | acc 98.9426% | success 0/128 | gamma 0.12728 | |rz| 0.9269
G58 | step  1800/2000 | best 19089.0 | acc 98.9426% | success 0/128 | gamma 0.10025 | |rz| 0.9294
G58 | step  1850/2000 | best 19089.0 | acc 98.9426% | success 0/128 | gamma 0.07505 | |rz| 0.9313
G58 | step  1900/2000 | best 19089.0 | acc 98.9426% | success 0/128 | gamma 0.05003 | |rz| 0.9328
G58 | step  1950/2000 | best 19089.0 | acc 98.9426% | success 0/128 | gamma 0.02501 | |rz| 0.9343
G58 | step  2000/2000 | best 19089.0 | acc 98.9426% | success 0/128 | gamma 0.00000 | |rz| 0.9428

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G58
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644269e-05,0.000019,0.000009,9.449862e-06,0.000955
1,theta_grad_mean_abs,6.230752e-07,0.000004,0.000005,2.559918e-07,0.000052
2,raw_R_step_mean_abs,2.999592e-02,0.002660,0.002744,1.977987e-03,0.049010
3,theta_step_mean_abs,2.864252e-02,0.000744,0.002082,6.941099e-04,0.028643
4,raw_R_grad_norm,6.115418e-02,0.019661,0.008519,8.518607e-03,0.797532
5,theta_grad_norm,6.247158e-04,0.008494,0.010569,2.488641e-04,0.404751
6,raw_R_step_norm,2.399673e+01,2.343781,2.400823,1.871138e+00,39.211285
7,theta_step_norm,2.301445e+01,1.016833,4.708497,8.819741e-01,23.014446

--------------------------------------------------------------------------------
RESULT SUMMARY: G58
--------------------------------------------------------------------------------
historical_best: 19293.0

V1:
v1_best: 19084.0
v1_gap: 209.0
v1_percent_accuracy: 98.91670554086974

V2:
v2_best: 19089.0
v2_gap: 204.0
v2_percent_accuracy: 98.94262167625564
v2_best_step: 1624
v2_best_replica: 50

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 64.34358286857605

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_10_12/logs/G58_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_10_12/best_spins/G58_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_10_12/partial_group_results.csv

################################################################################
RUNNING G59 | edge_list | seed=11
################################################################################
G59 | step     1/2000 | best 188.0 | acc 3.0891% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G59 | step    50/2000 | best 823.0 | acc 13.5228% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G59 | step   100/2000 | best 5379.0 | acc 88.3832% | success 0/128 | gamma 0.95048 | |rz| 0.1480
G59 | step   150/2000 | best 5794.0 | acc 95.2021% | success 0/128 | gamma 0.92546 | |rz| 0.6145
G59 | step   200/2000 | best 5818.0 | acc 95.5965% | success 0/128 | gamma 0.90045 | |rz| 0.6834
G59 | step   250/2000 | best 5831.0 | acc 95.8101% | success 0/128 | gamma 0.87544 | |rz| 0.7051
G59 | step   300/2000 | best 5835.0 | acc 95.8758% | success 0/128 | gamma 0.85043 | |rz| 0.7194
G59 | step   350/2000 | best 5836.0 | acc 95.8922% | success 0/128 | gamma 0.82541 | |rz| 0.7314
G59 | step   400/2000 | best 5852.0 | acc 96.1551% | success 0/128 | gamma 0.80040 | |rz| 0.7422
G59 | step   450/2000 | best 5855.0 | acc 96.2044% | success 0/128 | gamma 0.77539 | |rz| 0.7524
G59 | step   500/2000 | best 5855.0 | acc 96.2044% | success 0/128 | gamma 0.75038 | |rz| 0.7623
G59 | step   550/2000 | best 5855.0 | acc 96.2044% | success 0/128 | gamma 0.72536 | |rz| 0.7720
G59 | step   600/2000 | best 5856.0 | acc 96.2208% | success 0/128 | gamma 0.70035 | |rz| 0.7813
G59 | step   650/2000 | best 5863.0 | acc 96.3359% | success 0/128 | gamma 0.67534 | |rz| 0.7906
G59 | step   700/2000 | best 5864.0 | acc 96.3523% | success 0/128 | gamma 0.65033 | |rz| 0.7997
G59 | step   750/2000 | best 5866.0 | acc 96.3851% | success 0/128 | gamma 0.62531 | |rz| 0.8086
G59 | step   800/2000 | best 5868.0 | acc 96.4180% | success 0/128 | gamma 0.60030 | |rz| 0.8175
G59 | step   850/2000 | best 5871.0 | acc 96.4673% | success 0/128 | gamma 0.57529 | |rz| 0.8261
G59 | step   900/2000 | best 5872.0 | acc 96.4837% | success 0/128 | gamma 0.55028 | |rz| 0.8345
G59 | step   950/2000 | best 5874.0 | acc 96.5166% | success 0/128 | gamma 0.52526 | |rz| 0.8428
G59 | step  1000/2000 | best 5874.0 | acc 96.5166% | success 0/128 | gamma 0.50025 | |rz| 0.8509
G59 | step  1050/2000 | best 5874.0 | acc 96.5166% | success 0/128 | gamma 0.47524 | |rz| 0.8587
G59 | step  1100/2000 | best 5875.0 | acc 96.5330% | success 0/128 | gamma 0.45023 | |rz| 0.8662
G59 | step  1150/2000 | best 5878.0 | acc 96.5823% | success 0/128 | gamma 0.42521 | |rz| 0.8735
G59 | step  1200/2000 | best 5878.0 | acc 96.5823% | success 0/128 | gamma 0.40020 | |rz| 0.8805
G59 | step  1250/2000 | best 5878.0 | acc 96.5823% | success 0/128 | gamma 0.37519 | |rz| 0.8872
G59 | step  1300/2000 | best 5878.0 | acc 96.5823% | success 0/128 | gamma 0.35018 | |rz| 0.8936
G59 | step  1350/2000 | best 5878.0 | acc 96.5823% | success 0/128 | gamma 0.32517 | |rz| 0.8998
G59 | step  1400/2000 | best 5878.0 | acc 96.5823% | success 0/128 | gamma 0.30034 | |rz| 0.9056
G59 | step  1450/2000 | best 5878.0 | acc 96.5823% | success 0/128 | gamma 0.27732 | |rz| 0.9106
G59 | step  1500/2000 | best 5878.0 | acc 96.5823% | success 0/128 | gamma 0.26252 | |rz| 0.9142
G59 | step  1550/2000 | best 5878.0 | acc 96.5823% | success 0/128 | gamma 0.26035 | |rz| 0.9159
G59 | step  1600/2000 | best 5878.0 | acc 96.5823% | success 0/128 | gamma 0.25010 | |rz| 0.9187
G59 | step  1650/2000 | best 5878.0 | acc 96.5823% | success 0/128 | gamma 0.21052 | |rz| 0.9247
G59 | step  1700/2000 | best 5878.0 | acc 96.5823% | success 0/128 | gamma 0.16261 | |rz| 0.9302
G59 | step  1750/2000 | best 5878.0 | acc 96.5823% | success 0/128 | gamma 0.12728 | |rz| 0.9333
G59 | step  1800/2000 | best 5878.0 | acc 96.5823% | success 0/128 | gamma 0.10025 | |rz| 0.9351
G59 | step  1850/2000 | best 5878.0 | acc 96.5823% | success 0/128 | gamma 0.07505 | |rz| 0.9365
G59 | step  1900/2000 | best 5878.0 | acc 96.5823% | success 0/128 | gamma 0.05003 | |rz| 0.9376
G59 | step  1950/2000 | best 5878.0 | acc 96.5823% | success 0/128 | gamma 0.02501 | |rz| 0.9387
G59 | step  2000/2000 | best 5878.0 | acc 96.5823% | success 0/128 | gamma 0.00000 | |rz| 0.9456

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G59
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644263e-05,0.000023,0.000010,1.043219e-05,0.001261
1,theta_grad_mean_abs,6.237320e-07,0.000008,0.000007,2.569928e-07,0.000117
2,raw_R_step_mean_abs,2.999592e-02,0.002396,0.002377,2.140562e-03,0.051179
3,theta_step_mean_abs,2.864436e-02,0.001008,0.001897,9.169037e-04,0.031005
4,raw_R_grad_norm,6.115414e-02,0.025809,0.009934,9.934116e-03,1.431449
5,theta_grad_norm,6.255170e-04,0.010086,0.013394,2.500746e-04,0.539766
6,raw_R_step_norm,2.399673e+01,2.064227,2.122335,1.893432e+00,41.024887
7,theta_step_norm,2.301525e+01,1.128690,4.552231,8.825134e-01,28.600180

--------------------------------------------------------------------------------
RESULT SUMMARY: G59
--------------------------------------------------------------------------------
historical_best: 6086.0

V1:
v1_best: 5856.0
v1_gap: 230.0
v1_percent_accuracy: 96.22083470259612

V2:
v2_best: 5878.0
v2_gap: 208.0
v2_percent_accuracy: 96.58232007886954
v2_best_step: 1119
v2_best_replica: 90

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 69.239422082901

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_10_12/logs/G59_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_10_12/best_spins/G59_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_10_12/partial_group_results.csv

================================================================================
RUN GROUP COMPLETE
================================================================================
run_group: big_10_12
graphs: 5

Group results:

,run_group,partition,instance,graph_type,storage_mode,nodes,edges,n_steps,replicas,lr,...,final_best,final_gap,final_percent_accuracy,best_step_success_count,best_step_success_probability,ever_success_count,ever_success_probability,final_success_count,final_success_probability,v2_runtime_sec
0,big_10_12,10,G55,plain,edge_list,5000,12498,2000,128,0.03,...,10198.0,101.0,99.019322,0,0.0,0,0.0,0,0.0,48.720069
1,big_10_12,10,G56,plain,edge_list,5000,12498,2000,128,0.03,...,3908.0,109.0,97.286532,0,0.0,0,0.0,0,0.0,47.310549
2,big_10_12,11,G57,toroid,edge_list,5000,10000,2000,128,0.03,...,3434.0,60.0,98.282770,0,0.0,0,0.0,0,0.0,37.535047
3,big_10_12,12,G58,random,edge_list,5000,29570,2000,128,0.03,...,19089.0,204.0,98.942622,0,0.0,0,0.0,0,0.0,64.343583
4,big_10_12,12,G59,random,edge_list,5000,29570,2000,128,0.03,...,5878.0,208.0,96.582320,0,0.0,0,0.0,0,0.0,69.239422

Compact group results:

,instance,historical_best,v1_best,v1_gap,v1_percent_accuracy,v2_best,v2_gap,v2_percent_accuracy,v2_best_step,v2_best_replica,ever_success_count,ever_success_probability,final_best,final_gap,final_percent_accuracy,final_success_count,final_success_probability,v2_runtime_sec
0,G55,10299.0,10195.0,104.0,98.990193,10198.0,101.0,99.019322,1220,38,0,0.0,10198.0,101.0,99.019322,0,0.0,48.720069
1,G56,4017.0,3915.0,102.0,97.460792,3908.0,109.0,97.286532,1117,99,0,0.0,3908.0,109.0,97.286532,0,0.0,47.310549
2,G57,3494.0,3428.0,66.0,98.111048,3434.0,60.0,98.282770,601,24,0,0.0,3434.0,60.0,98.282770,0,0.0,37.535047
3,G58,19293.0,19084.0,209.0,98.916706,19089.0,204.0,98.942622,1624,50,0,0.0,19089.0,204.0,98.942622,0,0.0,64.343583
4,G59,6086.0,5856.0,230.0,96.220835,5878.0,208.0,96.582320,1119,90,0,0.0,5878.0,208.0,96.582320,0,0.0,69.239422

Saved group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_10_12/group_results.csv

Saved group logs:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_10_12/group_training_logs.csv

================================================================================
COMPACT GROUP RESULT
================================================================================

,instance,historical_best,v1_best,v1_gap,v1_percent_accuracy,v2_best,v2_gap,v2_percent_accuracy,v2_best_step,v2_best_replica,ever_success_count,ever_success_probability,final_best,final_gap,final_percent_accuracy,final_success_count,final_success_probability,v2_runtime_sec
0,G55,10299.0,10195.0,104.0,98.990193,10198.0,101.0,99.019322,1220,38,0,0.0,10198.0,101.0,99.019322,0,0.0,48.720069
1,G56,4017.0,3915.0,102.0,97.460792,3908.0,109.0,97.286532,1117,99,0,0.0,3908.0,109.0,97.286532,0,0.0,47.310549
2,G57,3494.0,3428.0,66.0,98.111048,3434.0,60.0,98.282770,601,24,0,0.0,3434.0,60.0,98.282770,0,0.0,37.535047
3,G58,19293.0,19084.0,209.0,98.916706,19089.0,204.0,98.942622,1624,50,0,0.0,19089.0,204.0,98.942622,0,0.0,64.343583
4,G59,6086.0,5856.0,230.0,96.220835,5878.0,208.0,96.582320,1119,90,0,0.0,5878.0,208.0,96.582320,0,0.0,69.239422

In [108]:
print("\nGroup summary:")
print("graphs:", len(group_results_df))
print("mean v1 accuracy %:", float(group_results_df["v1_percent_accuracy"].mean()))
print("mean v2 accuracy %:", float(group_results_df["v2_percent_accuracy"].mean()))
print("v1 gap-zero count:", int((group_results_df["v1_gap"] == 0).sum()))
print("v2 gap-zero count:", int((group_results_df["v2_gap"] == 0).sum()))
print("total v2 runtime sec:", float(group_results_df["v2_runtime_sec"].sum()))

Group summary:
graphs: 5
mean v1 accuracy %: 97.93991452233497
mean v2 accuracy %: 98.02271334421263
v1 gap-zero count: 0
v2 gap-zero count: 0
total v2 runtime sec: 267.14866971969604

In [109]:
# ============================================================
# Quick inspection: where did V2 improve over V1?
# ============================================================

inspection_df = group_results_df[
    [
        "instance",
        "historical_best",
        "v1_best",
        "v1_gap",
        "v1_percent_accuracy",
        "v2_best",
        "v2_gap",
        "v2_percent_accuracy",
        "v2_best_step",
        "ever_success_count",
        "ever_success_probability",
        "final_best",
        "final_gap",
        "final_percent_accuracy",
    ]
].copy()

inspection_df["gap_improvement"] = (
    inspection_df["v1_gap"] - inspection_df["v2_gap"]
)

inspection_df["accuracy_improvement"] = (
    inspection_df["v2_percent_accuracy"] - inspection_df["v1_percent_accuracy"]
)

inspection_df = inspection_df.sort_values(
    "gap_improvement",
    ascending=False,
).reset_index(drop=True)

print("=" * 80)
print("V2 IMPROVEMENT INSPECTION")
print("=" * 80)

display(inspection_df)

print("\nSummary:")
print("graphs:", len(inspection_df))
print("improved gap count:", int((inspection_df["gap_improvement"] > 0).sum()))
print("same gap count    :", int((inspection_df["gap_improvement"] == 0).sum()))
print("worse gap count   :", int((inspection_df["gap_improvement"] < 0).sum()))

print("\nGap improvement:")
print("mean:", float(inspection_df["gap_improvement"].mean()))
print("min :", float(inspection_df["gap_improvement"].min()))
print("max :", float(inspection_df["gap_improvement"].max()))

print("\nAccuracy improvement:")
print("mean:", float(inspection_df["accuracy_improvement"].mean()))
print("min :", float(inspection_df["accuracy_improvement"].min()))
print("max :", float(inspection_df["accuracy_improvement"].max()))

print("\nClosest V2 gaps:")
display(
    inspection_df.sort_values("v2_gap")[
        [
            "instance",
            "historical_best",
            "v2_best",
            "v2_gap",
            "v2_percent_accuracy",
            "v2_best_step",
            "ever_success_count",
            "final_gap",
        ]
    ].head(10)
)

================================================================================
V2 IMPROVEMENT INSPECTION
================================================================================

,instance,historical_best,v1_best,v1_gap,v1_percent_accuracy,v2_best,v2_gap,v2_percent_accuracy,v2_best_step,ever_success_count,ever_success_probability,final_best,final_gap,final_percent_accuracy,gap_improvement,accuracy_improvement
0,G59,6086.0,5856.0,230.0,96.220835,5878.0,208.0,96.582320,1119,0,0.0,5878.0,208.0,96.582320,22.0,0.361485
1,G57,3494.0,3428.0,66.0,98.111048,3434.0,60.0,98.282770,601,0,0.0,3434.0,60.0,98.282770,6.0,0.171723
2,G58,19293.0,19084.0,209.0,98.916706,19089.0,204.0,98.942622,1624,0,0.0,19089.0,204.0,98.942622,5.0,0.025916
3,G55,10299.0,10195.0,104.0,98.990193,10198.0,101.0,99.019322,1220,0,0.0,10198.0,101.0,99.019322,3.0,0.029129
4,G56,4017.0,3915.0,102.0,97.460792,3908.0,109.0,97.286532,1117,0,0.0,3908.0,109.0,97.286532,-7.0,-0.174259

Summary:
graphs: 5
improved gap count: 4
same gap count    : 0
worse gap count   : 1

Gap improvement:
mean: 5.8
min : -7.0
max : 22.0

Accuracy improvement:
mean: 0.08279882187766248
min : -0.17425939756036257
max : 0.36148537627342137

Closest V2 gaps:

,instance,historical_best,v2_best,v2_gap,v2_percent_accuracy,v2_best_step,ever_success_count,final_gap
1,G57,3494.0,3434.0,60.0,98.282770,601,0,60.0
3,G55,10299.0,10198.0,101.0,99.019322,1220,0,101.0
4,G56,4017.0,3908.0,109.0,97.286532,1117,0,109.0
2,G58,19293.0,19089.0,204.0,98.942622,1624,0,204.0
0,G59,6086.0,5878.0,208.0,96.582320,1119,0,208.0

# 4

In [110]:
# ============================================================
# Cell 10: Select run group and run QEFEM v2
# ============================================================

# ------------------------------------------------------------
# Choose run group here
# ------------------------------------------------------------
# 0 -> small_1_3   : G1-G21
# 1 -> small_4_6   : G22-G42
# 2 -> small_7_9   : G43-G54
# 3 -> big_10_12   : G55-G59
# 4 -> big_13_15   : G60-G64
# 5 -> big_16_18   : G65, G66, G67, G72
# 6 -> big_19_21   : G70, G77, G81

RUN_GROUP_INDEX = 4


# ------------------------------------------------------------
# Preview selected group
# ------------------------------------------------------------

selected_group_row = run_group_summary_df.iloc[RUN_GROUP_INDEX]

print("=" * 80)
print("SELECTED RUN GROUP")
print("=" * 80)

print("RUN_GROUP_INDEX:", RUN_GROUP_INDEX)
print("run_group:", selected_group_row["run_group"])
print("partitions:", selected_group_row["partitions"])
print("graphs_start:", selected_group_row["graphs_start"])
print("graphs_end:", selected_group_row["graphs_end"])
print("num_graphs:", selected_group_row["num_graphs"])
print("graph_types:", selected_group_row["graph_types"])
print("storage_modes:", selected_group_row["storage_modes"])
print("graphs:", selected_group_row["graphs"])


# ------------------------------------------------------------
# Run selected group
# ------------------------------------------------------------

group_results_df, group_logs_df = run_qefem_run_group(
    run_group_index=RUN_GROUP_INDEX
)


# ------------------------------------------------------------
# Final compact display
# ------------------------------------------------------------

compact_group_results_df = group_results_df[
    [
        "instance",
        "historical_best",
        "v1_best",
        "v1_gap",
        "v1_percent_accuracy",
        "v2_best",
        "v2_gap",
        "v2_percent_accuracy",
        "v2_best_step",
        "v2_best_replica",
        "ever_success_count",
        "ever_success_probability",
        "final_best",
        "final_gap",
        "final_percent_accuracy",
        "final_success_count",
        "final_success_probability",
        "v2_runtime_sec",
    ]
].copy()

print("\n" + "=" * 80)
print("COMPACT GROUP RESULT")
print("=" * 80)

display(compact_group_results_df)

================================================================================
SELECTED RUN GROUP
================================================================================
RUN_GROUP_INDEX: 4
run_group: big_13_15
partitions: [13, 14, 15]
graphs_start: G60
graphs_end: G64
num_graphs: 5
graph_types: ['plain', 'random', 'toroid']
storage_modes: ['edge_list']
graphs: ['G60', 'G61', 'G62', 'G63', 'G64']
================================================================================
RUNNING QEFEM V2 RUN GROUP
================================================================================
run_group_index: 4
run_group: big_13_15
graphs: ['G60', 'G61', 'G62', 'G63', 'G64']
num graphs: 5

Output directory:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_13_15

Selected benchmark rows:

,partition,instance,graph_type,storage_mode,nodes,edges,n_steps,replicas,lr,v1_best,historical_best,v1_gap,v1_percent_accuracy,v1_best_replica,v1_runtime_sec
0,13,G60,plain,edge_list,7000,17148,1000,128,0.01,14037.0,14188.0,151.0,98.935720,116,21.746036
1,13,G61,plain,edge_list,7000,17148,1000,128,0.01,5642.0,5796.0,154.0,97.342995,125,32.743163
2,14,G62,toroid,edge_list,7000,14000,1000,128,0.01,4790.0,4870.0,80.0,98.357290,97,33.244787
3,15,G63,random,edge_list,7000,41459,1000,128,0.01,26753.0,27047.0,294.0,98.913003,94,56.380865
4,15,G64,random,edge_list,7000,41459,1000,128,0.01,8415.0,8751.0,336.0,96.160439,113,57.947060

################################################################################
RUNNING G60 | edge_list | seed=7
################################################################################
G60 | step     1/2000 | best 8673.0 | acc 61.1291% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G60 | step    50/2000 | best 9188.0 | acc 64.7590% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G60 | step   100/2000 | best 9234.0 | acc 65.0832% | success 0/128 | gamma 0.95048 | |rz| 0.0011
G60 | step   150/2000 | best 13877.0 | acc 97.8080% | success 0/128 | gamma 0.92546 | |rz| 0.4449
G60 | step   200/2000 | best 13917.0 | acc 98.0899% | success 0/128 | gamma 0.90045 | |rz| 0.5606
G60 | step   250/2000 | best 13929.0 | acc 98.1745% | success 0/128 | gamma 0.87544 | |rz| 0.5927
G60 | step   300/2000 | best 13954.0 | acc 98.3507% | success 0/128 | gamma 0.85043 | |rz| 0.6135
G60 | step   350/2000 | best 13965.0 | acc 98.4282% | success 0/128 | gamma 0.82541 | |rz| 0.6313
G60 | step   400/2000 | best 13974.0 | acc 98.4917% | success 0/128 | gamma 0.80040 | |rz| 0.6477
G60 | step   450/2000 | best 13987.0 | acc 98.5833% | success 0/128 | gamma 0.77539 | |rz| 0.6635
G60 | step   500/2000 | best 14002.0 | acc 98.6890% | success 0/128 | gamma 0.75038 | |rz| 0.6787
G60 | step   550/2000 | best 14008.0 | acc 98.7313% | success 0/128 | gamma 0.72536 | |rz| 0.6935
G60 | step   600/2000 | best 14012.0 | acc 98.7595% | success 0/128 | gamma 0.70035 | |rz| 0.7079
G60 | step   650/2000 | best 14019.0 | acc 98.8089% | success 0/128 | gamma 0.67534 | |rz| 0.7219
G60 | step   700/2000 | best 14022.0 | acc 98.8300% | success 0/128 | gamma 0.65033 | |rz| 0.7356
G60 | step   750/2000 | best 14023.0 | acc 98.8370% | success 0/128 | gamma 0.62531 | |rz| 0.7489
G60 | step   800/2000 | best 14025.0 | acc 98.8511% | success 0/128 | gamma 0.60030 | |rz| 0.7619
G60 | step   850/2000 | best 14027.0 | acc 98.8652% | success 0/128 | gamma 0.57529 | |rz| 0.7746
G60 | step   900/2000 | best 14028.0 | acc 98.8723% | success 0/128 | gamma 0.55028 | |rz| 0.7869
G60 | step   950/2000 | best 14031.0 | acc 98.8934% | success 0/128 | gamma 0.52526 | |rz| 0.7988
G60 | step  1000/2000 | best 14031.0 | acc 98.8934% | success 0/128 | gamma 0.50025 | |rz| 0.8103
G60 | step  1050/2000 | best 14031.0 | acc 98.8934% | success 0/128 | gamma 0.47524 | |rz| 0.8214
G60 | step  1100/2000 | best 14032.0 | acc 98.9005% | success 0/128 | gamma 0.45023 | |rz| 0.8321
G60 | step  1150/2000 | best 14032.0 | acc 98.9005% | success 0/128 | gamma 0.42521 | |rz| 0.8424
G60 | step  1200/2000 | best 14033.0 | acc 98.9075% | success 0/128 | gamma 0.40020 | |rz| 0.8524
G60 | step  1250/2000 | best 14033.0 | acc 98.9075% | success 0/128 | gamma 0.37519 | |rz| 0.8621
G60 | step  1300/2000 | best 14034.0 | acc 98.9146% | success 0/128 | gamma 0.35018 | |rz| 0.8717
G60 | step  1350/2000 | best 14035.0 | acc 98.9216% | success 0/128 | gamma 0.32517 | |rz| 0.8810
G60 | step  1400/2000 | best 14035.0 | acc 98.9216% | success 0/128 | gamma 0.30034 | |rz| 0.8896
G60 | step  1450/2000 | best 14035.0 | acc 98.9216% | success 0/128 | gamma 0.27732 | |rz| 0.8973
G60 | step  1500/2000 | best 14035.0 | acc 98.9216% | success 0/128 | gamma 0.26252 | |rz| 0.9027
G60 | step  1550/2000 | best 14035.0 | acc 98.9216% | success 0/128 | gamma 0.26035 | |rz| 0.9054
G60 | step  1600/2000 | best 14035.0 | acc 98.9216% | success 0/128 | gamma 0.25010 | |rz| 0.9096
G60 | step  1650/2000 | best 14035.0 | acc 98.9216% | success 0/128 | gamma 0.21052 | |rz| 0.9184
G60 | step  1700/2000 | best 14035.0 | acc 98.9216% | success 0/128 | gamma 0.16261 | |rz| 0.9268
G60 | step  1750/2000 | best 14035.0 | acc 98.9216% | success 0/128 | gamma 0.12728 | |rz| 0.9316
G60 | step  1800/2000 | best 14035.0 | acc 98.9216% | success 0/128 | gamma 0.10025 | |rz| 0.9345
G60 | step  1850/2000 | best 14035.0 | acc 98.9216% | success 0/128 | gamma 0.07505 | |rz| 0.9368
G60 | step  1900/2000 | best 14035.0 | acc 98.9216% | success 0/128 | gamma 0.05003 | |rz| 0.9385
G60 | step  1950/2000 | best 14035.0 | acc 98.9216% | success 0/128 | gamma 0.02501 | |rz| 0.9398
G60 | step  2000/2000 | best 14035.0 | acc 98.9216% | success 0/128 | gamma 0.00000 | |rz| 0.9459

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G60
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644271e-05,0.000017,0.000009,8.852629e-06,0.000933
1,theta_grad_mean_abs,6.236085e-07,0.000004,0.000003,2.595691e-07,0.000134
2,raw_R_step_mean_abs,2.999592e-02,0.002667,0.002808,2.098842e-03,0.048871
3,theta_step_mean_abs,2.864709e-02,0.000806,0.001639,6.814178e-04,0.028647
4,raw_R_grad_norm,7.235862e-02,0.017374,0.008932,8.931702e-03,0.883072
5,theta_grad_norm,7.395877e-04,0.007232,0.008493,2.926093e-04,0.304975
6,raw_R_step_norm,2.839332e+01,2.742927,2.913414,2.376520e+00,46.260273
7,theta_step_norm,2.723414e+01,1.298649,5.278039,1.041000e+00,27.234140

--------------------------------------------------------------------------------
RESULT SUMMARY: G60
--------------------------------------------------------------------------------
historical_best: 14188.0

V1:
v1_best: 14037.0
v1_gap: 151.0
v1_percent_accuracy: 98.93572032703692

V2:
v2_best: 14035.0
v2_gap: 153.0
v2_percent_accuracy: 98.92162390752749
v2_best_step: 1316
v2_best_replica: 113

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 58.046552896499634

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_13_15/logs/G60_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_13_15/best_spins/G60_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_13_15/partial_group_results.csv

################################################################################
RUNNING G61 | edge_list | seed=8
################################################################################
G61 | step     1/2000 | best 293.0 | acc 5.0552% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G61 | step    50/2000 | best 786.0 | acc 13.5611% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G61 | step   100/2000 | best 818.0 | acc 14.1132% | success 0/128 | gamma 0.95048 | |rz| 0.0010
G61 | step   150/2000 | best 5474.0 | acc 94.4444% | success 0/128 | gamma 0.92546 | |rz| 0.4536
G61 | step   200/2000 | best 5540.0 | acc 95.5832% | success 0/128 | gamma 0.90045 | |rz| 0.5614
G61 | step   250/2000 | best 5562.0 | acc 95.9627% | success 0/128 | gamma 0.87544 | |rz| 0.5927
G61 | step   300/2000 | best 5569.0 | acc 96.0835% | success 0/128 | gamma 0.85043 | |rz| 0.6134
G61 | step   350/2000 | best 5582.0 | acc 96.3078% | success 0/128 | gamma 0.82541 | |rz| 0.6312
G61 | step   400/2000 | best 5594.0 | acc 96.5148% | success 0/128 | gamma 0.80040 | |rz| 0.6477
G61 | step   450/2000 | best 5606.0 | acc 96.7219% | success 0/128 | gamma 0.77539 | |rz| 0.6634
G61 | step   500/2000 | best 5617.0 | acc 96.9117% | success 0/128 | gamma 0.75038 | |rz| 0.6786
G61 | step   550/2000 | best 5622.0 | acc 96.9979% | success 0/128 | gamma 0.72536 | |rz| 0.6933
G61 | step   600/2000 | best 5627.0 | acc 97.0842% | success 0/128 | gamma 0.70035 | |rz| 0.7077
G61 | step   650/2000 | best 5635.0 | acc 97.2222% | success 0/128 | gamma 0.67534 | |rz| 0.7217
G61 | step   700/2000 | best 5639.0 | acc 97.2912% | success 0/128 | gamma 0.65033 | |rz| 0.7354
G61 | step   750/2000 | best 5643.0 | acc 97.3602% | success 0/128 | gamma 0.62531 | |rz| 0.7487
G61 | step   800/2000 | best 5643.0 | acc 97.3602% | success 0/128 | gamma 0.60030 | |rz| 0.7617
G61 | step   850/2000 | best 5646.0 | acc 97.4120% | success 0/128 | gamma 0.57529 | |rz| 0.7743
G61 | step   900/2000 | best 5647.0 | acc 97.4293% | success 0/128 | gamma 0.55028 | |rz| 0.7866
G61 | step   950/2000 | best 5650.0 | acc 97.4810% | success 0/128 | gamma 0.52526 | |rz| 0.7985
G61 | step  1000/2000 | best 5650.0 | acc 97.4810% | success 0/128 | gamma 0.50025 | |rz| 0.8100
G61 | step  1050/2000 | best 5651.0 | acc 97.4983% | success 0/128 | gamma 0.47524 | |rz| 0.8211
G61 | step  1100/2000 | best 5651.0 | acc 97.4983% | success 0/128 | gamma 0.45023 | |rz| 0.8318
G61 | step  1150/2000 | best 5651.0 | acc 97.4983% | success 0/128 | gamma 0.42521 | |rz| 0.8421
G61 | step  1200/2000 | best 5652.0 | acc 97.5155% | success 0/128 | gamma 0.40020 | |rz| 0.8521
G61 | step  1250/2000 | best 5652.0 | acc 97.5155% | success 0/128 | gamma 0.37519 | |rz| 0.8618
G61 | step  1300/2000 | best 5652.0 | acc 97.5155% | success 0/128 | gamma 0.35018 | |rz| 0.8714
G61 | step  1350/2000 | best 5653.0 | acc 97.5328% | success 0/128 | gamma 0.32517 | |rz| 0.8806
G61 | step  1400/2000 | best 5653.0 | acc 97.5328% | success 0/128 | gamma 0.30034 | |rz| 0.8893
G61 | step  1450/2000 | best 5653.0 | acc 97.5328% | success 0/128 | gamma 0.27732 | |rz| 0.8969
G61 | step  1500/2000 | best 5653.0 | acc 97.5328% | success 0/128 | gamma 0.26252 | |rz| 0.9024
G61 | step  1550/2000 | best 5654.0 | acc 97.5500% | success 0/128 | gamma 0.26035 | |rz| 0.9051
G61 | step  1600/2000 | best 5654.0 | acc 97.5500% | success 0/128 | gamma 0.25010 | |rz| 0.9092
G61 | step  1650/2000 | best 5654.0 | acc 97.5500% | success 0/128 | gamma 0.21052 | |rz| 0.9181
G61 | step  1700/2000 | best 5654.0 | acc 97.5500% | success 0/128 | gamma 0.16261 | |rz| 0.9264
G61 | step  1750/2000 | best 5654.0 | acc 97.5500% | success 0/128 | gamma 0.12728 | |rz| 0.9312
G61 | step  1800/2000 | best 5654.0 | acc 97.5500% | success 0/128 | gamma 0.10025 | |rz| 0.9342
G61 | step  1850/2000 | best 5654.0 | acc 97.5500% | success 0/128 | gamma 0.07505 | |rz| 0.9365
G61 | step  1900/2000 | best 5654.0 | acc 97.5500% | success 0/128 | gamma 0.05003 | |rz| 0.9382
G61 | step  1950/2000 | best 5654.0 | acc 97.5500% | success 0/128 | gamma 0.02501 | |rz| 0.9395
G61 | step  2000/2000 | best 5654.0 | acc 97.5500% | success 0/128 | gamma 0.00000 | |rz| 0.9456

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G61
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644273e-05,0.000017,0.000009,8.874390e-06,0.000933
1,theta_grad_mean_abs,6.237401e-07,0.000004,0.000004,2.594110e-07,0.000108
2,raw_R_step_mean_abs,2.999592e-02,0.002661,0.002807,2.091306e-03,0.048871
3,theta_step_mean_abs,2.864414e-02,0.000838,0.001678,7.438707e-04,0.028644
4,raw_R_grad_norm,7.235865e-02,0.017303,0.008952,8.951603e-03,0.883090
5,theta_grad_norm,7.400107e-04,0.006536,0.008875,2.924480e-04,0.279825
6,raw_R_step_norm,2.839332e+01,2.725029,2.913479,2.355571e+00,46.260410
7,theta_step_norm,2.723234e+01,1.180551,5.308300,1.041583e+00,27.232338

--------------------------------------------------------------------------------
RESULT SUMMARY: G61
--------------------------------------------------------------------------------
historical_best: 5796.0

V1:
v1_best: 5642.0
v1_gap: 154.0
v1_percent_accuracy: 97.34299516908212

V2:
v2_best: 5654.0
v2_gap: 142.0
v2_percent_accuracy: 97.55003450655624
v2_best_step: 1535
v2_best_replica: 54

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 56.68682527542114

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_13_15/logs/G61_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_13_15/best_spins/G61_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_13_15/partial_group_results.csv

################################################################################
RUNNING G62 | edge_list | seed=9
################################################################################
G62 | step     1/2000 | best 44.0 | acc 0.9035% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G62 | step    50/2000 | best 474.0 | acc 9.7331% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G62 | step   100/2000 | best 586.0 | acc 12.0329% | success 0/128 | gamma 0.95048 | |rz| 0.0010
G62 | step   150/2000 | best 4732.0 | acc 97.1663% | success 0/128 | gamma 0.92546 | |rz| 0.3522
G62 | step   200/2000 | best 4758.0 | acc 97.7002% | success 0/128 | gamma 0.90045 | |rz| 0.4939
G62 | step   250/2000 | best 4762.0 | acc 97.7823% | success 0/128 | gamma 0.87544 | |rz| 0.5491
G62 | step   300/2000 | best 4764.0 | acc 97.8234% | success 0/128 | gamma 0.85043 | |rz| 0.5822
G62 | step   350/2000 | best 4768.0 | acc 97.9055% | success 0/128 | gamma 0.82541 | |rz| 0.6093
G62 | step   400/2000 | best 4770.0 | acc 97.9466% | success 0/128 | gamma 0.80040 | |rz| 0.6337
G62 | step   450/2000 | best 4770.0 | acc 97.9466% | success 0/128 | gamma 0.77539 | |rz| 0.6561
G62 | step   500/2000 | best 4770.0 | acc 97.9466% | success 0/128 | gamma 0.75038 | |rz| 0.6770
G62 | step   550/2000 | best 4770.0 | acc 97.9466% | success 0/128 | gamma 0.72536 | |rz| 0.6965
G62 | step   600/2000 | best 4770.0 | acc 97.9466% | success 0/128 | gamma 0.70035 | |rz| 0.7147
G62 | step   650/2000 | best 4770.0 | acc 97.9466% | success 0/128 | gamma 0.67534 | |rz| 0.7318
G62 | step   700/2000 | best 4770.0 | acc 97.9466% | success 0/128 | gamma 0.65033 | |rz| 0.7478
G62 | step   750/2000 | best 4770.0 | acc 97.9466% | success 0/128 | gamma 0.62531 | |rz| 0.7628
G62 | step   800/2000 | best 4770.0 | acc 97.9466% | success 0/128 | gamma 0.60030 | |rz| 0.7768
G62 | step   850/2000 | best 4770.0 | acc 97.9466% | success 0/128 | gamma 0.57529 | |rz| 0.7900
G62 | step   900/2000 | best 4770.0 | acc 97.9466% | success 0/128 | gamma 0.55028 | |rz| 0.8023
G62 | step   950/2000 | best 4770.0 | acc 97.9466% | success 0/128 | gamma 0.52526 | |rz| 0.8139
G62 | step  1000/2000 | best 4770.0 | acc 97.9466% | success 0/128 | gamma 0.50025 | |rz| 0.8247
G62 | step  1050/2000 | best 4770.0 | acc 97.9466% | success 0/128 | gamma 0.47524 | |rz| 0.8348
G62 | step  1100/2000 | best 4770.0 | acc 97.9466% | success 0/128 | gamma 0.45023 | |rz| 0.8443
G62 | step  1150/2000 | best 4770.0 | acc 97.9466% | success 0/128 | gamma 0.42521 | |rz| 0.8532
G62 | step  1200/2000 | best 4770.0 | acc 97.9466% | success 0/128 | gamma 0.40020 | |rz| 0.8614
G62 | step  1250/2000 | best 4770.0 | acc 97.9466% | success 0/128 | gamma 0.37519 | |rz| 0.8691
G62 | step  1300/2000 | best 4770.0 | acc 97.9466% | success 0/128 | gamma 0.35018 | |rz| 0.8763
G62 | step  1350/2000 | best 4770.0 | acc 97.9466% | success 0/128 | gamma 0.32517 | |rz| 0.8829
G62 | step  1400/2000 | best 4770.0 | acc 97.9466% | success 0/128 | gamma 0.30034 | |rz| 0.8891
G62 | step  1450/2000 | best 4770.0 | acc 97.9466% | success 0/128 | gamma 0.27732 | |rz| 0.8944
G62 | step  1500/2000 | best 4770.0 | acc 97.9466% | success 0/128 | gamma 0.26252 | |rz| 0.8980
G62 | step  1550/2000 | best 4770.0 | acc 97.9466% | success 0/128 | gamma 0.26035 | |rz| 0.8994
G62 | step  1600/2000 | best 4770.0 | acc 97.9466% | success 0/128 | gamma 0.25010 | |rz| 0.9021
G62 | step  1650/2000 | best 4770.0 | acc 97.9466% | success 0/128 | gamma 0.21052 | |rz| 0.9085
G62 | step  1700/2000 | best 4770.0 | acc 97.9466% | success 0/128 | gamma 0.16261 | |rz| 0.9140
G62 | step  1750/2000 | best 4770.0 | acc 97.9466% | success 0/128 | gamma 0.12728 | |rz| 0.9168
G62 | step  1800/2000 | best 4770.0 | acc 97.9466% | success 0/128 | gamma 0.10025 | |rz| 0.9180
G62 | step  1850/2000 | best 4770.0 | acc 97.9466% | success 0/128 | gamma 0.07505 | |rz| 0.9185
G62 | step  1900/2000 | best 4770.0 | acc 97.9466% | success 0/128 | gamma 0.05003 | |rz| 0.9191
G62 | step  1950/2000 | best 4770.0 | acc 97.9466% | success 0/128 | gamma 0.02501 | |rz| 0.9200
G62 | step  2000/2000 | best 4770.0 | acc 97.9466% | success 0/128 | gamma 0.00000 | |rz| 0.9301

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G62
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644270e-05,0.000017,0.000008,7.838719e-06,0.000933
1,theta_grad_mean_abs,6.234674e-07,0.000003,0.000005,2.603826e-07,0.000114
2,raw_R_step_mean_abs,2.999592e-02,0.002992,0.002664,2.216058e-03,0.048871
3,theta_step_mean_abs,2.864273e-02,0.000754,0.002308,7.137326e-04,0.028643
4,raw_R_grad_norm,7.235861e-02,0.017302,0.007835,7.835428e-03,0.883092
5,theta_grad_norm,7.395613e-04,0.005553,0.011435,2.921301e-04,0.192993
6,raw_R_step_norm,2.839332e+01,3.011886,2.697010,2.319542e+00,46.260433
7,theta_step_norm,2.723156e+01,1.065138,7.196621,9.328628e-01,27.231556

--------------------------------------------------------------------------------
RESULT SUMMARY: G62
--------------------------------------------------------------------------------
historical_best: 4870.0

V1:
v1_best: 4790.0
v1_gap: 80.0
v1_percent_accuracy: 98.35728952772074

V2:
v2_best: 4770.0
v2_gap: 100.0
v2_percent_accuracy: 97.94661190965093
v2_best_step: 352
v2_best_replica: 84

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 50.14632511138916

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_13_15/logs/G62_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_13_15/best_spins/G62_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_13_15/partial_group_results.csv

################################################################################
RUNNING G63 | edge_list | seed=10
################################################################################
G63 | step     1/2000 | best 20802.0 | acc 76.9106% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G63 | step    50/2000 | best 21795.0 | acc 80.5819% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G63 | step   100/2000 | best 25040.0 | acc 92.5796% | success 0/128 | gamma 0.95048 | |rz| 0.0427
G63 | step   150/2000 | best 26497.0 | acc 97.9665% | success 0/128 | gamma 0.92546 | |rz| 0.4891
G63 | step   200/2000 | best 26587.0 | acc 98.2993% | success 0/128 | gamma 0.90045 | |rz| 0.5657
G63 | step   250/2000 | best 26617.0 | acc 98.4102% | success 0/128 | gamma 0.87544 | |rz| 0.5920
G63 | step   300/2000 | best 26640.0 | acc 98.4952% | success 0/128 | gamma 0.85043 | |rz| 0.6110
G63 | step   350/2000 | best 26647.0 | acc 98.5211% | success 0/128 | gamma 0.82541 | |rz| 0.6277
G63 | step   400/2000 | best 26658.0 | acc 98.5618% | success 0/128 | gamma 0.80040 | |rz| 0.6436
G63 | step   450/2000 | best 26673.0 | acc 98.6172% | success 0/128 | gamma 0.77539 | |rz| 0.6591
G63 | step   500/2000 | best 26691.0 | acc 98.6838% | success 0/128 | gamma 0.75038 | |rz| 0.6742
G63 | step   550/2000 | best 26698.0 | acc 98.7097% | success 0/128 | gamma 0.72536 | |rz| 0.6892
G63 | step   600/2000 | best 26705.0 | acc 98.7355% | success 0/128 | gamma 0.70035 | |rz| 0.7038
G63 | step   650/2000 | best 26713.0 | acc 98.7651% | success 0/128 | gamma 0.67534 | |rz| 0.7182
G63 | step   700/2000 | best 26720.0 | acc 98.7910% | success 0/128 | gamma 0.65033 | |rz| 0.7324
G63 | step   750/2000 | best 26725.0 | acc 98.8095% | success 0/128 | gamma 0.62531 | |rz| 0.7463
G63 | step   800/2000 | best 26737.0 | acc 98.8538% | success 0/128 | gamma 0.60030 | |rz| 0.7599
G63 | step   850/2000 | best 26744.0 | acc 98.8797% | success 0/128 | gamma 0.57529 | |rz| 0.7732
G63 | step   900/2000 | best 26748.0 | acc 98.8945% | success 0/128 | gamma 0.55028 | |rz| 0.7861
G63 | step   950/2000 | best 26752.0 | acc 98.9093% | success 0/128 | gamma 0.52526 | |rz| 0.7987
G63 | step  1000/2000 | best 26754.0 | acc 98.9167% | success 0/128 | gamma 0.50025 | |rz| 0.8107
G63 | step  1050/2000 | best 26756.0 | acc 98.9241% | success 0/128 | gamma 0.47524 | |rz| 0.8223
G63 | step  1100/2000 | best 26756.0 | acc 98.9241% | success 0/128 | gamma 0.45023 | |rz| 0.8334
G63 | step  1150/2000 | best 26756.0 | acc 98.9241% | success 0/128 | gamma 0.42521 | |rz| 0.8439
G63 | step  1200/2000 | best 26757.0 | acc 98.9278% | success 0/128 | gamma 0.40020 | |rz| 0.8539
G63 | step  1250/2000 | best 26758.0 | acc 98.9315% | success 0/128 | gamma 0.37519 | |rz| 0.8635
G63 | step  1300/2000 | best 26760.0 | acc 98.9389% | success 0/128 | gamma 0.35018 | |rz| 0.8727
G63 | step  1350/2000 | best 26762.0 | acc 98.9463% | success 0/128 | gamma 0.32517 | |rz| 0.8813
G63 | step  1400/2000 | best 26762.0 | acc 98.9463% | success 0/128 | gamma 0.30034 | |rz| 0.8893
G63 | step  1450/2000 | best 26763.0 | acc 98.9500% | success 0/128 | gamma 0.27732 | |rz| 0.8963
G63 | step  1500/2000 | best 26764.0 | acc 98.9537% | success 0/128 | gamma 0.26252 | |rz| 0.9013
G63 | step  1550/2000 | best 26764.0 | acc 98.9537% | success 0/128 | gamma 0.26035 | |rz| 0.9036
G63 | step  1600/2000 | best 26764.0 | acc 98.9537% | success 0/128 | gamma 0.25010 | |rz| 0.9074
G63 | step  1650/2000 | best 26765.0 | acc 98.9574% | success 0/128 | gamma 0.21052 | |rz| 0.9156
G63 | step  1700/2000 | best 26765.0 | acc 98.9574% | success 0/128 | gamma 0.16261 | |rz| 0.9230
G63 | step  1750/2000 | best 26765.0 | acc 98.9574% | success 0/128 | gamma 0.12728 | |rz| 0.9271
G63 | step  1800/2000 | best 26765.0 | acc 98.9574% | success 0/128 | gamma 0.10025 | |rz| 0.9296
G63 | step  1850/2000 | best 26765.0 | acc 98.9574% | success 0/128 | gamma 0.07505 | |rz| 0.9315
G63 | step  1900/2000 | best 26765.0 | acc 98.9574% | success 0/128 | gamma 0.05003 | |rz| 0.9330
G63 | step  1950/2000 | best 26765.0 | acc 98.9574% | success 0/128 | gamma 0.02501 | |rz| 0.9344
G63 | step  2000/2000 | best 26765.0 | acc 98.9574% | success 0/128 | gamma 0.00000 | |rz| 0.9431

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G63
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644261e-05,0.000019,0.000009,9.490383e-06,0.000962
1,theta_grad_mean_abs,6.231837e-07,0.000004,0.000006,2.557571e-07,0.000058
2,raw_R_step_mean_abs,2.999592e-02,0.002653,0.002747,1.974685e-03,0.049051
3,theta_step_mean_abs,2.864379e-02,0.000779,0.002111,6.685421e-04,0.028644
4,raw_R_grad_norm,7.235853e-02,0.023662,0.010191,1.019113e-02,0.960438
5,theta_grad_norm,7.394414e-04,0.009256,0.012829,2.943599e-04,0.540465
6,raw_R_step_norm,2.839332e+01,2.757237,2.843870,2.229566e+00,46.435867
7,theta_step_norm,2.723227e+01,1.280285,5.677673,1.044110e+00,27.232267

--------------------------------------------------------------------------------
RESULT SUMMARY: G63
--------------------------------------------------------------------------------
historical_best: 27047.0

V1:
v1_best: 26753.0
v1_gap: 294.0
v1_percent_accuracy: 98.91300329056828

V2:
v2_best: 26765.0
v2_gap: 282.0
v2_percent_accuracy: 98.95737050319813
v2_best_step: 1627
v2_best_replica: 9

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 91.89622282981873

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_13_15/logs/G63_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_13_15/best_spins/G63_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_13_15/partial_group_results.csv

################################################################################
RUNNING G64 | edge_list | seed=11
################################################################################
G64 | step     1/2000 | best 499.0 | acc 5.7022% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G64 | step    50/2000 | best 1298.0 | acc 14.8326% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G64 | step   100/2000 | best 7768.0 | acc 88.7670% | success 0/128 | gamma 0.95048 | |rz| 0.1504
G64 | step   150/2000 | best 8356.0 | acc 95.4862% | success 0/128 | gamma 0.92546 | |rz| 0.6178
G64 | step   200/2000 | best 8391.0 | acc 95.8862% | success 0/128 | gamma 0.90045 | |rz| 0.6872
G64 | step   250/2000 | best 8401.0 | acc 96.0005% | success 0/128 | gamma 0.87544 | |rz| 0.7089
G64 | step   300/2000 | best 8409.0 | acc 96.0919% | success 0/128 | gamma 0.85043 | |rz| 0.7234
G64 | step   350/2000 | best 8423.0 | acc 96.2519% | success 0/128 | gamma 0.82541 | |rz| 0.7355
G64 | step   400/2000 | best 8426.0 | acc 96.2861% | success 0/128 | gamma 0.80040 | |rz| 0.7465
G64 | step   450/2000 | best 8435.0 | acc 96.3890% | success 0/128 | gamma 0.77539 | |rz| 0.7569
G64 | step   500/2000 | best 8437.0 | acc 96.4118% | success 0/128 | gamma 0.75038 | |rz| 0.7669
G64 | step   550/2000 | best 8443.0 | acc 96.4804% | success 0/128 | gamma 0.72536 | |rz| 0.7767
G64 | step   600/2000 | best 8450.0 | acc 96.5604% | success 0/128 | gamma 0.70035 | |rz| 0.7863
G64 | step   650/2000 | best 8451.0 | acc 96.5718% | success 0/128 | gamma 0.67534 | |rz| 0.7956
G64 | step   700/2000 | best 8457.0 | acc 96.6404% | success 0/128 | gamma 0.65033 | |rz| 0.8048
G64 | step   750/2000 | best 8462.0 | acc 96.6975% | success 0/128 | gamma 0.62531 | |rz| 0.8138
G64 | step   800/2000 | best 8468.0 | acc 96.7661% | success 0/128 | gamma 0.60030 | |rz| 0.8226
G64 | step   850/2000 | best 8471.0 | acc 96.8004% | success 0/128 | gamma 0.57529 | |rz| 0.8312
G64 | step   900/2000 | best 8475.0 | acc 96.8461% | success 0/128 | gamma 0.55028 | |rz| 0.8396
G64 | step   950/2000 | best 8478.0 | acc 96.8804% | success 0/128 | gamma 0.52526 | |rz| 0.8479
G64 | step  1000/2000 | best 8478.0 | acc 96.8804% | success 0/128 | gamma 0.50025 | |rz| 0.8559
G64 | step  1050/2000 | best 8478.0 | acc 96.8804% | success 0/128 | gamma 0.47524 | |rz| 0.8637
G64 | step  1100/2000 | best 8478.0 | acc 96.8804% | success 0/128 | gamma 0.45023 | |rz| 0.8712
G64 | step  1150/2000 | best 8479.0 | acc 96.8918% | success 0/128 | gamma 0.42521 | |rz| 0.8784
G64 | step  1200/2000 | best 8479.0 | acc 96.8918% | success 0/128 | gamma 0.40020 | |rz| 0.8852
G64 | step  1250/2000 | best 8479.0 | acc 96.8918% | success 0/128 | gamma 0.37519 | |rz| 0.8919
G64 | step  1300/2000 | best 8480.0 | acc 96.9032% | success 0/128 | gamma 0.35018 | |rz| 0.8983
G64 | step  1350/2000 | best 8481.0 | acc 96.9146% | success 0/128 | gamma 0.32517 | |rz| 0.9045
G64 | step  1400/2000 | best 8483.0 | acc 96.9375% | success 0/128 | gamma 0.30034 | |rz| 0.9102
G64 | step  1450/2000 | best 8483.0 | acc 96.9375% | success 0/128 | gamma 0.27732 | |rz| 0.9153
G64 | step  1500/2000 | best 8484.0 | acc 96.9489% | success 0/128 | gamma 0.26252 | |rz| 0.9189
G64 | step  1550/2000 | best 8484.0 | acc 96.9489% | success 0/128 | gamma 0.26035 | |rz| 0.9206
G64 | step  1600/2000 | best 8484.0 | acc 96.9489% | success 0/128 | gamma 0.25010 | |rz| 0.9233
G64 | step  1650/2000 | best 8484.0 | acc 96.9489% | success 0/128 | gamma 0.21052 | |rz| 0.9293
G64 | step  1700/2000 | best 8484.0 | acc 96.9489% | success 0/128 | gamma 0.16261 | |rz| 0.9348
G64 | step  1750/2000 | best 8484.0 | acc 96.9489% | success 0/128 | gamma 0.12728 | |rz| 0.9379
G64 | step  1800/2000 | best 8484.0 | acc 96.9489% | success 0/128 | gamma 0.10025 | |rz| 0.9398
G64 | step  1850/2000 | best 8484.0 | acc 96.9489% | success 0/128 | gamma 0.07505 | |rz| 0.9412
G64 | step  1900/2000 | best 8484.0 | acc 96.9489% | success 0/128 | gamma 0.05003 | |rz| 0.9423
G64 | step  1950/2000 | best 8484.0 | acc 96.9489% | success 0/128 | gamma 0.02501 | |rz| 0.9433
G64 | step  2000/2000 | best 8484.0 | acc 96.9489% | success 0/128 | gamma 0.00000 | |rz| 0.9497

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G64
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644265e-05,0.000023,0.000010,1.047221e-05,0.001274
1,theta_grad_mean_abs,6.229587e-07,0.000008,0.000007,2.570145e-07,0.000107
2,raw_R_step_mean_abs,2.999592e-02,0.002416,0.002377,2.173478e-03,0.051258
3,theta_step_mean_abs,2.864393e-02,0.001025,0.001822,9.170656e-04,0.030681
4,raw_R_grad_norm,7.235856e-02,0.031241,0.011895,1.189537e-02,1.768305
5,theta_grad_norm,7.389223e-04,0.012333,0.016090,2.959308e-04,0.596133
6,raw_R_step_norm,2.839332e+01,2.464406,2.503724,2.279427e+00,48.618244
7,theta_step_norm,2.723191e+01,1.373360,5.185213,1.044721e+00,33.505157

--------------------------------------------------------------------------------
RESULT SUMMARY: G64
--------------------------------------------------------------------------------
historical_best: 8751.0

V1:
v1_best: 8415.0
v1_gap: 336.0
v1_percent_accuracy: 96.16043880699348

V2:
v2_best: 8484.0
v2_gap: 267.0
v2_percent_accuracy: 96.94892012341447
v2_best_step: 1481
v2_best_replica: 81

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 92.03417587280273

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_13_15/logs/G64_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_13_15/best_spins/G64_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_13_15/partial_group_results.csv

================================================================================
RUN GROUP COMPLETE
================================================================================
run_group: big_13_15
graphs: 5

Group results:

,run_group,partition,instance,graph_type,storage_mode,nodes,edges,n_steps,replicas,lr,...,final_best,final_gap,final_percent_accuracy,best_step_success_count,best_step_success_probability,ever_success_count,ever_success_probability,final_success_count,final_success_probability,v2_runtime_sec
0,big_13_15,13,G60,plain,edge_list,7000,17148,2000,128,0.03,...,14035.0,153.0,98.921624,0,0.0,0,0.0,0,0.0,58.046553
1,big_13_15,13,G61,plain,edge_list,7000,17148,2000,128,0.03,...,5654.0,142.0,97.550035,0,0.0,0,0.0,0,0.0,56.686825
2,big_13_15,14,G62,toroid,edge_list,7000,14000,2000,128,0.03,...,4770.0,100.0,97.946612,0,0.0,0,0.0,0,0.0,50.146325
3,big_13_15,15,G63,random,edge_list,7000,41459,2000,128,0.03,...,26765.0,282.0,98.957371,0,0.0,0,0.0,0,0.0,91.896223
4,big_13_15,15,G64,random,edge_list,7000,41459,2000,128,0.03,...,8484.0,267.0,96.948920,0,0.0,0,0.0,0,0.0,92.034176

Compact group results:

,instance,historical_best,v1_best,v1_gap,v1_percent_accuracy,v2_best,v2_gap,v2_percent_accuracy,v2_best_step,v2_best_replica,ever_success_count,ever_success_probability,final_best,final_gap,final_percent_accuracy,final_success_count,final_success_probability,v2_runtime_sec
0,G60,14188.0,14037.0,151.0,98.935720,14035.0,153.0,98.921624,1316,113,0,0.0,14035.0,153.0,98.921624,0,0.0,58.046553
1,G61,5796.0,5642.0,154.0,97.342995,5654.0,142.0,97.550035,1535,54,0,0.0,5654.0,142.0,97.550035,0,0.0,56.686825
2,G62,4870.0,4790.0,80.0,98.357290,4770.0,100.0,97.946612,352,84,0,0.0,4770.0,100.0,97.946612,0,0.0,50.146325
3,G63,27047.0,26753.0,294.0,98.913003,26765.0,282.0,98.957371,1627,9,0,0.0,26765.0,282.0,98.957371,0,0.0,91.896223
4,G64,8751.0,8415.0,336.0,96.160439,8484.0,267.0,96.948920,1481,81,0,0.0,8484.0,267.0,96.948920,0,0.0,92.034176

Saved group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_13_15/group_results.csv

Saved group logs:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_13_15/group_training_logs.csv

================================================================================
COMPACT GROUP RESULT
================================================================================

,instance,historical_best,v1_best,v1_gap,v1_percent_accuracy,v2_best,v2_gap,v2_percent_accuracy,v2_best_step,v2_best_replica,ever_success_count,ever_success_probability,final_best,final_gap,final_percent_accuracy,final_success_count,final_success_probability,v2_runtime_sec
0,G60,14188.0,14037.0,151.0,98.935720,14035.0,153.0,98.921624,1316,113,0,0.0,14035.0,153.0,98.921624,0,0.0,58.046553
1,G61,5796.0,5642.0,154.0,97.342995,5654.0,142.0,97.550035,1535,54,0,0.0,5654.0,142.0,97.550035,0,0.0,56.686825
2,G62,4870.0,4790.0,80.0,98.357290,4770.0,100.0,97.946612,352,84,0,0.0,4770.0,100.0,97.946612,0,0.0,50.146325
3,G63,27047.0,26753.0,294.0,98.913003,26765.0,282.0,98.957371,1627,9,0,0.0,26765.0,282.0,98.957371,0,0.0,91.896223
4,G64,8751.0,8415.0,336.0,96.160439,8484.0,267.0,96.948920,1481,81,0,0.0,8484.0,267.0,96.948920,0,0.0,92.034176

In [111]:
print("\nGroup summary:")
print("graphs:", len(group_results_df))
print("mean v1 accuracy %:", float(group_results_df["v1_percent_accuracy"].mean()))
print("mean v2 accuracy %:", float(group_results_df["v2_percent_accuracy"].mean()))
print("v1 gap-zero count:", int((group_results_df["v1_gap"] == 0).sum()))
print("v2 gap-zero count:", int((group_results_df["v2_gap"] == 0).sum()))
print("total v2 runtime sec:", float(group_results_df["v2_runtime_sec"].sum()))

Group summary:
graphs: 5
mean v1 accuracy %: 97.94188942428032
mean v2 accuracy %: 98.06491219006946
v1 gap-zero count: 0
v2 gap-zero count: 0
total v2 runtime sec: 348.8101019859314

In [112]:
# ============================================================
# Quick inspection: where did V2 improve over V1?
# ============================================================

inspection_df = group_results_df[
    [
        "instance",
        "historical_best",
        "v1_best",
        "v1_gap",
        "v1_percent_accuracy",
        "v2_best",
        "v2_gap",
        "v2_percent_accuracy",
        "v2_best_step",
        "ever_success_count",
        "ever_success_probability",
        "final_best",
        "final_gap",
        "final_percent_accuracy",
    ]
].copy()

inspection_df["gap_improvement"] = (
    inspection_df["v1_gap"] - inspection_df["v2_gap"]
)

inspection_df["accuracy_improvement"] = (
    inspection_df["v2_percent_accuracy"] - inspection_df["v1_percent_accuracy"]
)

inspection_df = inspection_df.sort_values(
    "gap_improvement",
    ascending=False,
).reset_index(drop=True)

print("=" * 80)
print("V2 IMPROVEMENT INSPECTION")
print("=" * 80)

display(inspection_df)

print("\nSummary:")
print("graphs:", len(inspection_df))
print("improved gap count:", int((inspection_df["gap_improvement"] > 0).sum()))
print("same gap count    :", int((inspection_df["gap_improvement"] == 0).sum()))
print("worse gap count   :", int((inspection_df["gap_improvement"] < 0).sum()))

print("\nGap improvement:")
print("mean:", float(inspection_df["gap_improvement"].mean()))
print("min :", float(inspection_df["gap_improvement"].min()))
print("max :", float(inspection_df["gap_improvement"].max()))

print("\nAccuracy improvement:")
print("mean:", float(inspection_df["accuracy_improvement"].mean()))
print("min :", float(inspection_df["accuracy_improvement"].min()))
print("max :", float(inspection_df["accuracy_improvement"].max()))

print("\nClosest V2 gaps:")
display(
    inspection_df.sort_values("v2_gap")[
        [
            "instance",
            "historical_best",
            "v2_best",
            "v2_gap",
            "v2_percent_accuracy",
            "v2_best_step",
            "ever_success_count",
            "final_gap",
        ]
    ].head(10)
)

================================================================================
V2 IMPROVEMENT INSPECTION
================================================================================

,instance,historical_best,v1_best,v1_gap,v1_percent_accuracy,v2_best,v2_gap,v2_percent_accuracy,v2_best_step,ever_success_count,ever_success_probability,final_best,final_gap,final_percent_accuracy,gap_improvement,accuracy_improvement
0,G64,8751.0,8415.0,336.0,96.160439,8484.0,267.0,96.948920,1481,0,0.0,8484.0,267.0,96.948920,69.0,0.788481
1,G61,5796.0,5642.0,154.0,97.342995,5654.0,142.0,97.550035,1535,0,0.0,5654.0,142.0,97.550035,12.0,0.207039
2,G63,27047.0,26753.0,294.0,98.913003,26765.0,282.0,98.957371,1627,0,0.0,26765.0,282.0,98.957371,12.0,0.044367
3,G60,14188.0,14037.0,151.0,98.935720,14035.0,153.0,98.921624,1316,0,0.0,14035.0,153.0,98.921624,-2.0,-0.014096
4,G62,4870.0,4790.0,80.0,98.357290,4770.0,100.0,97.946612,352,0,0.0,4770.0,100.0,97.946612,-20.0,-0.410678

Summary:
graphs: 5
improved gap count: 3
same gap count    : 0
worse gap count   : 2

Gap improvement:
mean: 14.2
min : -20.0
max : 69.0

Accuracy improvement:
mean: 0.12302276578914473
min : -0.41067761806981196
max : 0.7884813164209845

Closest V2 gaps:

,instance,historical_best,v2_best,v2_gap,v2_percent_accuracy,v2_best_step,ever_success_count,final_gap
4,G62,4870.0,4770.0,100.0,97.946612,352,0,100.0
1,G61,5796.0,5654.0,142.0,97.550035,1535,0,142.0
3,G60,14188.0,14035.0,153.0,98.921624,1316,0,153.0
0,G64,8751.0,8484.0,267.0,96.948920,1481,0,267.0
2,G63,27047.0,26765.0,282.0,98.957371,1627,0,282.0

# 5

In [113]:
# ============================================================
# Cell 10: Select run group and run QEFEM v2
# ============================================================

# ------------------------------------------------------------
# Choose run group here
# ------------------------------------------------------------
# 0 -> small_1_3   : G1-G21
# 1 -> small_4_6   : G22-G42
# 2 -> small_7_9   : G43-G54
# 3 -> big_10_12   : G55-G59
# 4 -> big_13_15   : G60-G64
# 5 -> big_16_18   : G65, G66, G67, G72
# 6 -> big_19_21   : G70, G77, G81

RUN_GROUP_INDEX = 5


# ------------------------------------------------------------
# Preview selected group
# ------------------------------------------------------------

selected_group_row = run_group_summary_df.iloc[RUN_GROUP_INDEX]

print("=" * 80)
print("SELECTED RUN GROUP")
print("=" * 80)

print("RUN_GROUP_INDEX:", RUN_GROUP_INDEX)
print("run_group:", selected_group_row["run_group"])
print("partitions:", selected_group_row["partitions"])
print("graphs_start:", selected_group_row["graphs_start"])
print("graphs_end:", selected_group_row["graphs_end"])
print("num_graphs:", selected_group_row["num_graphs"])
print("graph_types:", selected_group_row["graph_types"])
print("storage_modes:", selected_group_row["storage_modes"])
print("graphs:", selected_group_row["graphs"])


# ------------------------------------------------------------
# Run selected group
# ------------------------------------------------------------

group_results_df, group_logs_df = run_qefem_run_group(
    run_group_index=RUN_GROUP_INDEX
)


# ------------------------------------------------------------
# Final compact display
# ------------------------------------------------------------

compact_group_results_df = group_results_df[
    [
        "instance",
        "historical_best",
        "v1_best",
        "v1_gap",
        "v1_percent_accuracy",
        "v2_best",
        "v2_gap",
        "v2_percent_accuracy",
        "v2_best_step",
        "v2_best_replica",
        "ever_success_count",
        "ever_success_probability",
        "final_best",
        "final_gap",
        "final_percent_accuracy",
        "final_success_count",
        "final_success_probability",
        "v2_runtime_sec",
    ]
].copy()

print("\n" + "=" * 80)
print("COMPACT GROUP RESULT")
print("=" * 80)

display(compact_group_results_df)

================================================================================
SELECTED RUN GROUP
================================================================================
RUN_GROUP_INDEX: 5
run_group: big_16_18
partitions: [16, 17, 18]
graphs_start: G65
graphs_end: G72
num_graphs: 4
graph_types: ['toroid']
storage_modes: ['edge_list']
graphs: ['G65', 'G66', 'G67', 'G72']
================================================================================
RUNNING QEFEM V2 RUN GROUP
================================================================================
run_group_index: 5
run_group: big_16_18
graphs: ['G65', 'G66', 'G67', 'G72']
num graphs: 4

Output directory:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_16_18

Selected benchmark rows:

,partition,instance,graph_type,storage_mode,nodes,edges,n_steps,replicas,lr,v1_best,historical_best,v1_gap,v1_percent_accuracy,v1_best_replica,v1_runtime_sec
0,16,G65,toroid,edge_list,8000,16000,1000,128,0.01,5448.0,5562.0,114.0,97.950378,47,38.942341
1,17,G66,toroid,edge_list,9000,18000,1000,128,0.01,6228.0,6364.0,136.0,97.862979,95,42.966841
2,18,G67,toroid,edge_list,10000,20000,1000,128,0.01,6806.0,6950.0,144.0,97.928058,35,51.017605
3,18,G72,toroid,edge_list,10000,20000,1000,128,0.01,6860.0,7008.0,148.0,97.888128,17,56.816828

################################################################################
RUNNING G65 | edge_list | seed=7
################################################################################
G65 | step     1/2000 | best 62.0 | acc 1.1147% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G65 | step    50/2000 | best 618.0 | acc 11.1111% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G65 | step   100/2000 | best 696.0 | acc 12.5135% | success 0/128 | gamma 0.95048 | |rz| 0.0010
G65 | step   150/2000 | best 5394.0 | acc 96.9795% | success 0/128 | gamma 0.92546 | |rz| 0.3517
G65 | step   200/2000 | best 5428.0 | acc 97.5908% | success 0/128 | gamma 0.90045 | |rz| 0.4932
G65 | step   250/2000 | best 5432.0 | acc 97.6627% | success 0/128 | gamma 0.87544 | |rz| 0.5483
G65 | step   300/2000 | best 5436.0 | acc 97.7346% | success 0/128 | gamma 0.85043 | |rz| 0.5814
G65 | step   350/2000 | best 5438.0 | acc 97.7706% | success 0/128 | gamma 0.82541 | |rz| 0.6085
G65 | step   400/2000 | best 5438.0 | acc 97.7706% | success 0/128 | gamma 0.80040 | |rz| 0.6329
G65 | step   450/2000 | best 5442.0 | acc 97.8425% | success 0/128 | gamma 0.77539 | |rz| 0.6554
G65 | step   500/2000 | best 5444.0 | acc 97.8785% | success 0/128 | gamma 0.75038 | |rz| 0.6763
G65 | step   550/2000 | best 5444.0 | acc 97.8785% | success 0/128 | gamma 0.72536 | |rz| 0.6958
G65 | step   600/2000 | best 5444.0 | acc 97.8785% | success 0/128 | gamma 0.70035 | |rz| 0.7140
G65 | step   650/2000 | best 5444.0 | acc 97.8785% | success 0/128 | gamma 0.67534 | |rz| 0.7311
G65 | step   700/2000 | best 5444.0 | acc 97.8785% | success 0/128 | gamma 0.65033 | |rz| 0.7471
G65 | step   750/2000 | best 5444.0 | acc 97.8785% | success 0/128 | gamma 0.62531 | |rz| 0.7621
G65 | step   800/2000 | best 5444.0 | acc 97.8785% | success 0/128 | gamma 0.60030 | |rz| 0.7761
G65 | step   850/2000 | best 5444.0 | acc 97.8785% | success 0/128 | gamma 0.57529 | |rz| 0.7893
G65 | step   900/2000 | best 5444.0 | acc 97.8785% | success 0/128 | gamma 0.55028 | |rz| 0.8016
G65 | step   950/2000 | best 5444.0 | acc 97.8785% | success 0/128 | gamma 0.52526 | |rz| 0.8132
G65 | step  1000/2000 | best 5444.0 | acc 97.8785% | success 0/128 | gamma 0.50025 | |rz| 0.8240
G65 | step  1050/2000 | best 5444.0 | acc 97.8785% | success 0/128 | gamma 0.47524 | |rz| 0.8342
G65 | step  1100/2000 | best 5444.0 | acc 97.8785% | success 0/128 | gamma 0.45023 | |rz| 0.8437
G65 | step  1150/2000 | best 5444.0 | acc 97.8785% | success 0/128 | gamma 0.42521 | |rz| 0.8526
G65 | step  1200/2000 | best 5444.0 | acc 97.8785% | success 0/128 | gamma 0.40020 | |rz| 0.8609
G65 | step  1250/2000 | best 5444.0 | acc 97.8785% | success 0/128 | gamma 0.37519 | |rz| 0.8687
G65 | step  1300/2000 | best 5444.0 | acc 97.8785% | success 0/128 | gamma 0.35018 | |rz| 0.8759
G65 | step  1350/2000 | best 5444.0 | acc 97.8785% | success 0/128 | gamma 0.32517 | |rz| 0.8827
G65 | step  1400/2000 | best 5444.0 | acc 97.8785% | success 0/128 | gamma 0.30034 | |rz| 0.8889
G65 | step  1450/2000 | best 5444.0 | acc 97.8785% | success 0/128 | gamma 0.27732 | |rz| 0.8943
G65 | step  1500/2000 | best 5444.0 | acc 97.8785% | success 0/128 | gamma 0.26252 | |rz| 0.8979
G65 | step  1550/2000 | best 5444.0 | acc 97.8785% | success 0/128 | gamma 0.26035 | |rz| 0.8994
G65 | step  1600/2000 | best 5444.0 | acc 97.8785% | success 0/128 | gamma 0.25010 | |rz| 0.9022
G65 | step  1650/2000 | best 5444.0 | acc 97.8785% | success 0/128 | gamma 0.21052 | |rz| 0.9085
G65 | step  1700/2000 | best 5444.0 | acc 97.8785% | success 0/128 | gamma 0.16261 | |rz| 0.9142
G65 | step  1750/2000 | best 5444.0 | acc 97.8785% | success 0/128 | gamma 0.12728 | |rz| 0.9169
G65 | step  1800/2000 | best 5444.0 | acc 97.8785% | success 0/128 | gamma 0.10025 | |rz| 0.9181
G65 | step  1850/2000 | best 5444.0 | acc 97.8785% | success 0/128 | gamma 0.07505 | |rz| 0.9186
G65 | step  1900/2000 | best 5444.0 | acc 97.8785% | success 0/128 | gamma 0.05003 | |rz| 0.9191
G65 | step  1950/2000 | best 5444.0 | acc 97.8785% | success 0/128 | gamma 0.02501 | |rz| 0.9201
G65 | step  2000/2000 | best 5444.0 | acc 97.8785% | success 0/128 | gamma 0.00000 | |rz| 0.9308

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G65
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644272e-05,0.000017,0.000008,7.858413e-06,0.000933
1,theta_grad_mean_abs,6.235139e-07,0.000003,0.000005,2.604936e-07,0.000113
2,raw_R_step_mean_abs,2.999592e-02,0.002983,0.002672,2.212089e-03,0.048872
3,theta_step_mean_abs,2.864667e-02,0.000756,0.002392,7.116486e-04,0.028647
4,raw_R_grad_norm,7.735462e-02,0.018446,0.008400,8.399887e-03,0.944065
5,theta_grad_norm,7.904885e-04,0.005944,0.012415,3.125357e-04,0.205477
6,raw_R_step_norm,3.035373e+01,3.211375,2.893933,2.478607e+00,49.454483
7,theta_step_norm,2.911442e+01,1.138520,7.914367,9.930861e-01,29.114424

--------------------------------------------------------------------------------
RESULT SUMMARY: G65
--------------------------------------------------------------------------------
historical_best: 5562.0

V1:
v1_best: 5448.0
v1_gap: 114.0
v1_percent_accuracy: 97.95037756202804

V2:
v2_best: 5444.0
v2_gap: 118.0
v2_percent_accuracy: 97.8784609852571
v2_best_step: 468
v2_best_replica: 53

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 59.41776394844055

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_16_18/logs/G65_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_16_18/best_spins/G65_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_16_18/partial_group_results.csv

################################################################################
RUNNING G66 | edge_list | seed=8
################################################################################
G66 | step     1/2000 | best 160.0 | acc 2.5141% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G66 | step    50/2000 | best 742.0 | acc 11.6593% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G66 | step   100/2000 | best 796.0 | acc 12.5079% | success 0/128 | gamma 0.95048 | |rz| 0.0010
G66 | step   150/2000 | best 6166.0 | acc 96.8887% | success 0/128 | gamma 0.92546 | |rz| 0.3509
G66 | step   200/2000 | best 6194.0 | acc 97.3287% | success 0/128 | gamma 0.90045 | |rz| 0.4934
G66 | step   250/2000 | best 6198.0 | acc 97.3916% | success 0/128 | gamma 0.87544 | |rz| 0.5481
G66 | step   300/2000 | best 6204.0 | acc 97.4859% | success 0/128 | gamma 0.85043 | |rz| 0.5811
G66 | step   350/2000 | best 6210.0 | acc 97.5801% | success 0/128 | gamma 0.82541 | |rz| 0.6081
G66 | step   400/2000 | best 6212.0 | acc 97.6116% | success 0/128 | gamma 0.80040 | |rz| 0.6325
G66 | step   450/2000 | best 6212.0 | acc 97.6116% | success 0/128 | gamma 0.77539 | |rz| 0.6549
G66 | step   500/2000 | best 6214.0 | acc 97.6430% | success 0/128 | gamma 0.75038 | |rz| 0.6758
G66 | step   550/2000 | best 6214.0 | acc 97.6430% | success 0/128 | gamma 0.72536 | |rz| 0.6953
G66 | step   600/2000 | best 6216.0 | acc 97.6744% | success 0/128 | gamma 0.70035 | |rz| 0.7136
G66 | step   650/2000 | best 6218.0 | acc 97.7058% | success 0/128 | gamma 0.67534 | |rz| 0.7307
G66 | step   700/2000 | best 6218.0 | acc 97.7058% | success 0/128 | gamma 0.65033 | |rz| 0.7467
G66 | step   750/2000 | best 6218.0 | acc 97.7058% | success 0/128 | gamma 0.62531 | |rz| 0.7617
G66 | step   800/2000 | best 6218.0 | acc 97.7058% | success 0/128 | gamma 0.60030 | |rz| 0.7758
G66 | step   850/2000 | best 6218.0 | acc 97.7058% | success 0/128 | gamma 0.57529 | |rz| 0.7890
G66 | step   900/2000 | best 6218.0 | acc 97.7058% | success 0/128 | gamma 0.55028 | |rz| 0.8013
G66 | step   950/2000 | best 6218.0 | acc 97.7058% | success 0/128 | gamma 0.52526 | |rz| 0.8129
G66 | step  1000/2000 | best 6218.0 | acc 97.7058% | success 0/128 | gamma 0.50025 | |rz| 0.8238
G66 | step  1050/2000 | best 6218.0 | acc 97.7058% | success 0/128 | gamma 0.47524 | |rz| 0.8339
G66 | step  1100/2000 | best 6218.0 | acc 97.7058% | success 0/128 | gamma 0.45023 | |rz| 0.8434
G66 | step  1150/2000 | best 6218.0 | acc 97.7058% | success 0/128 | gamma 0.42521 | |rz| 0.8523
G66 | step  1200/2000 | best 6218.0 | acc 97.7058% | success 0/128 | gamma 0.40020 | |rz| 0.8607
G66 | step  1250/2000 | best 6218.0 | acc 97.7058% | success 0/128 | gamma 0.37519 | |rz| 0.8684
G66 | step  1300/2000 | best 6218.0 | acc 97.7058% | success 0/128 | gamma 0.35018 | |rz| 0.8757
G66 | step  1350/2000 | best 6218.0 | acc 97.7058% | success 0/128 | gamma 0.32517 | |rz| 0.8824
G66 | step  1400/2000 | best 6218.0 | acc 97.7058% | success 0/128 | gamma 0.30034 | |rz| 0.8886
G66 | step  1450/2000 | best 6218.0 | acc 97.7058% | success 0/128 | gamma 0.27732 | |rz| 0.8940
G66 | step  1500/2000 | best 6218.0 | acc 97.7058% | success 0/128 | gamma 0.26252 | |rz| 0.8976
G66 | step  1550/2000 | best 6218.0 | acc 97.7058% | success 0/128 | gamma 0.26035 | |rz| 0.8991
G66 | step  1600/2000 | best 6218.0 | acc 97.7058% | success 0/128 | gamma 0.25010 | |rz| 0.9019
G66 | step  1650/2000 | best 6218.0 | acc 97.7058% | success 0/128 | gamma 0.21052 | |rz| 0.9082
G66 | step  1700/2000 | best 6218.0 | acc 97.7058% | success 0/128 | gamma 0.16261 | |rz| 0.9138
G66 | step  1750/2000 | best 6218.0 | acc 97.7058% | success 0/128 | gamma 0.12728 | |rz| 0.9165
G66 | step  1800/2000 | best 6218.0 | acc 97.7058% | success 0/128 | gamma 0.10025 | |rz| 0.9176
G66 | step  1850/2000 | best 6218.0 | acc 97.7058% | success 0/128 | gamma 0.07505 | |rz| 0.9182
G66 | step  1900/2000 | best 6218.0 | acc 97.7058% | success 0/128 | gamma 0.05003 | |rz| 0.9187
G66 | step  1950/2000 | best 6218.0 | acc 97.7058% | success 0/128 | gamma 0.02501 | |rz| 0.9197
G66 | step  2000/2000 | best 6218.0 | acc 97.7058% | success 0/128 | gamma 0.00000 | |rz| 0.9306

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G66
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644267e-05,0.000017,0.000008,7.852887e-06,0.000933
1,theta_grad_mean_abs,6.236712e-07,0.000003,0.000005,2.604830e-07,0.000109
2,raw_R_step_mean_abs,2.999592e-02,0.002983,0.002669,2.210496e-03,0.048872
3,theta_step_mean_abs,2.864372e-02,0.000759,0.002432,7.121486e-04,0.028644
4,raw_R_grad_norm,8.204693e-02,0.019590,0.008903,8.902948e-03,1.001332
5,theta_grad_norm,8.390139e-04,0.006352,0.013376,3.313850e-04,0.212784
6,raw_R_step_norm,3.219500e+01,3.409156,3.066550,2.628315e+00,52.454407
7,theta_step_norm,3.087789e+01,1.216269,8.500065,1.064545e+00,30.877888

--------------------------------------------------------------------------------
RESULT SUMMARY: G66
--------------------------------------------------------------------------------
historical_best: 6364.0

V1:
v1_best: 6228.0
v1_gap: 136.0
v1_percent_accuracy: 97.8629792583281

V2:
v2_best: 6218.0
v2_gap: 146.0
v2_percent_accuracy: 97.70584538026398
v2_best_step: 624
v2_best_replica: 70

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 67.21220302581787

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_16_18/logs/G66_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_16_18/best_spins/G66_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_16_18/partial_group_results.csv

################################################################################
RUNNING G67 | edge_list | seed=9
################################################################################
G67 | step     1/2000 | best 76.0 | acc 1.0935% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G67 | step    50/2000 | best 674.0 | acc 9.6978% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G67 | step   100/2000 | best 728.0 | acc 10.4748% | success 0/128 | gamma 0.95048 | |rz| 0.0010
G67 | step   150/2000 | best 6740.0 | acc 96.9784% | success 0/128 | gamma 0.92546 | |rz| 0.3521
G67 | step   200/2000 | best 6786.0 | acc 97.6403% | success 0/128 | gamma 0.90045 | |rz| 0.4945
G67 | step   250/2000 | best 6794.0 | acc 97.7554% | success 0/128 | gamma 0.87544 | |rz| 0.5492
G67 | step   300/2000 | best 6798.0 | acc 97.8129% | success 0/128 | gamma 0.85043 | |rz| 0.5822
G67 | step   350/2000 | best 6800.0 | acc 97.8417% | success 0/128 | gamma 0.82541 | |rz| 0.6093
G67 | step   400/2000 | best 6804.0 | acc 97.8993% | success 0/128 | gamma 0.80040 | |rz| 0.6337
G67 | step   450/2000 | best 6806.0 | acc 97.9281% | success 0/128 | gamma 0.77539 | |rz| 0.6562
G67 | step   500/2000 | best 6806.0 | acc 97.9281% | success 0/128 | gamma 0.75038 | |rz| 0.6771
G67 | step   550/2000 | best 6810.0 | acc 97.9856% | success 0/128 | gamma 0.72536 | |rz| 0.6967
G67 | step   600/2000 | best 6812.0 | acc 98.0144% | success 0/128 | gamma 0.70035 | |rz| 0.7151
G67 | step   650/2000 | best 6812.0 | acc 98.0144% | success 0/128 | gamma 0.67534 | |rz| 0.7322
G67 | step   700/2000 | best 6812.0 | acc 98.0144% | success 0/128 | gamma 0.65033 | |rz| 0.7482
G67 | step   750/2000 | best 6812.0 | acc 98.0144% | success 0/128 | gamma 0.62531 | |rz| 0.7633
G67 | step   800/2000 | best 6812.0 | acc 98.0144% | success 0/128 | gamma 0.60030 | |rz| 0.7773
G67 | step   850/2000 | best 6812.0 | acc 98.0144% | success 0/128 | gamma 0.57529 | |rz| 0.7905
G67 | step   900/2000 | best 6812.0 | acc 98.0144% | success 0/128 | gamma 0.55028 | |rz| 0.8028
G67 | step   950/2000 | best 6812.0 | acc 98.0144% | success 0/128 | gamma 0.52526 | |rz| 0.8144
G67 | step  1000/2000 | best 6812.0 | acc 98.0144% | success 0/128 | gamma 0.50025 | |rz| 0.8253
G67 | step  1050/2000 | best 6812.0 | acc 98.0144% | success 0/128 | gamma 0.47524 | |rz| 0.8355
G67 | step  1100/2000 | best 6812.0 | acc 98.0144% | success 0/128 | gamma 0.45023 | |rz| 0.8450
G67 | step  1150/2000 | best 6812.0 | acc 98.0144% | success 0/128 | gamma 0.42521 | |rz| 0.8539
G67 | step  1200/2000 | best 6812.0 | acc 98.0144% | success 0/128 | gamma 0.40020 | |rz| 0.8622
G67 | step  1250/2000 | best 6812.0 | acc 98.0144% | success 0/128 | gamma 0.37519 | |rz| 0.8699
G67 | step  1300/2000 | best 6812.0 | acc 98.0144% | success 0/128 | gamma 0.35018 | |rz| 0.8771
G67 | step  1350/2000 | best 6812.0 | acc 98.0144% | success 0/128 | gamma 0.32517 | |rz| 0.8838
G67 | step  1400/2000 | best 6812.0 | acc 98.0144% | success 0/128 | gamma 0.30034 | |rz| 0.8900
G67 | step  1450/2000 | best 6812.0 | acc 98.0144% | success 0/128 | gamma 0.27732 | |rz| 0.8954
G67 | step  1500/2000 | best 6812.0 | acc 98.0144% | success 0/128 | gamma 0.26252 | |rz| 0.8990
G67 | step  1550/2000 | best 6812.0 | acc 98.0144% | success 0/128 | gamma 0.26035 | |rz| 0.9005
G67 | step  1600/2000 | best 6812.0 | acc 98.0144% | success 0/128 | gamma 0.25010 | |rz| 0.9032
G67 | step  1650/2000 | best 6812.0 | acc 98.0144% | success 0/128 | gamma 0.21052 | |rz| 0.9095
G67 | step  1700/2000 | best 6812.0 | acc 98.0144% | success 0/128 | gamma 0.16261 | |rz| 0.9152
G67 | step  1750/2000 | best 6812.0 | acc 98.0144% | success 0/128 | gamma 0.12728 | |rz| 0.9179
G67 | step  1800/2000 | best 6812.0 | acc 98.0144% | success 0/128 | gamma 0.10025 | |rz| 0.9191
G67 | step  1850/2000 | best 6812.0 | acc 98.0144% | success 0/128 | gamma 0.07505 | |rz| 0.9196
G67 | step  1900/2000 | best 6812.0 | acc 98.0144% | success 0/128 | gamma 0.05003 | |rz| 0.9201
G67 | step  1950/2000 | best 6812.0 | acc 98.0144% | success 0/128 | gamma 0.02501 | |rz| 0.9210
G67 | step  2000/2000 | best 6812.0 | acc 98.0144% | success 0/128 | gamma 0.00000 | |rz| 0.9315

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G67
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644272e-05,0.000017,0.000008,7.853436e-06,0.000933
1,theta_grad_mean_abs,6.236215e-07,0.000003,0.000005,2.604580e-07,0.000111
2,raw_R_step_mean_abs,2.999592e-02,0.002990,0.002668,2.214214e-03,0.048871
3,theta_step_mean_abs,2.864433e-02,0.000756,0.002359,7.106561e-04,0.028644
4,raw_R_grad_norm,8.648510e-02,0.020665,0.009376,9.376453e-03,1.055496
5,theta_grad_norm,8.842395e-04,0.006646,0.013904,3.493299e-04,0.228310
6,raw_R_step_norm,3.393650e+01,3.595069,3.227864,2.770316e+00,55.291790
7,theta_step_norm,3.254859e+01,1.276487,8.805022,1.127835e+00,32.548592

--------------------------------------------------------------------------------
RESULT SUMMARY: G67
--------------------------------------------------------------------------------
historical_best: 6950.0

V1:
v1_best: 6806.0
v1_gap: 144.0
v1_percent_accuracy: 97.92805755395683

V2:
v2_best: 6812.0
v2_gap: 138.0
v2_percent_accuracy: 98.01438848920863
v2_best_step: 564
v2_best_replica: 30

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 71.30514812469482

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_16_18/logs/G67_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_16_18/best_spins/G67_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_16_18/partial_group_results.csv

################################################################################
RUNNING G72 | edge_list | seed=10
################################################################################
G72 | step     1/2000 | best 138.0 | acc 1.9692% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G72 | step    50/2000 | best 740.0 | acc 10.5594% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G72 | step   100/2000 | best 844.0 | acc 12.0434% | success 0/128 | gamma 0.95048 | |rz| 0.0010
G72 | step   150/2000 | best 6786.0 | acc 96.8322% | success 0/128 | gamma 0.92546 | |rz| 0.3523
G72 | step   200/2000 | best 6828.0 | acc 97.4315% | success 0/128 | gamma 0.90045 | |rz| 0.4934
G72 | step   250/2000 | best 6832.0 | acc 97.4886% | success 0/128 | gamma 0.87544 | |rz| 0.5484
G72 | step   300/2000 | best 6836.0 | acc 97.5457% | success 0/128 | gamma 0.85043 | |rz| 0.5814
G72 | step   350/2000 | best 6840.0 | acc 97.6027% | success 0/128 | gamma 0.82541 | |rz| 0.6084
G72 | step   400/2000 | best 6840.0 | acc 97.6027% | success 0/128 | gamma 0.80040 | |rz| 0.6326
G72 | step   450/2000 | best 6842.0 | acc 97.6313% | success 0/128 | gamma 0.77539 | |rz| 0.6550
G72 | step   500/2000 | best 6842.0 | acc 97.6313% | success 0/128 | gamma 0.75038 | |rz| 0.6758
G72 | step   550/2000 | best 6842.0 | acc 97.6313% | success 0/128 | gamma 0.72536 | |rz| 0.6953
G72 | step   600/2000 | best 6844.0 | acc 97.6598% | success 0/128 | gamma 0.70035 | |rz| 0.7136
G72 | step   650/2000 | best 6844.0 | acc 97.6598% | success 0/128 | gamma 0.67534 | |rz| 0.7306
G72 | step   700/2000 | best 6844.0 | acc 97.6598% | success 0/128 | gamma 0.65033 | |rz| 0.7466
G72 | step   750/2000 | best 6844.0 | acc 97.6598% | success 0/128 | gamma 0.62531 | |rz| 0.7615
G72 | step   800/2000 | best 6844.0 | acc 97.6598% | success 0/128 | gamma 0.60030 | |rz| 0.7755
G72 | step   850/2000 | best 6844.0 | acc 97.6598% | success 0/128 | gamma 0.57529 | |rz| 0.7887
G72 | step   900/2000 | best 6844.0 | acc 97.6598% | success 0/128 | gamma 0.55028 | |rz| 0.8009
G72 | step   950/2000 | best 6844.0 | acc 97.6598% | success 0/128 | gamma 0.52526 | |rz| 0.8125
G72 | step  1000/2000 | best 6844.0 | acc 97.6598% | success 0/128 | gamma 0.50025 | |rz| 0.8233
G72 | step  1050/2000 | best 6844.0 | acc 97.6598% | success 0/128 | gamma 0.47524 | |rz| 0.8334
G72 | step  1100/2000 | best 6844.0 | acc 97.6598% | success 0/128 | gamma 0.45023 | |rz| 0.8428
G72 | step  1150/2000 | best 6844.0 | acc 97.6598% | success 0/128 | gamma 0.42521 | |rz| 0.8517
G72 | step  1200/2000 | best 6844.0 | acc 97.6598% | success 0/128 | gamma 0.40020 | |rz| 0.8599
G72 | step  1250/2000 | best 6844.0 | acc 97.6598% | success 0/128 | gamma 0.37519 | |rz| 0.8677
G72 | step  1300/2000 | best 6844.0 | acc 97.6598% | success 0/128 | gamma 0.35018 | |rz| 0.8749
G72 | step  1350/2000 | best 6844.0 | acc 97.6598% | success 0/128 | gamma 0.32517 | |rz| 0.8815
G72 | step  1400/2000 | best 6844.0 | acc 97.6598% | success 0/128 | gamma 0.30034 | |rz| 0.8877
G72 | step  1450/2000 | best 6844.0 | acc 97.6598% | success 0/128 | gamma 0.27732 | |rz| 0.8931
G72 | step  1500/2000 | best 6844.0 | acc 97.6598% | success 0/128 | gamma 0.26252 | |rz| 0.8967
G72 | step  1550/2000 | best 6844.0 | acc 97.6598% | success 0/128 | gamma 0.26035 | |rz| 0.8982
G72 | step  1600/2000 | best 6844.0 | acc 97.6598% | success 0/128 | gamma 0.25010 | |rz| 0.9009
G72 | step  1650/2000 | best 6844.0 | acc 97.6598% | success 0/128 | gamma 0.21052 | |rz| 0.9073
G72 | step  1700/2000 | best 6844.0 | acc 97.6598% | success 0/128 | gamma 0.16261 | |rz| 0.9129
G72 | step  1750/2000 | best 6844.0 | acc 97.6598% | success 0/128 | gamma 0.12728 | |rz| 0.9156
G72 | step  1800/2000 | best 6844.0 | acc 97.6598% | success 0/128 | gamma 0.10025 | |rz| 0.9167
G72 | step  1850/2000 | best 6844.0 | acc 97.6598% | success 0/128 | gamma 0.07505 | |rz| 0.9170
G72 | step  1900/2000 | best 6844.0 | acc 97.6598% | success 0/128 | gamma 0.05003 | |rz| 0.9175
G72 | step  1950/2000 | best 6844.0 | acc 97.6598% | success 0/128 | gamma 0.02501 | |rz| 0.9185
G72 | step  2000/2000 | best 6844.0 | acc 97.6598% | success 0/128 | gamma 0.00000 | |rz| 0.9297

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G72
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644262e-05,0.000017,0.000008,7.830991e-06,0.000933
1,theta_grad_mean_abs,6.231911e-07,0.000003,0.000005,2.603721e-07,0.000115
2,raw_R_step_mean_abs,2.999592e-02,0.002981,0.002663,2.207928e-03,0.048872
3,theta_step_mean_abs,2.864354e-02,0.000753,0.002472,7.100633e-04,0.028644
4,raw_R_grad_norm,8.648500e-02,0.020629,0.009359,9.358653e-03,1.055497
5,theta_grad_norm,8.835514e-04,0.006642,0.014091,3.491449e-04,0.233364
6,raw_R_step_norm,3.393650e+01,3.591478,3.225987,2.766042e+00,55.291813
7,theta_step_norm,3.254841e+01,1.271292,9.112137,1.093685e+00,32.548409

--------------------------------------------------------------------------------
RESULT SUMMARY: G72
--------------------------------------------------------------------------------
historical_best: 7008.0

V1:
v1_best: 6860.0
v1_gap: 148.0
v1_percent_accuracy: 97.88812785388129

V2:
v2_best: 6844.0
v2_gap: 164.0
v2_percent_accuracy: 97.65981735159818
v2_best_step: 559
v2_best_replica: 17

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 72.22571206092834

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_16_18/logs/G72_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_16_18/best_spins/G72_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_16_18/partial_group_results.csv

================================================================================
RUN GROUP COMPLETE
================================================================================
run_group: big_16_18
graphs: 4

Group results:

,run_group,partition,instance,graph_type,storage_mode,nodes,edges,n_steps,replicas,lr,...,final_best,final_gap,final_percent_accuracy,best_step_success_count,best_step_success_probability,ever_success_count,ever_success_probability,final_success_count,final_success_probability,v2_runtime_sec
0,big_16_18,16,G65,toroid,edge_list,8000,16000,2000,128,0.03,...,5444.0,118.0,97.878461,0,0.0,0,0.0,0,0.0,59.417764
1,big_16_18,17,G66,toroid,edge_list,9000,18000,2000,128,0.03,...,6218.0,146.0,97.705845,0,0.0,0,0.0,0,0.0,67.212203
2,big_16_18,18,G67,toroid,edge_list,10000,20000,2000,128,0.03,...,6812.0,138.0,98.014388,0,0.0,0,0.0,0,0.0,71.305148
3,big_16_18,18,G72,toroid,edge_list,10000,20000,2000,128,0.03,...,6844.0,164.0,97.659817,0,0.0,0,0.0,0,0.0,72.225712

Compact group results:

,instance,historical_best,v1_best,v1_gap,v1_percent_accuracy,v2_best,v2_gap,v2_percent_accuracy,v2_best_step,v2_best_replica,ever_success_count,ever_success_probability,final_best,final_gap,final_percent_accuracy,final_success_count,final_success_probability,v2_runtime_sec
0,G65,5562.0,5448.0,114.0,97.950378,5444.0,118.0,97.878461,468,53,0,0.0,5444.0,118.0,97.878461,0,0.0,59.417764
1,G66,6364.0,6228.0,136.0,97.862979,6218.0,146.0,97.705845,624,70,0,0.0,6218.0,146.0,97.705845,0,0.0,67.212203
2,G67,6950.0,6806.0,144.0,97.928058,6812.0,138.0,98.014388,564,30,0,0.0,6812.0,138.0,98.014388,0,0.0,71.305148
3,G72,7008.0,6860.0,148.0,97.888128,6844.0,164.0,97.659817,559,17,0,0.0,6844.0,164.0,97.659817,0,0.0,72.225712

Saved group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_16_18/group_results.csv

Saved group logs:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_16_18/group_training_logs.csv

================================================================================
COMPACT GROUP RESULT
================================================================================

,instance,historical_best,v1_best,v1_gap,v1_percent_accuracy,v2_best,v2_gap,v2_percent_accuracy,v2_best_step,v2_best_replica,ever_success_count,ever_success_probability,final_best,final_gap,final_percent_accuracy,final_success_count,final_success_probability,v2_runtime_sec
0,G65,5562.0,5448.0,114.0,97.950378,5444.0,118.0,97.878461,468,53,0,0.0,5444.0,118.0,97.878461,0,0.0,59.417764
1,G66,6364.0,6228.0,136.0,97.862979,6218.0,146.0,97.705845,624,70,0,0.0,6218.0,146.0,97.705845,0,0.0,67.212203
2,G67,6950.0,6806.0,144.0,97.928058,6812.0,138.0,98.014388,564,30,0,0.0,6812.0,138.0,98.014388,0,0.0,71.305148
3,G72,7008.0,6860.0,148.0,97.888128,6844.0,164.0,97.659817,559,17,0,0.0,6844.0,164.0,97.659817,0,0.0,72.225712

In [114]:
print("\nGroup summary:")
print("graphs:", len(group_results_df))
print("mean v1 accuracy %:", float(group_results_df["v1_percent_accuracy"].mean()))
print("mean v2 accuracy %:", float(group_results_df["v2_percent_accuracy"].mean()))
print("v1 gap-zero count:", int((group_results_df["v1_gap"] == 0).sum()))
print("v2 gap-zero count:", int((group_results_df["v2_gap"] == 0).sum()))
print("total v2 runtime sec:", float(group_results_df["v2_runtime_sec"].sum()))

Group summary:
graphs: 4
mean v1 accuracy %: 97.90738555704857
mean v2 accuracy %: 97.81462805158198
v1 gap-zero count: 0
v2 gap-zero count: 0
total v2 runtime sec: 270.1608271598816

In [115]:
# ============================================================
# Quick inspection: where did V2 improve over V1?
# ============================================================

inspection_df = group_results_df[
    [
        "instance",
        "historical_best",
        "v1_best",
        "v1_gap",
        "v1_percent_accuracy",
        "v2_best",
        "v2_gap",
        "v2_percent_accuracy",
        "v2_best_step",
        "ever_success_count",
        "ever_success_probability",
        "final_best",
        "final_gap",
        "final_percent_accuracy",
    ]
].copy()

inspection_df["gap_improvement"] = (
    inspection_df["v1_gap"] - inspection_df["v2_gap"]
)

inspection_df["accuracy_improvement"] = (
    inspection_df["v2_percent_accuracy"] - inspection_df["v1_percent_accuracy"]
)

inspection_df = inspection_df.sort_values(
    "gap_improvement",
    ascending=False,
).reset_index(drop=True)

print("=" * 80)
print("V2 IMPROVEMENT INSPECTION")
print("=" * 80)

display(inspection_df)

print("\nSummary:")
print("graphs:", len(inspection_df))
print("improved gap count:", int((inspection_df["gap_improvement"] > 0).sum()))
print("same gap count    :", int((inspection_df["gap_improvement"] == 0).sum()))
print("worse gap count   :", int((inspection_df["gap_improvement"] < 0).sum()))

print("\nGap improvement:")
print("mean:", float(inspection_df["gap_improvement"].mean()))
print("min :", float(inspection_df["gap_improvement"].min()))
print("max :", float(inspection_df["gap_improvement"].max()))

print("\nAccuracy improvement:")
print("mean:", float(inspection_df["accuracy_improvement"].mean()))
print("min :", float(inspection_df["accuracy_improvement"].min()))
print("max :", float(inspection_df["accuracy_improvement"].max()))

print("\nClosest V2 gaps:")
display(
    inspection_df.sort_values("v2_gap")[
        [
            "instance",
            "historical_best",
            "v2_best",
            "v2_gap",
            "v2_percent_accuracy",
            "v2_best_step",
            "ever_success_count",
            "final_gap",
        ]
    ].head(10)
)

================================================================================
V2 IMPROVEMENT INSPECTION
================================================================================

,instance,historical_best,v1_best,v1_gap,v1_percent_accuracy,v2_best,v2_gap,v2_percent_accuracy,v2_best_step,ever_success_count,ever_success_probability,final_best,final_gap,final_percent_accuracy,gap_improvement,accuracy_improvement
0,G67,6950.0,6806.0,144.0,97.928058,6812.0,138.0,98.014388,564,0,0.0,6812.0,138.0,98.014388,6.0,0.086331
1,G65,5562.0,5448.0,114.0,97.950378,5444.0,118.0,97.878461,468,0,0.0,5444.0,118.0,97.878461,-4.0,-0.071917
2,G66,6364.0,6228.0,136.0,97.862979,6218.0,146.0,97.705845,624,0,0.0,6218.0,146.0,97.705845,-10.0,-0.157134
3,G72,7008.0,6860.0,148.0,97.888128,6844.0,164.0,97.659817,559,0,0.0,6844.0,164.0,97.659817,-16.0,-0.228311

Summary:
graphs: 4
improved gap count: 1
same gap count    : 0
worse gap count   : 3

Gap improvement:
mean: -6.0
min : -16.0
max : 6.0

Accuracy improvement:
mean: -0.09275750546659012
min : -0.228310502283108
max : 0.08633093525179447

Closest V2 gaps:

,instance,historical_best,v2_best,v2_gap,v2_percent_accuracy,v2_best_step,ever_success_count,final_gap
1,G65,5562.0,5444.0,118.0,97.878461,468,0,118.0
0,G67,6950.0,6812.0,138.0,98.014388,564,0,138.0
2,G66,6364.0,6218.0,146.0,97.705845,624,0,146.0
3,G72,7008.0,6844.0,164.0,97.659817,559,0,164.0

# 6

In [120]:
# ============================================================
# Cell 10: Select run group and run QEFEM v2
# ============================================================

# ------------------------------------------------------------
# Choose run group here
# ------------------------------------------------------------
# 0 -> small_1_3   : G1-G21
# 1 -> small_4_6   : G22-G42
# 2 -> small_7_9   : G43-G54
# 3 -> big_10_12   : G55-G59
# 4 -> big_13_15   : G60-G64
# 5 -> big_16_18   : G65, G66, G67, G72
# 6 -> big_19_21   : G70, G77, G81

RUN_GROUP_INDEX = 6


# ------------------------------------------------------------
# Preview selected group
# ------------------------------------------------------------

selected_group_row = run_group_summary_df.iloc[RUN_GROUP_INDEX]

print("=" * 80)
print("SELECTED RUN GROUP")
print("=" * 80)

print("RUN_GROUP_INDEX:", RUN_GROUP_INDEX)
print("run_group:", selected_group_row["run_group"])
print("partitions:", selected_group_row["partitions"])
print("graphs_start:", selected_group_row["graphs_start"])
print("graphs_end:", selected_group_row["graphs_end"])
print("num_graphs:", selected_group_row["num_graphs"])
print("graph_types:", selected_group_row["graph_types"])
print("storage_modes:", selected_group_row["storage_modes"])
print("graphs:", selected_group_row["graphs"])


# ------------------------------------------------------------
# Run selected group
# ------------------------------------------------------------

group_results_df, group_logs_df = run_qefem_run_group(
    run_group_index=RUN_GROUP_INDEX
)


# ------------------------------------------------------------
# Final compact display
# ------------------------------------------------------------

compact_group_results_df = group_results_df[
    [
        "instance",
        "historical_best",
        "v1_best",
        "v1_gap",
        "v1_percent_accuracy",
        "v2_best",
        "v2_gap",
        "v2_percent_accuracy",
        "v2_best_step",
        "v2_best_replica",
        "ever_success_count",
        "ever_success_probability",
        "final_best",
        "final_gap",
        "final_percent_accuracy",
        "final_success_count",
        "final_success_probability",
        "v2_runtime_sec",
    ]
].copy()

print("\n" + "=" * 80)
print("COMPACT GROUP RESULT")
print("=" * 80)

display(compact_group_results_df)

================================================================================
SELECTED RUN GROUP
================================================================================
RUN_GROUP_INDEX: 6
run_group: big_19_21
partitions: [19, 20, 21]
graphs_start: G70
graphs_end: G81
num_graphs: 3
graph_types: ['plain', 'toroid']
storage_modes: ['edge_list']
graphs: ['G70', 'G77', 'G81']
================================================================================
RUNNING QEFEM V2 RUN GROUP
================================================================================
run_group_index: 6
run_group: big_19_21
graphs: ['G70', 'G77', 'G81']
num graphs: 3

Output directory:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_19_21

Selected benchmark rows:

,partition,instance,graph_type,storage_mode,nodes,edges,n_steps,replicas,lr,v1_best,historical_best,v1_gap,v1_percent_accuracy,v1_best_replica,v1_runtime_sec
0,19,G70,plain,edge_list,10000,9999,1000,128,0.01,9412.0,9591.0,179.0,98.133667,62,36.532485
1,20,G77,toroid,edge_list,14000,28000,1000,128,0.01,9722.0,9940.0,218.0,97.806841,106,62.788516
2,21,G81,toroid,edge_list,20000,40000,1000,128,0.01,13716.0,14060.0,344.0,97.553343,63,84.624155

################################################################################
RUNNING G70 | edge_list | seed=7
################################################################################
G70 | step     1/2000 | best 5091.0 | acc 53.0810% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G70 | step    50/2000 | best 5440.0 | acc 56.7198% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G70 | step   100/2000 | best 5450.0 | acc 56.8241% | success 0/128 | gamma 0.95048 | |rz| 0.0009
G70 | step   150/2000 | best 9065.0 | acc 94.5157% | success 0/128 | gamma 0.92546 | |rz| 0.1300
G70 | step   200/2000 | best 9084.0 | acc 94.7138% | success 0/128 | gamma 0.90045 | |rz| 0.1940
G70 | step   250/2000 | best 9084.0 | acc 94.7138% | success 0/128 | gamma 0.87544 | |rz| 0.2283
G70 | step   300/2000 | best 9084.0 | acc 94.7138% | success 0/128 | gamma 0.85043 | |rz| 0.2552
G70 | step   350/2000 | best 9084.0 | acc 94.7138% | success 0/128 | gamma 0.82541 | |rz| 0.2808
G70 | step   400/2000 | best 9084.0 | acc 94.7138% | success 0/128 | gamma 0.80040 | |rz| 0.3057
G70 | step   450/2000 | best 9085.0 | acc 94.7242% | success 0/128 | gamma 0.77539 | |rz| 0.3305
G70 | step   500/2000 | best 9097.0 | acc 94.8493% | success 0/128 | gamma 0.75038 | |rz| 0.3550
G70 | step   550/2000 | best 9108.0 | acc 94.9640% | success 0/128 | gamma 0.72536 | |rz| 0.3792
G70 | step   600/2000 | best 9124.0 | acc 95.1309% | success 0/128 | gamma 0.70035 | |rz| 0.4033
G70 | step   650/2000 | best 9139.0 | acc 95.2872% | success 0/128 | gamma 0.67534 | |rz| 0.4271
G70 | step   700/2000 | best 9156.0 | acc 95.4645% | success 0/128 | gamma 0.65033 | |rz| 0.4500
G70 | step   750/2000 | best 9166.0 | acc 95.5688% | success 0/128 | gamma 0.62531 | |rz| 0.4726
G70 | step   800/2000 | best 9184.0 | acc 95.7564% | success 0/128 | gamma 0.60030 | |rz| 0.4947
G70 | step   850/2000 | best 9211.0 | acc 96.0380% | success 0/128 | gamma 0.57529 | |rz| 0.5164
G70 | step   900/2000 | best 9228.0 | acc 96.2152% | success 0/128 | gamma 0.55028 | |rz| 0.5380
G70 | step   950/2000 | best 9251.0 | acc 96.4550% | success 0/128 | gamma 0.52526 | |rz| 0.5585
G70 | step  1000/2000 | best 9255.0 | acc 96.4967% | success 0/128 | gamma 0.50025 | |rz| 0.5789
G70 | step  1050/2000 | best 9295.0 | acc 96.9138% | success 0/128 | gamma 0.47524 | |rz| 0.5976
G70 | step  1100/2000 | best 9333.0 | acc 97.3100% | success 0/128 | gamma 0.45023 | |rz| 0.6186
G70 | step  1150/2000 | best 9334.0 | acc 97.3204% | success 0/128 | gamma 0.42521 | |rz| 0.6384
G70 | step  1200/2000 | best 9334.0 | acc 97.3204% | success 0/128 | gamma 0.40020 | |rz| 0.6557
G70 | step  1250/2000 | best 9334.0 | acc 97.3204% | success 0/128 | gamma 0.37519 | |rz| 0.6721
G70 | step  1300/2000 | best 9334.0 | acc 97.3204% | success 0/128 | gamma 0.35018 | |rz| 0.6879
G70 | step  1350/2000 | best 9390.0 | acc 97.9043% | success 0/128 | gamma 0.32517 | |rz| 0.7028
G70 | step  1400/2000 | best 9393.0 | acc 97.9356% | success 0/128 | gamma 0.30034 | |rz| 0.7224
G70 | step  1450/2000 | best 9399.0 | acc 97.9981% | success 0/128 | gamma 0.27732 | |rz| 0.7377
G70 | step  1500/2000 | best 9404.0 | acc 98.0503% | success 0/128 | gamma 0.26252 | |rz| 0.7482
G70 | step  1550/2000 | best 9493.0 | acc 98.9782% | success 0/128 | gamma 0.26035 | |rz| 0.7630
G70 | step  1600/2000 | best 9497.0 | acc 99.0199% | success 0/128 | gamma 0.25010 | |rz| 0.7764
G70 | step  1650/2000 | best 9497.0 | acc 99.0199% | success 0/128 | gamma 0.21052 | |rz| 0.7929
G70 | step  1700/2000 | best 9497.0 | acc 99.0199% | success 0/128 | gamma 0.16261 | |rz| 0.8079
G70 | step  1750/2000 | best 9497.0 | acc 99.0199% | success 0/128 | gamma 0.12728 | |rz| 0.8168
G70 | step  1800/2000 | best 9497.0 | acc 99.0199% | success 0/128 | gamma 0.10025 | |rz| 0.8222
G70 | step  1850/2000 | best 9497.0 | acc 99.0199% | success 0/128 | gamma 0.07505 | |rz| 0.8262
G70 | step  1900/2000 | best 9497.0 | acc 99.0199% | success 0/128 | gamma 0.05003 | |rz| 0.8291
G70 | step  1950/2000 | best 9497.0 | acc 99.0199% | success 0/128 | gamma 0.02501 | |rz| 0.8312
G70 | step  2000/2000 | best 9497.0 | acc 99.0199% | success 0/128 | gamma 0.00000 | |rz| 0.8362

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G70
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644270e-05,0.000013,0.000009,9.212492e-06,0.000933
1,theta_grad_mean_abs,6.235870e-07,0.000004,0.000003,2.635047e-07,0.000026
2,raw_R_step_mean_abs,2.999592e-02,0.002346,0.003214,1.048077e-03,0.048872
3,theta_step_mean_abs,2.864611e-02,0.000991,0.001631,8.579483e-04,0.028646
4,raw_R_grad_norm,8.648509e-02,0.018050,0.011829,1.182900e-02,1.055499
5,theta_grad_norm,8.839731e-04,0.007186,0.009378,3.474836e-04,0.114177
6,raw_R_step_norm,3.393650e+01,3.242879,4.143429,1.881671e+00,55.291840
7,theta_step_norm,3.255038e+01,1.696587,5.879339,1.244814e+00,32.550385

--------------------------------------------------------------------------------
RESULT SUMMARY: G70
--------------------------------------------------------------------------------
historical_best: 9591.0

V1:
v1_best: 9412.0
v1_gap: 179.0
v1_percent_accuracy: 98.1336669794599

V2:
v2_best: 9497.0
v2_gap: 94.0
v2_percent_accuracy: 99.01991450318006
v2_best_step: 1560
v2_best_replica: 24

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 59.23065805435181

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_19_21/logs/G70_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_19_21/best_spins/G70_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_19_21/partial_group_results.csv

################################################################################
RUNNING G77 | edge_list | seed=8
################################################################################
G77 | step     1/2000 | best 200.0 | acc 2.0121% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G77 | step    50/2000 | best 1134.0 | acc 11.4085% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G77 | step   100/2000 | best 1188.0 | acc 11.9517% | success 0/128 | gamma 0.95048 | |rz| 0.0010
G77 | step   150/2000 | best 9618.0 | acc 96.7606% | success 0/128 | gamma 0.92546 | |rz| 0.3518
G77 | step   200/2000 | best 9690.0 | acc 97.4849% | success 0/128 | gamma 0.90045 | |rz| 0.4946
G77 | step   250/2000 | best 9692.0 | acc 97.5050% | success 0/128 | gamma 0.87544 | |rz| 0.5493
G77 | step   300/2000 | best 9698.0 | acc 97.5654% | success 0/128 | gamma 0.85043 | |rz| 0.5823
G77 | step   350/2000 | best 9706.0 | acc 97.6459% | success 0/128 | gamma 0.82541 | |rz| 0.6093
G77 | step   400/2000 | best 9710.0 | acc 97.6861% | success 0/128 | gamma 0.80040 | |rz| 0.6337
G77 | step   450/2000 | best 9716.0 | acc 97.7465% | success 0/128 | gamma 0.77539 | |rz| 0.6561
G77 | step   500/2000 | best 9720.0 | acc 97.7867% | success 0/128 | gamma 0.75038 | |rz| 0.6770
G77 | step   550/2000 | best 9720.0 | acc 97.7867% | success 0/128 | gamma 0.72536 | |rz| 0.6966
G77 | step   600/2000 | best 9720.0 | acc 97.7867% | success 0/128 | gamma 0.70035 | |rz| 0.7149
G77 | step   650/2000 | best 9720.0 | acc 97.7867% | success 0/128 | gamma 0.67534 | |rz| 0.7320
G77 | step   700/2000 | best 9720.0 | acc 97.7867% | success 0/128 | gamma 0.65033 | |rz| 0.7480
G77 | step   750/2000 | best 9720.0 | acc 97.7867% | success 0/128 | gamma 0.62531 | |rz| 0.7630
G77 | step   800/2000 | best 9720.0 | acc 97.7867% | success 0/128 | gamma 0.60030 | |rz| 0.7771
G77 | step   850/2000 | best 9720.0 | acc 97.7867% | success 0/128 | gamma 0.57529 | |rz| 0.7903
G77 | step   900/2000 | best 9720.0 | acc 97.7867% | success 0/128 | gamma 0.55028 | |rz| 0.8027
G77 | step   950/2000 | best 9720.0 | acc 97.7867% | success 0/128 | gamma 0.52526 | |rz| 0.8143
G77 | step  1000/2000 | best 9720.0 | acc 97.7867% | success 0/128 | gamma 0.50025 | |rz| 0.8252
G77 | step  1050/2000 | best 9720.0 | acc 97.7867% | success 0/128 | gamma 0.47524 | |rz| 0.8354
G77 | step  1100/2000 | best 9720.0 | acc 97.7867% | success 0/128 | gamma 0.45023 | |rz| 0.8450
G77 | step  1150/2000 | best 9720.0 | acc 97.7867% | success 0/128 | gamma 0.42521 | |rz| 0.8539
G77 | step  1200/2000 | best 9720.0 | acc 97.7867% | success 0/128 | gamma 0.40020 | |rz| 0.8623
G77 | step  1250/2000 | best 9720.0 | acc 97.7867% | success 0/128 | gamma 0.37519 | |rz| 0.8701
G77 | step  1300/2000 | best 9720.0 | acc 97.7867% | success 0/128 | gamma 0.35018 | |rz| 0.8774
G77 | step  1350/2000 | best 9720.0 | acc 97.7867% | success 0/128 | gamma 0.32517 | |rz| 0.8841
G77 | step  1400/2000 | best 9720.0 | acc 97.7867% | success 0/128 | gamma 0.30034 | |rz| 0.8904
G77 | step  1450/2000 | best 9720.0 | acc 97.7867% | success 0/128 | gamma 0.27732 | |rz| 0.8958
G77 | step  1500/2000 | best 9720.0 | acc 97.7867% | success 0/128 | gamma 0.26252 | |rz| 0.8995
G77 | step  1550/2000 | best 9720.0 | acc 97.7867% | success 0/128 | gamma 0.26035 | |rz| 0.9009
G77 | step  1600/2000 | best 9720.0 | acc 97.7867% | success 0/128 | gamma 0.25010 | |rz| 0.9037
G77 | step  1650/2000 | best 9720.0 | acc 97.7867% | success 0/128 | gamma 0.21052 | |rz| 0.9101
G77 | step  1700/2000 | best 9720.0 | acc 97.7867% | success 0/128 | gamma 0.16261 | |rz| 0.9158
G77 | step  1750/2000 | best 9720.0 | acc 97.7867% | success 0/128 | gamma 0.12728 | |rz| 0.9186
G77 | step  1800/2000 | best 9720.0 | acc 97.7867% | success 0/128 | gamma 0.10025 | |rz| 0.9198
G77 | step  1850/2000 | best 9720.0 | acc 97.7867% | success 0/128 | gamma 0.07505 | |rz| 0.9203
G77 | step  1900/2000 | best 9720.0 | acc 97.7867% | success 0/128 | gamma 0.05003 | |rz| 0.9208
G77 | step  1950/2000 | best 9720.0 | acc 97.7867% | success 0/128 | gamma 0.02501 | |rz| 0.9217
G77 | step  2000/2000 | best 9720.0 | acc 97.7867% | success 0/128 | gamma 0.00000 | |rz| 0.9323

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G77
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644268e-05,0.000017,0.000008,7.874100e-06,0.000933
1,theta_grad_mean_abs,6.236174e-07,0.000003,0.000005,2.606334e-07,0.000111
2,raw_R_step_mean_abs,2.999592e-02,0.002987,0.002675,2.213889e-03,0.048872
3,theta_step_mean_abs,2.864399e-02,0.000754,0.002372,7.139532e-04,0.028644
4,raw_R_grad_norm,1.023305e-01,0.024435,0.011126,1.112595e-02,1.248880
5,theta_grad_norm,1.046338e-03,0.007855,0.016475,4.135495e-04,0.268134
6,raw_R_step_norm,4.015421e+01,4.251412,3.831420,3.280022e+00,65.422134
7,theta_step_norm,3.851163e+01,1.503282,10.452410,1.336521e+00,38.511631

--------------------------------------------------------------------------------
RESULT SUMMARY: G77
--------------------------------------------------------------------------------
historical_best: 9940.0

V1:
v1_best: 9722.0
v1_gap: 218.0
v1_percent_accuracy: 97.80684104627768

V2:
v2_best: 9720.0
v2_gap: 220.0
v2_percent_accuracy: 97.78672032193158
v2_best_step: 474
v2_best_replica: 24

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 102.55550599098206

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_19_21/logs/G77_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_19_21/best_spins/G77_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_19_21/partial_group_results.csv

################################################################################
RUNNING G81 | edge_list | seed=9
################################################################################
G81 | step     1/2000 | best 138.0 | acc 0.9815% | success 0/128 | gamma 1.00000 | |rz| 0.0002
G81 | step    50/2000 | best 1400.0 | acc 9.9573% | success 0/128 | gamma 0.97549 | |rz| 0.0000
G81 | step   100/2000 | best 1538.0 | acc 10.9388% | success 0/128 | gamma 0.95048 | |rz| 0.0010
G81 | step   150/2000 | best 13598.0 | acc 96.7141% | success 0/128 | gamma 0.92546 | |rz| 0.3516
G81 | step   200/2000 | best 13674.0 | acc 97.2546% | success 0/128 | gamma 0.90045 | |rz| 0.4940
G81 | step   250/2000 | best 13690.0 | acc 97.3684% | success 0/128 | gamma 0.87544 | |rz| 0.5486
G81 | step   300/2000 | best 13698.0 | acc 97.4253% | success 0/128 | gamma 0.85043 | |rz| 0.5815
G81 | step   350/2000 | best 13706.0 | acc 97.4822% | success 0/128 | gamma 0.82541 | |rz| 0.6084
G81 | step   400/2000 | best 13712.0 | acc 97.5249% | success 0/128 | gamma 0.80040 | |rz| 0.6327
G81 | step   450/2000 | best 13720.0 | acc 97.5818% | success 0/128 | gamma 0.77539 | |rz| 0.6551
G81 | step   500/2000 | best 13722.0 | acc 97.5960% | success 0/128 | gamma 0.75038 | |rz| 0.6759
G81 | step   550/2000 | best 13732.0 | acc 97.6671% | success 0/128 | gamma 0.72536 | |rz| 0.6955
G81 | step   600/2000 | best 13736.0 | acc 97.6956% | success 0/128 | gamma 0.70035 | |rz| 0.7137
G81 | step   650/2000 | best 13736.0 | acc 97.6956% | success 0/128 | gamma 0.67534 | |rz| 0.7308
G81 | step   700/2000 | best 13736.0 | acc 97.6956% | success 0/128 | gamma 0.65033 | |rz| 0.7468
G81 | step   750/2000 | best 13736.0 | acc 97.6956% | success 0/128 | gamma 0.62531 | |rz| 0.7618
G81 | step   800/2000 | best 13736.0 | acc 97.6956% | success 0/128 | gamma 0.60030 | |rz| 0.7758
G81 | step   850/2000 | best 13736.0 | acc 97.6956% | success 0/128 | gamma 0.57529 | |rz| 0.7889
G81 | step   900/2000 | best 13736.0 | acc 97.6956% | success 0/128 | gamma 0.55028 | |rz| 0.8012
G81 | step   950/2000 | best 13736.0 | acc 97.6956% | success 0/128 | gamma 0.52526 | |rz| 0.8127
G81 | step  1000/2000 | best 13736.0 | acc 97.6956% | success 0/128 | gamma 0.50025 | |rz| 0.8235
G81 | step  1050/2000 | best 13736.0 | acc 97.6956% | success 0/128 | gamma 0.47524 | |rz| 0.8337
G81 | step  1100/2000 | best 13736.0 | acc 97.6956% | success 0/128 | gamma 0.45023 | |rz| 0.8431
G81 | step  1150/2000 | best 13736.0 | acc 97.6956% | success 0/128 | gamma 0.42521 | |rz| 0.8520
G81 | step  1200/2000 | best 13736.0 | acc 97.6956% | success 0/128 | gamma 0.40020 | |rz| 0.8602
G81 | step  1250/2000 | best 13736.0 | acc 97.6956% | success 0/128 | gamma 0.37519 | |rz| 0.8679
G81 | step  1300/2000 | best 13736.0 | acc 97.6956% | success 0/128 | gamma 0.35018 | |rz| 0.8751
G81 | step  1350/2000 | best 13736.0 | acc 97.6956% | success 0/128 | gamma 0.32517 | |rz| 0.8818
G81 | step  1400/2000 | best 13736.0 | acc 97.6956% | success 0/128 | gamma 0.30034 | |rz| 0.8879
G81 | step  1450/2000 | best 13736.0 | acc 97.6956% | success 0/128 | gamma 0.27732 | |rz| 0.8933
G81 | step  1500/2000 | best 13736.0 | acc 97.6956% | success 0/128 | gamma 0.26252 | |rz| 0.8969
G81 | step  1550/2000 | best 13736.0 | acc 97.6956% | success 0/128 | gamma 0.26035 | |rz| 0.8984
G81 | step  1600/2000 | best 13736.0 | acc 97.6956% | success 0/128 | gamma 0.25010 | |rz| 0.9011
G81 | step  1650/2000 | best 13736.0 | acc 97.6956% | success 0/128 | gamma 0.21052 | |rz| 0.9075
G81 | step  1700/2000 | best 13736.0 | acc 97.6956% | success 0/128 | gamma 0.16261 | |rz| 0.9130
G81 | step  1750/2000 | best 13736.0 | acc 97.6956% | success 0/128 | gamma 0.12728 | |rz| 0.9157
G81 | step  1800/2000 | best 13736.0 | acc 97.6956% | success 0/128 | gamma 0.10025 | |rz| 0.9168
G81 | step  1850/2000 | best 13736.0 | acc 97.6956% | success 0/128 | gamma 0.07505 | |rz| 0.9172
G81 | step  1900/2000 | best 13736.0 | acc 97.6956% | success 0/128 | gamma 0.05003 | |rz| 0.9177
G81 | step  1950/2000 | best 13736.0 | acc 97.6956% | success 0/128 | gamma 0.02501 | |rz| 0.9187
G81 | step  2000/2000 | best 13736.0 | acc 97.6956% | success 0/128 | gamma 0.00000 | |rz| 0.9297

--------------------------------------------------------------------------------
GRADIENT / MOBILITY SUMMARY: G81
--------------------------------------------------------------------------------

,metric,first,middle,last,min,max
0,raw_R_grad_mean_abs,7.644279e-05,0.000017,0.000008,7.832678e-06,0.000933
1,theta_grad_mean_abs,6.233132e-07,0.000003,0.000005,2.604597e-07,0.000110
2,raw_R_step_mean_abs,2.999592e-02,0.002981,0.002661,2.208933e-03,0.048871
3,theta_step_mean_abs,2.864160e-02,0.000754,0.002446,7.130051e-04,0.028642
4,raw_R_grad_norm,1.223085e-01,0.029187,0.013240,1.323988e-02,1.492697
5,theta_grad_norm,1.249878e-03,0.009429,0.019909,4.939203e-04,0.320046
6,raw_R_step_norm,4.799347e+01,5.077480,4.559593,3.915072e+00,78.194382
7,theta_step_norm,4.602776e+01,1.802230,12.723351,1.588722e+00,46.027756

--------------------------------------------------------------------------------
RESULT SUMMARY: G81
--------------------------------------------------------------------------------
historical_best: 14060.0

V1:
v1_best: 13716.0
v1_gap: 344.0
v1_percent_accuracy: 97.55334281650072

V2:
v2_best: 13736.0
v2_gap: 324.0
v2_percent_accuracy: 97.69559032716927
v2_best_step: 559
v2_best_replica: 1

Replica success:
ever_success_count: 0
ever_success_probability: 0.0
best_step_success_count: 0
best_step_success_probability: 0.0
final_success_count: 0
final_success_probability: 0.0

Runtime:
v2_runtime_sec: 179.00275182724

Saved graph log:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_19_21/logs/G81_training_log.csv
Saved best spins:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_19_21/best_spins/G81_best_spins.pt
Saved partial group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_19_21/partial_group_results.csv

================================================================================
RUN GROUP COMPLETE
================================================================================
run_group: big_19_21
graphs: 3

Group results:

,run_group,partition,instance,graph_type,storage_mode,nodes,edges,n_steps,replicas,lr,...,final_best,final_gap,final_percent_accuracy,best_step_success_count,best_step_success_probability,ever_success_count,ever_success_probability,final_success_count,final_success_probability,v2_runtime_sec
0,big_19_21,19,G70,plain,edge_list,10000,9999,2000,128,0.03,...,9497.0,94.0,99.019915,0,0.0,0,0.0,0,0.0,59.230658
1,big_19_21,20,G77,toroid,edge_list,14000,28000,2000,128,0.03,...,9720.0,220.0,97.786720,0,0.0,0,0.0,0,0.0,102.555506
2,big_19_21,21,G81,toroid,edge_list,20000,40000,2000,128,0.03,...,13736.0,324.0,97.695590,0,0.0,0,0.0,0,0.0,179.002752

Compact group results:

,instance,historical_best,v1_best,v1_gap,v1_percent_accuracy,v2_best,v2_gap,v2_percent_accuracy,v2_best_step,v2_best_replica,ever_success_count,ever_success_probability,final_best,final_gap,final_percent_accuracy,final_success_count,final_success_probability,v2_runtime_sec
0,G70,9591.0,9412.0,179.0,98.133667,9497.0,94.0,99.019915,1560,24,0,0.0,9497.0,94.0,99.019915,0,0.0,59.230658
1,G77,9940.0,9722.0,218.0,97.806841,9720.0,220.0,97.786720,474,24,0,0.0,9720.0,220.0,97.786720,0,0.0,102.555506
2,G81,14060.0,13716.0,344.0,97.553343,13736.0,324.0,97.695590,559,1,0,0.0,13736.0,324.0,97.695590,0,0.0,179.002752

Saved group results:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_19_21/group_results.csv

Saved group logs:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs/big_19_21/group_training_logs.csv

================================================================================
COMPACT GROUP RESULT
================================================================================

,instance,historical_best,v1_best,v1_gap,v1_percent_accuracy,v2_best,v2_gap,v2_percent_accuracy,v2_best_step,v2_best_replica,ever_success_count,ever_success_probability,final_best,final_gap,final_percent_accuracy,final_success_count,final_success_probability,v2_runtime_sec
0,G70,9591.0,9412.0,179.0,98.133667,9497.0,94.0,99.019915,1560,24,0,0.0,9497.0,94.0,99.019915,0,0.0,59.230658
1,G77,9940.0,9722.0,218.0,97.806841,9720.0,220.0,97.786720,474,24,0,0.0,9720.0,220.0,97.786720,0,0.0,102.555506
2,G81,14060.0,13716.0,344.0,97.553343,13736.0,324.0,97.695590,559,1,0,0.0,13736.0,324.0,97.695590,0,0.0,179.002752

In [121]:
print("\nGroup summary:")
print("graphs:", len(group_results_df))
print("mean v1 accuracy %:", float(group_results_df["v1_percent_accuracy"].mean()))
print("mean v2 accuracy %:", float(group_results_df["v2_percent_accuracy"].mean()))
print("v1 gap-zero count:", int((group_results_df["v1_gap"] == 0).sum()))
print("v2 gap-zero count:", int((group_results_df["v2_gap"] == 0).sum()))
print("total v2 runtime sec:", float(group_results_df["v2_runtime_sec"].sum()))

Group summary:
graphs: 3
mean v1 accuracy %: 97.83128361407944
mean v2 accuracy %: 98.16740838409363
v1 gap-zero count: 0
v2 gap-zero count: 0
total v2 runtime sec: 340.78891587257385

In [122]:
# ============================================================
# Quick inspection: where did V2 improve over V1?
# ============================================================

inspection_df = group_results_df[
    [
        "instance",
        "historical_best",
        "v1_best",
        "v1_gap",
        "v1_percent_accuracy",
        "v2_best",
        "v2_gap",
        "v2_percent_accuracy",
        "v2_best_step",
        "ever_success_count",
        "ever_success_probability",
        "final_best",
        "final_gap",
        "final_percent_accuracy",
    ]
].copy()

inspection_df["gap_improvement"] = (
    inspection_df["v1_gap"] - inspection_df["v2_gap"]
)

inspection_df["accuracy_improvement"] = (
    inspection_df["v2_percent_accuracy"] - inspection_df["v1_percent_accuracy"]
)

inspection_df = inspection_df.sort_values(
    "gap_improvement",
    ascending=False,
).reset_index(drop=True)

print("=" * 80)
print("V2 IMPROVEMENT INSPECTION")
print("=" * 80)

display(inspection_df)

print("\nSummary:")
print("graphs:", len(inspection_df))
print("improved gap count:", int((inspection_df["gap_improvement"] > 0).sum()))
print("same gap count    :", int((inspection_df["gap_improvement"] == 0).sum()))
print("worse gap count   :", int((inspection_df["gap_improvement"] < 0).sum()))

print("\nGap improvement:")
print("mean:", float(inspection_df["gap_improvement"].mean()))
print("min :", float(inspection_df["gap_improvement"].min()))
print("max :", float(inspection_df["gap_improvement"].max()))

print("\nAccuracy improvement:")
print("mean:", float(inspection_df["accuracy_improvement"].mean()))
print("min :", float(inspection_df["accuracy_improvement"].min()))
print("max :", float(inspection_df["accuracy_improvement"].max()))

print("\nClosest V2 gaps:")
display(
    inspection_df.sort_values("v2_gap")[
        [
            "instance",
            "historical_best",
            "v2_best",
            "v2_gap",
            "v2_percent_accuracy",
            "v2_best_step",
            "ever_success_count",
            "final_gap",
        ]
    ].head(10)
)

================================================================================
V2 IMPROVEMENT INSPECTION
================================================================================

,instance,historical_best,v1_best,v1_gap,v1_percent_accuracy,v2_best,v2_gap,v2_percent_accuracy,v2_best_step,ever_success_count,ever_success_probability,final_best,final_gap,final_percent_accuracy,gap_improvement,accuracy_improvement
0,G70,9591.0,9412.0,179.0,98.133667,9497.0,94.0,99.019915,1560,0,0.0,9497.0,94.0,99.019915,85.0,0.886248
1,G81,14060.0,13716.0,344.0,97.553343,13736.0,324.0,97.695590,559,0,0.0,13736.0,324.0,97.695590,20.0,0.142248
2,G77,9940.0,9722.0,218.0,97.806841,9720.0,220.0,97.786720,474,0,0.0,9720.0,220.0,97.786720,-2.0,-0.020121

Summary:
graphs: 3
improved gap count: 2
same gap count    : 0
worse gap count   : 1

Gap improvement:
mean: 34.333333333333336
min : -2.0
max : 85.0

Accuracy improvement:
mean: 0.336124770014204
min : -0.020120724346099905
max : 0.8862475237201579

Closest V2 gaps:

,instance,historical_best,v2_best,v2_gap,v2_percent_accuracy,v2_best_step,ever_success_count,final_gap
0,G70,9591.0,9497.0,94.0,99.019915,1560,0,94.0
2,G77,9940.0,9720.0,220.0,97.786720,474,0,220.0
1,G81,14060.0,13736.0,324.0,97.695590,559,0,324.0

In [124]:
# ============================================================
# Check saved QEFEM v2 result files on disk
# ============================================================

from pathlib import Path
import pandas as pd

print("=" * 80)
print("CHECK SAVED QEFEM V2 FILES")
print("=" * 80)

print("QEFEM_V2_OUTPUT_DIR:")
print(QEFEM_V2_OUTPUT_DIR.resolve())

saved_result_paths = sorted(
    QEFEM_V2_OUTPUT_DIR.glob("*/group_results.csv")
)

saved_log_paths = sorted(
    QEFEM_V2_OUTPUT_DIR.glob("*/group_training_logs.csv")
)

partial_result_paths = sorted(
    QEFEM_V2_OUTPUT_DIR.glob("*/partial_group_results.csv")
)

print("\nSaved group_results.csv files:")
for path in saved_result_paths:
    df = pd.read_csv(path)
    print(
        path,
        "| rows:",
        len(df),
        "| instances:",
        df["instance"].tolist()
    )

print("\nSaved group_training_logs.csv files:")
for path in saved_log_paths:
    df = pd.read_csv(path)
    print(
        path,
        "| rows:",
        len(df),
        "| instances:",
        sorted(df["instance"].unique().tolist())
    )

print("\nSaved partial_group_results.csv files:")
for path in partial_result_paths:
    df = pd.read_csv(path)
    print(
        path,
        "| rows:",
        len(df),
        "| instances:",
        df["instance"].tolist()
    )

================================================================================
CHECK SAVED QEFEM V2 FILES
================================================================================
QEFEM_V2_OUTPUT_DIR:
/Users/ronit/Desktop/QeFEM/main/maxcut_results/qefem_v2_outputs

Saved group_results.csv files:
qefem_v2_outputs/big_10_12/group_results.csv | rows: 5 | instances: ['G55', 'G56', 'G57', 'G58', 'G59']
qefem_v2_outputs/big_13_15/group_results.csv | rows: 5 | instances: ['G60', 'G61', 'G62', 'G63', 'G64']
qefem_v2_outputs/big_16_18/group_results.csv | rows: 4 | instances: ['G65', 'G66', 'G67', 'G72']
qefem_v2_outputs/big_19_21/group_results.csv | rows: 3 | instances: ['G70', 'G77', 'G81']
qefem_v2_outputs/small_1_3/group_results.csv | rows: 21 | instances: ['G1', 'G2', 'G3', 'G4', 'G5', 'G6', 'G7', 'G8', 'G9', 'G10', 'G11', 'G12', 'G13', 'G14', 'G15', 'G16', 'G17', 'G18', 'G19', 'G20', 'G21']
qefem_v2_outputs/small_4_6/group_results.csv | rows: 21 | instances: ['G22', 'G23', 'G24', 'G25', 'G26', 'G27', 'G28', 'G29', 'G30', 'G31', 'G32', 'G33', 'G34', 'G35', 'G36', 'G37', 'G38', 'G39', 'G40', 'G41', 'G42']
qefem_v2_outputs/small_7_9/group_results.csv | rows: 12 | instances: ['G43', 'G44', 'G45', 'G46', 'G47', 'G48', 'G49', 'G50', 'G51', 'G52', 'G53', 'G54']

Saved group_training_logs.csv files:
qefem_v2_outputs/big_10_12/group_training_logs.csv | rows: 205 | instances: ['G55', 'G56', 'G57', 'G58', 'G59']
qefem_v2_outputs/big_13_15/group_training_logs.csv | rows: 205 | instances: ['G60', 'G61', 'G62', 'G63', 'G64']
qefem_v2_outputs/big_16_18/group_training_logs.csv | rows: 164 | instances: ['G65', 'G66', 'G67', 'G72']
qefem_v2_outputs/big_19_21/group_training_logs.csv | rows: 123 | instances: ['G70', 'G77', 'G81']
qefem_v2_outputs/small_1_3/group_training_logs.csv | rows: 861 | instances: ['G1', 'G10', 'G11', 'G12', 'G13', 'G14', 'G15', 'G16', 'G17', 'G18', 'G19', 'G2', 'G20', 'G21', 'G3', 'G4', 'G5', 'G6', 'G7', 'G8', 'G9']
qefem_v2_outputs/small_4_6/group_training_logs.csv | rows: 861 | instances: ['G22', 'G23', 'G24', 'G25', 'G26', 'G27', 'G28', 'G29', 'G30', 'G31', 'G32', 'G33', 'G34', 'G35', 'G36', 'G37', 'G38', 'G39', 'G40', 'G41', 'G42']
qefem_v2_outputs/small_7_9/group_training_logs.csv | rows: 492 | instances: ['G43', 'G44', 'G45', 'G46', 'G47', 'G48', 'G49', 'G50', 'G51', 'G52', 'G53', 'G54']

Saved partial_group_results.csv files:
qefem_v2_outputs/big_10_12/partial_group_results.csv | rows: 5 | instances: ['G55', 'G56', 'G57', 'G58', 'G59']
qefem_v2_outputs/big_13_15/partial_group_results.csv | rows: 5 | instances: ['G60', 'G61', 'G62', 'G63', 'G64']
qefem_v2_outputs/big_16_18/partial_group_results.csv | rows: 4 | instances: ['G65', 'G66', 'G67', 'G72']
qefem_v2_outputs/big_19_21/partial_group_results.csv | rows: 3 | instances: ['G70', 'G77', 'G81']
qefem_v2_outputs/small_1_3/partial_group_results.csv | rows: 21 | instances: ['G1', 'G2', 'G3', 'G4', 'G5', 'G6', 'G7', 'G8', 'G9', 'G10', 'G11', 'G12', 'G13', 'G14', 'G15', 'G16', 'G17', 'G18', 'G19', 'G20', 'G21']
qefem_v2_outputs/small_4_6/partial_group_results.csv | rows: 21 | instances: ['G22', 'G23', 'G24', 'G25', 'G26', 'G27', 'G28', 'G29', 'G30', 'G31', 'G32', 'G33', 'G34', 'G35', 'G36', 'G37', 'G38', 'G39', 'G40', 'G41', 'G42']
qefem_v2_outputs/small_7_9/partial_group_results.csv | rows: 12 | instances: ['G43', 'G44', 'G45', 'G46', 'G47', 'G48', 'G49', 'G50', 'G51', 'G52', 'G53', 'G54']